respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Late_Outstanding_Payments__c</fullName>
        <label>Late Outstanding Payments</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Limit_Exceeded__c</fullName>
        <formula>Total_Collection_Outstanding_Balance__c - Credit_Limit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Limit Exceeded</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_Import_Export_Warnings.cls
public with sharing class NEU_Import_Export_Warnings 
{
    
    public Customer_Quote__c record;
    public String disp_1 {get;set;}
    public String disp_2 {get;set;}
    
    ApexPages.StandardController con;
    
    public NEU_Import_Export_Warnings(ApexPages.StandardController stdController) 
    {
        con = stdController;

        try 
        { 
            record = [select Id, Name, Account_for__c, Account_for__r.Credit_Limit__c, Account_for__r.Limit_Exceeded__c, Account_for__r.Late_Outstanding_Payments__c from Customer_Quote__c where id = :con.getRecord().id];
        } 
        catch(Exception ee){record = new Customer_Quote__c();}
        
        
        //PLEASE, CHECK LIMIT OF CREDIT ALREADY EXCEEDED ON ACCOUNT
        if(record.Account_for__r.Credit_Limit__c  != null && record.Account_for__r.Credit_Limit__c > 0 && record.Account_for__r.Limit_Exceeded__c > 0)
            disp_1 = 'display:block;';
        else
            disp_1 = 'display:none;';
        
        //PLEASE, CHECK OUTSTANDING PAYMENTS ALREADY DUE ON ACCOUNT
        if(record.Account_for__r.Late_Outstanding_Payments__c > 0)
            disp_2 = 'display:block;';
        else
            disp_2 = 'display:none;';
        
    }
}