respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_InternalFollower</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_External_Follower_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account External Follower User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_PartnerUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ActiveSap__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Area__c</fullName>
        <inlineHelpText>Make sure that you have the same Business Areas for ACCOUNTS, FAMILIES, PRICE LISTS and SUPPLY PROJECTS.</inlineHelpText>
        <label>Business Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air Freight</fullName>
                </value>
                <value>
                    <fullName>Animal Nutrition</fullName>
                </value>
                <value>
                    <fullName>Auto-Parts</fullName>
                </value>
                <value>
                    <fullName>Cloths &amp; Accessories</fullName>
                </value>
                <value>
                    <fullName>Construction &amp; Engineering</fullName>
                </value>
                <value>
                    <fullName>Construction &amp; Mining</fullName>
                </value>
                <value>
                    <fullName>Energy &amp; Hydrocarbons</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverages</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Machinery &amp; Parts</fullName>
                </value>
                <value>
                    <fullName>MERA Autoparts</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Other Services</fullName>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                </value>
                <value>
                    <fullName>Rail Freight</fullName>
                </value>
                <value>
                    <fullName>Recruiting Services</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Sea Freight</fullName>
                </value>
                <value>
                    <fullName>Telecom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Consignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consignee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Consignee)</relationshipLabel>
        <relationshipName>NEU_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Transporter</fullName>
        <active>true</active>
        <description>Logistic companies that we use to transport our goods. Valid for Carriers, Forwarders, 3PLs,...etc.</description>
        <label>Supply Chain Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <formula>Account_for__r.Owner.FirstName  &amp; &quot; &quot; &amp;Account_for__r.Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner (Sales Executive)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Catalog_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Catalog Price List</label>
        <referenceTo>Price_List__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Catalog</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comercio_Exterior__c</fullName>
        <label>Comercio Exterior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Consignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer or Agente Aduanal</inlineHelpText>
        <label>Cuenta Destino</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Consignee, Supply Chain Partner, Agente Aduanal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Consignee Account (Destination))</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Reference__c</fullName>
        <label>Customer Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Final Destination Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Initial Origin Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <inlineHelpText>Only Approved as Succesfull Quotes will be available for Pick &amp; Ship</inlineHelpText>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote being prepared</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Quote being prepared</label>
                </value>
                <value>
                    <fullName>Awaiting costs suppliers</fullName>
                    <color>#FF0000</color>
                    <label>Awaiting costs suppliers</label>
                </value>
                <value>
                    <fullName>Sent awaiting response</fullName>
                    <color>#FF6600</color>
                    <label>Sent awaiting response</label>
                </value>
                <value>
                    <fullName>Approved as Succesful</fullName>
                    <color>#006600</color>
                    <label>Approved as Succesful</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <color>#3366FF</color>
                    <label>Shipped</label>
                </value>
                <value>
                    <fullName>Quote Declined</fullName>
                    <color>#FF0000</color>
                    <label>Quote Declined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                    <default>true</default>
                    <label>NATIONAL</label>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer, Supplier or Agente Aduanal</inlineHelpText>
        <label>Cuenta Origen</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Shipper, Customer, Supply Chain Partner, Supplier Owner or Lessee of Vehicule, Agente Aduanal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Supplier/Shipper Account)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Supplier_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <defaultValue>&quot;P2G&quot;</defaultValue>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                    <default>true</default>
                    <label>P2G</label>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Until__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Until__c</fullName>
        <defaultValue>now()</defaultValue>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Import_Export_Fee_Line__c.object
<CustomObject>
    <description>Specifies transport fees associated to an Import-Export. Child object from &quot;Freight Rates Management&quot;</description>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <formula>TEXT(Import_Export_Quote__r.Quotation_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quotation Status</label>
        <type>Text</type>
    </fields>
    <label>Import-Export Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/User.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_NEU_OM_UpdateFoImpExpQuoteTest.cls
@isTest
public class P2G_NEU_OM_UpdateFoImpExpQuoteTest {
    
    @isTest
    static void NEU_OM_UpdateFoImportExportQuote(){ //ok                
        List<Account> list_accounts = NEU_Utils.getAccounts('Customer,Transporter,');
        Account cuenta = list_accounts[0];
        cuenta.ActiveSap__c = true;
        cuenta.Account_Executive_User__c=UserInfo.getUserId();
        cuenta.Account_External_Follower_User__c=UserInfo.getUserId();
        insert cuenta;
        Account sup = list_accounts[1];
        insert sup;
        Contact contacto = new Contact(AccountId = cuenta.Id, LastName='test contact');
        insert contacto;
        Contact contacto2 = new Contact(AccountId = cuenta.Id, LastName='test contact');
        insert contacto2;
        Price_List__c pricelist = new Price_List__c(Name = 'Test acount' /*,Business_Area__c = 'Sales'*/, Items_Account_Owner__c = cuenta.Id);
        insert pricelist;
        //Customer_Quote__c importexportquote = new Customer_Quote__c(Consignee__c = cuenta.Id, Supplier_Account__c = sup.Id, Catalog_Price_List__c = pricelist.id, Account_for__c = cuenta.Id, Quotation_Status__c = 'Approved as Succesful');
        /*
        Customer_Quote__c importexportquote = new Customer_Quote__c(Consignee__c = cuenta.Id, Supplier_Account__c = sup.Id, Catalog_Price_List__c = pricelist.id, Account_for__c = cuenta.Id, Quotation_Status__c = 'Quote being prepared', Origin_Address__c = '', Destination_Address__c = '', Only_Warehouse_Service__c = true);
        insert importexportquote;
        */

        User userT = [select id,managerId, userRole.Name  from user where id =: UserInfo.getUserId() limit 1];

        Rol_Margen__c rolMargen = TestDataFactory.createRolMargen(userT.userRole.Name);//Director Comercial ,Director Regional

        Customer_Quote__c importexportquote = new Customer_Quote__c();

        String recordTypeId = Schema.SObjectType.Customer_Quote__c.getRecordTypeInfosByName().get('Import-Export Quote').getRecordTypeId();

        importexportquote.RecordTypeId = recordTypeId;

        importexportquote.Name='.';

        importexportquote.Account_for__c = cuenta.Id;
        importexportquote.Consignee__c=cuenta.Id;
        importexportquote.Supplier_Account__c = sup.Id;

        importexportquote.Team__c = 'P2G';

        importexportquote.Quotation_Status__c = 'Quote being prepared';

        importexportquote.Customer_Reference__c = 'hola soy una prueba';

        importexportquote.Valid_From__c = system.today();

        importexportquote.Valid_Until__c = system.today();

        importexportquote.Comercio_Exterior__c = 'No';

        importexportquote.Freight_Mode__c = 'Road';

        importexportquote.Service_Mode__c = 'NATIONAL';

        importexportquote.Service_Type__c = 'FTL';

        importexportquote.CurrencyIsoCode = 'MXN';

        importexportquote.ETD__c = Date.today();

        importexportquote.ETA__c = Date.today();

        importexportquote.Community_Status__c = 'CUSTOMER CREATED';

        importexportquote.Pricing_Executive__c= userT.Id;

        importexportquote.Operations_Exec__c = userT.Id;

        insert importexportquote;
 

        Quote_Item_Line__c quote = new Quote_Item_Line__c(Import_Export_Quote__c = importexportquote.id,Name = 'lineas items',Units__c=10);
        insert quote;
        
        Fee__c service_rate = new Fee__c();
        service_rate.Name = 'Sercie Rate Test';
        service_rate.Fee_Category__c = 'Disbursement';
        service_rate.Rate_Type__c = 'Per Kg';
        service_rate.Account_for__c = cuenta.Id;
        insert service_rate;
        
        Import_Export_Fee_Line__c ie_service_line = new Import_Export_Fee_Line__c();
        ie_service_line.Import_Export_Quote__c = importexportquote.Id;
        ie_service_line.Name = '001'; 
        ie_service_line.Service_Rate_Name__c = service_rate.Id; 
        ie_service_line.Extension_Service_Name__c = 'Test Name'; 
        ie_service_line.Discount__c = 10; 
        ie_service_line.Quote_Buy_Price__c = 10; 
        ie_service_line.Quote_Sell_Price__c = 10;
        ie_service_line.Units__c = 10;
        insert ie_service_line;
        
        //importexportquote.Quotation_Status__c ='Approved as Succesful';
        //update importexportquote;
        
    }
}