respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Arrendatario_Propietario__c</fullName>
        <description>Describe si es Propietario de la unidad o Arrendatario de la unidad</description>
        <label>Tipo de Relacion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Propietario</fullName>
                </value>
                <value>
                    <fullName>Arrendatario</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comgps_cta__c</fullName>
        <label>Compañía GPS</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Debit_Note__c.object
<CustomObject>
    <description>Objeto para registrar las Debit Notes a partir de los folios SP</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Campo para asignar al cliente al que hará referencia la Debit Note</description>
        <label>Account for (Customer)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Debit Notes</relationshipLabel>
        <relationshipName>Debit_Notes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Debit Note</label>
    <nameField>
        <displayFormat>DN-{YY}-{000000}</displayFormat>
        <label>Debit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debit Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Operadores__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Proveedor (SCP)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operadores</relationshipLabel>
        <relationshipName>Operadores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Fecha_de_vigencia_de_la_licencia__c</fullName>
        <label>Fecha de Vigencia de la Licencia</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Licvig_ope__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Licencia Vigente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Numlicvig_ope__c</fullName>
        <label>Num. Licencia Vigente</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telfij_ope__c</fullName>
        <label>Teléfono fijo</label>
        <type>Phone</type>
    </fields>
    <label>Operadores</label>
    <nameField>
        <label>Nombre Operador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supply Chain Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Carrier)</relationshipLabel>
        <relationshipName>Shipments_Carrier</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compania_GPS__c</fullName>
        <formula>Carrier__r.Comgps_cta__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Compañía GPS</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contrasena_Cuenta_Espejo__c</fullName>
        <label>Contraseña Cuenta Espejo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Liga_Cuenta_Espejo__c</fullName>
        <label>Liga Cuenta Espejo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>National_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator 1</label>
        <referenceTo>Operadores__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Status_Plann__c</fullName>
        <label>Shipment Status Planner</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Re assigned</fullName>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Rejected PakControl</fullName>
                </value>
                <value>
                    <fullName>Operative Failure</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Delivery on Route</fullName>
                    <isActive>false</isActive>
                    <label>Delivery On Route</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Usuario_Cuenta_Espejo__c</fullName>
        <label>Usuario Cuenta Espejo</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VERIFY_PAK_CONTROL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VERIFY PAK CONTROL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Vehicle__c.Account_for_SCP__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Carrier__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VerificacionPak__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VerificacionPak</label>
        <type>Checkbox</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Account_Owner_Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Leseer or Owner Vehicle</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles (Supplier Leseer or Owner Vehicle)</relationshipLabel>
        <relationshipName>Vehicles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_for_SCP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account for (SCP)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nombre_Aseguradora__c</fullName>
        <description>Expresa el nombre de la aseguradora que cubre los riesgos del autotransporte utilizado para el traslado de los bienes o mercancías.</description>
        <inlineHelpText>Expresa el nombre de la aseguradora que cubre los riesgos del autotransporte utilizado para el traslado de los bienes o mercancías.</inlineHelpText>
        <label>Asegura Carga</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Numero_Poliza_Seguro__c</fullName>
        <description>Registra el número de póliza asignado por la aseguradora, que cubre los riesgos del autotransporte utilizado para el traslado de los bienes o mercancías.</description>
        <inlineHelpText>Registra el número de póliza asignado por la aseguradora, que cubre los riesgos del autotransporte utilizado para el traslado de los bienes o mercancías.</inlineHelpText>
        <label>Poliza Carga</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Poliza_Responsabilidad_civil__c</fullName>
        <label>Poliza Responsabilidad civil</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Poliza_Seguro_Medio_Ambiente__c</fullName>
        <label>Poliza Seguro Medio Ambiente</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Number__c</fullName>
        <label>Registration Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APX_Verificacion_Pak_Control.cls
/**
 * @description       : 
 * @author            : Brandom Gonzalez
 * @group             : 
 * @last modified on  : 08-12-2022
 * @last modified by  : Brandom Gonzalez
 * % Test			  : 87%
**/
public with sharing class APX_Verificacion_Pak_Control {   
    
    @AuraEnabled(cacheable = true)
    public static List<Shipment__c> getRecord(String spId){
        system.debug('APX_Verificacion_Pak_Control: ' + spId);
        return [Select Id,Name,Carrier__c,Carrier__r.Name, Compania_GPS__c,Liga_Cuenta_Espejo__c,Usuario_Cuenta_Espejo__c,Contrasena_Cuenta_Espejo__c,
                National_Operator__c,National_Operator__r.Name, Vehicle__c,Vehicle__r.Name, Vehicle__r.Registration_Number__c,Vehicle__r.Numero_Poliza_Seguro__c, 
                National_Operator__r.Numlicvig_ope__c,Vehicle__r.Poliza_Responsabilidad_civil__c,Vehicle__r.Poliza_Seguro_Medio_Ambiente__c, 
                National_Operator__r.Licvig_ope__c,National_Operator__r.Fecha_de_vigencia_de_la_licencia__c,National_Operator__r.Telfij_ope__c,
                Vehicle__r.Account_Owner_Vehicle__c, Vehicle__r.Account_Owner_Vehicle__r.Name, Vehicle__r.Account_Owner_Vehicle__r.Parent.Name, Vehicle__r.Account_Owner_Vehicle__r.Record_Type_Name__c,
                Vehicle__r.Account_Owner_Vehicle__r.Arrendatario_Propietario__c, Account_for__c, Account_for__r.Name, Account_for__r.RecordType.Name,
                Vehicle__r.Nombre_Aseguradora__c from  Shipment__c where Id=:spId];
    }      

    @AuraEnabled
    public static void  cancelModal(String recordId){
        try {
            
            Shipment__c sp = [Select Id, name, Shipment_Status_Plann__c from Shipment__c where Id=:recordId];
            sp.Shipment_Status_Plann__c = 'In Progress';
            update sp; 
            system.debug('Se ha cambiado el Shipment status planner: ' + sp.Shipment_Status_Plann__c);

        } catch (Exception e) {
            system.debug('Ocurrio un erro al actualizar el Shipment status planner cuando cierra el modal: ' + e.getCause() + ' Linea: ' + e.getLineNumber() + 
                            ' mensaje: ' + e.getMessage());

            String errorMsg = e.getMessage();
            Integer i = errorMsg.lastIndexOf('_EXCEPTION,');
            String pureErrorMsg = errorMsg.substring(i+1);            
            throw new AuraHandledException(pureErrorMsg);            
        }
    }

    @AuraEnabled
    public static String updateShipmentData(String recordId, Shipment__c spData, Vehicle__c vData, Operadores__c opeData, String carrierGPS){
        try {
                    
            System.debug('Actualizar datos del Shipment, Vehiculo, Operador y Cuenta...');            
            
            Shipment__c ship = [select id, Vehicle__c,National_Operator__c, Carrier__c from Shipment__c where id=:recordId]; 
            Account carrier = [Select Id, name from Account where Id =: ship.Carrier__c];

            spData.Id = recordId;        
            vData.Id = ship.Vehicle__c;
            opeData.Id = ship.National_Operator__c;       
            ship.VERIFY_PAK_CONTROL__c = true;
            ship.VerificacionPak__c = true;     
            carrier.Comgps_cta__c = carrierGPS;

            update vData;
            update spData;            
            update opeData;
            update ship;
            update carrier;

            System.debug('Se ha actualizado correctamente los datos');
            return 'Se ha validado correctamente los datos';       
                        
        } catch (Exception e) {
            system.debug('Ocurrio un erro al actualizar los datos: ' + e.getCause() + ' Linea: ' + e.getLineNumber() + 
                            ' mensaje: ' + e.getMessage());
            
            return e.getMessage();                            
        }
    }

    @AuraEnabled(cacheable = true)
    public static List<SObject> findRecords(String search, String objectName, String accId, String type){
        try {            
            String searchName = '%'+search+'%';           
            string searchText = '\'%' + String.escapeSingleQuotes(search) + '%\'';                         
            String label = (objectName == 'Vehicle__c') ? 'Account_for_SCP__c': (objectName == 'Operadores__c') ? 'Account__c' : (objectName == 'Shipment__c') ? 'Account_for__c' : (objectName == 'Debit_Note__c') ? 'Account_for__c' :null;
            String query;
            String carrierID='\''+accId+'\''; 
            system.debug('Obteniendo registros de:  ' + objectName + ' label: ' + label);

            if(objectName == 'Account'){
               String recordType = '\'' + String.escapeSingleQuotes(type) + '\'';
               query = 'SELECT Id, Name FROM ' +objectName+ ' WHERE Name LIKE '+searchText+' and RecordType.Name ='+recordType+' limit 5';             
            }else{                
                query = 'SELECT Id, Name FROM ' +objectName+ ' WHERE Name LIKE '+searchText+' and '+label+' ='+carrierID+' limit 5';
                system.debug('No Account: ' + query);                                
            }           
            system.debug('return: ' + Database.query(query));
            
            return Database.query(query);
            
        } catch (Exception e) {
            system.debug('Ocurrio un error al encontrar la informacion de  ' +objectName + ' : ' + e.getCause() + ' Linea: ' + e.getLineNumber() + 
                            ' mensaje: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static String updateShipmentObject(String spId, Id objId){
        
        String name;

        try {
            
            string objectName= string.valueOf(objId.getSObjectType());
            Shipment__c sp = [Select Carrier__c, National_Operator__c, Vehicle__c from Shipment__c where Id =: spId];            

            if(objectName == 'Account'){
                sp.Carrier__c = objId;                
                name = 'Carrier';
            }else if(objectName == 'Operadores__c'){                
                sp.National_Operator__c = objId;
                name = 'Operador';                
            }else if(objectName == 'Vehicle__c'){
                sp.vehicle__c = objId;  
                name = 'Vehiculo';              
            }

            update sp;            
            system.debug('Se ha actualizado  ' + name + ' del Shipment correctamente');

            return name;

        } catch (Exception e) {
            system.debug('Ocurrio un error al actualizar el ' +name + ' : ' + e.getCause() + ' Linea: ' + e.getLineNumber() + ' mensaje: ' + e.getMessage());
            return name;            
        }
    }

    @AuraEnabled
    public static Boolean recordChangeData(String recordId, Id objId){
        
        String name;

        try {

            string objectName= string.valueOf(objId.getSObjectType());
            Shipment__c sp = [Select Carrier__c, National_Operator__c, Vehicle__c from Shipment__c where Id =: recordId];            

            if(objectName == 'Account'){
                sp.Carrier__c = null;
                sp.National_Operator__c = null;      
                sp.vehicle__c = null;          
                name = 'Carrier';
            }else if(objectName == 'Operadores__c'){                
                sp.National_Operator__c = null;
                name = 'Operador';                
            }else if(objectName == 'Vehicle__c'){
                sp.vehicle__c = null;
                name = 'Vehiculo';
            }

            update sp;            
            system.debug('Se ha cambiado ' + name + ' del Shipment correctamente');        
            return true;

        } catch (Exception e) {

            system.debug('Ocurrio un error cambiar los datos del ' +name + ' : ' + e.getCause() + ' Linea: ' + e.getLineNumber() + ' mensaje: ' + e.getMessage());
            return false;            
        }
    }    
}