respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Brand_Name__c</fullName>
        <label>Brand Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NEU_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Proovedor_validado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Proovedor validado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TAX_ID__c</fullName>
        <label>TAX ID (RFC)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ubicta_cta__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nacional</fullName>
                    <label>National</label>
                </value>
                <value>
                    <fullName>Internacional</fullName>
                    <label>International</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Catalogo_SAT__c.object
<CustomObject>
    <description>Permite llevar el registro de los catalogos del SAT para la carta porte</description>
    <fields>
        <fullName>Clave_SAT__c</fullName>
        <description>Catalgo SAT Clave del catalogo al que corresponde</description>
        <label>Clave SAT</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Catalogo SAT</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos SAT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Operadores__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Proveedor (SCP)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operadores</relationshipLabel>
        <relationshipName>Operadores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cel_ope__c</fullName>
        <label>Celular</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Codigo_Postal_Operador__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codigo Postal Operador</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo_SAT__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Codigo Postal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo_SAT__c</referenceTo>
        <relationshipLabel>Operadores (Codigo Postal Operador)</relationshipLabel>
        <relationshipName>Operadores4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Medprev_ope__c</fullName>
        <label>Med Preventiva</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numlicvig_ope__c</fullName>
        <label>Num. Licencia Vigente</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operador_Validado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Operador Validado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proovedor_validado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Proovedor validado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RFC_Operador__c</fullName>
        <description>Registra el RFC del operador del autotransporte de carga federal.</description>
        <inlineHelpText>Registra el RFC del operador del autotransporte de carga federal.</inlineHelpText>
        <label>RFC Operador</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telfij_ope__c</fullName>
        <label>Teléfono fijo</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Validado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validado</label>
        <type>Checkbox</type>
    </fields>
    <label>Operadores</label>
    <nameField>
        <label>Nombre Operador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supply Chain Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Carrier)</relationshipLabel>
        <relationshipName>Shipments_Carrier</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Move_Type__c</fullName>
        <label>Move Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Door to Door</fullName>
                </value>
                <value>
                    <fullName>Door to Port</fullName>
                </value>
                <value>
                    <fullName>Port to Door</fullName>
                </value>
                <value>
                    <fullName>Port to Port</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>National_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator 1</label>
        <referenceTo>Operadores__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operador_Validado__c</fullName>
        <formula>National_Operator__r.Validado__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Operador Validado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operation_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operation Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Break-bulk</fullName>
                </value>
                <value>
                    <fullName>Containerised</fullName>
                </value>
                <value>
                    <fullName>LCL Cargo</fullName>
                </value>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>CONSOLIDADO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Sea&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058LK&amp;oid=00Db0000000I1t3&amp;lastMod=1358783213000&apos;, &apos;Import - Sea&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Air&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058O4&amp;oid=00Db0000000I1t3&amp;lastMod=1358783262000&apos;, &apos;Import - Air&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Road&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OY&amp;oid=00Db0000000I1t3&amp;lastMod=1358783362000&apos;, &apos;Import - Road&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Rail&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OJ&amp;oid=00Db0000000I1t3&amp;lastMod=1358783317000&apos;, &apos;Import - Rail&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Sea&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058Nz&amp;oid=00Db0000000I1t3&amp;lastMod=1358783241000&apos;, &apos;Export - Sea&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Air&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058O9&amp;oid=00Db0000000I1t3&amp;lastMod=1358783289000&apos;, &apos;Export - Air&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Road&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OU&amp;oid=00Db0000000I1t3&amp;lastMod=1358783382000&apos;, &apos;Export - Road&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Rail&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OT&amp;oid=00Db0000000I1t3&amp;lastMod=1358783338000&apos;, &apos;Export - Rail&apos;), &apos;&apos;))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type (REVISAR)</label>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/API_send_SP_to_PakControl_Test.cls
@istest
public with sharing class API_send_SP_to_PakControl_Test {
    @TestSetup
    static void makeData(){
        
            //user        
            User userT = new User();
            userT.FirstName = 'leo';
            userT.LastName = 'test';
            userT.Email = 'leoTest@test.com';
            userT.Username = 'leoTest@test.com.leoTest';
            userT.Alias = 'TestL';
            userT.TimeZoneSidKey = 'America/Mexico_City';
            userT.LocaleSidKey = 'es_MX';
            userT.EmailEncodingKey = 'UTF-8';
            userT.ProfileId = [Select Id from Profile where Name = 'System Administrator'].Id;
            userT.LanguageLocaleKey = 'es_MX';
            insert userT;
    
            //Account        
            Account accCustomer = createAccount('Cuenta customer', 'Customer');
            insert accCustomer;
    
            Account accCarrier = createAccount('Cuenta carrier', 'Supply Chain Partner');        
            insert accCarrier;
    
            //Container Type
            Container_Type__c ctV = new Container_Type__c();
            ctV.Name = 'caja test';
            ctV.Type__c = 'Road';
            ctV.Height_cm__c = 250;
            ctV.Length_cm__c = 1450;
            ctV.Width_cm__c = 250;
            ctV.Cargo_Weight_Kg__c = 25000;
            insert ctV;   
            
            //RecordType: produccion:Configuracion Autotransporte  UAT: Configuracion Autotrasporte
            /*Catalogo_SAT__c trans1 = createCatalogoSat('Camión-Remolque-Test', 'T3S17','Configuracion Autotrasporte');                        
            insert trans1;        
    
            //RecordType: AUT y  produccion : Tipo de Permiso     
            Catalogo_SAT__c trans2 = createCatalogoSat('Autotransporte Federal Test' , 'T3S172','Tipo de Permiso');
            insert trans2;*/
    
    
            // cp
            Catalogo_SAT__c cp = new Catalogo_SAT__c();        
            cp.Name  = '980828';
            cp.Clave_SAT__c = '980828';
            cp.RecordTypeId = Schema.SobjectType.Catalogo_SAT__c.getRecordTypeInfosByName().get('Codigo Postal').getRecordTypeId();        
            insert cp;
    
            //Operador        
            Operadores__c operador = new Operadores__c();
            operador.Account__c = accCarrier.Id;		
            operador.Name = 'Operador test';
            operador.Cel_ope__c = '123456789';
            operador.Telfij_ope__c = '123123123';
            operador.Medprev_ope__c = '123123';
            operador.Proovedor_validado__c = true;
            operador.Validado__c = true;        
            operador.Operador_Validado__c = true;
            operador.Codigo_Postal_Operador__c = cp.Id;
            operador.RFC_Operador__c = 'TestRFC';
            operador.Numlicvig_ope__c = '123135';
            
            insert operador;
    
            Catalogo_SAT__c catalogo = new Catalogo_SAT__c();
            catalogo.Name = 'Caja de acero test';
            catalogo.Clave_SAT__c = 'Caja de acero test';
            catalogo.RecordTypeId = Schema.SobjectType.Catalogo_SAT__c.getRecordTypeInfosByName().get('Unidad Peso').getRecordTypeId();
            insert catalogo;      
    
            Shipment__c new_shipment = new Shipment__c();
            new_shipment.Name = 'SP-FN-21-280888';                      
            new_shipment.Freight_Mode__c = 'Road';
            new_shipment.Account_for__c=accCustomer.Id;             
            new_shipment.Service_Mode__c = 'NATIONAL';
            new_shipment.Service_Type__c =  'LTL';
            new_shipment.Move_Type__c = 'Door to Door';        
            new_shipment.Only_Warehouse_Service__c = false;                    
            new_shipment.Operation_Executive__c = userT.Id; 
            new_shipment.Carrier__c = accCarrier.Id; 
            new_shipment.National_Operator__c = operador.Id;
            insert new_shipment;    
    }
    public static Account createAccount(String name, String recordType){
        
        Account accountT = new Account();
        accountT.RecordTypeId = Schema.SobjectType.Account.getRecordTypeInfosByName().get(recordType).getRecordTypeId();
        accountT.name = name;    

        if(recordType == 'Supply Chain Partner'){
            accountT.Phone = '8311109798';
            accountT.Brand_Name__c = 'Cuenta carrier';
            accountT.NEU_Email__c = 'test@live.com';
            accountT.TAX_ID__c = 'TEST1106099H1';
            accountT.Ubicta_cta__c = 'Nacional';
            accountT.Grupo_SAP_PICK__c = 'FLETES TEST';
            accountT.SCPNombre_Acta_Constitutiva__c = 'N A';
            accountT.Bank_Name_Supplier_Form2__c = 'Banorte Test';
            accountT.Bank_Account_Number__c = '0720780101000000';
            accountT.Bank_Account_Name__c = 'Cuenta carrier';
            accountT.Credit_Limit__c = 500;
            accountT.Anticipo__c = 'No';
            accountT.Sujeto_a_retencion__c = 'Si';
            accountT.Factoraje__c = 'No';
            accountT.C_digo_IVA_Permitido__c = 'IRF';
            accountT.Indicador_de_impuestos__c = 'V2';
        
        }else{        
            accountT.AccountSource = 'Other';
            accountT.TAX_ID__c = 'TEST1106090000';
        }

        return accountT;            
    }
    public static Catalogo_SAT__c createCatalogoSat(String name, String claveSat, String RecordType){

        Catalogo_SAT__c trans = new Catalogo_SAT__c();        
        trans.Name  = name;
        trans.Clave_SAT__c = claveSat;
        trans.RecordTypeId =Schema.SobjectType.Catalogo_SAT__c.getRecordTypeInfosByName().get(RecordType).getRecordTypeId();
        return trans;        
    }

    @isTest
    public static void MethotTest() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ControlRoomSPMock());
        Shipment__c spObj=[SELECT id,name FROM Shipment__c limit 1];
        API_send_SP_to_PakControl.send_SP(spObj.id);
        Test.stopTest();
    }
}