respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_InternalFollower</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Supplier</fullName>
        <active>true</active>
        <description>Suppliers we purchase goods from.</description>
        <label>Supplier</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Supplier_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Executive User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Suppliers_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <label>Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Supply Chain Partner, Purchase Agent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Suppliers Quotes/Orders (Supplier)</relationshipLabel>
        <relationshipName>Suppliers_Quotes_Supplier</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Supplier Quote/Order</label>
    <nameField>
        <displayFormat>SQO# {YYYY}-{000000}</displayFormat>
        <label>Supplier Quote/Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_NEU_SQO_Update_ConversionsTest.cls
@isTest
public class P2G_NEU_SQO_Update_ConversionsTest {    
    @isTest
    static void P2G_NEU_SQO_Update_Conversions(){
        Test.startTest();
        List<Account> list_accounts = NEU_Utils.getAccounts('Supplier,');
        Account a = list_accounts[0];
        insert a;  
        Supplier_Quote__c supquote = new Supplier_Quote__c(Supplier__c=a.Id);
        insert supquote;
        
        supquote.Account_Executive_User__c=UserInfo.getUserId();
        update supquote;
        Test.stopTest();
    }
}