respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NEU_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supply Chain Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Carrier)</relationshipLabel>
        <relationshipName>Shipments_Carrier</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Acuse_SAP__c</fullName>
        <label>Date Acuse SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Verify_Acuse_SAPTxt__c</fullName>
        <label>DATE ACUSE RECIBIDO</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_Acuse_SAP__c</fullName>
        <label>Status Acuse SAP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Carrier__c</fullName>
        <formula>Service_Rate_Name__r.Carrier_Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Carrier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Orden_Compra__c</fullName>
        <description>orden de compra dada por sap</description>
        <label>Orden de Compra</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_AcuseRecibidoEmail.cls
public class P2G_AcuseRecibidoEmail {
    public static void sendEmail(List<Shipment__c> newShipments, Map<Id, Shipment__c> oldMap){
        
        Set<Id> shipmentIds = new Set<Id>();

        for (Shipment__c newShipment : newShipments) { 
            Shipment__c oldshipment = oldMap.get(newShipment.Id);
            
            if(newShipment.Status_Acuse_SAP__c == 'ACUSE RECIBIDO' && oldShipment.Status_Acuse_SAP__c != 'ACUSE RECIBIDO') {
                shipmentIds.add(newShipment.Id);
            }
        }
        if(!shipmentIds.isEmpty()){
            List<Id> shipmentIdsList = new List<Id>();
            shipmentIdsList.addAll(shipmentIds);
            
        	sendEmailFuture(new List<Id>(shipmentIdsList));
            }
    }
        @future
        public static void sendEmailFuture(List<Id> shipmentIds) {
            
            List<Shipment__c> shipments = [
            SELECT Id, Name, Status_Acuse_SAP__c, Carrier__c, Carrier__r.NEU_Email__c, Carrier__r.Name, Date_Verify_Acuse_SAPTxt__c/*Date_Acuse_SAP__c --campo de uat*/ FROM Shipment__c WHERE Id IN :shipmentIds
        ];

        Map<Id, List<Shipment_Fee_Line__c>> serviceLines = new Map<Id, List<Shipment_Fee_Line__c>>();
            
        for(Shipment_Fee_Line__c serviceLine : [SELECT Id, Name, Shipment__c, Orden_Compra__c FROM Shipment_Fee_Line__c WHERE Shipment__c IN :shipmentIds]) {
        	if (!serviceLines.containsKey(serviceLine.Shipment__c)) {
                    serviceLines.put(serviceLine.Shipment__c, new List <Shipment_Fee_Line__c>());
            }
            
           	serviceLines.get(serviceLine.Shipment__c).add(serviceLine);
		}
        List<Messaging.SingleEmailMessage> emails =  new List<Messaging.SingleEmailMessage>();

        for (Shipment__c shipment : shipments) {
             
            String ordenCompra = '';
            
            List<Shipment_Fee_Line__c> sLines = serviceLines.get(shipment.Id);
                if (sLines != null) {
                    for (Shipment_fee_Line__c sLine : sLines) {
                        ordenCompra += sLine.Orden_Compra__c;
                    }
                }
            
            	Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

                email.setToAddresses(new List<String>{
                    shipment.Carrier__r.NEU_Email__c
                });
                
                email.setSubject('Notificación de recepción de acuse en base al folio ' + shipment.Name);
                String fechaAcuse = shipment.Date_Verify_Acuse_SAPTxt__c != null ? shipment.Date_Verify_Acuse_SAPTxt__c.format() : '';
            	//String fechaAcuse = shipment.Date_Acuse_SAP__c != null ? shipment.Date_Acuse_SAP__c.format() : ''; UAT
                String htmlBody = '';
                htmlBody += '<html>';
                htmlBody += '<body>';
                htmlBody += '<p>Buen día <b>' + shipment.Carrier__r.Name + '</b>,</p>';
                htmlBody += '<p>Se ha aprobado y anexado con éxito al día <b>' + fechaAcuse + '</b>, el acuse correspondiente a la orden de compra <b>' + ordenCompra + '</b>, servicio <b>' + shipment.Name + '</b>.</p>';
                htmlBody += '</body>';
                htmlBody += '</html>';  
                 
                email.setHtmlBody(htmlBody);
                    
                emails.add(email);    
            }
            if(!emails.isEmpty()) {
                Messaging.sendEmail(emails);
            }
        }
    }