respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ActiveSap__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Anticipo__c</fullName>
        <label>Anticipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bank_Account_Name__c</fullName>
        <label>Bank Account Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Name_Supplier_Form2__c</fullName>
        <label>Bank Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1010</fullName>
                    <label>ACCENDO BANCO</label>
                </value>
                <value>
                    <fullName>0062</fullName>
                    <label>AFIRME</label>
                </value>
                <value>
                    <fullName>0065</fullName>
                    <label>ANAHUAC</label>
                </value>
                <value>
                    <fullName>0127</fullName>
                    <label>AZTECA</label>
                </value>
                <value>
                    <fullName>0002</fullName>
                    <label>BANAMEX</label>
                </value>
                <value>
                    <fullName>0145</fullName>
                    <label>BANCO BASE</label>
                </value>
                <value>
                    <fullName>0030</fullName>
                    <label>BANCO DEL BAJIO</label>
                </value>
                <value>
                    <fullName>0131</fullName>
                    <label>BANCO FAMSA</label>
                </value>
                <value>
                    <fullName>0006</fullName>
                    <label>BANCOMEXT</label>
                </value>
                <value>
                    <fullName>0112</fullName>
                    <label>BANCO MONEX</label>
                </value>
                <value>
                    <fullName>0137</fullName>
                    <label>BANCOPPEL</label>
                </value>
                <value>
                    <fullName>1012</fullName>
                    <label>BANCO PROMERICA</label>
                </value>
                <value>
                    <fullName>1016</fullName>
                    <label>BANCREA</label>
                </value>
                <value>
                    <fullName>0019</fullName>
                    <label>BANJERCITO</label>
                </value>
                <value>
                    <fullName>0003</fullName>
                    <label>BANK OF AMERICA SA</label>
                </value>
                <value>
                    <fullName>0009</fullName>
                    <label>BANOBRAS</label>
                </value>
                <value>
                    <fullName>0072</fullName>
                    <label>BANORTE IXE</label>
                </value>
                <value>
                    <fullName>0071</fullName>
                    <label>BANPAIS</label>
                </value>
                <value>
                    <fullName>0058</fullName>
                    <label>BANREGIO</label>
                </value>
                <value>
                    <fullName>0060</fullName>
                    <label>BANSI</label>
                </value>
                <value>
                    <fullName>0001</fullName>
                    <label>BANXICO</label>
                </value>
                <value>
                    <fullName>0012</fullName>
                    <label>BBVA BANCOMER</label>
                </value>
                <value>
                    <fullName>0143</fullName>
                    <label>CIBANCO</label>
                </value>
                <value>
                    <fullName>0021</fullName>
                    <label>HSBC</label>
                </value>
                <value>
                    <fullName>1018</fullName>
                    <label>HSBC BANK USA</label>
                </value>
                <value>
                    <fullName>0036</fullName>
                    <label>INBURSA</label>
                </value>
                <value>
                    <fullName>0136</fullName>
                    <label>INTER BANCO</label>
                </value>
                <value>
                    <fullName>1019</fullName>
                    <label>INTERCAM Banco</label>
                </value>
                <value>
                    <fullName>0059</fullName>
                    <label>INVEX</label>
                </value>
                <value>
                    <fullName>0032</fullName>
                    <label>IXE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>C_digo_IVA_Permitido__c</fullName>
        <label>Código IVA Permitido</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1IRA</fullName>
                    <label>IVA RETENIDO ARRENDAMIENTO</label>
                </value>
                <value>
                    <fullName>1IRH</fullName>
                    <label>IVA RETENIDO HONORARIOS</label>
                </value>
                <value>
                    <fullName>IRF</fullName>
                    <label>IVA 4% FLETES</label>
                </value>
                <value>
                    <fullName>IRFP</fullName>
                    <label>IVA RETENIDO 4% FLETES PTE</label>
                </value>
                <value>
                    <fullName>3IRA</fullName>
                    <label>IVA RETENIDO ARRENDAMIENTOS 8%</label>
                </value>
                <value>
                    <fullName>3IRH</fullName>
                    <label>IVA RETENIDO HONORARIOS 8%</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Carrier_Class__c</fullName>
        <label>Clasificacion</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Oro</fullName>
                </value>
                <value>
                    <fullName>Plata</fullName>
                </value>
                <value>
                    <fullName>Bronce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Carrier_Evaluation__c</fullName>
        <label>Evaluacion</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Plus</fullName>
                </value>
                <value>
                    <fullName>Basico</fullName>
                </value>
                <value>
                    <fullName>Auditoría Externa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit_Terms__c</fullName>
        <label>Credit Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contado</fullName>
                </value>
                <value>
                    <fullName>Pago Inmediato</fullName>
                </value>
                <value>
                    <fullName>1 Día</fullName>
                </value>
                <value>
                    <fullName>2 Días</fullName>
                </value>
                <value>
                    <fullName>3 Días</fullName>
                </value>
                <value>
                    <fullName>4 Días</fullName>
                </value>
                <value>
                    <fullName>5 Días</fullName>
                </value>
                <value>
                    <fullName>7 Días</fullName>
                </value>
                <value>
                    <fullName>8 Días</fullName>
                </value>
                <value>
                    <fullName>9 Días</fullName>
                </value>
                <value>
                    <fullName>10 Días</fullName>
                </value>
                <value>
                    <fullName>15 Días</fullName>
                </value>
                <value>
                    <fullName>16 Días</fullName>
                </value>
                <value>
                    <fullName>19 Días</fullName>
                </value>
                <value>
                    <fullName>20 Días</fullName>
                </value>
                <value>
                    <fullName>21 Días</fullName>
                </value>
                <value>
                    <fullName>22 Días</fullName>
                </value>
                <value>
                    <fullName>23 Días</fullName>
                </value>
                <value>
                    <fullName>25 Días</fullName>
                </value>
                <value>
                    <fullName>28 Días</fullName>
                </value>
                <value>
                    <fullName>31 Días</fullName>
                </value>
                <value>
                    <fullName>38 Días</fullName>
                </value>
                <value>
                    <fullName>60 Días</fullName>
                </value>
                <value>
                    <fullName>24 Dias</fullName>
                </value>
                <value>
                    <fullName>12 Dias</fullName>
                </value>
                <value>
                    <fullName>6 Días</fullName>
                </value>
                <value>
                    <fullName>50 Días</fullName>
                </value>
                <value>
                    <fullName>55 Días</fullName>
                </value>
                <value>
                    <fullName>40 Días</fullName>
                </value>
                <value>
                    <fullName>120 Días</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Factoraje__c</fullName>
        <label>Factoraje</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grupo_SAP_PICK__c</fullName>
        <label>Grupo SAP</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>CONSOLIDADO P</fullName>
                </value>
                <value>
                    <fullName>FLETES P</fullName>
                </value>
                <value>
                    <fullName>SERV LOGISTICOS P</fullName>
                </value>
                <value>
                    <fullName>MAYOREO P</fullName>
                </value>
                <value>
                    <fullName>INTERNACIONAL P</fullName>
                </value>
                <value>
                    <fullName>PROV GENERAL P</fullName>
                </value>
                <value>
                    <fullName>PROV GENERAL C</fullName>
                </value>
                <value>
                    <fullName>PROV SERVICIOS P</fullName>
                </value>
                <value>
                    <fullName>SERVICIOS P</fullName>
                </value>
                <value>
                    <fullName>PROV RENTAS P</fullName>
                </value>
                <value>
                    <fullName>PROV SEGUROS P</fullName>
                </value>
                <value>
                    <fullName>PROV CONSULTA P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Indicador_de_impuestos__c</fullName>
        <inlineHelpText>V0 IVA COMPRAS 0% 
V2 IVA COMPRAS 16% (Default) 
VE IVA COMPRAS Exento</inlineHelpText>
        <label>Indicador de impuestos</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>V0</fullName>
                </value>
                <value>
                    <fullName>V2</fullName>
                </value>
                <value>
                    <fullName>V3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NEU_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sujeto_a_retencion__c</fullName>
        <label>Sujeto a retencion</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Swift_Number__c</fullName>
        <label>Swift Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TAX_ID__c</fullName>
        <label>TAX ID (RFC)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workplace_AccOwner__c</fullName>
        <formula>Owner.PrcCode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Workplace Owner</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PAK_AcctProvWs.cls
public class PAK_AcctProvWs {
    public ApexPages.StandardController c {get;set;}
    Public Account prov {get;set;}
    public String idProv {get;set;}
    
    public PAK_AcctProvWs(ApexPages.StandardController Controller){
        c = Controller;
        prov = (Account)Controller.getRecord();
        idProv = Controller.getId(); 
    }
    
    public PageReference sendWs(){
        System.debug('PAK_AcctProvWs - id: ' + idProv);
        string body = '';
        List<Account> lstProvedores = new List<Account>();
        List<Response__c> lstResponses = new List<Response__c>();
        try{
            lstProvedores = [SELECT Id, Name, TAX_ID__c, Customer_Id__c, Phone, NEU_Email__c, Workplace_AccOwner__c, ActiveSap__c, Grupo_SAP_PICK__c, 
                             CurrencyIsoCode, Carrier_Class__c, Carrier_Evaluation__c, Credit_Terms__c, Bank_Name_Supplier_Form2__c, Bank_Account_Name__c, 
                             Bank_Account_Number__c, Swift_Number__c, Credit_Limit__c, Anticipo__c, Factoraje__c, Indicador_de_impuestos__c, C_digo_IVA_Permitido__c, BillingAddress, 
                             BillingStreet, BillingCity, BillingPostalCode, BillingState, BillingCountry, Sujeto_a_retencion__c,
                             (SELECT Tipcon_cont__c, Id, FirstName, LastName, Phone, MobilePhone, Email  FROM Contacts)
                             FROM Account 
                             WHERE Id = :idProv];
            body ='<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">'+
                '<soapenv:Header/>'+
                '<soapenv:Body>'+
                '<tem:altaProveedor>'+
                '<tem:proveedores>';
            for(Account prov : lstProvedores){
                string active = prov.ActiveSap__c == true ? '1' : '0';
                string retencion = prov.Sujeto_a_retencion__c != null ? prov.Sujeto_a_retencion__c : '';
                body += '<tem:Proveedor>' +
                    '<tem:salesforceId>'+prov.Id+'</tem:salesforceId>'+
                    '<tem:nombre>'+prov.Name+'</tem:nombre>'+
                    '<tem:rfc>'+(prov.TAX_ID__c == null ? '': prov.TAX_ID__c)+'</tem:rfc>'+
                    '<tem:cardCode>'+(prov.Customer_Id__c == null ? '': prov.Customer_Id__c)+'</tem:cardCode>'+
                    '<tem:phone>'+(prov.Phone == null ? '' : prov.Phone)+'</tem:phone>'+
                    '<tem:email>'+(prov.NEU_Email__c == null ? '' : prov.NEU_Email__c)+'</tem:email>'+
                    '<tem:workplaceOwner>'+(prov.Workplace_AccOwner__c == null ? '':prov.Workplace_AccOwner__c)+'</tem:workplaceOwner>'+
                    '<tem:active>'+active+'</tem:active>'+                    
                    '<tem:grupoSap>'+(prov.Grupo_SAP_PICK__c == null ? '':prov.Grupo_SAP_PICK__c)+'</tem:grupoSap>'+
                    '<tem:moneda>'+(prov.CurrencyIsoCode == null ? '':prov.CurrencyIsoCode)+'</tem:moneda>'+
                    '<tem:clasificacion>'+(prov.Carrier_Class__c == null ? '':prov.Carrier_Class__c)+'</tem:clasificacion>'+
                    '<tem:evaluacion>'+(prov.Carrier_Evaluation__c == null ? '':prov.Carrier_Evaluation__c)+'</tem:evaluacion>' +
                    '<tem:credTerms>'+(prov.Credit_Terms__c == null ? '':prov.Credit_Terms__c)+'</tem:credTerms>' +
                    '<tem:bankName>'+(prov.Bank_Name_Supplier_Form2__c == null ? '':prov.Bank_Name_Supplier_Form2__c)+'</tem:bankName>' +
                    '<tem:bankAcctName>'+(prov.Bank_Account_Name__c == null ? '':prov.Bank_Account_Name__c)+'</tem:bankAcctName>' +
                    '<tem:bankAcctNumber>'+(prov.Bank_Account_Number__c == null ? '':prov.Bank_Account_Number__c)+'</tem:bankAcctNumber>' +
                    '<tem:swiftNumber>'+(prov.Swift_Number__c == null ? '':prov.Swift_Number__c)+'</tem:swiftNumber>' +                    
                    '<tem:creditLimit>'+(prov.Credit_Limit__c == null ? 0: prov.Credit_Limit__c)+'</tem:creditLimit>' +
                    '<tem:anticipo>'+(prov.Anticipo__c == null ? '':prov.Anticipo__c)+'</tem:anticipo>' +                    
                    '<tem:billingAddress>'+(prov.BillingAddress == null ? '': (prov.BillingStreet + '|' + prov.BillingCity + '|' + prov.BillingPostalCode + '|' + prov.BillingState + '|' + prov.BillingCountry))+'</tem:billingAddress>' +
                    '<tem:factoraje>'+(prov.Factoraje__c == null ? '':prov.Factoraje__c)+'</tem:factoraje>' +
                    '<tem:indicadorImpuestos>'+(prov.Indicador_de_impuestos__c == null ? '':prov.Indicador_de_impuestos__c)+'</tem:indicadorImpuestos>' +
                    '<tem:codigoIva>'+(prov.C_digo_IVA_Permitido__c == null ? '':prov.C_digo_IVA_Permitido__c)+'</tem:codigoIva>' +
                    '<tem:retencion>' + retencion +'</tem:retencion>';
                if(prov.Contacts.size()>0){
                    body += '<tem:Contactos>';
                    for(Contact contact : prov.Contacts){
                        body += '<tem:ContactoProveedor>' +
                            '<tem:salesforceAcctId>'+prov.Id+'</tem:salesforceAcctId>' +
                            '<tem:salesforceId>'+contact.Id+'</tem:salesforceId>' +
                            '<tem:nombre>'+(contact.FirstName == null ? '':contact.FirstName)+'</tem:nombre>' + 
                            '<tem:apellido>'+(contact.LastName == null ? '':contact.LastName)+'</tem:apellido>' + 
                            '<tem:telefono>'+(contact.Phone == null ? '':contact.Phone)+'</tem:telefono>' + 
                            '<tem:celular>'+(contact.MobilePhone == null ? '':contact.MobilePhone)+'</tem:celular>' + 
                            '<tem:correo>'+(contact.Email == null ? '':contact.Email)+'</tem:correo>' + 
                            '<tem:tipoContacto>'+(contact.Tipcon_cont__c == null ? '':contact.Tipcon_cont__c)+'</tem:tipoContacto>' + 
                            '</tem:ContactoProveedor>'; 
                    }
                    body += '</tem:Contactos>';
                }
                body += '</tem:Proveedor>';
            }
            body += '</tem:proveedores>' +
                '</tem:altaProveedor>' +
                '</soapenv:Body>' +
                '</soapenv:Envelope>';
            
            Http httpProtocol = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint('http://35.169.18.187/pakws92/WSAltaProveedores.asmx');
            request.setMethod('POST');
            request.setHeader('Content-Type', 'text/xml;charset=utf-8');
            request.setHeader('SOAPAction', 'http://tempuri.org/altaProveedor');
            request.setBody(body);
            HttpResponse response = httpProtocol.send(request);
            System.debug('Response: '+response.getBody());
            System.debug('Request Body: '+body);
            if(response.getStatusCode() == 200){
                // OK - Enviar response si hay error en alguno
                System.debug('PAK_AcctProvWS: OK');
                Dom.Document doc = new Dom.Document();doc.load(response.getBody());
                Dom.XMLNode root = doc.getRootElement();
                root = root.getChildElement('Body','http://schemas.xmlsoap.org/soap/envelope/').getChildElement('altaProveedorResponse','http://tempuri.org/').getChildElement('altaProveedorResult','http://tempuri.org/');
                System.debug('Respuesta: ' + root.getText());
                List<String> respuestas = (List<string>)JSON.deserialize(root.getText(), List<string>.class);
                System.debug('Respuestas: ' + respuestas);
                Integer count = 0;
                for(String r : respuestas){
                    if(r != 'OK'){
                        Response__c res = new Response__c();res.Object__c = 'Account';res.Account__c = lstProvedores[count].Id;res.Type__c = 'ERROR';res.Message__c = r;
                        lstResponses.add(res);
                    }   
                    count++;
                }
                if(lstResponses.size()>0){
                    insert lstResponses;
                }
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.CONFIRM,'Proveedor enviado correctamente a SAP. Esperar respuesta en área de responses.');
                ApexPages.addMessage(myMsg); 
            }else{
                //Error
                System.debug('PAK_AcctProvWS: Ocurrio un error porfavor de comunicarse con el administrador del sistema');
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Ocurrio un error porfavor de comunicarse con el administrador del sistema');
                ApexPages.addMessage(myMsg);
            } 
        }catch(Exception e){
            System.debug('PAK_AcctProvWS: Error: ' + e.getLineNumber()+'------------'+e.getMessage() + '------' + e.getStackTraceString());
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'ERROR: ' + e.getLineNumber()+'------------'+e.getMessage() + '------' + e.getStackTraceString());
            ApexPages.addMessage(myMsg);
        }
        return null;
    }
    
    /*@future(callout=true)
public static void updateProvAcct(Set<Id> ids){
System.debug('PAK_AcctProvWs - ids: ' + ids);
string body = '';
List<Account> lstProvedores = new List<Account>();
List<Response__c> lstResponses = new List<Response__c>();
try{
lstProvedores = [SELECT Id, Name, TAX_ID__c, Customer_Id__c, Phone, NEU_Email__c, Workplace_AccOwner__c, ActiveSap__c, Grupo_SAP__c, 
CurrencyIsoCode, Carrier_Class__c, Carrier_Evaluation__c, Credit_Terms__c, Bank_Name_Supplier_Form__c, Bank_Account_Name__c, 
Bank_Account_Number__c, Swift_Number__c, Credit_Limit__c, Anticipo__c, Factoraje__c, Indicador_de_impuestos__c, C_digo_IVA_Permitido__c, BillingAddress, 
BillingStreet, BillingCity, BillingPostalCode, BillingState, BillingCountry, Sujeto_a_retencion__c,
(SELECT Tipcon_cont__c, Id, FirstName, LastName, Phone, MobilePhone, Email  FROM Contacts)
FROM Account 
WHERE Id IN :ids];
body ='<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">'+
'<soapenv:Header/>'+
'<soapenv:Body>'+
'<tem:altaProveedor>'+
'<tem:proveedores>';
for(Account prov : lstProvedores){
string active = prov.ActiveSap__c == true ? '1' : '0';
string retencion = prov.Sujeto_a_retencion__c != null ? prov.Sujeto_a_retencion__c : '';
body += '<tem:Proveedor>' +
'<tem:salesforceId>'+prov.Id+'</tem:salesforceId>'+
'<tem:nombre>'+prov.Name+'</tem:nombre>'+
'<tem:rfc>'+(prov.TAX_ID__c == null ? '': prov.TAX_ID__c)+'</tem:rfc>'+
'<tem:cardCode>'+(prov.Customer_Id__c == null ? '': prov.Customer_Id__c)+'</tem:cardCode>'+
'<tem:phone>'+(prov.Phone == null ? '' : prov.Phone)+'</tem:phone>'+
'<tem:email>'+(prov.NEU_Email__c == null ? '' : prov.NEU_Email__c)+'</tem:email>'+
'<tem:workplaceOwner>'+(prov.Workplace_AccOwner__c == null ? '':prov.Workplace_AccOwner__c)+'</tem:workplaceOwner>'+
'<tem:active>'+active+'</tem:active>'+                    
'<tem:grupoSap>'+(prov.Grupo_SAP__c == null ? '':prov.Grupo_SAP__c)+'</tem:grupoSap>'+
'<tem:moneda>'+(prov.CurrencyIsoCode == null ? '':prov.CurrencyIsoCode)+'</tem:moneda>'+
'<tem:clasificacion>'+(prov.Carrier_Class__c == null ? '':prov.Carrier_Class__c)+'</tem:clasificacion>'+
'<tem:evaluacion>'+(prov.Carrier_Evaluation__c == null ? '':prov.Carrier_Evaluation__c)+'</tem:evaluacion>' +
'<tem:credTerms>'+(prov.Credit_Terms__c == null ? '':prov.Credit_Terms__c)+'</tem:credTerms>' +
'<tem:bankName>'+(prov.Bank_Name_Supplier_Form__c == null ? '':prov.Bank_Name_Supplier_Form__c)+'</tem:bankName>' +
'<tem:bankAcctName>'+(prov.Bank_Account_Name__c == null ? '':prov.Bank_Account_Name__c)+'</tem:bankAcctName>' +
'<tem:bankAcctNumber>'+(prov.Bank_Account_Number__c == null ? '':prov.Bank_Account_Number__c)+'</tem:bankAcctNumber>' +
'<tem:swiftNumber>'+(prov.Swift_Number__c == null ? '':prov.Swift_Number__c)+'</tem:swiftNumber>' +                    
'<tem:creditLimit>'+(prov.Credit_Limit__c == null ? 0: prov.Credit_Limit__c)+'</tem:creditLimit>' +
'<tem:anticipo>'+(prov.Anticipo__c == null ? '':prov.Anticipo__c)+'</tem:anticipo>' +                    
'<tem:billingAddress>'+(prov.BillingAddress == null ? '': (prov.BillingStreet + '|' + prov.BillingCity + '|' + prov.BillingPostalCode + '|' + prov.BillingState + '|' + prov.BillingCountry))+'</tem:billingAddress>' +
'<tem:factoraje>'+(prov.Factoraje__c == null ? '':prov.Factoraje__c)+'</tem:factoraje>' +
'<tem:indicadorImpuestos>'+(prov.Indicador_de_impuestos__c == null ? '':prov.Indicador_de_impuestos__c)+'</tem:indicadorImpuestos>' +
'<tem:codigoIva>'+(prov.C_digo_IVA_Permitido__c == null ? '':prov.C_digo_IVA_Permitido__c)+'</tem:codigoIva>' +
'<tem:retencion>' + retencion +'</tem:retencion>';
if(prov.Contacts.size()>0){
body += '<tem:Contactos>';
for(Contact contact : prov.Contacts){
body += '<tem:ContactoProveedor>' +
'<tem:salesforceAcctId>'+prov.Id+'</tem:salesforceAcctId>' +
'<tem:salesforceId>'+contact.Id+'</tem:salesforceId>' +
'<tem:nombre>'+(contact.FirstName == null ? '':contact.FirstName)+'</tem:nombre>' + 
'<tem:apellido>'+(contact.LastName == null ? '':contact.LastName)+'</tem:apellido>' + 
'<tem:telefono>'+(contact.Phone == null ? '':contact.Phone)+'</tem:telefono>' + 
'<tem:celular>'+(contact.MobilePhone == null ? '':contact.MobilePhone)+'</tem:celular>' + 
'<tem:correo>'+(contact.Email == null ? '':contact.Email)+'</tem:correo>' + 
'<tem:tipoContacto>'+(contact.Tipcon_cont__c == null ? '':contact.Tipcon_cont__c)+'</tem:tipoContacto>' + 
'</tem:ContactoProveedor>'; 
}
body += '</tem:Contactos>';
}
body += '</tem:Proveedor>';
}
body += '</tem:proveedores>' +
'</tem:altaProveedor>' +
'</soapenv:Body>' +
'</soapenv:Envelope>';

Http httpProtocol = new Http();
HttpRequest request = new HttpRequest();
request.setEndpoint('http://35.169.18.187/pakws/WSAltaProveedores.asmx');
request.setMethod('POST');
request.setHeader('Content-Type', 'text/xml;charset=utf-8');
request.setHeader('SOAPAction', 'http://tempuri.org/altaProveedor');
request.setBody(body);
HttpResponse response = httpProtocol.send(request);
System.debug('Response: '+response.getBody());
System.debug('Request Body: '+body);
if(response.getStatusCode() == 200){
// OK - Enviar response si hay error en alguno
System.debug('PAK_AcctProvWS: OK');
Dom.Document doc = new Dom.Document();doc.load(response.getBody());
Dom.XMLNode root = doc.getRootElement();
root = root.getChildElement('Body','http://schemas.xmlsoap.org/soap/envelope/').getChildElement('altaProveedorResponse','http://tempuri.org/').getChildElement('altaProveedorResult','http://tempuri.org/');
System.debug('Respuesta: ' + root.getText());
List<String> respuestas = (List<string>)JSON.deserialize(root.getText(), List<string>.class);
System.debug('Respuestas: ' + respuestas);
Integer count = 0;
for(String r : respuestas){
if(r != 'OK'){
Response__c res = new Response__c();res.Object__c = 'Account';res.Account__c = lstProvedores[count].Id;res.Type__c = 'ERROR';res.Message__c = r;
lstResponses.add(res);
}   
count++;
}
if(lstResponses.size()>0){
insert lstResponses;
}
}else{
//Error
System.debug('PAK_AcctProvWS: Ocurrio un error porfavor de comunicarse con el administrador del sistema');
} 
}catch(Exception e){
System.debug('PAK_AcctProvWS: Error: ' + e.getLineNumber()+'------------'+e.getMessage() + '------' + e.getStackTraceString());
}
}*/
}