respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venta_Sap__c</fullName>
        <label>Venta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sin Asignar</fullName>
                </value>
                <value>
                    <fullName>Credito</fullName>
                </value>
                <value>
                    <fullName>Contado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Air_Shipment_Status__c</fullName>
        <label>Air Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contact with Origin</fullName>
                </value>
                <value>
                    <fullName>Pickup and Delivery to Airline</fullName>
                </value>
                <value>
                    <fullName>Documentation</fullName>
                </value>
                <value>
                    <fullName>Flight Confirmation</fullName>
                </value>
                <value>
                    <fullName>Layover</fullName>
                </value>
                <value>
                    <fullName>Arrival Confirmation</fullName>
                </value>
                <value>
                    <fullName>Pending with Customs Broker</fullName>
                </value>
                <value>
                    <fullName>Final Delivery</fullName>
                </value>
                <value>
                    <fullName>Finish</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Consigness Notification</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ocean_Shipment_Status__c</fullName>
        <label>Ocean Impo Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booking Confirmation</fullName>
                </value>
                <value>
                    <fullName>Pickup Confirmation</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
                <value>
                    <fullName>ETD</fullName>
                </value>
                <value>
                    <fullName>ETA-15</fullName>
                </value>
                <value>
                    <fullName>ETA-10</fullName>
                </value>
                <value>
                    <fullName>ETA-7</fullName>
                </value>
                <value>
                    <fullName>ETA-4</fullName>
                </value>
                <value>
                    <fullName>ETA</fullName>
                </value>
                <value>
                    <fullName>Telex Confirmation</fullName>
                </value>
                <value>
                    <fullName>Customs Clearences</fullName>
                </value>
                <value>
                    <fullName>Final Delivery</fullName>
                </value>
                <value>
                    <fullName>Finished</fullName>
                </value>
                <value>
                    <fullName>Pending Information</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Transport Request</fullName>
                </value>
                <value>
                    <fullName>Empty Continer Return</fullName>
                </value>
                <value>
                    <fullName>ETA -2</fullName>
                </value>
                <value>
                    <fullName>CNEE</fullName>
                </value>
                <value>
                    <fullName>EIR</fullName>
                </value>
                <value>
                    <fullName>Demurrage cut</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Booking Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment_Status_Mon__c</fullName>
        <label>Shipment Status Monitoreo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned_M</fullName>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>In Progress_M</fullName>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Awaiting load_M</fullName>
                    <label>Awaiting load</label>
                </value>
                <value>
                    <fullName>Loading_M</fullName>
                    <label>Loading</label>
                </value>
                <value>
                    <fullName>Delivery on Route_M</fullName>
                    <label>Delivery on Route</label>
                </value>
                <value>
                    <fullName>Awaiting Unload_M</fullName>
                    <label>Awaiting Unload</label>
                </value>
                <value>
                    <fullName>Unloading_M</fullName>
                    <label>Unloading</label>
                </value>
                <value>
                    <fullName>Finished_M</fullName>
                    <label>Finished</label>
                </value>
                <value>
                    <fullName>Failure_M</fullName>
                    <label>Failure</label>
                </value>
                <value>
                    <fullName>Incident_M</fullName>
                    <label>Incident</label>
                </value>
                <value>
                    <fullName>Cancel_M</fullName>
                    <label>Cancel</label>
                </value>
                <value>
                    <fullName>In Warehouse_M</fullName>
                    <label>In Warehouse</label>
                </value>
                <value>
                    <fullName>False_M</fullName>
                    <label>False</label>
                </value>
                <value>
                    <fullName>Operative Failure_M</fullName>
                    <label>Operative Failure</label>
                </value>
                <value>
                    <fullName>Robo_M</fullName>
                    <label>Robo</label>
                </value>
                <value>
                    <fullName>Error en Monitoreo_M</fullName>
                    <label>Error en Monitoreo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment_Status_Plann__c</fullName>
        <label>Shipment Status Planner</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Re assigned</fullName>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Rejected PakControl</fullName>
                </value>
                <value>
                    <fullName>Operative Failure</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Delivery on Route</fullName>
                    <isActive>false</isActive>
                    <label>Delivery On Route</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment_Status__c</fullName>
        <label>Ocean Expo Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending but Pre-Captured</fullName>
                    <default>true</default>
                    <label>Schedules</label>
                </value>
                <value>
                    <fullName>Booking Confirmation</fullName>
                </value>
                <value>
                    <fullName>Planned for delivery - Not yet on route</fullName>
                    <label>Pickup</label>
                </value>
                <value>
                    <fullName>Captured but not yet sent EDI</fullName>
                    <label>Documents</label>
                </value>
                <value>
                    <fullName>Pending - Missing Documents/Instructions</fullName>
                    <label>Shipping Instructions / VGM</label>
                </value>
                <value>
                    <fullName>Submitted to Customs</fullName>
                    <label>Cut Off</label>
                </value>
                <value>
                    <fullName>Cleared but Awaiting Vessel</fullName>
                    <label>BL Draft</label>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                    <label>ETD</label>
                </value>
                <value>
                    <fullName>Cleared but Stopped</fullName>
                    <label>Invoice</label>
                </value>
                <value>
                    <fullName>Delivered to Depot</fullName>
                    <label>MBL/HBL</label>
                </value>
                <value>
                    <fullName>Agent Notified</fullName>
                    <label>Payment</label>
                </value>
                <value>
                    <fullName>ETA -15</fullName>
                </value>
                <value>
                    <fullName>ETA -10</fullName>
                </value>
                <value>
                    <fullName>ETA -7</fullName>
                </value>
                <value>
                    <fullName>ETA -4</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <label>ETA</label>
                </value>
                <value>
                    <fullName>TLX Confirmation</fullName>
                </value>
                <value>
                    <fullName>Delivery On route</fullName>
                </value>
                <value>
                    <fullName>Finished</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment_Type__c</fullName>
        <formula>LEFT(RIGHT(Name, LEN(Name) - FIND (&quot;-&quot;, Name)), FIND(&quot;-&quot; , RIGHT(Name, LEN(Name) - FIND (&quot;-&quot;, Name)))-1)</formula>
        <label>Shipment_Type</label>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_ShipmentSender.cls
public class P2G_ShipmentSender {
    
    public static void enviar(Id shipmentId) {        
        // Validar antes de enviar
        if (!debeEnviar(shipmentId)) {
            System.debug('Shipment no cumple condiciones para envío automático: ' + shipmentId);
            return;
        }
        
        // Ejecutar envío asíncrono
        enviarAsync(shipmentId);
    }
    
    private static Boolean debeEnviar(Id shipmentId) {        
        try {
            Boolean flagSendSAP=false;
            List<Shipment__c> ships = [
                SELECT Id, Name, Shipment_Type__c, Shipment_Status_Mon__c,
                       Ocean_Shipment_Status__c, Shipment_Status__c,
                       Air_Shipment_Status__c, Account_for__r.Venta_Sap__c,
                       Shipment_Status_Plann__c, Freight_Mode__c
                FROM Shipment__c 
                WHERE Id = :shipmentId 
                LIMIT 1
            ];
            System.debug('ships '+ships);
            // Ahora sí podemos validar si está vacío
            if (ships.isEmpty()) {
                System.debug('Shipment no encontrado: ' + shipmentId);
                return flagSendSAP;
            }
            
            Shipment__c ship = ships[0];
            String tipo = ship.Shipment_Type__c;

            /*
            if (tipo != 'M' && tipo != 'A') {
                System.debug('Tipo no válido: ' + tipo);
                return false;
            }            
            
            if (tipo == 'M') {
                if (ship.Ocean_Shipment_Status__c == 'ETD' || ship.Shipment_Status__c == 'ETD') {
                    System.debug('Tipo M - ETD encontrado');
                    return true;
                } else {
                    System.debug('Tipo M - No se encontró ETD. Ocean: ' + ship.Ocean_Shipment_Status__c + 
                                 ' | Shipment: ' + ship.Shipment_Status__c);
                    return false;
                }
            }
            
            if (tipo == 'A') {
                if (ship.Air_Shipment_Status__c == 'Flight Confirmation') {
                    System.debug('Tipo A - Flight Confirmation encontrado');
                    return true;
                } else {
                    System.debug('Tipo A - Air_Shipment_Status__c: ' + ship.Air_Shipment_Status__c);
                    return false;
                }
            }*/
            switch on tipo{
                when 'M'{                    
                    //Maritimo Import
                    if(ship.Account_for__r.Venta_Sap__c == 'Credito' && ship.Ocean_Shipment_Status__c == 'ETD') {
                        System.debug('Tipo M - ETD encontrado');
                        flagSendSAP=true;
                    } 
                    
                    if(ship.Account_for__r.Venta_Sap__c == 'Contado' && ship.Ocean_Shipment_Status__c == 'Booking Confirmation') {
                        System.debug('Tipo M - Booking Confirmation encontrado');
                        flagSendSAP=true;
                    }
                    
                    //Maritimo Export
                    if(ship.Account_for__r.Venta_Sap__c == 'Credito' && ship.Shipment_Status__c == 'Delivered') {
                        System.debug('Tipo M - ETD encontrado');
                        flagSendSAP=true;
                    } 
                    //Schedules -> Pending but Pre-Captured
                    if(ship.Account_for__r.Venta_Sap__c == 'Contado' && ship.Shipment_Status__c == 'Pending but Pre-Captured') {
                        System.debug('Tipo M - Booking Confirmation encontrado');
                       	flagSendSAP=true;
                    }                    
                    /*
                     else {
                        System.debug('Tipo M - No se encontró ETD. Ocean: ' + ship.Ocean_Shipment_Status__c + 
                                     ' | Shipment: ' + ship.Shipment_Status__c);
                        return false;
                    }*/
                }
                when 'A'{
                    if (ship.Account_for__r.Venta_Sap__c == 'Credito' && ship.Air_Shipment_Status__c == 'Flight Confirmation') {
                        System.debug('Tipo A - Flight Confirmation encontrado');
                        flagSendSAP=true;
                    }
                    if (ship.Account_for__r.Venta_Sap__c == 'Contado' && ship.Air_Shipment_Status__c == 'Contact with Origin') {
                        System.debug('Tipo A - Contact with Origin encontrado');
                        flagSendSAP=true;
                    }
                }
                when 'PTO'{
                    if(ship.Account_for__r.Venta_Sap__c == 'Credito' && ship.Shipment_Status_Mon__c=='Delivery on Route_M' ){
                        System.debug('Tipo PTO - Delivery on route encontrado');
                        flagSendSAP=true;
                    }
                    if(ship.Account_for__r.Venta_Sap__c == 'Contado' && ship.Shipment_Status_Mon__c=='In Progress_M'){
                        System.debug('Tipo PTO - In progress encontrado');
                        flagSendSAP=true;
                    }
                }
                when 'FI'{                    
                    if(ship.Account_for__r.Venta_Sap__c == 'Credito' && ship.Shipment_Status_Mon__c=='Delivery on Route_M' ){
                        System.debug('Tipo PTO - Delivery on route encontrado');
                        flagSendSAP=true;
                    }
                    if(ship.Account_for__r.Venta_Sap__c == 'Contado' && ship.Shipment_Status_Mon__c=='In Progress_M'){
                        System.debug('Tipo PTO - In progress encontrado');
                        flagSendSAP=true;
                    }                    
                }
                when 'FN'{         
                    System.debug('Entra a los FN');
                    if(ship.Account_for__r.Venta_Sap__c == 'Credito' && ship.Shipment_Status_Mon__c=='Delivery on Route_M' ){                        
                        System.debug('Tipo FN - Delivery on route encontrado');
                        flagSendSAP=true;
                    }
                    if(ship.Account_for__r.Venta_Sap__c == 'Contado' && ship.Shipment_Status_Mon__c=='In Progress_M'){
                        System.debug('Tipo FN - In progress encontrado');
                        flagSendSAP=true;
                    }
                }
                when 'PQ'{
                     if(ship.Account_for__r.Venta_Sap__c == 'Contado' && ship.Shipment_Status_Plann__c == 'In progress') {
                        System.debug('Tipo PQ - In progress');
                        flagSendSAP=true;
                    }

                    if(ship.Account_for__r.Venta_Sap__c == 'Credito' && ship.Shipment_Status_Plann__c == 'Confirmed') {
                        System.debug('Tipo PQ - Confirmed');
                        flagSendSAP=true;
                    }                    
                }
                when 'W'{
                    //ETD -> Delivered
                    if(ship.Account_for__r.Venta_Sap__c == 'Credito' && ship.Shipment_Status__c == 'Delivered') {
                        System.debug('Tipo W - Delivered encontrado');
                        flagSendSAP=true;
                    }
                }

                when 'R'{
                    if(ship.Freight_Mode__c=='Air'){
                        if(ship.Account_for__r.Venta_Sap__c == 'Credito' && ship.Air_Shipment_Status__c=='Consigness Notification'){
                            System.debug('Tipo R/Air - Consigness Notification encontrado');
                            flagSendSAP=true;                            
                        }                        
                    }
                    if(ship.Freight_Mode__c=='Sea'){
                        if(ship.Account_for__r.Venta_Sap__c == 'Credito' && ship.Shipment_Status__c=='ETA -15'){
                            System.debug('Tipo R/SEA - ETA-15 encontrado');
                            flagSendSAP=true;
                        }                        
                    }                    
                    
                }
                when 'AW'{
                    if(ship.Account_for__r.Venta_Sap__c == 'Credito' && ship.Air_Shipment_Status__c=='Pickup and Delivery to Airline'){
                        System.debug('Tipo AW - Pickup and Delivery to Airline encontrado');
                        flagSendSAP=true;
                    }
                }
                when else{
                    System.debug('No entra en ninguna condicion encontrado');                    
                }                
            }
            return flagSendSAP;
                        
        } catch (Exception e) {
            System.debug('Error en validación: ' + e.getMessage());
            return false;
        }
    }
    
    private static void enviarAsync(Id shipmentId) {
        Boolean flagSendToSAPTest=Boolean.valueOf(System.Label.SendToSAPTest);
        //= Boolean.valueOf(System.Label.SendToSAPTest);
        try {
            Shipment__c mockShipment = new Shipment__c(Id = shipmentId);
            ApexPages.StandardController mockController = new ApexPages.StandardController(mockShipment);
            
            // Ejecutar tu clase existente
            if(flagSendToSAPTest){
            	System.debug('Envio exitoso para Shipment Test: ' + shipmentId);    
            }else{
                PAK_SendToOrder sendToOrder = new PAK_SendToOrder(mockController);
            	sendToOrder.IdShipment = shipmentId;
            	sendToOrder.SendWS();   
                System.debug('Envio exitoso para Shipment: ' + shipmentId);                	
            }                        
            
            
        } catch (Exception e) {
            System.debug('Error en envío para Shipment ' + shipmentId + ': ' + e.getMessage());
        }
    }
}