respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Carrier_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Carrier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Carrier Account)</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomRate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tarifario</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fee_Category__c</fullName>
        <inlineHelpText>Be aware that if you change the values of this picklist the hard corde of the Import-Export PDF quote must also be changed by our end.</inlineHelpText>
        <label>Rate Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Road Freights</fullName>
                    <default>true</default>
                    <label>Road Freights</label>
                </value>
                <value>
                    <fullName>Other Service Charges</fullName>
                </value>
                <value>
                    <fullName>Sea Freights</fullName>
                </value>
                <value>
                    <fullName>Air Freights</fullName>
                </value>
                <value>
                    <fullName>POL Charges</fullName>
                </value>
                <value>
                    <fullName>POD Charges</fullName>
                </value>
                <value>
                    <fullName>Drayages</fullName>
                </value>
                <value>
                    <fullName>Mayoreo</fullName>
                </value>
                <value>
                    <fullName>Tarimas</fullName>
                </value>
                <value>
                    <fullName>Warehouse</fullName>
                </value>
                <value>
                    <fullName>IMPAK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sell Rate</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>% Service Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GroupGVS</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Negociacion__c</fullName>
        <label>Negociacion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SI</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                    <default>true</default>
                    <label>Fixed</label>
                </value>
                <value>
                    <fullName>Per Kg</fullName>
                </value>
                <value>
                    <fullName>Per M3</fullName>
                </value>
                <value>
                    <fullName>Per Container</fullName>
                </value>
                <value>
                    <fullName>Per TON</fullName>
                </value>
                <value>
                    <fullName>Per Pallet</fullName>
                </value>
                <value>
                    <fullName>Per Day</fullName>
                </value>
                <value>
                    <fullName>% of Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Service_Type_Buy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SAP Service Type Buy</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Group__c</field>
                <operation>equals</operation>
                <valueField>SAP_Service_Type__c.Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>SAP_Service_Type__c.Activo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Service_Type__c</referenceTo>
        <relationshipLabel>Services Rates (SAP Service Type Buy)</relationshipLabel>
        <relationshipName>Services_Rates1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Service_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SAP Service Type Sell</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Group__c</field>
                <operation>equals</operation>
                <valueField>SAP_Service_Type__c.Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>SAP_Service_Type__c.Activo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Service_Type__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Services_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TT_Days__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <label>TT Days</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tarifario_Compras__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tarifario Compras</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Until__c</fullName>
        <defaultValue>now()</defaultValue>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <recordTypes>
        <fullName>Fee_Freight</fullName>
        <active>true</active>
        <label>Sea/Ground Freight</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_FileUploaderController.cls
public class P2G_FileUploaderController {
    
    @TestVisible
    private static final List<String> EXPECTED_HEADERS_CLIENTES = new List<String>{
        'Nombre del Cliente',
        'Customer ID',
        'Ruta',
        'Sap service Type Sell',
        'Sap service Type Buy',
        'Sell Rate',
        'Valid From dd/mm/yyyy',
        'Valid Until dd/mm/yyyy',
        'Container Type'
    };
    
    @TestVisible
    private static final List<String> EXPECTED_HEADERS_PROVEEDORES = new List<String>{
        'Nombre del Proveedor',
        'Customer ID',
        'Ruta',
        'Sap service Type Sell',
        'Sap service Type Buy',
        'Sell Rate',
        'Valid From dd/mm/yyyy',
        'Valid Until dd/mm/yyyy',
        'Container Type'
    };
    
    @AuraEnabled
    public static String procesarCSV(String csvContent, String operacion) {
        
        if (String.isBlank(csvContent)) {
            throw new AuraHandledException('El contenido del archivo está vacío.');
        }
        
        List<String> lines = csvContent.split('\\r?\\n');
        
        if (lines.size() < 2) {
            throw new AuraHandledException('El archivo debe contener al menos una fila de datos.');
        }
        
        List<String> headers = obtenerHeaders(lines[0]);
        
        List<String> expectedHeaders;
        if ('proveedores'.equalsIgnoreCase(operacion)) {
            expectedHeaders = EXPECTED_HEADERS_PROVEEDORES;
        } else {
            expectedHeaders = EXPECTED_HEADERS_CLIENTES;
        }
        
        for (String required : expectedHeaders) {
            if (!headers.contains(required)) {
                throw new AuraHandledException('Falta la columna: ' + required);
            }
        }
        
        Map<String, Integer> colIndex = new Map<String, Integer>();
        for (Integer i = 0; i < headers.size(); i++) {
            colIndex.put(headers[i], i);
        }
        
        String currentUserName = UserInfo.getName();
        List<Fee__c> feesToInsert = new List<Fee__c>();
        List<String> errorMessages = new List<String>();
        
        Id feeRecordTypeId = getFeeRecordTypeId(operacion);
        
        for (Integer rowIdx = 1; rowIdx < lines.size(); rowIdx++) {
            
            String line = lines[rowIdx];
            if (String.isBlank(line)) {
                continue;
            }
            
            List<String> values = line.split(',', -1);
            while (values.size() < headers.size()) {
                values.add('');
            }
            
            try {
                String nombreEntidad;
                if ('proveedores'.equalsIgnoreCase(operacion)) {
                    nombreEntidad = getValue(values, colIndex, 'Nombre del Proveedor');
                } else {
                    nombreEntidad = getValue(values, colIndex, 'Nombre del Cliente');
                }
                
                String customerId = getValue(values, colIndex, 'Customer ID');
                String ruta = getValue(values, colIndex, 'Ruta');
                String sapSell = getValue(values, colIndex, 'Sap service Type Sell');
                String sapBuy = getValue(values, colIndex, 'Sap service Type Buy');
                String sellRateStr = getValue(values, colIndex, 'Sell Rate');
                String validFromStr = getValue(values, colIndex, 'Valid From dd/mm/yyyy');
                String validUntilStr = getValue(values, colIndex, 'Valid Until dd/mm/yyyy');
                String containerType = getValue(values, colIndex, 'Container Type');
                                
                Id accountId = getAccountId(nombreEntidad, customerId);
                                
                Id clientePorDefectoId = null;
                if ('proveedores'.equalsIgnoreCase(operacion)) {
                    clientePorDefectoId = getClientePorDefecto();
                }
                
                Id routeId = getRouteId(ruta);
                Id sapSellId = getSAPServiceTypeId(sapSell);
                Id sapBuyId = getSAPServiceTypeId(sapBuy);
                Id containerTypeId = getContainerTypeId(containerType);
                
                Date validFrom = parseDate(validFromStr);
                Date validUntil = parseDate(validUntilStr);
                Decimal sellRate = Decimal.valueOf(sellRateStr);
                
                Fee__c fee = new Fee__c();
                
                if ('proveedores'.equalsIgnoreCase(operacion)) {
                    fee.Carrier_Account__c = accountId;          
                    fee.Account_for__c = clientePorDefectoId;    
                } else {
                    fee.Account_for__c = accountId;              
                }
                
                fee.Route__c = routeId;
                fee.SAP_Service_Type__c = sapSellId;
                fee.SAP_Service_Type_Buy__c = sapBuyId;
                fee.Fee_Rate__c = sellRate;
                fee.Valid_From__c = validFrom;
                fee.Valid_Until__c = validUntil;
                fee.Container_Type__c = containerTypeId;
                
                fee.Comments__c = 'Se creó por solicitud del usuario ' + currentUserName;
                fee.CustomRate__c = true;
                fee.Active__c = true;
                fee.Fee_Category__c = 'Road Freights';
                fee.Group__c = 'SP-FN-FLETE NACIONAL';
                fee.Name = 'Tarifas nacionales';
                fee.Negociacion__c = 'SI';
                fee.Rate_Type__c = 'Fixed';
                fee.RecordTypeId = feeRecordTypeId;
                fee.Tarifario_Compras__c = true;
                fee.TT_Days__c = '1';
                
                feesToInsert.add(fee);
                
            } catch (Exception e) {
                errorMessages.add('Fila ' + (rowIdx + 1) + ': ' + e.getMessage());
            }
        }
        
        Integer insertedCount = 0;
        if (!feesToInsert.isEmpty()) {
            Database.SaveResult[] results = Database.insert(feesToInsert, false);
            for (Integer i = 0; i < results.size(); i++) {
                if (results[i].isSuccess()) {
                    insertedCount++;
                } else {
                    for (Database.Error err : results[i].getErrors()) {
                        String errorDetail = 'REGISTRO ' + (i + 1) + ' | STATUS: ' + err.getStatusCode() + ' | MENSAJE: ' + err.getMessage();
                        errorMessages.add(errorDetail);
                        System.debug(LoggingLevel.ERROR, '========== ERROR INSERT FEE ==========');
                        System.debug(LoggingLevel.ERROR, errorDetail);
                        System.debug(LoggingLevel.ERROR, '=======================================');
                    }
                }
            }
        }
        
        String resultMsg = 'Registros insertados exitosamente: ' + insertedCount;
        if (!errorMessages.isEmpty()) {
            resultMsg += '\n\nErrores encontrados:\n' + String.join(errorMessages, '\n');
        }
        
        if (insertedCount == 0 && !errorMessages.isEmpty()) {
            if (Test.isRunningTest()) {
                return resultMsg;
            }
            throw new AuraHandledException(resultMsg);
        }
        
        return resultMsg;
    }
        
    private static List<String> obtenerHeaders(String lineaCabecera) {
        List<String> headers = new List<String>();
        for (String h : lineaCabecera.split(',')) {
            headers.add(h.trim());
        }
        return headers;
    }
    
    private static String getValue(List<String> values, Map<String, Integer> colIndex, String colName) {
        Integer idx = colIndex.get(colName);
        if (idx != null && idx < values.size()) {
            return values[idx] != null ? values[idx].trim() : '';
        }
        return '';
    }
    
    private static Id getAccountId(String nombreEntidad, String customerId) {
        if (String.isBlank(nombreEntidad) && String.isBlank(customerId)) {
            return null;
        }
        String query = 'SELECT Id FROM Account WHERE Name = :nombreEntidad AND Customer_Id__c = :customerId LIMIT 1';
        List<Account> accs = Database.query(query);
        if (accs.isEmpty()) {
            throw new AuraHandledException('No se encontró Account para "' + nombreEntidad + '" con Customer ID "' + customerId + '"');
        }
        return accs[0].Id;
    }
        
    private static Id getClientePorDefecto() {
        String query = 'SELECT Id FROM Account WHERE Name LIKE \'%Ejemplo%\' AND Customer_Id__c != null LIMIT 1';
        List<Account> accs = Database.query(query);
        if (accs.isEmpty()) {
            throw new AuraHandledException('No se encontró una cuenta cliente por defecto para proveedores.');
        }
        return accs[0].Id;
    }
    
    @TestVisible
    private static Id getRouteId(String ruta) {
        if (String.isBlank(ruta)) {
            return null;
        }
        String query = 'SELECT Id FROM Carrier_Line_Load_Point__c WHERE Name = :ruta LIMIT 1';
        List<Carrier_Line_Load_Point__c> routes = Database.query(query);
        if (routes.isEmpty()) {
            throw new AuraHandledException('No se encontró Ruta "' + ruta + '"');
        }
        return routes[0].Id;
    }
    
    @TestVisible
    private static Id getSAPServiceTypeId(String sapType) {
        if (String.isBlank(sapType)) {
            return null;
        }
        String query = 'SELECT Id FROM SAP_Service_Type__c WHERE Name = :sapType LIMIT 1';
        List<SAP_Service_Type__c> types = Database.query(query);
        if (types.isEmpty()) {
            throw new AuraHandledException('No se encontró SAP Service Type "' + sapType + '"');
        }
        return types[0].Id;
    }
    
    @TestVisible
    private static Id getContainerTypeId(String containerType) {
        if (String.isBlank(containerType)) {
            return null;
        }
        String query = 'SELECT Id FROM Container_Type__c WHERE Name = :containerType LIMIT 1';
        List<Container_Type__c> containers = Database.query(query);
        if (containers.isEmpty()) {
            throw new AuraHandledException('No se encontró Container Type "' + containerType + '"');
        }
        return containers[0].Id;
    }
    
    @TestVisible
    private static Date parseDate(String dateStr) {
        if (String.isBlank(dateStr)) {
            return null;
        }
        try {
            List<String> parts = dateStr.split('/');
            if (parts.size() != 3) {
                return null;
            }
            Integer day = Integer.valueOf(parts[0]);
            Integer month = Integer.valueOf(parts[1]);
            Integer year = Integer.valueOf(parts[2]);
            return Date.newInstance(year, month, day);
        } catch (Exception e) {
            throw new AuraHandledException('Fecha inválida: ' + dateStr + '. Debe ser dd/mm/yyyy');
        }
    }
    
    @TestVisible
    private static Id getFeeRecordTypeId(String operacion) {        
        String developerName = 'Fee_Freight';
        List<RecordType> recordTypes = [
            SELECT Id, Name
            FROM RecordType
            WHERE SObjectType = 'Fee__c'
            AND DeveloperName = :developerName
            LIMIT 1
        ];
        if (recordTypes.isEmpty()) {
            throw new AuraHandledException('No se encontró el Record Type "' + developerName + '" para Fee__c.');
        }
        return recordTypes[0].Id;
    }
}