respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_InternalFollower</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_External_Follower_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account External Follower User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_PartnerUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_NEU_OM_UpdateFoSupplyProjectTest.cls
@isTest
public class P2G_NEU_OM_UpdateFoSupplyProjectTest {
    @isTest
    static void NEU_OM_UpdateFoSupplyProject() //ok
    {
        
        //List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');        
        
        Account cuenta= new Account();
        cuenta.Name='Test';
        cuenta.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        cuenta.OwnerId=UserInfo.getUserId(); 
        cuenta.Account_Executive_User__c=UserInfo.getUserId();
        cuenta.Account_External_Follower_User__c=UserInfo.getUserId();
        insert cuenta;
        Contact contacto = new Contact(AccountId = cuenta.Id, LastName='test contact');
        insert contacto;
        Supply_Project__c supplyproject = new Supply_Project__c(Name='project test', Customer__c = cuenta.Id);
        insert supplyproject;
    }
}