respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Load/Discharge</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Airport_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site of Load/Discharge</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Location__c.Country__c</field>
                <operation>equals</operation>
                <valueField>$Source.Country_of_Load__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.State_of_Load_Discharge__c</field>
                <operation>equals</operation>
                <valueField>Location__c.State__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.State__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts who use this Site</relationshipLabel>
        <relationshipName>AccountsSite</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Location__c.object
<CustomObject>
    <description>Object used to define locations within given countries. Can be automatically generated from First Steps https://c.eu11.visual.force.com/apex/NEU_First_Steps</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <label>Subdivision</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNLOCODE__c</fullName>
        <label>UNLOCODE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Country_of_Discharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Discharge</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Shipments (Country of Discharge)</relationshipLabel>
        <relationshipName>Shipments_Country_of_Discharge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Load</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Shipments (Country of Load)</relationshipLabel>
        <relationshipName>Shipments_Country_of_Load</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ETA_Point_of_Discharge__c</fullName>
        <label>ETA</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ETD_from_Point_of_Load__c</fullName>
        <label>ETD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>OI Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments_Route</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_NEU_ShipmentsSearchTest.cls
@isTest
public class P2G_NEU_ShipmentsSearchTest {
    
    @isTest
    static void test_NEU_ShipmentsSearch()
    {
        
        NEU_StaticVariableHelper.setBoolean1(true);
        
        //List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        //Account a = list_accounts[0];
        //insert a;
        Account a= new Account();
        a.Name='Test';
        a.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        a.OwnerId=UserInfo.getUserId();
        insert a;
        Shipment__c ship = new Shipment__c(Name = 'SP-TS-00056', Account_for__c = a.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', ETA_Point_of_Discharge__c =system.today(), ETD_from_Point_of_Load__c = system.today(), Only_Warehouse_Service__c = true);
        insert ship;
        NEU_ShipmentsSearch ss = new NEU_ShipmentsSearch();
        ss.orden_ship_filtro_orders = 'Name';
        ss.orden_ship_filtro_orders_modo = 'asc';
        ss.orden_ship_filtro_request = 'Name';
        ss.orden_ship_filtro_request_modo = 'asc';
        ss.orden_ship_filtro_quotes = 'Name';
        ss.orden_ship_filtro_quotes_modo = 'asc';
        ss.sta_list = '';
        ss.serv_list = '';
        ss.getETD_operator_list();
        ss.getETA_operator_list();
        ss.carga_filtros();
        ss.go_compare_ship_order();
        ss.go_compare_ship_request();
        ss.search_shipments();
        ss.go_compare_ship_quote();
        ss.anterior_siguiente_Instalacion();
        ss.anterior_siguiente_order();
        ss.anterior_siguiente_request();
        
    }
    
    @isTest(SeeAllData=true)
    static void NEU_ShipmentsSearch() 
    {
        
        NEU_StaticVariableHelper.setBoolean1(true);
        
        //List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        //Account account_test = list_accounts[0];
        //insert account_test;
        Account account_test= new Account();
        account_test.Name='Test';
        account_test.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        account_test.OwnerId=UserInfo.getUserId();
        insert account_test;
        
        Country__c Country = new Country__c(Name='test country',  ISO_Code__c='EUR');
        insert Country;
        Location__c localizacion = new Location__c(Name='test localizacion', City__c='test city', Country__c= country.Id, Subdivision__c='test subdivision', UNLOCODE__c='ABC');
        insert localizacion;
        Carrier_Line_Load_Point__c route = new Carrier_Line_Load_Point__c(Name='test',  Country_of_Discharge__c=Country.Id, Country_of_Load__c=Country.Id, Port_Airport_of_Discharge__c=localizacion.Id, Port_Airport_of_Load__c=localizacion.Id);
        insert route;
        
        Shipment__c shipment_test = new Shipment__c();
        shipment_test.Account_for__c = account_test.Id;
        shipment_test.Freight_Mode__c = 'Sea';
        shipment_test.Service_Mode__c = 'Import';
        shipment_test.ETD_from_Point_of_Load__c=System.today();
        shipment_test.Route__c=route.Id;
        shipment_test.Only_Warehouse_Service__c = true;
        shipment_test.Name = 'SP-TS-00058';
        insert shipment_test;
        
        NEU_ShipmentsSearch c = new NEU_ShipmentsSearch();
        c.shipment_status=c.shipment_status;
        c.shipments_requests=c.shipments_requests;
        c.shipments_quotes=c.shipments_quotes;
        c.shipments_orders=c.shipments_quotes;
        c.sta_list=c.sta_list;
        c.serv_list=c.serv_list;
        c.sta_list='[]';
        c.serv_list='[]';
        c.id_record_type_requests=c.id_record_type_requests;
        c.id_record_type_quotes=c.id_record_type_quotes;
        c.id_record_type_orders=c.id_record_type_orders;
        c.orden_ship_filtro_orders=c.orden_ship_filtro_orders;
        c.orden_ship_filtro_orders_modo=c.orden_ship_filtro_orders_modo;
        c.orden_ship_filtro_quotes=c.orden_ship_filtro_quotes;
        c.orden_ship_filtro_quotes_modo=c.orden_ship_filtro_quotes_modo;
        c.orden_ship_filtro_request=c.orden_ship_filtro_request;
        c.orden_ship_filtro_request_modo=c.orden_ship_filtro_request_modo;
        c.orden_ship_filtro_orders='Name';
        c.orden_ship_filtro_orders_modo='asc';
        c.orden_ship_filtro_quotes='Name';
        c.orden_ship_filtro_quotes_modo='asc';
        c.orden_ship_filtro_request='Name';
        c.orden_ship_filtro_request_modo='asc';
        c.url_tracking_externa=c.url_tracking_externa;
        c.params=c.params;
        c.ETD_operator_selected=c.ETD_operator_selected;
        c.getETD_operator_list();
        c.ETA_operator_selected=c.ETA_operator_selected;
        c.getETA_operator_list();
        c.carga_filtros();
        c.record.ETD_from_Point_of_Load__c=System.today();
        c.record.ETA_Point_of_Discharge__c=System.today();
        c.record.Route__c=route.Id;
        c.ETD_operator_selected='not equal to';
        c.ETA_operator_selected='not equal to';
        c.go_compare_ship_order();
        c.go_compare_ship_quote();
        c.go_compare_ship_request();
        c.search_shipments();
        
    }
}