respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operation_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operation Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Break-bulk</fullName>
                </value>
                <value>
                    <fullName>Containerised</fullName>
                </value>
                <value>
                    <fullName>LCL Cargo</fullName>
                </value>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>CONSOLIDADO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warehouse_Movement_Type__c</fullName>
        <label>Warehouse Movement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Entries (In)</fullName>
                </value>
                <value>
                    <fullName>Deliveries (Out)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_NEU_GenerateWEDocSaveTest.cls
@isTest
public class P2G_NEU_GenerateWEDocSaveTest {
    
    @isTest(SeeAllData=true)
    static void testConstructor() {
        
        Account acc= new Account();
        acc.Name='Test';
        acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        acc.OwnerId=UserInfo.getUserId();
        insert acc;
        
        Shipment__c sp = new Shipment__c ();
        sp.Name = 'SP-FN-21-280888';                      
        sp.Freight_Mode__c = 'Road';
        sp.Account_for__c=acc.Id;             
        sp.Service_Mode__c = 'NATIONAL';
        sp.Service_Type__c =  'LTL';        
        sp.Only_Warehouse_Service__c = false;                    
        sp.Operation_Executive__c = userinfo.getUserId();                 
        sp.Warehouse_Movement_Type__c = 'Entries (In)';
        insert sp;  
        
        
        Test.startTest();
        ApexPages.StandardController stdController = new ApexPages.StandardController(sp);
        NEU_GenerateWEDocSave controller = new NEU_GenerateWEDocSave(stdController);
        Test.stopTest();        
    }
    
    @isTest(SeeAllData=true)
    static void testConstructorWithException() {        
        Shipment__c invalidShipment = new Shipment__c();
        
        Test.startTest();
        ApexPages.StandardController stdController = new ApexPages.StandardController(invalidShipment);
        NEU_GenerateWEDocSave controller = new NEU_GenerateWEDocSave(stdController);
        Test.stopTest();
        
    }
    
    @isTest(SeeAllData=true)
    static void testCrearForEntry() {
        Account acc= new Account();
        acc.Name='Test';
        acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        acc.OwnerId=UserInfo.getUserId();
        insert acc;
        
        Shipment__c sp = new Shipment__c ();
        sp.Name = 'SP-FN-21-280888';                      
        sp.Freight_Mode__c = 'Road';
        sp.Account_for__c=acc.Id;             
        sp.Service_Mode__c = 'NATIONAL';
        sp.Service_Type__c =  'LTL';        
        sp.Only_Warehouse_Service__c = false;                    
        sp.Operation_Executive__c = userinfo.getUserId();                 
        sp.Warehouse_Movement_Type__c = 'Entries (In)';
        insert sp;  
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(sp);
        NEU_GenerateWEDocSave controller = new NEU_GenerateWEDocSave(stdController);
        
        Test.setCurrentPage(Page.NEU_GenerateWEDoc);
        ApexPages.currentPage().getParameters().put('id', sp.Id);
        
        Test.startTest();
        PageReference result = controller.crear();
        Test.stopTest();        
    }
    
    @isTest(SeeAllData=true)
    static void testCrearForDelivery() {
        Account acc= new Account();
        acc.Name='Test';
        acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        acc.OwnerId=UserInfo.getUserId();
        insert acc;
        
        Shipment__c sp = new Shipment__c ();
        sp.Name = 'SP-FN-21-280888';                      
        sp.Freight_Mode__c = 'Road';
        sp.Account_for__c=acc.Id;             
        sp.Service_Mode__c = 'NATIONAL';
        sp.Service_Type__c =  'LTL';        
        sp.Only_Warehouse_Service__c = false;                    
        sp.Operation_Executive__c = userinfo.getUserId();                 
        sp.Warehouse_Movement_Type__c = 'Entries (In)';
        insert sp;  
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(sp);
        NEU_GenerateWEDocSave controller = new NEU_GenerateWEDocSave(stdController);
        
        Test.setCurrentPage(Page.NEU_GenerateWEDoc);
        ApexPages.currentPage().getParameters().put('id', sp.Id);
        
        Test.startTest();
        PageReference result = controller.crear();
        Test.stopTest();        
    }
    
    @isTest(SeeAllData=true)
    static void testCrearWithVisualforceException() {
        Account acc= new Account();
        acc.Name='Test';
        acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        acc.OwnerId=UserInfo.getUserId();
        insert acc;
        
        Shipment__c sp = new Shipment__c ();
        sp.Name = 'SP-FN-21-280888';                      
        sp.Freight_Mode__c = 'Road';
        sp.Account_for__c=acc.Id;             
        sp.Service_Mode__c = 'NATIONAL';
        sp.Service_Type__c =  'LTL';        
        sp.Only_Warehouse_Service__c = false;                    
        sp.Operation_Executive__c = userinfo.getUserId();                 
        sp.Warehouse_Movement_Type__c = 'Entries (In)';
        insert sp;  
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(sp);
        NEU_GenerateWEDocSave controller = new NEU_GenerateWEDocSave(stdController);
        
        Test.startTest();
        PageReference result = controller.crear();
        Test.stopTest();        
    }
    
    @isTest(SeeAllData=true)
    static void testCrearWithDMLException() {
        Account acc= new Account();
        acc.Name='Test';
        acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        acc.OwnerId=UserInfo.getUserId();
        insert acc;
        
        Shipment__c sp = new Shipment__c ();
        sp.Name = 'SP-FN-21-280888';                      
        sp.Freight_Mode__c = 'Road';
        sp.Account_for__c=acc.Id;             
        sp.Service_Mode__c = 'NATIONAL';
        sp.Service_Type__c =  'LTL';        
        sp.Only_Warehouse_Service__c = false;                    
        sp.Operation_Executive__c = userinfo.getUserId();                 
        sp.Warehouse_Movement_Type__c = 'Entries (In)';
        insert sp;  
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(sp);
        NEU_GenerateWEDocSave controller = new NEU_GenerateWEDocSave(stdController);
        
        controller.documento_asociado.Name = null;
        
        Test.setCurrentPage(Page.NEU_GenerateWEDoc);
        ApexPages.currentPage().getParameters().put('id', sp.Id);
        
        Test.startTest();
        PageReference result = controller.crear();
        Test.stopTest();
    }
    
    @isTest
    static void testDocumentoAsociadoProperty() {
        NEU_GenerateWEDocSave controller = new NEU_GenerateWEDocSave(new ApexPages.StandardController(new Shipment__c()));
        
        Test.startTest();
        Document doc = controller.documento_asociado;
        Test.stopTest();        
    }
    
    @isTest(SeeAllData=true)
    static void pageReferenceCrearTest() {
        // Obtener datos de prueba
        Shipment__c sp = [SELECT Id, Name, Warehouse_Movement_Type__c, Account_for__c 
                          FROM Shipment__c LIMIT 1];        
        List<Folder> directorio = [SELECT Id, Name FROM Folder LIMIT 1];
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(sp);
        
        
        Test.startTest();
        
        // Configurar página y parámetros
        PageReference pdf = Page.NEU_GenerateWEDoc;
        pdf.getParameters().put('id', sp.Id);
        
        // Obtener contenido del PDF
        Blob body;
        try {
            body = pdf.getContent();            
        } catch(VisualforceException e) {
            body = Blob.valueOf('Some Text');
        }
        
        
        
        NEU_GenerateWEDocSave controller = new NEU_GenerateWEDocSave(stdController);
        
        controller.record = sp;
        
        Document doc = new Document();
        doc.Body = body;
        doc.Name = sp.Name + '_Warehouse_' + 
            (sp.Warehouse_Movement_Type__c == 'Entries (In)' ? 'Recepcion' : 
             (sp.Warehouse_Movement_Type__c == 'Deliveries (Out)' ? 'Embarque' : '')) + '.pdf';
        doc.AuthorId = UserInfo.getUserId();
        doc.FolderId = directorio.isEmpty() ? null : directorio[0].Id;
        doc.IsPublic = true;
        
        controller.documento_asociado = doc;
        
        Test.stopTest();    
    }
}