respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_InternalFollower</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Associated_Document__c.object
<CustomObject>
    <description>Import space for documents created and associated to an Account, Import-Export and/or shipment.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Document_URL__c</fullName>
        <label>Document URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Import-Export Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer_Quote__c.Account_for__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supply_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supply Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supply_Project__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supply_Project__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Document</label>
    <nameField>
        <label>Associated Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <formula>Account_for__r.Owner.FirstName  &amp; &quot; &quot; &amp;Account_for__r.Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner (Sales Executive)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_for_Billing_Address__c</fullName>
        <description>Specify Billing Address with parameters: Street, City, Postal Code, State and Country</description>
        <formula>Account_for__r.BillingStreet  &amp; &quot;, &quot; &amp;  Account_for__r.BillingCity &amp; &quot;, &quot; &amp;  Account_for__r.BillingPostalCode &amp; &quot;, &quot; &amp;  Account_for__r.BillingState &amp; &quot;, &quot; &amp;  Account_for__r.BillingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account for (Billing Address)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_for_Shipping_Address__c</fullName>
        <description>Specify Shipping Street, City, Postal Code, State and Country</description>
        <formula>Account_for__r.ShippingStreet  &amp; &quot;, &quot; &amp;  Account_for__r.ShippingCity  &amp; &quot;, &quot; &amp; Account_for__r.ShippingPostalCode  &amp; &quot;, &quot; &amp;  Account_for__r.ShippingState &amp; &quot;, &quot; &amp;  Account_for__r.ShippingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account for (Shipping Address)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Approved_Date__c</fullName>
        <label>Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comparison_Search__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comparison Search</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders - Comparison Search</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Dependent on Account for (Customer)</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Contact)</relationshipLabel>
        <relationshipName>Import_Export_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <inlineHelpText>Only Approved as Succesfull Quotes will be available for Pick &amp; Ship</inlineHelpText>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote being prepared</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Quote being prepared</label>
                </value>
                <value>
                    <fullName>Awaiting costs suppliers</fullName>
                    <color>#FF0000</color>
                    <label>Awaiting costs suppliers</label>
                </value>
                <value>
                    <fullName>Sent awaiting response</fullName>
                    <color>#FF6600</color>
                    <label>Sent awaiting response</label>
                </value>
                <value>
                    <fullName>Approved as Succesful</fullName>
                    <color>#006600</color>
                    <label>Approved as Succesful</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <color>#3366FF</color>
                    <label>Shipped</label>
                </value>
                <value>
                    <fullName>Quote Declined</fullName>
                    <color>#FF0000</color>
                    <label>Quote Declined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SUM_Sell_Origin_Amount_number__c</fullName>
        <label>SUM Sell Origin Amount (number)</label>
        <summarizedField>Quote_Item_Line__c.Origin_Sell_Amount_header_currency__c</summarizedField>
        <summaryForeignKey>Quote_Item_Line__c.Import_Export_Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                    <default>true</default>
                    <label>NATIONAL</label>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supply_Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supply Project Name</label>
        <referenceTo>Supply_Project__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_Import_Export_Comparison_save_pdf.cls
public with sharing class NEU_Import_Export_Comparison_save_pdf {

	public Customer_Quote__c record;
	
	public Customer_Quote__c buscador {get;set;}
	
	public String id_quote {get;set;}
    public string language {get;set;}
    public Integer numberDocuments{get;set;}
	    
	public List<Customer_Quote__c> quotes_cc {get; set;}
	
    public Document documento_asociado 
    {
        get 
        {
      		if (documento_asociado == null)
            	documento_asociado = new Document();
      		return documento_asociado;
        }
        set;
    }
    
    private List<SelectOption> newcategories=null;
    public  List<SelectOption> getnewcategories()
    {
        if(newcategories==null)
        {
            newcategories=new List<SelectOption>();
            newcategories.add(new SelectOption('EN','ENGLISH'));
            //newcategories.add(new SelectOption('ES','SPANISH'));
            language ='EN';
        }
        return newcategories;
    }
    
    public String querystring
    {
    	get
    	{
    		if(querystring==null)
    		{
		    	querystring='?id='+record.Id;
		    	querystring+='&services_charges=true';
		        if(language == 'EN' || Test.isRunningTest())
		        {
		            querystring+='&lang=en_US'; 
		        }
		        if(language == 'ES' || Test.isRunningTest())
		        {
		            querystring+='&lang=es_ES'; 
		        }
		   		String ids=getIdsOptions(); 
		        if(ids!='')
		            querystring+='&ids='+ids;
    		}
    		return querystring;
    	}
    	set;
    }
    
	ApexPages.StandardController con;
            
    public NEU_Import_Export_Comparison_save_pdf(ApexPages.StandardController stdController) 
    {
        con = stdController;
        
        try 
        { 
        	record = [SELECT Id, Name, Account_for__c,  Quotation_Status__c, Approved_Date__c, 
        			  Account_Executive_User__c, Account_for__r.Name, Account_for_Billing_Address__c,
        			  Account_for_Shipping_Address__c, Contact__r.Name, SUM_Sell_Origin_Amount_number__c, 
        			  Supply_Project_Name__r.Name, Supply_Project_Name__c, Freight_Mode__c, Service_Mode__c,
        			  Route__c
        			  FROM Customer_Quote__c 
        			  WHERE id =: con.getRecord().id limit 1 for update];
        } catch( Exception ee) { 
            record = new Customer_Quote__c();
        }
        
        quotes_cc = new List<Customer_Quote__c>();
    	quotes_cc.add(record);
        
        try 
        { 
			List<Associated_Document__c> documentos = [SELECT Id FROM Associated_Document__c WHERE Import_Export_Quote__c =: record.Id];
			numberDocuments = documentos.size();
        } catch( Exception ee) { 
            numberDocuments = 0;
        }
        
        buscador = new Customer_Quote__c();
        
    }
    
    public void updateFilters()
    {
		querystring=null;
    }
    
    public string getIdsOptions()
    {
   		String ids=''; 
        for(Customer_Quote__c ie : quotes_cc)
       	{
			if(ie.Id!=null && ie.Id != record.Id)
			{
			    if(ids=='')
		        	ids+=ie.Id;
		   		else
		        	ids+=','+ie.Id;				
			}
       	}
        return ids;  	
    }
    
    public PageReference crear()
    {
		PageReference pdf = null;
        pdf = Page.NEU_IE_Comparison_PDF;
        
        pdf.getParameters().put('id',record.Id);
        
        if(language == 'EN' || Test.isRunningTest())
        {
            pdf.getParameters().put('services_charges','true');
            pdf.getParameters().put('lang','en_US'); 
        }
        if(language == 'ES' || Test.isRunningTest())
        {
            pdf.getParameters().put('services_charges','true');
            pdf.getParameters().put('lang','es_ES'); 
        }
         
   		String ids=getIdsOptions(); 
        if(ids!='')
            pdf.getParameters().put('ids',ids);
                                
        Blob body;
        
        try 
        {
        	body = pdf.getContent();
        } 
        catch (VisualforceException e) { body = Blob.valueOf('Some Text');}
        
        List<Folder> directorio = new List<Folder>();
        directorio = [Select Id, Name from Folder where Name =:'Associated Documents'];
        documento_asociado.Body = body;
        documento_asociado.Name = record.name +'IEQ-Comparison.pdf';
        documento_asociado.AuthorId = UserInfo.getUserId();
        if(directorio.size()>0)
            documento_asociado.FolderId = directorio[0].Id;
        documento_asociado.IsPublic = true; 

        try 
        {
            if(documento_asociado.Name != '' && documento_asociado.Name != null)
                insert documento_asociado;
        }  
        catch (DMLException e)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error in File Upload.'));
        }
    
        
        Associated_Document__c new_document = new Associated_Document__c();
        
        new_document.Account__c = record.Account_for__c;
        new_document.Name = record.Name +' IEQ-Comparison.pdf';
        new_document.Import_Export_Quote__c=record.Id;
        if(record.Supply_Project_Name__r.Name != null)
            new_document.Supply_Project__c =record.Supply_Project_Name__c;
            
        new_document.Document_URL__c = '/servlet/servlet.ImageServer?id='+documento_asociado.Id+'&oid=' + UserInfo.getOrganizationId(); 
        
        try
        {
            insert new_document;
            return new PageReference('/'+record.Id);
        }
        catch(Exception ex){return null;}
             
    }
    
	public void add_quote()
	{
		updateFilters();
		
		List<Customer_Quote__c> quotes = new List<Customer_Quote__c>();
		if(buscador.Comparison_Search__c != null)
		{
			String consulta = '';
			consulta += 'SELECT Id, Name, Freight_Mode__c, Service_Mode__c, Quotation_Status__c, Route__c, Account_for__c ';
			consulta += 'FROM Customer_Quote__c WHERE Id = \''+buscador.Comparison_Search__c+'\' AND Id NOT IN :quotes_cc';
			quotes = Database.query(consulta);
		}
					
		for(Customer_Quote__c ie : quotes)
		{
			if(record.Route__c != ie.Route__c)
			{
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'The selected quote must have the same Route as main quote.'));
				break;
			}
			if(record.Account_for__c != ie.Account_for__c)
			{
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'The selected quote must have the same Account as main quote.'));
				break;
			}
			quotes_cc.add(ie);
		}
	}
	
	public void remove_quote()
	{
		updateFilters();
		Integer i = 0;
		
		if(quotes_cc.size() > 0)
		{
			for(Customer_Quote__c ie : quotes_cc)
			{
				if(ie.Id == id_quote)
					break;
				
				i++;
			}
			quotes_cc.remove(i);
		}
	}
	    
}