respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venta_Sap__c</fullName>
        <label>Venta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sin Asignar</fullName>
                </value>
                <value>
                    <fullName>Credito</fullName>
                </value>
                <value>
                    <fullName>Contado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Air_Shipment_Status__c</fullName>
        <label>Air Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contact with Origin</fullName>
                </value>
                <value>
                    <fullName>Pickup and Delivery to Airline</fullName>
                </value>
                <value>
                    <fullName>Documentation</fullName>
                </value>
                <value>
                    <fullName>Flight Confirmation</fullName>
                </value>
                <value>
                    <fullName>Layover</fullName>
                </value>
                <value>
                    <fullName>Arrival Confirmation</fullName>
                </value>
                <value>
                    <fullName>Pending with Customs Broker</fullName>
                </value>
                <value>
                    <fullName>Final Delivery</fullName>
                </value>
                <value>
                    <fullName>Finish</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Consigness Notification</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ocean_Shipment_Status__c</fullName>
        <label>Ocean Impo Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Booking Confirmation</fullName>
                </value>
                <value>
                    <fullName>Pickup Confirmation</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
                <value>
                    <fullName>ETD</fullName>
                </value>
                <value>
                    <fullName>ETA-15</fullName>
                </value>
                <value>
                    <fullName>ETA-10</fullName>
                </value>
                <value>
                    <fullName>ETA-7</fullName>
                </value>
                <value>
                    <fullName>ETA-4</fullName>
                </value>
                <value>
                    <fullName>ETA</fullName>
                </value>
                <value>
                    <fullName>Telex Confirmation</fullName>
                </value>
                <value>
                    <fullName>Customs Clearences</fullName>
                </value>
                <value>
                    <fullName>Final Delivery</fullName>
                </value>
                <value>
                    <fullName>Finished</fullName>
                </value>
                <value>
                    <fullName>Pending Information</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Transport Request</fullName>
                </value>
                <value>
                    <fullName>Empty Continer Return</fullName>
                </value>
                <value>
                    <fullName>ETA -2</fullName>
                </value>
                <value>
                    <fullName>CNEE</fullName>
                </value>
                <value>
                    <fullName>EIR</fullName>
                </value>
                <value>
                    <fullName>Demurrage cut</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Booking Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment_Status_Mon__c</fullName>
        <label>Shipment Status Monitoreo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned_M</fullName>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>In Progress_M</fullName>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Awaiting load_M</fullName>
                    <label>Awaiting load</label>
                </value>
                <value>
                    <fullName>Loading_M</fullName>
                    <label>Loading</label>
                </value>
                <value>
                    <fullName>Delivery on Route_M</fullName>
                    <label>Delivery on Route</label>
                </value>
                <value>
                    <fullName>Awaiting Unload_M</fullName>
                    <label>Awaiting Unload</label>
                </value>
                <value>
                    <fullName>Unloading_M</fullName>
                    <label>Unloading</label>
                </value>
                <value>
                    <fullName>Finished_M</fullName>
                    <label>Finished</label>
                </value>
                <value>
                    <fullName>Failure_M</fullName>
                    <label>Failure</label>
                </value>
                <value>
                    <fullName>Incident_M</fullName>
                    <label>Incident</label>
                </value>
                <value>
                    <fullName>Cancel_M</fullName>
                    <label>Cancel</label>
                </value>
                <value>
                    <fullName>In Warehouse_M</fullName>
                    <label>In Warehouse</label>
                </value>
                <value>
                    <fullName>False_M</fullName>
                    <label>False</label>
                </value>
                <value>
                    <fullName>Operative Failure_M</fullName>
                    <label>Operative Failure</label>
                </value>
                <value>
                    <fullName>Robo_M</fullName>
                    <label>Robo</label>
                </value>
                <value>
                    <fullName>Error en Monitoreo_M</fullName>
                    <label>Error en Monitoreo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment_Status_Plann__c</fullName>
        <label>Shipment Status Planner</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Re assigned</fullName>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Rejected PakControl</fullName>
                </value>
                <value>
                    <fullName>Operative Failure</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Delivery on Route</fullName>
                    <isActive>false</isActive>
                    <label>Delivery On Route</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Shipment__c</fullName>
        <description>Picklist Exclusivo para Integracion con SAP, No ultiizar</description>
        <label>Status Shipment SAP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Send to Sap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VerificacionPak__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VerificacionPak</label>
        <type>Checkbox</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PAK_SendToOrder_Test.cls
@isTest(SeeAllData=true)
public class PAK_SendToOrder_Test {
    
    @isTest
    static void testSendWS_Success() {
        // Obtener un Shipment real que tenga líneas y cumpla condiciones
        Shipment__c ship = [SELECT Id, Name, Account_for__r.Venta_Sap__c, Order__c,
                                   Shipment_Status_Plann__c, Status_Shipment__c
                            FROM Shipment__c 
                            WHERE Order__c != NULL 
                            AND Account_for__r.Venta_Sap__c != NULL
                            AND Account_for__r.Venta_Sap__c != ''
                            LIMIT 1];
        
        if (ship == null) {
            System.debug('No hay Shipment disponible para prueba');
            return;
        }
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ship);
        PAK_SendToOrder sendToOrder = new PAK_SendToOrder(sc);
        sendToOrder.IdShipment = ship.Id;
        
        PageReference result = sendToOrder.SendWS();
        
        Test.stopTest();
        
        Assert.isNull(result);
    }
    
    @isTest
    static void testSendWS_Contado() {
        // Buscar Shipment de tipo Contado
        Shipment__c ship = [SELECT Id, Name, Account_for__r.Venta_Sap__c, Order__c
                            FROM Shipment__c 
                            WHERE Account_for__r.Venta_Sap__c = 'Contado'
                            AND Order__c != NULL
                            LIMIT 1];
        
        if (ship == null) {
            System.debug('No hay Shipment Contado disponible');
            return;
        }
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ship);
        PAK_SendToOrder sendToOrder = new PAK_SendToOrder(sc);
        sendToOrder.IdShipment = ship.Id;
        
        PageReference result = sendToOrder.SendWS();
        
        Test.stopTest();
    }
    
    @isTest
    static void testSendWS_Credito() {
        // Buscar Shipment de tipo Crédito
        Shipment__c ship = [SELECT Id, Name, Account_for__r.Venta_Sap__c, Order__c
                            FROM Shipment__c 
                            WHERE Account_for__r.Venta_Sap__c = 'Credito'
                            AND Order__c != NULL
                            LIMIT 1];
        
        if (ship == null) {
            System.debug('No hay Shipment Crédito disponible');
            return;
        }
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ship);
        PAK_SendToOrder sendToOrder = new PAK_SendToOrder(sc);
        sendToOrder.IdShipment = ship.Id;
        
        PageReference result = sendToOrder.SendWS();
        
        Test.stopTest();
    }
    
    @isTest
    static void testSendWS_TipoM() {
        // Buscar Shipment tipo M (Marítimo)
        Shipment__c ship = [SELECT Id, Name, Account_for__r.Venta_Sap__c, Order__c,
                                   Service_Mode__c, Ocean_Shipment_Status__c
                            FROM Shipment__c 
                            WHERE Name LIKE '%-M-%'
                            AND Order__c != NULL
                            LIMIT 1];
        
        if (ship == null) {
            System.debug('No hay Shipment tipo M disponible');
            return;
        }
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ship);
        PAK_SendToOrder sendToOrder = new PAK_SendToOrder(sc);
        sendToOrder.IdShipment = ship.Id;
        
        PageReference result = sendToOrder.SendWS();
        
        Test.stopTest();
        
    }
    
    @isTest
    static void testSendWS_TipoA() {
        // Buscar Shipment tipo A (Aéreo)
        Shipment__c ship = [SELECT Id, Name, Account_for__r.Venta_Sap__c, Order__c,
                                   Air_Shipment_Status__c
                            FROM Shipment__c 
                            WHERE Name LIKE '%-A-%'
                            AND Order__c != NULL
                            LIMIT 1];
        
        if (ship == null) {
            System.debug('No hay Shipment tipo A disponible');
            return;
        }
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ship);
        PAK_SendToOrder sendToOrder = new PAK_SendToOrder(sc);
        sendToOrder.IdShipment = ship.Id;
        
        PageReference result = sendToOrder.SendWS();
        
        Test.stopTest();
        
    }
    
    @isTest
    static void testSendWS_TipoFN() {
        // Buscar Shipment tipo FN (Frontera Nacional)
        Shipment__c ship = [SELECT Id, Name, Account_for__r.Venta_Sap__c, Order__c,
                                   Shipment_Status_Mon__c, VerificacionPak__c
                            FROM Shipment__c 
                            WHERE Name LIKE '%-FN-%'
                            AND Order__c != NULL
                            LIMIT 1];
        
        if (ship == null) {
            System.debug('No hay Shipment tipo FN disponible');
            return;
        }
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ship);
        PAK_SendToOrder sendToOrder = new PAK_SendToOrder(sc);
        sendToOrder.IdShipment = ship.Id;
        
        PageReference result = sendToOrder.SendWS();
        
        Test.stopTest();
        
    }
    
    @isTest
    static void testSendWS_NoVentaSap() {
        // Buscar Shipment sin Venta_Sap__c configurado
        Shipment__c ship = [SELECT Id, Name, Order__c
                            FROM Shipment__c 
                            WHERE (Account_for__r.Venta_Sap__c = NULL OR Account_for__r.Venta_Sap__c = '')
                            AND Order__c != NULL
                            LIMIT 1];
        
        if (ship == null) {
            System.debug('No hay Shipment sin Venta_Sap__c disponible');
            return;
        }
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ship);
        PAK_SendToOrder sendToOrder = new PAK_SendToOrder(sc);
        sendToOrder.IdShipment = ship.Id;
        
        PageReference result = sendToOrder.SendWS();
        
        Test.stopTest();
        
    }
    
    @isTest
    static void testSendWS_WithoutLines() {
        // Buscar Shipment sin líneas de servicio
        Shipment__c ship = [SELECT Id, Name, Order__c
                            FROM Shipment__c 
                            WHERE Id NOT IN (SELECT Shipment__c FROM Shipment_Fee_Line__c)
                            AND Order__c != NULL
                            LIMIT 1];
        
        if (ship == null) {
            System.debug('No hay Shipment sin líneas disponible');
            return;
        }
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ship);
        PAK_SendToOrder sendToOrder = new PAK_SendToOrder(sc);
        sendToOrder.IdShipment = ship.Id;
        
        PageReference result = sendToOrder.SendWS();
        
        Test.stopTest();
    }
    
    @isTest
    static void testBatchMode() {
        // Probar modo batch con datos reales
        Shipment__c ship = [SELECT Id FROM Shipment__c WHERE Order__c != NULL LIMIT 1];
        
        if (ship == null) {
            System.debug('No hay Shipment disponible');
            return;
        }
        
        Test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ship);
        PAK_SendToOrder sendToOrder = new PAK_SendToOrder(sc);
        sendToOrder.IdShipment = ship.Id;
        
        // En modo batch, addMessage debe hacer System.debug, no fallar
        PageReference result = sendToOrder.SendWS();
        
        Test.stopTest();
    }
    
    @isTest
    static void testValidarEstatus() {
        // Probar método ValidarEstatus con datos reales
        Shipment__c ship = [SELECT Id, Name, Account_for__r.Venta_Sap__c, 
                                   Shipment_Status_Mon__c, Shipment_Status_Plann__c,
                                   Status_Shipment__c
                            FROM Shipment__c 
                            WHERE Order__c != NULL 
                            LIMIT 1];
        
        if (ship == null) {
            System.debug('No hay Shipment disponible');
            return;
        }
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ship);
        PAK_SendToOrder sendToOrder = new PAK_SendToOrder(sc);
        sendToOrder.IdShipment = ship.Id;
        
        // Extraer tipo del Name
        if (ship.Name != null && ship.Name.contains('-')) {
            sendToOrder.TipoShipment = ship.Name.substringBetween('-', '-');
        }

        PAK_SendToOrder.byPass();
        
    }
}