respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Barras_logisticas_pendientes__c</fullName>
        <label>Barras logisticas pendientes</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Costo_reposicion_barra_logistica__c</fullName>
        <label>Costo reposición x barra logistica</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monto_retenido_incidencias_barras__c</fullName>
        <label>Monto retenido incidencias x barras</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Retorno_barras_logisticas__c</fullName>
        <description>Captura el porcentaje de las barras logísticas devueltas</description>
        <label>% Retorno de barras logisticas</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tiempo_promedio_devolucion_barras__c</fullName>
        <label>Tiempo promedio de devolución de barras</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_barras_perdidas__c</fullName>
        <label>Total de barras perdidas</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supply Chain Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Carrier)</relationshipLabel>
        <relationshipName>Shipments_Carrier</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requiere_barras_logisticas__c</fullName>
        <defaultValue>false</defaultValue>
        <label>¿Requiere barras logisticas?</label>
        <type>Checkbox</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_GenerateBarraLogistica.cls
public class P2G_GenerateBarraLogistica {
    public void mainShipment(List<Shipment__c> newRecords, Map<Id, Shipment__c> oldMap){
        Set<Id> shipmentIds=new Set<Id>();
        Shipment__c oldShipment;
        for(Shipment__c shipment: newRecords){
            oldShipment=oldMap.get(shipment.Id);
            if(shipment.Requiere_barras_logisticas__c && 
               (shipment.Requiere_barras_logisticas__c!=oldShipment.Requiere_barras_logisticas__c) && 
               shipment.Carrier__c!=null){
                createBarraLogistica(shipment);
            }
        }
    }
    
    public static List<Barra_Logistica__c> getAllBarraLogistica(Id shipmentId){
        return [SELECT Id, Shipment__c, CreatedDate FROM Barra_Logistica__c WHERE Shipment__c =: shipmentId ORDER BY CreatedDate DESC LIMIT 1];
    }
    
    public static void createBarraLogistica(Shipment__c shipment){        
        List<Barra_Logistica__c> listBarrasLogisticas = getAllBarraLogistica(shipment.Id);
        Account getInfoCarrier=getDataToCarrier(shipment.Carrier__c);
        if(listBarrasLogisticas.isEmpty()){
            Barra_Logistica__c newBarraLogistica= new Barra_Logistica__c();
            newBarraLogistica.Shipment__c=shipment.Id;
            newBarraLogistica.Account__c=getInfoCarrier.Id;
            insert newBarraLogistica;
        }        
    }  
    
    public static Account getDataToCarrier(Id accountId){
        return [SELECT Id,Retorno_barras_logisticas__c,Barras_logisticas_pendientes__c,
                Monto_retenido_incidencias_barras__c,Tiempo_promedio_devolucion_barras__c,
                Total_barras_perdidas__c, Costo_reposicion_barra_logistica__c
                FROM Account WHERE Id=:accountId];
    }
    
    public void mainBarraLogistica(List<Barra_Logistica__c> newRecords, Map<Id, Barra_Logistica__c> oldMap){        
        Set<Id> barraLogisticaIds=new Set<Id>();
        Barra_Logistica__c oldBarraLogistica;
        for(Barra_Logistica__c barra: newRecords){
            oldBarraLogistica=oldMap.get(barra.Id);
            if((barra.Faltantes__c!=null && barra.Faltantes__c!=oldBarraLogistica.Faltantes__c) || 
               (barra.Danadas__c!=null && barra.Danadas__c!= oldBarraLogistica.Danadas__c)){
                   updateBarraLogistica(barra);				                
            }
        }
    }
    
    public static void updateBarraLogistica(Barra_Logistica__c barraLogistica){
        Account getInfoCarrier=getDataToCarrier(barraLogistica.Account__c);
        if(getInfoCarrier!=null){
            Double danadas = barraLogistica.Danadas__c != null ? barraLogistica.Danadas__c : 0;
    		Double faltantes = barraLogistica.Faltantes__c != null ? barraLogistica.Faltantes__c : 0;
    		Double costo = getInfoCarrier.Costo_reposicion_barra_logistica__c != null ? getInfoCarrier.Costo_reposicion_barra_logistica__c : 0;
			Double deudaTotalAdeudo = costo * (danadas + faltantes);
    		barraLogistica.Cargo_no_retorno__c = deudaTotalAdeudo;
            //update barraLogistica;
        }
    }
    
}