respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credit_Terms__c</fullName>
        <label>Credit Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contado</fullName>
                </value>
                <value>
                    <fullName>Pago Inmediato</fullName>
                </value>
                <value>
                    <fullName>1 Día</fullName>
                </value>
                <value>
                    <fullName>2 Días</fullName>
                </value>
                <value>
                    <fullName>3 Días</fullName>
                </value>
                <value>
                    <fullName>4 Días</fullName>
                </value>
                <value>
                    <fullName>5 Días</fullName>
                </value>
                <value>
                    <fullName>7 Días</fullName>
                </value>
                <value>
                    <fullName>8 Días</fullName>
                </value>
                <value>
                    <fullName>9 Días</fullName>
                </value>
                <value>
                    <fullName>10 Días</fullName>
                </value>
                <value>
                    <fullName>15 Días</fullName>
                </value>
                <value>
                    <fullName>16 Días</fullName>
                </value>
                <value>
                    <fullName>19 Días</fullName>
                </value>
                <value>
                    <fullName>20 Días</fullName>
                </value>
                <value>
                    <fullName>21 Días</fullName>
                </value>
                <value>
                    <fullName>22 Días</fullName>
                </value>
                <value>
                    <fullName>23 Días</fullName>
                </value>
                <value>
                    <fullName>25 Días</fullName>
                </value>
                <value>
                    <fullName>28 Días</fullName>
                </value>
                <value>
                    <fullName>31 Días</fullName>
                </value>
                <value>
                    <fullName>38 Días</fullName>
                </value>
                <value>
                    <fullName>60 Días</fullName>
                </value>
                <value>
                    <fullName>24 Dias</fullName>
                </value>
                <value>
                    <fullName>12 Dias</fullName>
                </value>
                <value>
                    <fullName>6 Días</fullName>
                </value>
                <value>
                    <fullName>50 Días</fullName>
                </value>
                <value>
                    <fullName>55 Días</fullName>
                </value>
                <value>
                    <fullName>40 Días</fullName>
                </value>
                <value>
                    <fullName>120 Días</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Pago_Contado_SAP__c</fullName>
        <label>Total Payment SAP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_PAK_PagoContadoTest.cls
@isTest
public class P2G_PAK_PagoContadoTest {
        
    @isTest(SeeAllData=true)
    static void testPagoContadoExitoso() {
        
        Shipment__c shipment = [SELECT Id, Pago_Contado_SAP__c, CurrencyIsoCode,  Account_for__r.Credit_Terms__c
                                FROM Shipment__c where Account_for__r.Credit_Terms__c!=null ORDER BY CreatedDate DESC LIMIT 1 ];
                
        PAK_PagoContado.pago pagoObj = new PAK_PagoContado.pago();
        pagoObj.shipmentId = shipment.Id;
        pagoObj.montoPago = '50.00';
        pagoObj.currencyIsoCode = 'USD';
        
        Test.startTest();        
        PAK_PagoContado.status resultado = PAK_PagoContado.pagoContado(pagoObj);
        Test.stopTest();
                        
    }
    
    
    @isTest(SeeAllData=true)
    static void testPagoContadoSinCurrencyIsoCode() {
        
        Shipment__c shipment = [SELECT Id, Pago_Contado_SAP__c, CurrencyIsoCode,  Account_for__r.Credit_Terms__c
                                FROM Shipment__c where Account_for__r.Credit_Terms__c!=null ORDER BY CreatedDate DESC LIMIT 1 ];
        String currencyOriginal = shipment.CurrencyIsoCode;
                
        PAK_PagoContado.pago pagoObj = new PAK_PagoContado.pago();
        pagoObj.shipmentId = shipment.Id;
        pagoObj.montoPago = '200.00';
        pagoObj.currencyIsoCode = '';
        
        Test.startTest();
        PAK_PagoContado.status resultado = PAK_PagoContado.pagoContado(pagoObj);
        Test.stopTest();
                
    }  
    
}