respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Last_Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer, Supplier or Agente Aduanal</inlineHelpText>
        <label>Cuenta Origen</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Shipper, Customer, Supply Chain Partner, Supplier Owner or Lessee of Vehicule, Agente Aduanal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Supplier/Shipper Account)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Supplier_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer or Supplier</inlineHelpText>
        <label>Cuenta Origen</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Supplier/Shipper Account)</relationshipLabel>
        <relationshipName>Shipments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Disbursement__c.object
<CustomObject>
    <description>Object specifying all payment history and details along with each Import-Export on each Account</description>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Disbursements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Disbursement</label>
    <nameField>
        <label>Disbursement Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_NewDisbursementButton.cls
public with sharing class NEU_NewDisbursementButton 
{
	public pagereference redirect()
	{
		string redirect_address = '';
		string prefix = Schema.getGlobalDescribe().get('Shipment_Disbursement__c').getDescribe().getKeyPrefix();
		
		if(Apexpages.currentPage().getParameters().get('import_export_id') != null)
		{
			List<Customer_Quote__c> import_export = [select Id, Name, Supplier_Account__c, Supplier_Account__r.Name from Customer_Quote__c where Id =: Apexpages.currentPage().getParameters().get('import_export_id')];
			
			if(import_export.size() > 0)
			{
				redirect_address = '/'+prefix+'/e?CF00N0Y00000Oj0bA='+import_export[0].Name+'&CF00N0Y00000Oj0bA_lkid='+import_export[0].Id+'&retURL=%2F'+import_export[0].Id+'&Name=<Se creará automáticamente>';
				if(import_export[0].Supplier_Account__c != null)
					redirect_address += '&CF00N0Y00000Oj0KV='+import_export[0].Supplier_Account__r.Name+'&CF00N0Y00000Oj0KV_lkid='+import_export[0].Supplier_Account__c;
			}
				
		}
		if(Apexpages.currentPage().getParameters().get('shipment_id') != null)
		{
			List<Shipment__c> shipment = [select Id, Name, Supplier_Account__c, Supplier_Account__r.Name from Shipment__c where Id =: Apexpages.currentPage().getParameters().get('shipment_id')];
			
			if(shipment.size() > 0)
			{
				List<Customer_Quote__c> import_export = [select Id, Name from Customer_Quote__c where Last_Shipment__c =: shipment[0].Id];

				if(import_export.size() > 0)
				{
					redirect_address = '/'+prefix+'/e?CF00N0Y00000Oj0bd='+shipment[0].Name+'&CF00N0Y00000Oj0bd_lkid='+shipment[0].Id+'&CF00N0Y00000Oj0bA='+import_export[0].Name+'&CF00N0Y00000Oj0bA_lkid='+import_export[0].Id+'&retURL=%2F'+import_export[0].Id+'&Name=<Se creará automáticamente>';
					if(shipment[0].Supplier_Account__c != null)
						redirect_address += '&CF00N0Y00000Oj0KV='+shipment[0].Supplier_Account__r.Name+'&CF00N0Y00000Oj0KV_lkid='+shipment[0].Supplier_Account__c;
				}
			}
		}
		
		PageReference pgReturnPage;
        String returnUrl = redirect_address;
        pgReturnPage = new PageReference(returnUrl);
        pgReturnPage.setRedirect(true);
        return pgReturnPage;
	}    
}