respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venta_Sap__c</fullName>
        <label>Venta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sin Asignar</fullName>
                </value>
                <value>
                    <fullName>Credito</fullName>
                </value>
                <value>
                    <fullName>Contado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Catalogo_SAT__c.object
<CustomObject>
    <description>Permite llevar el registro de los catalogos del SAT para la carta porte</description>
    <label>Catalogo SAT</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos SAT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ByPass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ByPass</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clave_de_Unidad_de_Peso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clave de Unidad de Peso</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo_SAT__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Unidad Peso</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo_SAT__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Pricing_responded__c</fullName>
        <label>Date Pricing responded</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Final Destination Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Impak_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Impak Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Margin_at_Destination_by_Default__c</fullName>
        <label>Margin at Destination by Default</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Move_Type__c</fullName>
        <label>Move Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Door to Door</fullName>
                    <default>true</default>
                    <label>Door to Door</label>
                </value>
                <value>
                    <fullName>Door to Port</fullName>
                </value>
                <value>
                    <fullName>Port to Door</fullName>
                </value>
                <value>
                    <fullName>Port to Port</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Initial Origin Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Pricing_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Import_Export_Quotes_Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                    <default>true</default>
                    <label>NATIONAL</label>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>FP</fullName>
                </value>
                <value>
                    <fullName>FO</fullName>
                </value>
                <value>
                    <fullName>MAYOREO</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venta_Sap__c</fullName>
        <formula>text(Account_for__r.Venta_Sap__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Venta</label>
        <type>Text</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Import_Export_Fee_Line__c.object
<CustomObject>
    <description>Specifies transport fees associated to an Import-Export. Child object from &quot;Freight Rates Management&quot;</description>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote/Order</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Service Lines</relationshipLabel>
        <relationshipName>Import_Export_Fees_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Quote_Sell_Price__c</fullName>
        <label>Quote Sell Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Units</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FN</fullName>
                    <default>true</default>
                    <label>FN - Flete Nacional</label>
                </value>
                <value>
                    <fullName>FI</fullName>
                    <label>FI - Flete Internacional</label>
                </value>
                <value>
                    <fullName>PQ</fullName>
                    <label>PQ - Paqueterias</label>
                </value>
                <value>
                    <fullName>T</fullName>
                    <label>T - Tarimas</label>
                </value>
                <value>
                    <fullName>M</fullName>
                    <label>M - Maritimo</label>
                </value>
                <value>
                    <fullName>A</fullName>
                    <label>A - Aereo</label>
                </value>
                <value>
                    <fullName>WH</fullName>
                    <label>WH - Almacenajes</label>
                </value>
                <value>
                    <fullName>EX-Seguros</fullName>
                </value>
                <value>
                    <fullName>PTO - Puerto</fullName>
                </value>
                <value>
                    <fullName>R - Global Routing</fullName>
                </value>
                <value>
                    <fullName>PQI - Paquertería Internacional</fullName>
                </value>
                <value>
                    <fullName>CE - Aduanas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateOppAmmountTest.cls
@isTest
public class UpdateOppAmmountTest {
    @isTest
    public static void test(){
        User us = TestDataFactory.createUserAdmin();
        Account a = new Account();
        a.Name = 'test';
        a.Customer_Id__c = '58SQL1256';
        a.OwnerId = us.Id;
        a.Venta_Sap__c = 'Contado';         
        insert a;
                
        Rol_Margen__c rm = TestDataFactory.createRolMargen('Director Comercial'); 
        Opportunity op = new Opportunity();
        op.AccountId = a.Id;
        op.Name = 'Test OP';
        op.Service_Type__c = 'FN';
        op.StageName = 'Prospecting';
        op.CloseDate = date.today() + 3;
        insert op;
        
        /*Customer_Quote__c q = new Customer_Quote__c();
        q.Name = 'Test';
        q.Account_for__c = a.Id;
        q.Only_Warehouse_Service__c = true;
        q.Opportunity__c = op.Id;
        q.Pricing_Executive__c=userinfo.getUserId();
        insert q;*/   
        
        Catalogo_SAT__c catalogo = TestDataFactory.createCatalogoSat('Caja de acero test' , 'TCA125','Unidad Peso'); 
        
        Customer_Quote__c folio = new Customer_Quote__c();
        folio.Account_for__c = a.Id;
        folio.Freight_Mode__c = 'Sea';
        folio.Service_Mode__c = 'EXPORT'; 
        folio.Service_Type__c = 'FCL';
        folio.Move_Type__c = 'Door to Door';
        folio.Origin_Address__c = 'Address Test'; 
        folio.Destination_Address__c = 'Address Test';
        folio.ByPass__c = true;
        folio.Impak_Request__c = true;
        folio.Date_Pricing_responded__c = System.today();
        folio.Clave_de_Unidad_de_Peso__c = catalogo.Id;       
        folio.Margin_at_Destination_by_Default__c = 10;
        folio.Only_Warehouse_Service__c = true;
        folio.Pricing_Executive__c = UserInfo.getUserId();
        folio.Opportunity__c = op.Id;
        insert folio;
        
        Import_Export_Fee_Line__c l = new Import_Export_Fee_Line__c();
        l.Name = '001';
        l.Import_Export_Quote__c = folio.Id;
        l.Units__c = 1;
        l.Quote_Sell_Price__c = 100;
        insert l;
    }
}