respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credit_Terms__c</fullName>
        <label>Credit Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contado</fullName>
                </value>
                <value>
                    <fullName>Pago Inmediato</fullName>
                </value>
                <value>
                    <fullName>1 Día</fullName>
                </value>
                <value>
                    <fullName>2 Días</fullName>
                </value>
                <value>
                    <fullName>3 Días</fullName>
                </value>
                <value>
                    <fullName>4 Días</fullName>
                </value>
                <value>
                    <fullName>5 Días</fullName>
                </value>
                <value>
                    <fullName>7 Días</fullName>
                </value>
                <value>
                    <fullName>8 Días</fullName>
                </value>
                <value>
                    <fullName>9 Días</fullName>
                </value>
                <value>
                    <fullName>10 Días</fullName>
                </value>
                <value>
                    <fullName>15 Días</fullName>
                </value>
                <value>
                    <fullName>16 Días</fullName>
                </value>
                <value>
                    <fullName>19 Días</fullName>
                </value>
                <value>
                    <fullName>20 Días</fullName>
                </value>
                <value>
                    <fullName>21 Días</fullName>
                </value>
                <value>
                    <fullName>22 Días</fullName>
                </value>
                <value>
                    <fullName>23 Días</fullName>
                </value>
                <value>
                    <fullName>25 Días</fullName>
                </value>
                <value>
                    <fullName>28 Días</fullName>
                </value>
                <value>
                    <fullName>31 Días</fullName>
                </value>
                <value>
                    <fullName>38 Días</fullName>
                </value>
                <value>
                    <fullName>60 Días</fullName>
                </value>
                <value>
                    <fullName>24 Dias</fullName>
                </value>
                <value>
                    <fullName>12 Dias</fullName>
                </value>
                <value>
                    <fullName>6 Días</fullName>
                </value>
                <value>
                    <fullName>50 Días</fullName>
                </value>
                <value>
                    <fullName>55 Días</fullName>
                </value>
                <value>
                    <fullName>40 Días</fullName>
                </value>
                <value>
                    <fullName>120 Días</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Comercio_Exterior__c</fullName>
        <label>Comercio Exterior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Pricing_responded__c</fullName>
        <label>Date Pricing responded</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Send_Request__c</fullName>
        <label>Date Send Request</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Final Destination Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Initial Origin Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PDF_Notes_EN__c</fullName>
        <label>PDF Notes EN</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <inlineHelpText>Only Approved as Succesfull Quotes will be available for Pick &amp; Ship</inlineHelpText>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote being prepared</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Quote being prepared</label>
                </value>
                <value>
                    <fullName>Awaiting costs suppliers</fullName>
                    <color>#FF0000</color>
                    <label>Awaiting costs suppliers</label>
                </value>
                <value>
                    <fullName>Sent awaiting response</fullName>
                    <color>#FF6600</color>
                    <label>Sent awaiting response</label>
                </value>
                <value>
                    <fullName>Approved as Succesful</fullName>
                    <color>#006600</color>
                    <label>Approved as Succesful</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <color>#3366FF</color>
                    <label>Shipped</label>
                </value>
                <value>
                    <fullName>Quote Declined</fullName>
                    <color>#FF0000</color>
                    <label>Quote Declined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                    <default>true</default>
                    <label>NATIONAL</label>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>FP</fullName>
                </value>
                <value>
                    <fullName>FO</fullName>
                </value>
                <value>
                    <fullName>MAYOREO</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Observations__c</fullName>
        <inlineHelpText>Only Approved as Successful Quotes will be available for Status Observations</inlineHelpText>
        <label>Status Observations</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <defaultValue>&quot;P2G&quot;</defaultValue>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                    <default>true</default>
                    <label>P2G</label>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ActualizaFolioIE_test.cls
@isTest
private class ActualizaFolioIE_test {

    static testMethod void ActualizaFolioIE_test () //ok
    {
        List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        Account account_test = list_accounts[0];
        account_test.Credit_Terms__c = '15 days';
        insert account_test;
        list<Customer_Quote__c> lista = new list<Customer_Quote__c>();
        lista.add(CrearQuote('Sea','IMPORT','FTL',account_test.Id));
               
        test.startTest();
         insert lista;
        test.stopTest();
    }
    static testMethod void ActualizaFolioIE_test2 () //ok
    {
        List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        Account account_test = list_accounts[0];
        account_test.Credit_Terms__c = '15 days';
        insert account_test;
        list<Customer_Quote__c> lista = new list<Customer_Quote__c>();
        lista.add(CrearQuote('Road','IMPORT','FTL',account_test.Id));
        lista.add(CrearQuote('Road','IMPORT','LTL',account_test.Id));
        lista.add(CrearQuote('Road','IMPORT','FP',account_test.Id));
        lista.add(CrearQuote('Road','IMPORT','FO',account_test.Id));
        lista.add(CrearQuote('Road','IMPORT','TARIMAS',account_test.Id));
        lista.add(CrearQuote('Road','IMPORT','MAYOREO',account_test.Id));
        lista.add(CrearQuote('Road','EXPORT','MAYOREO',account_test.Id));
        lista.add(CrearQuote('Road','EXPORT','FTL',account_test.Id));
        lista.add(CrearQuote('Road','EXPORT','LTL',account_test.Id));
        lista.add(CrearQuote('Road','EXPORT','FP',account_test.Id));
        lista.add(CrearQuote('Road','EXPORT','FO',account_test.Id));
        lista.add(CrearQuote('Road','EXPORT','TARIMAS',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','MAYOREO',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','FTL',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','LTL',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','FP',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','FO',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','TARIMAS',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','Extras',account_test.Id));
        lista.add(CrearQuote('Road','INTERNATIONAL','Extras',account_test.Id));
        lista.add(CrearQuote('Road','PORT','Extras',account_test.Id));
        
        lista.add(CrearQuote('Air','IMPORT','PAQUETERIA',account_test.Id));
        lista.add(CrearQuote('Air','IMPORT','CARGA',account_test.Id));
        lista.add(CrearQuote('Air','EXPORT','PAQUETERIA',account_test.Id));
        lista.add(CrearQuote('Air','EXPORT','CARGA',account_test.Id));
        lista.add(CrearQuote('Air','INTERNATIONAL','PAQUETERIA',account_test.Id));
        lista.add(CrearQuote('Air','INTERNATIONAL','CARGA',account_test.Id));
        lista.add(CrearQuote('Air','NATIONAL','PAQUETERIA',account_test.Id));
        lista.add(CrearQuote('Air','NATIONAL','CARGA',account_test.Id));
        lista.add(CrearQuote('Air','NATIONAL','ENVIO NACIONAL',account_test.Id));
        
        Customer_Quote__c Quote = CrearQuote('Sea','IMPORT','ENVIO NACIONAL',account_test.Id);
        Quote.Team__c = 'WCA';
        lista.add(Quote);
        
        Customer_Quote__c Quote2 = CrearQuote('Sea','EXPORT','ENVIO NACIONAL',account_test.Id);
        Quote2.Team__c = 'WCA';
        lista.add(Quote2);
        
        Customer_Quote__c Quote3 = CrearQuote('Air','EXPORT','ENVIO NACIONAL',account_test.Id);
        Quote3.Team__c = 'WCA';
        lista.add(Quote3);
        
        Customer_Quote__c Quote4 = CrearQuote('Air','IMPORT','ENVIO NACIONAL',account_test.Id);
        Quote4.Team__c = 'WCA';
       
        lista.add(Quote4);
        
        test.startTest();
        insert lista;
        
         for(Customer_Quote__c cq : lista)
        {
            cq.PDF_Notes_EN__c=null;
           
        }
        update lista;
        test.stopTest();
    }
     static testMethod void ActualizaFolioIE_test3 () //ok
    {
        List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        Account account_test = list_accounts[0];
        account_test.Credit_Terms__c = '15 days';
        insert account_test;
        list<Customer_Quote__c> lista = new list<Customer_Quote__c>();
        lista.add(CrearQuote('Road','IMPORT','FTL',account_test.Id));
        lista.add(CrearQuote('Road','IMPORT','LTL',account_test.Id));
        lista.add(CrearQuote('Road','IMPORT','FP',account_test.Id));
        lista.add(CrearQuote('Road','IMPORT','FO',account_test.Id));
        lista.add(CrearQuote('Road','IMPORT','TARIMAS',account_test.Id));
        lista.add(CrearQuote('Road','IMPORT','MAYOREO',account_test.Id));
        lista.add(CrearQuote('Road','EXPORT','MAYOREO',account_test.Id));
        lista.add(CrearQuote('Road','EXPORT','FTL',account_test.Id));
        lista.add(CrearQuote('Road','EXPORT','LTL',account_test.Id));
        lista.add(CrearQuote('Road','EXPORT','FP',account_test.Id));
        lista.add(CrearQuote('Road','EXPORT','FO',account_test.Id));
        lista.add(CrearQuote('Road','EXPORT','TARIMAS',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','MAYOREO',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','FTL',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','LTL',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','FP',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','FO',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','TARIMAS',account_test.Id));
        lista.add(CrearQuote('Road','NATIONAL','Extras',account_test.Id));
        lista.add(CrearQuote('Road','INTERNATIONAL','Extras',account_test.Id));
        lista.add(CrearQuote('Road','PORT','Extras',account_test.Id));
        
        lista.add(CrearQuote('Air','IMPORT','PAQUETERIA',account_test.Id));
        lista.add(CrearQuote('Air','IMPORT','CARGA',account_test.Id));
        lista.add(CrearQuote('Air','EXPORT','PAQUETERIA',account_test.Id));
        lista.add(CrearQuote('Air','EXPORT','CARGA',account_test.Id));
        lista.add(CrearQuote('Air','INTERNATIONAL','PAQUETERIA',account_test.Id));
        lista.add(CrearQuote('Air','INTERNATIONAL','CARGA',account_test.Id));
        lista.add(CrearQuote('Air','NATIONAL','PAQUETERIA',account_test.Id));
        lista.add(CrearQuote('Air','NATIONAL','CARGA',account_test.Id));
        lista.add(CrearQuote('Air','NATIONAL','ENVIO NACIONAL',account_test.Id));
        
        Customer_Quote__c Quote = CrearQuote('Sea','IMPORT','ENVIO NACIONAL',account_test.Id);
        Quote.Team__c = 'WCA';
        lista.add(Quote);
        
        Customer_Quote__c Quote2 = CrearQuote('Sea','EXPORT','ENVIO NACIONAL',account_test.Id);
        Quote2.Team__c = 'WCA';
        lista.add(Quote2);
        
        Customer_Quote__c Quote3 = CrearQuote('Air','EXPORT','ENVIO NACIONAL',account_test.Id);
        Quote3.Team__c = 'WCA';
        lista.add(Quote3);
        
        Customer_Quote__c Quote4 = CrearQuote('Air','IMPORT','ENVIO NACIONAL',account_test.Id);
        Quote4.Team__c = 'WCA';
       
        lista.add(Quote4);
         insert lista;
        test.startTest();
       
        
        for(Customer_Quote__c cq : lista)
        {
            cq.Origin_Address__c = 'ASD';
            cq.Only_Warehouse_Service__c = false;
           
        }
        update lista;
        
        
        test.stopTest();
    }
      static testMethod void TimeResponseTest () //ok
      {
            List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
            Account account_test = list_accounts[0];
            account_test.Credit_Terms__c = '15 days';
            insert account_test;
            list<Customer_Quote__c> lista = new list<Customer_Quote__c>();
        	lista.add(CrearQuote('Road','IMPORT','FTL',account_test.Id));
            insert lista;
           test.startTest();
       
        datetime fecha = datetime.now();
        string year = string.valueOf(Date.today().year());
                    string month = string.valueOf(Date.today().month());
                    string day = string.valueOf(fecha.addDays(2).day());
                    string hour = '15';
                    string minute = '00';
                    string second = '00';
                    string stringDate = year + '-' + month + '-' + day + ' ' + hour + ':' + minute +  ':' + second;
		Datetime DateHoy = Datetime.valueOfGMT(stringDate);
          
        for(Customer_Quote__c cq : lista)
        {
            cq.Status_Observations__c ='prueba';
            cq.Only_Warehouse_Service__c = false;
            cq.Date_Pricing_responded__c = DateHoy.addDays(3);
            cq.Date_Pricing_responded__c = DateHoy.addHours(5);
        }
        update lista;
        test.stopTest();

      }
    public static Customer_Quote__c CrearQuote(string Freight_Mode,string Service_Mode, string Service_Type, string accountId)
    {
        Customer_Quote__c importexportquote = new Customer_Quote__c();
        importexportquote.Account_for__c = accountId;
        importexportquote.Quotation_Status__c = 'Quote being prepared'; 
        importexportquote.Origin_Address__c = '';
        importexportquote.Destination_Address__c = '';  
        importexportquote.Only_Warehouse_Service__c = true;
        importexportquote.Comercio_Exterior__c = 'Si';
        importexportquote.Freight_Mode__c = Freight_Mode;
        importexportquote.Service_Mode__c =Service_Mode;
        importexportquote.Service_Type__c = Service_Type;
        string year = string.valueOf(Date.today().year());
                    string month = string.valueOf(Date.today().month());
                    string day = string.valueOf(Date.today().day());
                    string hour = '09';
                    string minute = '00';
                    string second = '00';
                    string stringDate = year + '-' + month + '-' + day + ' ' + hour + ':' + minute +  ':' + second;
		Datetime FechaCalculada = Datetime.valueOfGMT(stringDate);
        importexportquote.Date_Send_Request__c = FechaCalculada;
          year = string.valueOf(Date.today().year());
                     month = string.valueOf(Date.today().month());
                     day = string.valueOf(Date.today().day());
                     hour = '16';
                     minute = '30';
                     second = '00';
                     stringDate = year + '-' + month + '-' + day + ' ' + hour + ':' + minute +  ':' + second;
		FechaCalculada = Datetime.valueOfGMT(stringDate);
        importexportquote.Date_Pricing_responded__c = FechaCalculada;
        NEU_CurrencyUtils.setCurrencyIsoCode(importexportquote, 'MXN');
        return importexportquote;
    }
}