respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segmentacion</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nuevo</fullName>
                </value>
                <value>
                    <fullName>Bronce</fullName>
                </value>
                <value>
                    <fullName>Plata</fullName>
                </value>
                <value>
                    <fullName>Cuenta Clave</fullName>
                </value>
                <value>
                    <fullName>None1</fullName>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Oro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venta_Sap__c</fullName>
        <label>Venta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sin Asignar</fullName>
                </value>
                <value>
                    <fullName>Credito</fullName>
                </value>
                <value>
                    <fullName>Contado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkPlace__c</fullName>
        <label>WorkPlace</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MTY</fullName>
                </value>
                <value>
                    <fullName>MXN</fullName>
                </value>
                <value>
                    <fullName>SAL</fullName>
                </value>
                <value>
                    <fullName>GDL</fullName>
                </value>
                <value>
                    <fullName>CUU</fullName>
                </value>
                <value>
                    <fullName>HER</fullName>
                </value>
                <value>
                    <fullName>JUA</fullName>
                </value>
                <value>
                    <fullName>LEO</fullName>
                </value>
                <value>
                    <fullName>MXI</fullName>
                </value>
                <value>
                    <fullName>MXS</fullName>
                </value>
                <value>
                    <fullName>SLP</fullName>
                </value>
                <value>
                    <fullName>PUE</fullName>
                </value>
                <value>
                    <fullName>TIJ</fullName>
                </value>
                <value>
                    <fullName>TOL</fullName>
                </value>
                <value>
                    <fullName>TOR</fullName>
                </value>
                <value>
                    <fullName>QUE</fullName>
                </value>
                <value>
                    <fullName>VER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Catalogo_SAT__c.object
<CustomObject>
    <description>Permite llevar el registro de los catalogos del SAT para la carta porte</description>
    <fields>
        <fullName>Material_PeligrosoCP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Material Peligroso</label>
        <type>Checkbox</type>
    </fields>
    <label>Catalogo SAT</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos SAT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Comercio_Exterior__c</fullName>
        <label>Comercio Exterior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Reference_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Reference Form</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer_Quote__c.Account_for__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Account_for__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Customer Reference Form)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Reference__c</fullName>
        <label>Customer Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <inlineHelpText>Only Approved as Succesfull Quotes will be available for Pick &amp; Ship</inlineHelpText>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote being prepared</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Quote being prepared</label>
                </value>
                <value>
                    <fullName>Awaiting costs suppliers</fullName>
                    <color>#FF0000</color>
                    <label>Awaiting costs suppliers</label>
                </value>
                <value>
                    <fullName>Sent awaiting response</fullName>
                    <color>#FF6600</color>
                    <label>Sent awaiting response</label>
                </value>
                <value>
                    <fullName>Approved as Succesful</fullName>
                    <color>#006600</color>
                    <label>Approved as Succesful</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <color>#3366FF</color>
                    <label>Shipped</label>
                </value>
                <value>
                    <fullName>Quote Declined</fullName>
                    <color>#FF0000</color>
                    <label>Quote Declined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <defaultValue>&quot;P2G&quot;</defaultValue>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                    <default>true</default>
                    <label>P2G</label>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Until__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Venta_Sap__c</fullName>
        <formula>text(Account_for__r.Venta_Sap__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Venta</label>
        <type>Text</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Import_Export_Fee_Line__c.object
<CustomObject>
    <description>Specifies transport fees associated to an Import-Export. Child object from &quot;Freight Rates Management&quot;</description>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <formula>TEXT(Import_Export_Quote__r.Quotation_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quotation Status</label>
        <type>Text</type>
    </fields>
    <label>Import-Export Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Location__c.object
<CustomObject>
    <description>Object used to define locations within given countries. Can be automatically generated from First Steps https://c.eu11.visual.force.com/apex/NEU_First_Steps</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>State__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Location Default</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ISO_Code_2c__c</fullName>
        <label>ISO_Code_2c</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Iso_Code__c</fullName>
        <label>Iso Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone_Planner_email__c</fullName>
        <label>Planner email</label>
        <type>Email</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/User.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Workplace__c</fullName>
        <label>Workplace</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_CloneImportExport_Test.cls
@isTest
public class NEU_CloneImportExport_Test {

    @testSetup
    static void SetUp(){
        List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        Account account_test = list_accounts[0];
        account_test.Name = 'Bimbo';
        account_test.Credit_Limit__c = 1000000;
        account_test.Venta_Sap__c='Credito';
        account_test.Segment__c='Nuevo';
        account_test.Workplace__c=null;
        insert account_test;
        User userT = [select id,managerId, userRole.Name  from user where id =: UserInfo.getUserId() limit 1];
        Rol_Margen__c rolMargen = TestDataFactory.createRolMargen(userT.userRole.Name);//Director Comercial ,Director Regional
        Catalogo_SAT__c catalogo = TestDataFactory.createCatalogoSat('Caja de acero test' , 'TCA125','Unidad Peso');
        Catalogo_SAT__c producto = TestDataFactory.createCatalogoSat('Papel' , 'TCA127','Productos y Servicios cP');
        Catalogo_SAT__c materialPeligro = TestDataFactory.createCatalogoSat('Aluminio' , 'TCA126','Material Peligroso');
        Catalogo_SAT__c embalaje = TestDataFactory.createCatalogoSat('Caja' , 'TCA128','Tipo de Embalaje');
        Catalogo_SAT__c palet = TestDataFactory.createCatalogoSat('Pallet' , 'TCA228','Unidad Peso');
        catalogo.Material_PeligrosoCP__c=true;
        update catalogo;
        Country__c country = new Country__c(Name='Mxico');
        insert country;
        State__c state = new State__c(Name='Sonora',Country__c=country.Id,Iso_Code__c='SON',ISO_Code_2c__c='SO',Zone_Planner_email__c='kuresa@gmaidl.com',Active__c=true);
        insert state;
        Location__c location = new Location__c(Name='xalapa', State__c=state.Id,Country__c=country.Id);
        insert location;
        Container_Type__c container = new Container_Type__c(Name='Super tracto Camion',Type__c='Road',Cargo_Weight_Kg__c=22222);
        insert container;
        Customer_Quote__c quote = new Customer_Quote__c();
        String recordTypeId = Schema.SObjectType.Customer_Quote__c.getRecordTypeInfosByName().get('Import-Export Quote').getRecordTypeId();
        quote.RecordTypeId = recordTypeId;
        quote.Name='.';
        quote.Account_for__c = account_test.Id;
        quote.Team__c = 'P2G';
        quote.Quotation_Status__c = 'Quote being prepared';
        quote.Customer_Reference__c = 'holi';
        //quote.Customer_Reference_Form__c = fleteNacional.idReferenceForm;
        quote.Valid_From__c = system.today();
        quote.Valid_Until__c = system.today();
        //inicio FN-FLET_NACIONAL_IC
        quote.Comercio_Exterior__c = 'No';
        quote.Freight_Mode__c = 'Road';
        quote.Service_Mode__c = 'NATIONAL';
        quote.Service_Type__c = 'FTL';
        quote.CurrencyIsoCode = 'MXN';
        //termino FN-FLET_NACIONAL_IC
        quote.Country_ofLoad__c = location.Country__c;
        quote.State_of_Load__c = location.State__c;
        quote.Site_of_Load__c = location.Id;
        quote.Country_ofDischarge__c = location.Country__c;
        quote.State_of_Discharge__c = location.State__c;
        quote.Site_of_Discharge__c = location.Id;
        quote.ETD__c = Date.today();
        quote.ETA__c = Date.today();
        quote.Community_Status__c = 'CUSTOMER CREATED';
        quote.Pricing_Executive__c= userT.Id;
        quote.Operations_Exec__c = userT.Id;
        insert quote;
                Import_Export_Fee_Line__c serviceLine = new Import_Export_Fee_Line__c();
        serviceLine.Import_Export_Quote__c = quote.id;
        serviceLine.Name = '001';
        serviceLine.Conversion_Rate_to_Currency_Header__c= integer.valueOf('1');
        serviceLine.Tarifario_ServRate__c = integer.valueOf('1');
        serviceLine.Units__c = 1;
        serviceLine.CurrencyIsoCode	= 'MXN';
        serviceLine.Service_Rate_Name__c = null;
        serviceLine.Quote_Sell_Price__c = 0;
        serviceLine.Quote_Buy_Price__c = 0;
        insert serviceLine;
    }
    public static testMethod void Test_NEU_CloneImportExport()
    {
        Customer_Quote__c importexportquote = [SELECT Id, Name FROM Customer_Quote__c limit 1];
        NEU_StaticVariableHelper.setBoolean1(true);
        NEU_CloneImportExport ie = new NEU_CloneImportExport(new ApexPages.StandardController( importexportquote ));
        ie.duplicate_order();
        ie.back_record();
        String res=ie.resultado;
    }
}