respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Load/Discharge</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Airport_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site of Load/Discharge</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Location__c.Country__c</field>
                <operation>equals</operation>
                <valueField>$Source.Country_of_Load__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.State_of_Load_Discharge__c</field>
                <operation>equals</operation>
                <valueField>Location__c.State__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.State__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts who use this Site</relationshipLabel>
        <relationshipName>AccountsSite</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Supplier</fullName>
        <active>true</active>
        <description>Suppliers we purchase goods from.</description>
        <label>Supplier</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Location__c.object
<CustomObject>
    <description>Object used to define locations within given countries. Can be automatically generated from First Steps https://c.eu11.visual.force.com/apex/NEU_First_Steps</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <label>Subdivision</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNLOCODE__c</fullName>
        <label>UNLOCODE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Supplier_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Country_of_Discharge__c</fullName>
        <formula>Route__r.Country_of_Discharge__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>As specified in &quot;Country of Discharge&quot; inside &quot;Route&quot;</inlineHelpText>
        <label>Route - Country of Discharge</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_of_Load__c</fullName>
        <formula>Route__r.Country_of_Load__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>As specified in &quot;Country of Load&quot; inside &quot;Route&quot;</inlineHelpText>
        <label>Route - Country of Load</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Suppliers_Quotes_Buyer_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pickup / Delivery Drayage</label>
        <referenceTo>Delivery_Zone__c</referenceTo>
        <relationshipLabel>Suppliers Quotes/Orders</relationshipLabel>
        <relationshipName>Suppliers_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Airport_of_Discharge__c</fullName>
        <formula>Route__r.Port_Airport_of_Discharge__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>As specified in &quot;Port / Airport of Discharge&quot; inside &quot;Route&quot;</inlineHelpText>
        <label>Route - Port / Airport of Discharge</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Port_Airport_of_Load__c</fullName>
        <formula>Route__r.Port_Airport_of_Load__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>As specified in &quot;Port / Airport of Load&quot; inside &quot;Route&quot;</inlineHelpText>
        <label>Route - Port / Airport of Load</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Suppliers Quotes/Orders</relationshipLabel>
        <relationshipName>Suppliers_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Quote_Status__c</fullName>
        <label>Supplier Quote/Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Valid</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Sent Bid</fullName>
                </value>
                <value>
                    <fullName>Sent Final Bid</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Import-Export Consolidated</fullName>
                </value>
                <value>
                    <fullName>Consolidated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <label>Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Supply Chain Partner, Purchase Agent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Suppliers Quotes/Orders (Supplier)</relationshipLabel>
        <relationshipName>Suppliers_Quotes_Supplier</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Supply_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Supply Project</label>
        <referenceTo>Supply_Project__c</referenceTo>
        <relationshipName>Suppliers_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Quote/Order</label>
    <nameField>
        <displayFormat>SQO# {YYYY}-{000000}</displayFormat>
        <label>Supplier Quote/Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Warehouse__c.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Warehouses</relationshipLabel>
        <relationshipName>Warehouses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Warehouses</relationshipLabel>
        <relationshipName>Warehouses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>Location__c.Country__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.State__c</field>
                <operation>equals</operation>
                <valueField>Location__c.State__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.State__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Warehouses</relationshipLabel>
        <relationshipName>Warehouses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_NEU_Associated_10DocumentsTest.cls
@isTest
public class P2G_NEU_Associated_10DocumentsTest {
	@isTest(SeeAllData=true)
    static void testGetTypeDocument() {
        Account sup= new Account();
		sup.Name='Test';
		sup.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Supplier').getRecordTypeId();		
        sup.OwnerId=UserInfo.getUserId();
        insert sup;

        Account acc= new Account();
		acc.Name='Test';
		acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        acc.OwnerId=UserInfo.getUserId();
        insert acc;

        Country__c Country = new Country__c(Name='test country',  ISO_Code__c='EUR');
        insert Country;        
        Location__c localizacion = new Location__c(Name='test localizacion', City__c='test city', Country__c= country.Id, Subdivision__c='test subdivision', UNLOCODE__c='ABC');
        insert localizacion;
        Warehouse__c almacen = new Warehouse__c(Name='test', Account_Owner__c=acc.Id, Country__c=Country.Id, Location__c=localizacion.Id);
        insert almacen;
        Delivery_Zone__c delivery_zone = new Delivery_Zone__c(Name= 'test', Port_Airport__c=localizacion.Id, Warehouse__c=almacen.Id);
        insert delivery_zone;
        Supply_Project__c supplyproject = new Supply_Project__c(Name='project test', Customer__c = acc.Id);
        insert supplyproject;
        Carrier_Line_Load_Point__c route = new Carrier_Line_Load_Point__c(Name='test',  Country_of_Discharge__c=Country.Id, Country_of_Load__c=Country.Id, Port_Airport_of_Discharge__c=localizacion.Id, Port_Airport_of_Load__c=localizacion.Id);
        insert route;
        Supplier_Quote__c supquote = new Supplier_Quote__c(Supply_Project__c = supplyproject.Id, Supplier__c = sup.Id, Delivery_Zone__c = delivery_zone.Id, Supplier_Quote_Status__c = 'Approved', Route__c=route.Id);
        insert supquote;
        
        PageReference pageRef = Page.NEU_Associated_10Documents_Request;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', supquote.Id);
        ApexPages.currentPage().getParameters().put('docu', '1');
        
        Test.startTest();
        NEU_Associated_10Documents_Request controller = new NEU_Associated_10Documents_Request();
        String docType = controller.gettype_document();
        Test.stopTest();
        
        
    }
    
    @isTest(SeeAllData=true)
    static void testUploadDocumentsWithSpecificFolder() {        
        Account sup= new Account();
		sup.Name='Test';
		sup.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Supplier').getRecordTypeId();		
        sup.OwnerId=UserInfo.getUserId();
        insert sup;

        Account acc= new Account();
		acc.Name='Test';
		acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        acc.OwnerId=UserInfo.getUserId();
        insert acc;

        Country__c Country = new Country__c(Name='test country',  ISO_Code__c='EUR');
        insert Country;        
        Location__c localizacion = new Location__c(Name='test localizacion', City__c='test city', Country__c= country.Id, Subdivision__c='test subdivision', UNLOCODE__c='ABC');
        insert localizacion;
        Warehouse__c almacen = new Warehouse__c(Name='test', Account_Owner__c=acc.Id, Country__c=Country.Id, Location__c=localizacion.Id);
        insert almacen;
        Delivery_Zone__c delivery_zone = new Delivery_Zone__c(Name= 'test', Port_Airport__c=localizacion.Id, Warehouse__c=almacen.Id);
        insert delivery_zone;
        Supply_Project__c supplyproject = new Supply_Project__c(Name='project test', Customer__c = acc.Id);
        insert supplyproject;
        Carrier_Line_Load_Point__c route = new Carrier_Line_Load_Point__c(Name='test',  Country_of_Discharge__c=Country.Id, Country_of_Load__c=Country.Id, Port_Airport_of_Discharge__c=localizacion.Id, Port_Airport_of_Load__c=localizacion.Id);
        insert route;
        Supplier_Quote__c supquote = new Supplier_Quote__c(Supply_Project__c = supplyproject.Id, Supplier__c = sup.Id, Delivery_Zone__c = delivery_zone.Id, Supplier_Quote_Status__c = 'Approved', Route__c=route.Id);
        insert supquote;
        Folder existingFolder = [SELECT Id, Name FROM Folder WHERE Type = 'Document' LIMIT 1];
        
        PageReference pageRef = Page.NEU_Associated_10Documents_Request;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', supquote.Id);
        ApexPages.currentPage().getParameters().put('docu', '1');
        
        NEU_Associated_10Documents_Request controller = new NEU_Associated_10Documents_Request();
        controller.gettype_document();
        controller.Document_Description = 'Test Description';
        controller.documento_asociado = Blob.valueOf('Test file content');
        controller.documento_asociadoName = 'testfile.txt';
                
        controller.Document_type = existingFolder.Name;
        
        Test.startTest();
        PageReference result = controller.Upload_Documents();
        Test.stopTest();
        
    }
    
    @isTest(SeeAllData=true)
    static void testUploadDocumentsWithDefaultFolder() {        
        Folder defaultFolder;
        try {
            defaultFolder = [SELECT Id, Name FROM Folder WHERE Name = 'Associated Documents' AND Type = 'Document' LIMIT 1];
        } catch(Exception e) {            
            defaultFolder = [SELECT Id, Name FROM Folder WHERE Type = 'Document' LIMIT 1];
        }
        
        Account sup= new Account();
		sup.Name='Test';
		sup.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Supplier').getRecordTypeId();		
        sup.OwnerId=UserInfo.getUserId();
        insert sup;

        Account acc= new Account();
		acc.Name='Test';
		acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        acc.OwnerId=UserInfo.getUserId();
        insert acc;

        Country__c Country = new Country__c(Name='test country',  ISO_Code__c='EUR');
        insert Country;        
        Location__c localizacion = new Location__c(Name='test localizacion', City__c='test city', Country__c= country.Id, Subdivision__c='test subdivision', UNLOCODE__c='ABC');
        insert localizacion;
        Warehouse__c almacen = new Warehouse__c(Name='test', Account_Owner__c=acc.Id, Country__c=Country.Id, Location__c=localizacion.Id);
        insert almacen;
        Delivery_Zone__c delivery_zone = new Delivery_Zone__c(Name= 'test', Port_Airport__c=localizacion.Id, Warehouse__c=almacen.Id);
        insert delivery_zone;
        Supply_Project__c supplyproject = new Supply_Project__c(Name='project test', Customer__c = acc.Id);
        insert supplyproject;
        Carrier_Line_Load_Point__c route = new Carrier_Line_Load_Point__c(Name='test',  Country_of_Discharge__c=Country.Id, Country_of_Load__c=Country.Id, Port_Airport_of_Discharge__c=localizacion.Id, Port_Airport_of_Load__c=localizacion.Id);
        insert route;
        Supplier_Quote__c supquote = new Supplier_Quote__c(Supply_Project__c = supplyproject.Id, Supplier__c = sup.Id, Delivery_Zone__c = delivery_zone.Id, Supplier_Quote_Status__c = 'Approved', Route__c=route.Id);
        insert supquote;
        
        PageReference pageRef = Page.NEU_Associated_10Documents_Request;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', supquote.Id);
        ApexPages.currentPage().getParameters().put('docu', '2');
        
        NEU_Associated_10Documents_Request controller = new NEU_Associated_10Documents_Request();
        controller.gettype_document();
        controller.Document_Description = 'Test Description';
        controller.documento_asociado = Blob.valueOf('Test file content');
        controller.documento_asociadoName = 'testfile.txt';
        
        Test.startTest();
        PageReference result = controller.Upload_Documents();
        Test.stopTest();
        
    }
    
    @isTest(SeeAllData=true)
    static void testUploadDocumentsWithError() {
        Account sup= new Account();
		sup.Name='Test';
		sup.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Supplier').getRecordTypeId();		
        sup.OwnerId=UserInfo.getUserId();
        insert sup;

        Account acc= new Account();
		acc.Name='Test';
		acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        acc.OwnerId=UserInfo.getUserId();
        insert acc;

        Country__c Country = new Country__c(Name='test country',  ISO_Code__c='EUR');
        insert Country;        
        Location__c localizacion = new Location__c(Name='test localizacion', City__c='test city', Country__c= country.Id, Subdivision__c='test subdivision', UNLOCODE__c='ABC');
        insert localizacion;
        Warehouse__c almacen = new Warehouse__c(Name='test', Account_Owner__c=acc.Id, Country__c=Country.Id, Location__c=localizacion.Id);
        insert almacen;
        Delivery_Zone__c delivery_zone = new Delivery_Zone__c(Name= 'test', Port_Airport__c=localizacion.Id, Warehouse__c=almacen.Id);
        insert delivery_zone;
        Supply_Project__c supplyproject = new Supply_Project__c(Name='project test', Customer__c = acc.Id);
        insert supplyproject;
        Carrier_Line_Load_Point__c route = new Carrier_Line_Load_Point__c(Name='test',  Country_of_Discharge__c=Country.Id, Country_of_Load__c=Country.Id, Port_Airport_of_Discharge__c=localizacion.Id, Port_Airport_of_Load__c=localizacion.Id);
        insert route;
        Supplier_Quote__c supquote = new Supplier_Quote__c(Supply_Project__c = supplyproject.Id, Supplier__c = sup.Id, Delivery_Zone__c = delivery_zone.Id, Supplier_Quote_Status__c = 'Approved', Route__c=route.Id);
        insert supquote;

        Folder existingFolder = [SELECT Id, Name FROM Folder WHERE Type = 'Document' LIMIT 1];
        
        PageReference pageRef = Page.NEU_Associated_10Documents_Request;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', supquote.Id);
        ApexPages.currentPage().getParameters().put('docu', '1');
        
        NEU_Associated_10Documents_Request controller = new NEU_Associated_10Documents_Request();
        controller.gettype_document();
        controller.Document_Description = 'Test Description';
        controller.documento_asociado = Blob.valueOf('Test file content');
        controller.documento_asociadoName = 'testfile.txt';
        controller.Document_type = existingFolder.Name;
                
        controller.documento_asociadoName = null;
        
        Test.startTest();
        PageReference result = controller.Upload_Documents();
        Test.stopTest();
        
        
    }
}