respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ActiveSap__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts Addresses</relationshipLabel>
        <relationshipName>Accounts_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&quot;Shipping Address&quot;</defaultValue>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Address</fullName>
                </value>
                <value>
                    <fullName>Shipping Address</fullName>
                    <default>true</default>
                    <label>Shipping Address</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_Destination_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup filter to select from Account Addresses associated to the selected Consignee Account</description>
        <inlineHelpText>Specify Consignee Account first</inlineHelpText>
        <label>Account Destination Address</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Account_Address__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account_Address__c.status__c</field>
                <operation>equals</operation>
                <value>Validado</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>equals</operation>
                <value>NATIONAL</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>notEqual</operation>
                <value>NATIONAL</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Address__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Account Destination Address)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Origin_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Dependent on &quot;Supplier/Shipper Account&quot;</inlineHelpText>
        <label>Account Origin Address</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (4)</booleanFilter>
            <filterItems>
                <field>Account_Address__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account_Address__c.status__c</field>
                <operation>equals</operation>
                <value>Validado</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>equals</operation>
                <value>NATIONAL</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>notEqual</operation>
                <value>NATIONAL</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Address__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Account Origin Address)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Final Destination Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Motivo__c</fullName>
        <label>Motivo</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Initial Origin Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Pricing_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Import_Export_Quotes_Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <inlineHelpText>Only Approved as Succesfull Quotes will be available for Pick &amp; Ship</inlineHelpText>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote being prepared</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Quote being prepared</label>
                </value>
                <value>
                    <fullName>Awaiting costs suppliers</fullName>
                    <color>#FF0000</color>
                    <label>Awaiting costs suppliers</label>
                </value>
                <value>
                    <fullName>Sent awaiting response</fullName>
                    <color>#FF6600</color>
                    <label>Sent awaiting response</label>
                </value>
                <value>
                    <fullName>Approved as Succesful</fullName>
                    <color>#006600</color>
                    <label>Approved as Succesful</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <color>#3366FF</color>
                    <label>Shipped</label>
                </value>
                <value>
                    <fullName>Quote Declined</fullName>
                    <color>#FF0000</color>
                    <label>Quote Declined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                    <default>true</default>
                    <label>NATIONAL</label>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <defaultValue>&quot;P2G&quot;</defaultValue>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                    <default>true</default>
                    <label>P2G</label>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>% Service Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Import_Export_Fee_Line__c.object
<CustomObject>
    <description>Specifies transport fees associated to an Import-Export. Child object from &quot;Freight Rates Management&quot;</description>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote/Order</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Service Lines</relationshipLabel>
        <relationshipName>Import_Export_Fees_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <formula>TEXT(Import_Export_Quote__r.Quotation_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quotation Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Units</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Quote_Item_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of an Import-Export to generate Shipment Cargo Lines.</description>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Total_Shipping_Weight_Kgs__c</fullName>
        <label>Peso Bruto (KG)</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Cargo Line</label>
    <nameField>
        <label>Imp-Exp Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/User.object
<CustomObject>
    <fields>
        <fullName>FN_Marg_Op__c</fullName>
        <label>FN - Margen Operativo</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/Pak_MargenOperativo_Test.cls
@isTest()
public class Pak_MargenOperativo_Test {
    @isTest
    public static void pruebaFN(){
        
         Test.startTest();

   // try {
   
        
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        
        list<User> users = [select Alias,Email,LastName from user where UserName = 'testfn2@testorg.com'];
        
        UserRole obj=new UserRole(Name= 'Asesor Comercial'); 
        insert obj; 
        
        
        
        User u = users.size() > 0 ? users[0] : new User(Alias = 'testfn2', Email='testfn2@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='testfn2', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='testfn2@testorg.com',FN_Marg_Op__c=40);
          u.UserRoleId = obj.Id;
      //  update u;

        System.runAs(u) {
            
            Rol_Margen__c rolm = new Rol_Margen__c();
        rolm.Name = 'Asesor Comercial';
        rolm.FN_Margen_Operativo__c = 1;
        rolm.FI_Margen_Operativo__c  = 1;
        
        insert rolm;
            
            NEU_StaticVariableHelper.setBoolean1(false);
            
            List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
            Account a = list_accounts[0];
            a.ActiveSap__c = true;
            insert a;   Account_Address__c address = new Account_Address__c();
            address.Name = 'Bonafont Cln';
            address.Account__c = a.id;
            address.Address__c ='Conocida';
            address.Address_Coordinates__Latitude__s=  22.023033;
            address.Address_Coordinates__Longitude__s=-102.285602;
            address.Type__c = 'Shipping Address	';
            insert address;
            
            Account_Address__c address2 = new Account_Address__c();
            address2.Name = 'Cln';
            address2.Account__c = a.id;
            address2.Address__c ='Conocida';
            address2.Address_Coordinates__Latitude__s=19.6248115;
            address2.Address_Coordinates__Longitude__s=-99.18076289999999;
            address2.Type__c = 'Shipping Address	';
            insert address2;
            
            Customer_Quote__c cq = new Customer_Quote__c();
            cq.Team__c = 'P2G';
            cq.Account_for__c = a.id;
            cq.Quotation_status__c ='Quote being prepared';
            cq.Only_Warehouse_Service__c  = true;
            cq.Freight_Mode__c = 'Road';
            cq.Service_Mode__c = 'NATIONAL';
            cq.Name = 'FN-21-003507';
            cq.Destination_Address__c = 'Hola';
            cq.Origin_Address__c = 'Hola';
            cq.Account_Origin_Address__c = address.id;
            cq.Account_Destination_Address__c = address2.id;
            cq.Motivo__c = 'dada';
            cq.Pricing_Executive__c = u.id;
            
            insert cq;
            
            Quote_Item_Line__c quote = new Quote_Item_Line__c(Import_Export_Quote__c = cq.id,Name = 'lineas items', Units__c = 1,Total_Shipping_Weight_Kgs__c= 1);
            insert quote;
            Fee__c fee = new Fee__c(Name = 'test fees', Fee_Category__c = 'Disbursement', Rate_Type__c = 'Fixed', Account_for__c = a.Id);
            insert fee;
            Import_Export_Fee_Line__c quote2 = new Import_Export_Fee_Line__c(Import_Export_Quote__c = cq.id,Name = 'lineas items', Service_Rate_Name__c= fee.Id, Extension_Service_Name__c='test extension fee name', Discount__c=10, Quote_Buy_Price__c=10, Quote_Sell_Price__c=10,Units__c=10 );
            insert quote2;
            
            cq.Quotation_status__c = 'Approved as Succesful';
            update cq;
        } 
        
           
  /*  } catch (Exception e) {
       System.debug('An error occurred');
    }*/

   Test.stopTest();
        
    }
    
    @isTest
    public static void pruebaFI(){
         Test.startTest();
       // try
        //{
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        
       list<User>  users = [select Alias,Email,LastName from user where UserName = 'testfi2@testorg.com'];
        
        UserRole obj=new UserRole(Name= 'Asesor Comercial'); 
        insert obj; 
        
        
        
        User u = users.size()>0 ? users[0] : new User(Alias = 'testfi2', Email='testfi2@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='testfi2', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='testfi2@testorg.com',FI_Marg_Op__c = 30);
        
        u.UserRoleId = obj.Id;
     //   update u;
        
        System.runAs(u) {
            
              Rol_Margen__c rolm = new Rol_Margen__c();
        rolm.Name = 'Asesor Comercial';
        rolm.FN_Margen_Operativo__c = 1;
        rolm.FI_Margen_Operativo__c  = 1;
        insert rolm;
            
            NEU_StaticVariableHelper.setBoolean1(false);
            
            List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
            Account a = list_accounts[0];
            a.ActiveSap__c = true;
            insert a;
            
            Customer_Quote__c cq = new Customer_Quote__c();
            cq.Team__c = 'P2G';
            cq.Account_for__c = a.id;
            cq.Quotation_status__c ='Quote being prepared';
            cq.Only_Warehouse_Service__c  = true;
            cq.Freight_Mode__c = 'Road';
            cq.Service_Mode__c = 'NATIONAL';
            cq.Name = 'AW-21-003507';
            cq.Motivo__c = 'dada';
            cq.Pricing_Executive__c = u.id;
            
            cq.Destination_Address__c = 'Hola';
            cq.Origin_Address__c = 'Hola';
            insert cq;
            
            
            Quote_Item_Line__c quote = new Quote_Item_Line__c(Import_Export_Quote__c = cq.id,Name = 'lineas items', Units__c = 1,Total_Shipping_Weight_Kgs__c= 1);
            insert quote;
            Fee__c fee = new Fee__c(Name = 'test fees', Fee_Category__c = 'Disbursement', Rate_Type__c = 'Fixed', Account_for__c = a.Id);
            insert fee;
            Import_Export_Fee_Line__c quote2 = new Import_Export_Fee_Line__c(Import_Export_Quote__c = cq.id,Name = 'lineas items', Service_Rate_Name__c= fee.Id, Extension_Service_Name__c='test extension fee name', Discount__c=10, Quote_Buy_Price__c=10, Quote_Sell_Price__c=10,Units__c=10 );
            insert quote2;
            
            cq.Quotation_status__c = 'Approved as Succesful';
            update cq;
        }
            

  /*  } catch (Exception e) {
       System.debug('An error occurred');
    }*/

   Test.stopTest();
        
    }
    
    
}