respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>status__c</fullName>
        <description>Este campo registra los estatus en el proceso de validación de las coordenadas por el equipo de monitoreo en control room status_CR</description>
        <label>Status CR</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nuevo</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>Pendiente</fullName>
                </value>
                <value>
                    <fullName>Validado</fullName>
                </value>
                <value>
                    <fullName>Rechazado</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_SendBatchAddress.cls
public class P2G_SendBatchAddress implements Database.Batchable<SObject>, Database.AllowsCallouts {
    //P2G_SendBatchAddress batch = new P2G_SendBatchAddress();
	//Database.executeBatch(batch, 50);

    // Query para obtener los registros que deseas procesar
    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id FROM Account_Address__c WHERE status__c = \'Nuevo\'';
        return Database.getQueryLocator(query);
    }

    // Procesa los registros en lotes de 50
    public void execute(Database.BatchableContext BC, List<Account_Address__c> scope) {
        for(Account_Address__c accAddress : scope) {
            P2G_updateAddresWs.send(accAddress.Id);
        }
    }

    // Finaliza el batch
    public void finish(Database.BatchableContext BC) {
        System.debug('Batch finalizado');
    
        // Crear el mensaje de correo
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(new String[] {'alberto.garcia@2gologistics.com'});
        email.setSubject('Batch Terminado');
        email.setPlainTextBody('Batch terminado de envio de direcciones a CR');
        
        // Enviar el correo
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
        }
}