respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bloqueo_Tarifario__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bloqueo Tarifario</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>CustomRate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tarifario</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>% Service Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Service_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SAP Service Type Sell</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Group__c</field>
                <operation>equals</operation>
                <valueField>SAP_Service_Type__c.Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>SAP_Service_Type__c.Activo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Service_Type__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Services_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_Until__c</fullName>
        <defaultValue>now()</defaultValue>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <recordTypes>
        <fullName>Servicios</fullName>
        <active>true</active>
        <label>Servicios</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments_Route</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Sap_Service_Type__c</fullName>
        <formula>Service_Rate_Name__r.SAP_Service_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sap Service Type Sell</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Rate_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Name</label>
        <referenceTo>Fee__c</referenceTo>
        <relationshipLabel>Shipment Service Lines</relationshipLabel>
        <relationshipName>Shipment_Service_Lines_Service_Rate_Name</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Sell_Price__c</fullName>
        <label>Shipment Sell Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_LockSellPrice.cls
public class P2G_LockSellPrice {
    public static void  validateSellPriceLock(List<Shipment_Fee_Line__c> newServiceLines, Map<Id, Shipment_Fee_Line__c>  oldMap) {
        Set<Id> shipmentIds = new Set<Id>();
        Set<Id> serviceRateIds = new Set<Id>();
		        
        for (Shipment_Fee_Line__c newServiceLine : newServiceLines)  {
            Shipment_Fee_Line__c oldServiceLines = oldMap.get(newServiceLine.Id);
            
            if (newServiceLine.Shipment__c != null && newServiceLine.Shipment_Sell_Price__c != oldServiceLines.Shipment_Sell_Price__c) {
                    shipmentIds.add(newServiceLine.Shipment__c);
                
                if (newServiceLine.Service_Rate_Name__c != null) {
                    serviceRateIds.add(newServiceLine.Service_Rate_Name__c);
            	}
			}
        }
        
        if (shipmentIds.isEmpty() || serviceRateIds.isEmpty()) {
            return;
        }
        
        Map<Id, Shipment__c> shipmentMap = new Map<Id, Shipment__c>(
        [
            SELECT Id, Account_for__c, Account_for__r.Bloqueo_Tarifario__c 
            FROM Shipment__c 
            WHERE Id IN :shipmentIds
        ]  
        );
        System.debug('shipmentMap: ' + shipmentMap);
        
        Map<Id, Fee__c> serviceRateMap = new Map<Id, Fee__c>(
        [
            SELECT Id, Name, Route__c, Route__r.Name, SAP_Service_Type__c, Account_for__c
            FROM Fee__c 
            WHERE Id IN :serviceRateIds
        ]
        );
		System.debug('ServiceRateMap: ' + serviceRateMap);
		        
        Set<Id> routeIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        
        for (Fee__c serviceRate : serviceRateMap.values()) {
            if (serviceRate.Route__c != null) {
                routeIds.add(serviceRate.Route__c);
            }
            
            if(serviceRate.Account_for__c != null) {
                accountIds.add(serviceRate.Account_for__c);
            }
        }
        System.debug('set de Route Ids: '+ routeIds);
		System.debug('set de Account Ids: '+ accountIds);
        
        if(routeIds.isEmpty() || accountIds.isEmpty()) {
            return;
        }
        
        Map<Id,Set<Id>> accountAndRoutes = new Map<Id, Set<Id>>();

        for (Fee__c tarifarioOriginal : [
            SELECT Id, Name, Route__c, Account_for__c, Valid_Until__c, CustomRate__c
            FROM Fee__c
            WHERE Route__c IN :routeIds AND Account_for__c IN :accountIds AND CustomRate__c = true AND Valid_Until__c >= TODAY
        ]) {
            if (!accountAndRoutes.containsKey(tarifarioOriginal.Route__c)) {
                accountAndRoutes.put(tarifarioOriginal.Route__c, new Set<Id>());
            }
            accountAndRoutes.get(tarifarioOriginal.Route__c).add(tarifarioOriginal.Account_for__c);
        }
        System.debug('Mapa accounts y routes: ' + accountAndRoutes);
        
		for (Shipment_Fee_Line__c newServiceLine : newServiceLines)  {
            Shipment_Fee_Line__c oldServiceLines = oldMap.get(newServiceLine.Id);
            
            Shipment__c shipment = shipmentMap.get(newServiceLine.Shipment__c);
            Fee__c serviceRate = serviceRateMap.get(newServiceLine.Service_Rate_Name__c);
            
            Boolean accountHasBloqueoTarifario = 
                shipment != null &&
                shipment.Account_for__c != null &&
                shipment.account_for__r.Bloqueo_tarifario__c == true;
            System.debug('accountHasBloqueoTarifario: ' + accountHasBloqueoTarifario);
            
            Boolean routeHasTarifario = 
                serviceRate != null &&
                serviceRate.Route__c != null &&
                serviceRate.Account_for__c !=null &&
                (newServiceLine.SAP_Service_Type__c  == 'FLETE NACIONAL (IC) (FN)' || newServiceLine.SAP_Service_Type__c  == 'SERVICIOS LOGISTICOS NACIONALES FN (IC) (FN)') &&
				accountAndRoutes.containsKey(serviceRate.Route__c) &&
                accountAndRoutes.get(serviceRate.Route__c).contains(serviceRate.Account_for__c);
            System.debug('routeHasTarifario: ' + routeHasTarifario);

            if(accountHasBloqueoTarifario && routeHasTarifario) {
                newServiceLine.Shipment_Sell_Price__c.addError('No es posible modificar el Precio de Venta de un Tarifario.');
            }
        }
    }
}