respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Area__c</fullName>
        <inlineHelpText>Make sure that you have the same Business Areas for ACCOUNTS, FAMILIES, PRICE LISTS and SUPPLY PROJECTS.</inlineHelpText>
        <label>Business Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air Freight</fullName>
                </value>
                <value>
                    <fullName>Animal Nutrition</fullName>
                </value>
                <value>
                    <fullName>Auto-Parts</fullName>
                </value>
                <value>
                    <fullName>Cloths &amp; Accessories</fullName>
                </value>
                <value>
                    <fullName>Construction &amp; Engineering</fullName>
                </value>
                <value>
                    <fullName>Construction &amp; Mining</fullName>
                </value>
                <value>
                    <fullName>Energy &amp; Hydrocarbons</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverages</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Machinery &amp; Parts</fullName>
                </value>
                <value>
                    <fullName>MERA Autoparts</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Other Services</fullName>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                </value>
                <value>
                    <fullName>Rail Freight</fullName>
                </value>
                <value>
                    <fullName>Recruiting Services</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Sea Freight</fullName>
                </value>
                <value>
                    <fullName>Telecom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Comercio_Exterior__c</fullName>
        <label>Comercio Exterior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Reference__c</fullName>
        <label>Customer Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Final Destination Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Initial Origin Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <inlineHelpText>Only Approved as Succesfull Quotes will be available for Pick &amp; Ship</inlineHelpText>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote being prepared</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Quote being prepared</label>
                </value>
                <value>
                    <fullName>Awaiting costs suppliers</fullName>
                    <color>#FF0000</color>
                    <label>Awaiting costs suppliers</label>
                </value>
                <value>
                    <fullName>Sent awaiting response</fullName>
                    <color>#FF6600</color>
                    <label>Sent awaiting response</label>
                </value>
                <value>
                    <fullName>Approved as Succesful</fullName>
                    <color>#006600</color>
                    <label>Approved as Succesful</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <color>#3366FF</color>
                    <label>Shipped</label>
                </value>
                <value>
                    <fullName>Quote Declined</fullName>
                    <color>#FF0000</color>
                    <label>Quote Declined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                    <default>true</default>
                    <label>NATIONAL</label>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <defaultValue>&quot;P2G&quot;</defaultValue>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                    <default>true</default>
                    <label>P2G</label>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Until__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Delivery Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Pickup Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Consolidation_Data__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Reference__c</fullName>
        <formula>Import_Export_Quote__r.Customer_Reference__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Reference</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <formula>TEXT( Shipment__r.Freight_Mode__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Freight Mode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <formula>TEXT(Import_Export_Quote__r.Quotation_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quotation Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Shipment_Orders_Consolidation_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Consolidation Data</label>
    <nameField>
        <label>Shipment Consolidation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Consolidation Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/User.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_Shipment_Consolidation_DataTest.cls
@isTest
public class P2G_Shipment_Consolidation_DataTest {
	@isTest
    static void NEU_Update_Last_Shipment_IE(){
        Account b = new Account(Name = 'Test client', RecordTypeId = Schema.SobjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId() /*,Business_Area__c = 'Sales'*/);
        //List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        Account a = b;
        insert a;
        Shipment__c ship = new Shipment__c(Name='SP-FN-TEST0002',Account_for__c = a.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', Only_Warehouse_Service__c = true);
        insert ship;
        //Customer_Quote__c importexportquote = new Customer_Quote__c(Account_for__c = a.Id, Quotation_Status__c='Quote being prepared', Origin_Address__c = '', Destination_Address__c = '', Only_Warehouse_Service__c = true);
        //insert importexportquote;
        
        
        User userT = [select id,managerId, userRole.Name  from user where id =: UserInfo.getUserId() limit 1];
        Rol_Margen__c rolMargen = TestDataFactory.createRolMargen(userT.userRole.Name);//Director Comercial ,Director Regional
        Customer_Quote__c quote = new Customer_Quote__c();
        String recordTypeId = Schema.SObjectType.Customer_Quote__c.getRecordTypeInfosByName().get('Import-Export Quote').getRecordTypeId();
        quote.RecordTypeId = recordTypeId;
        quote.Name='.';
        quote.Account_for__c = a.Id;
        quote.Team__c = 'P2G';
        quote.Quotation_Status__c = 'Quote being prepared';
        quote.Customer_Reference__c = 'hola soy una prueba';
        quote.Valid_From__c = system.today();
        quote.Valid_Until__c = system.today();
        quote.Comercio_Exterior__c = 'No';
        quote.Freight_Mode__c = 'Road';
        quote.Service_Mode__c = 'NATIONAL';
        quote.Service_Type__c = 'FTL';
        quote.CurrencyIsoCode = 'MXN';
        quote.ETD__c = Date.today();
        quote.ETA__c = Date.today();
        quote.Community_Status__c = 'CUSTOMER CREATED';
        quote.Pricing_Executive__c= userT.Id;
        quote.Operations_Exec__c = userT.Id;
        insert quote;
        
        Shipment_Consolidation_Data__c shipconsodata = new Shipment_Consolidation_Data__c(Name= ' test shipconsodata', Shipment__c = ship.Id, Import_Export_Quote__c = quote.Id);
        insert shipconsodata;
    }
}