respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Supplier</fullName>
        <active>true</active>
        <description>Suppliers we purchase goods from.</description>
        <label>Supplier</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Supplier_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Suppliers_Quotes_Buyer_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <label>Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Supply Chain Partner, Purchase Agent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Suppliers Quotes/Orders (Supplier)</relationshipLabel>
        <relationshipName>Suppliers_Quotes_Supplier</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Supply_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Supply Project</label>
        <referenceTo>Supply_Project__c</referenceTo>
        <relationshipName>Suppliers_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Quote/Order</label>
    <nameField>
        <displayFormat>SQO# {YYYY}-{000000}</displayFormat>
        <label>Supplier Quote/Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_NEU_OM_UpdateFoSupplierQuote.cls
@isTest
public class P2G_NEU_OM_UpdateFoSupplierQuote {
    @isTest
    static void NEU_OM_UpdateFoSupplierQuote(){
        
        List<Account> list_accounts = NEU_Utils.getAccounts('Customer,Supplier,');
        Account a = list_accounts[0];
        insert a;
        Account sup = list_accounts[1];
        insert sup;
        Supply_Project__c supplyproject = new Supply_Project__c(Name='project test', Customer__c = a.Id);
        insert supplyproject;
        Supplier_Quote__c supquote = new Supplier_Quote__c(Supply_Project__c= supplyproject.Id,Supplier__c=sup.Id);
        insert supquote;
    }
}