respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Load/Discharge</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Airport_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site of Load/Discharge</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Location__c.Country__c</field>
                <operation>equals</operation>
                <valueField>$Source.Country_of_Load__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.State_of_Load_Discharge__c</field>
                <operation>equals</operation>
                <valueField>Location__c.State__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.State__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts who use this Site</relationshipLabel>
        <relationshipName>AccountsSite</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Final Destination Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ETD__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>ETD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Move_Type__c</fullName>
        <label>Move Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Door to Door</fullName>
                    <default>true</default>
                    <label>Door to Door</label>
                </value>
                <value>
                    <fullName>Door to Port</fullName>
                </value>
                <value>
                    <fullName>Port to Door</fullName>
                </value>
                <value>
                    <fullName>Port to Port</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Initial Origin Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                    <default>true</default>
                    <label>NATIONAL</label>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>FP</fullName>
                </value>
                <value>
                    <fullName>FO</fullName>
                </value>
                <value>
                    <fullName>MAYOREO</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer, Supplier or Agente Aduanal</inlineHelpText>
        <label>Cuenta Origen</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Shipper, Customer, Supply Chain Partner, Supplier Owner or Lessee of Vehicule, Agente Aduanal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Supplier/Shipper Account)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Supplier_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supply_Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supply Project Name</label>
        <referenceTo>Supply_Project__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Location__c.object
<CustomObject>
    <description>Object used to define locations within given countries. Can be automatically generated from First Steps https://c.eu11.visual.force.com/apex/NEU_First_Steps</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <label>Subdivision</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNLOCODE__c</fullName>
        <label>UNLOCODE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Quote_Item_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of an Import-Export to generate Shipment Cargo Lines.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Conversion to currency of &quot;Units&quot; x &quot;Price&quot;</description>
        <formula>Units__c  *  Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>&quot;Units&quot; x &quot;Price&quot;</inlineHelpText>
        <label>Origin Sell Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Number__c</fullName>
        <label>Delivery Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ETD__c</fullName>
        <label>ETD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Name</label>
        <referenceTo>Sourcing_Item__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Supplier_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Supplier/Owner</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Quote_Item_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Unit Origin Sell Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Supplier_Quote_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Specify Supplier Quote first</inlineHelpText>
        <label>Supplier Quote/Order Line</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier_Quote_Line__c.Supplier_Quote__c</field>
                <operation>equals</operation>
                <valueField>$Source.Supplier_Quote__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Supplier_Quote_Line__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Cargo Line</label>
    <nameField>
        <label>Imp-Exp Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Supplier_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Number__c</fullName>
        <label>Delivery Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Item Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Supplier Quote/Order Line</label>
    <nameField>
        <label>SQO Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Quote/Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_Generate_Shipments_test.cls
@isTest
public class NEU_Generate_Shipments_test {
 
    public static testMethod void test_NEU_Generate_Shipments() {
     	
/*NEU_StaticVariableHelper.setBoolean1(true);
     	
        List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        Account a = list_accounts[0];
        insert a;
        Customer_Quote__c importexportquote = new Customer_Quote__c(  Account_for__c = a.Id, Freight_Mode__c='Air',Service_Mode__c='Import', Service_Type__c='LCL Cargo',Move_Type__c='Door to Door',Origin_Address__c='tst adrress', Destination_Address__c='test address');
        insert importexportquote;
        Quote_Item_Line__c quote = new Quote_Item_Line__c(Import_Export_Quote__c = importexportquote.id,Name = 'lineas items', Units__c = 10);
        insert quote;
        Country__c Country = new Country__c(Name='test country',  ISO_Code__c='EUR');
        insert Country;
        Location__c localizacion = new Location__c(Name='test localizacion', City__c='test city', Country__c= country.Id, Subdivision__c='test subdivision', UNLOCODE__c='ABC');
        insert localizacion;
        Carrier_Line_Load_Point__c route = new Carrier_Line_Load_Point__c(Name='test',  Country_of_Discharge__c=Country.Id, Country_of_Load__c=Country.Id, Port_Airport_of_Discharge__c=localizacion.Id, Port_Airport_of_Load__c=localizacion.Id);
        insert route;
        Pricebook2 standardPricebook = new Pricebook2(
		Id = Test.getStandardPricebookId(),
		IsActive = true*/
          NEU_Generate_Shipments  gs = new NEU_Generate_Shipments();
        gs.bypass();
        
    }
//Execute an update DML on the Pricebook2 record, to make IsStandard to true
/*
Update standardPricebook;
        //Id stdPriceBook = Test.getStandardPricebookId();
        List<Product2> prods = [SELECT Id FROM Product2 WHERE Name = 'Testsp'];
        Product2 p;
        PricebookEntry pbe;
        
        if(prods.size()>0){
            p = prods[0];
            pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id =:p.Id LIMIT 1];
        }else{
            p = new Product2(Name='Testsp', IsActive = true);
            insert p;
            
            pbe = new PricebookEntry();
            pbe.IsActive = true;
            pbe.UnitPrice = 1;
            pbe.Product2Id = p.Id;
            pbe.Pricebook2Id = standardPricebook.ID;
            insert pbe;
        }         
        
        NEU_Generate_Shipments  gs = new NEU_Generate_Shipments(new ApexPages.StandardController( importexportquote ));

         
        gs.decimalSep = gs.decimalSep;
        gs.thousandSep = gs.thousandSep;
        gs.filter_shipment = gs.filter_shipment;
        gs.filter_program = gs.filter_program;
        gs.filter_vessel = gs.filter_vessel;
        gs.getcontainers();
        gs.new_route();
        gs.search_routes();
        gs.getrouteid();
        gs.setrouteid(route.Id);
        gs.actualizar_table_route();
        gs.new_filter_route.Country_of_Load__c= Country.Id;
        gs.new_filter_route.Country_of_Discharge__c= Country.Id;
        gs.getlist_route();
        gs.getnumero_dias2();
        gs.getShowLines();
        gs.getShowImportExportItemLines();
        gs.getLines();
        gs.orden_quotes  = 'total_pallet_linea-asc';
        gs.go_compare();
         gs.direccion_selected = gs.direccion_selected;
         gs.direccion_selected_destination = gs.direccion_selected_destination;
         gs.alertuser=gs.alertuser;
         gs.TotalNumberBoxes = gs.TotalNumberBoxes;
         gs.TotalNumberPallets=gs.TotalNumberPallets;
         gs.Grossweight = gs.Grossweight;
         gs.Cube=gs.Cube;
         gs.FreeSpaceCont=gs.FreeSpaceCont;
         gs.porc_ocupacion=gs.porc_ocupacion;
         gs.total_pallet_linea=gs.total_pallet_linea;
         gs.container_selected=gs.container_selected;
         gs.currency_cuenta=gs.currency_cuenta;
         gs.linea_modificada=gs.linea_modificada;
         gs.max_peso_container=gs.max_peso_container;
         gs.max_volumen_container=gs.max_volumen_container;
         gs.num_cont_x_pallet=gs.num_cont_x_pallet;
         gs.la_lista_no_cero=gs.la_lista_no_cero;
         gs.searchDestinationAddress=gs.searchDestinationAddress;
         gs.searchOriginAddress=gs.searchOriginAddress;
        for(NEU_Generate_Shipments.Line_s l : gs.getLines())
            l.selected = true;
        gs.applyLines();
        gs.splitQuoteLine(quote.Id,1);
         gs.check_shipment_created();
         gs.shipment_truckstop.Freight_MOde__c = 'Road';
         gs.createTrackingTruckstop();
		 gs.bypass();
        gs.bypass2();
        NEU_Generate_Shipments.Line_s lines_obj = new NEU_Generate_Shipments.Line_s(quote, true, '', 10, quote.Id, 10, 10, 10, false,'', 10, 10, 10, false);
        NEU_Generate_Shipments.Line_s lines_obj2 = new NEU_Generate_Shipments.Line_s(quote, true, '', 8, quote.Id, 8, 8, 8, false,'', 8, 8, 8, false);
        lines_obj.getintegersupply();
        lines_obj.getFinalUnits();
        lines_obj.getFinalStock();
        lines_obj.getId();
        lines_obj.getHeaderId();
        lines_obj.getItemId();
        lines_obj.getItemType();
        lines_obj.getSupplierId();
        lines_obj.getItemName();
        lines_obj.getFamilyName();
        lines_obj.campo_compare='total_pallet_linea';
        lines_obj.orden_de_comparacion='asc';
        lines_obj.compareTo(lines_obj);
        
        lines_obj.campo_compare='total_pallet_linea';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='total_volumen_linea';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='total_peso_linea';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='extension';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='totalcajas';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Item_Name__r.Name';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Item_Supplier_Owner__r.Name';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Import_Export_Quote__r.Account_for__r.Name';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Delivery_Date__c';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Delivery_Number__c';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Import_Export_Quote__r.Supplier_Account__c';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Name';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Import_Export_Quote__r.Name';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Units__c';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Price__c';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.ETD__c';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Supplier_Quote_Line__r.Delivery_Date__c';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Amount__c';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        lines_obj.campo_compare='quote_line.Import_Export_Quote__r.Supply_Project_Name__r.Name';
        lines_obj.orden_de_comparacion='desc';
        lines_obj.compareTo(lines_obj2);
        
     }*/
}