respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Venta_Sap__c</fullName>
        <label>Venta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sin Asignar</fullName>
                </value>
                <value>
                    <fullName>Credito</fullName>
                </value>
                <value>
                    <fullName>Contado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>% Service Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GroupGVS</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Service_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SAP Service Type Sell</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Group__c</field>
                <operation>equals</operation>
                <valueField>SAP_Service_Type__c.Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>SAP_Service_Type__c.Activo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Service_Type__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Services_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SST_Sociedad__c</fullName>
        <description>Este campo consulta el valor de Sociedad dentro del SAP SERVICE TYPE relacionado al Service Rate</description>
        <formula>TEXT( SAP_Service_Type__r.SST_Sociedad__c )</formula>
        <label>Sociedad</label>
        <type>Text</type>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sap_Service_Type__c</fullName>
        <label>Sap Service Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Rate_Name__c</fullName>
        <label>Rate Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Std_Buy_Amount__c</fullName>
        <label>Buy Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments_Route</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment_Status_Plann__c</fullName>
        <label>Shipment Status Planner</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Re assigned</fullName>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Rejected PakControl</fullName>
                </value>
                <value>
                    <fullName>Operative Failure</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Delivery on Route</fullName>
                    <isActive>false</isActive>
                    <label>Delivery On Route</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Traslado_Ingreso__c</fullName>
        <label>Tipo de Carta Porte</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ingreso</fullName>
                    <default>true</default>
                    <label>Ingreso</label>
                </value>
                <value>
                    <fullName>Traslado</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <isActive>false</isActive>
                    <label>Normal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <label>% VAT</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VERIFY_PAK_CONTROL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VERIFY PAK CONTROL</label>
        <type>Checkbox</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <formula>TEXT(Service_Rate_Name__r.Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SST_Sociedad__c</fullName>
        <description>Campo que consulta el valor de Sociedad en el Service Rate</description>
        <formula>Service_Rate_Name__r.SST_Sociedad__c</formula>
        <label>Sociedad</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sap_Service_Type__c</fullName>
        <formula>Service_Rate_Name__r.SAP_Service_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sap Service Type Sell</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Rate_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Name</label>
        <referenceTo>Fee__c</referenceTo>
        <relationshipLabel>Shipment Service Lines</relationshipLabel>
        <relationshipName>Shipment_Service_Lines_Service_Rate_Name</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Std_Buy_Amount__c</fullName>
        <formula>IF(Shipment_Buy_Price__c &gt;= 0 ,MAX (Shipment_Buy_Price__c * Units__c, IF((ISNULL(Shipment_Buy_Price__c )== true) || (Shipment_Buy_Price__c = 0), 0, Min_Amount__c ) ), MIN (Shipment_Buy_Price__c * Units__c, IF((ISNULL(Shipment_Buy_Price__c )== true) || (Shipment_Buy_Price__c = 0), 0, - Min_Amount__c ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Buy Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SendToSAPTest.cls
@isTest
public class SendToSAPTest {
    @isTest
    public static void test(){
        List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        Account account_test = list_accounts[0];
        account_test.Credit_Limit__c = 1000000;
        account_test.Venta_Sap__c='Credito';
        insert account_test;
        list<  Shipment_Fee_Line__c> lista = new list< Shipment_Fee_Line__c>();
        list<  Shipment_Fee_Line__c> updateLista = new list< Shipment_Fee_Line__c>();
        Shipment__c ship = new Shipment__c(Name= 'SP-FN-21-00345', Account_for__c = account_test.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', Only_Warehouse_Service__c = true,Shipment_Status_Plann__c = 'Confirmed',Traslado_Ingreso__c='Traslado',VERIFY_PAK_CONTROL__C=true);
        insert ship;
        SAP_Service_Type__c SPST= new SAP_Service_Type__c();
        SPST.Group__c='SP-PTO-PUERTOS';
        SPST.Name='FLETE LOCAL (IC) (PTO)';
        SPST.Code__c='PTO-FLETE_LOCAL_(IC)';
        SPST.SST_Sociedad__c='PGL';
        SPST.Activo__c=true;
        insert SPST;
        Fee__c srn=new Fee__c();
        srn.Group__c='SP-PTO-PUERTOS';
        // srn.Route__c='Apodaca - Atlanta,GA';
        srn.SAP_Service_Type__c=SPST.id;
        srn.Account_for__c=account_test.id;
        insert srn;
        Shipment_Fee_Line__c spFL=new Shipment_Fee_Line__c(); 
        spfl.Shipment__c=ship.id;
        spfl.Service_Rate_Name__c=srn.id;
        insert spFL;
        
        Id stdPriceBook = Test.getStandardPricebookId();
        List<Product2> prods = [SELECT Id FROM Product2 WHERE Name = :ship.Name];
        Product2 p;
        PricebookEntry pbe;
        
        if(prods.size()>0){
            p = prods[0];
            pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id =:p.Id LIMIT 1];
        }else{
            p = new Product2(Name=ship.Name, IsActive = true);
            insert p;
            
            pbe = new PricebookEntry();
            pbe.IsActive = true;
            pbe.UnitPrice = 1;
            pbe.Product2Id = p.Id;
            pbe.Pricebook2Id = stdPriceBook;
            insert pbe;
        }               
        
        Order order = new Order();
        order.AccountId = ship.Account_for__c;
        order.Status = 'Draft';
        order.EffectiveDate = Date.today();
        order.Pricebook2Id = stdPriceBook;
        order.DefaultProduct__c = p.Id;
        order.DefaultPbe__c = pbe.Id;
        order.Shipment__c = ship.Id;
        insert order;
        
        System.debug('ORDER: ' + order.Id);
        
        Status_Datetime__c statusdate =new Status_Datetime__c();
        statusdate.Shipment__c=ship.id;
        statusdate.Status_Value__c='Confirmed';
        insert statusdate;

        OrderItem line = new OrderItem();
        line.ShipServLineId__c = 'test';
        line.ServLine_Name__c = 'test';
        line.Service_Rate_Name__c = 'PSTest';
        line.Quantity = 1;
        line.UnitPrice = 1;
        line.VAT__c = '16';
        line.Group__c = 'terr';
        line.ItemCode__c = 'FTN';
        line.CurrencyLine__c = 'MXN';
        line.Std_Buy_Amount__c = 100;
        line.Product2Id = p.Id;
        line.PricebookEntryId = pbe.Id;
        line.OrderId = order.Id;        
        insert line;
        
        line = new OrderItem();
        line.ShipServLineId__c = 'test';
        line.ServLine_Name__c = 'test';
        line.Service_Rate_Name__c = 'test';
        line.Quantity = 1;
        line.UnitPrice = 1;
        line.VAT__c = '16';
        line.Group__c = 'terr';
        line.ItemCode__c = 'FTN';
        line.CurrencyLine__c = 'MXN';
        line.Std_Buy_Amount__c = 100;
        line.Product2Id = p.Id;
        line.PricebookEntryId = pbe.Id;
        line.OrderId = order.Id;
        insert line;
        
        delete line;
    }
}