respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_InternalFollower</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_External_Follower_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account External Follower User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_PartnerUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Associated_Document__c.object
<CustomObject>
    <description>Import space for documents created and associated to an Account, Import-Export and/or shipment.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Claim__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Import-Export Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer_Quote__c.Account_for__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SCM_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SCM Contract</label>
        <referenceTo>SCM_Contract__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Consolidation_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment Consolidation Data</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shipment_Consolidation_Data__c.Shipment__c</field>
                <operation>equals</operation>
                <valueField>$Source.Shipment__c</valueField>
            </filterItems>
            <filterItems>
                <field>Shipment_Consolidation_Data__c.Import_Export_Quote__c</field>
                <operation>equals</operation>
                <valueField>$Source.Import_Export_Quote__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Shipment_Consolidation_Data__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Disbursement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment Disbursement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Shipment__c</field>
                <operation>equals</operation>
                <valueField>Shipment_Disbursement__c.Shipment__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Shipment_Disbursement__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shipment__c.Account_for__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shopping_Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Field Order</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shopping_Cart__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Shopping_Cart__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Quote/Order</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier_Quote__c.Supply_Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Supply_Project__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier_Quote__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Document</label>
    <nameField>
        <label>Associated Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <formula>Account_for__r.Owner.FirstName  &amp; &quot; &quot; &amp;Account_for__r.Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner (Sales Executive)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment_Consolidation_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment Consolidation Data</label>
        <referenceTo>Shipment_Consolidation_Data__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Consolidation_Data__c.object
<CustomObject>
    <fields>
        <fullName>Disbursement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Disbursement</label>
        <referenceTo>Shipment_Disbursement__c</referenceTo>
        <relationshipLabel>Shipment Consolidation Data</relationshipLabel>
        <relationshipName>Shipment_Consolidation_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Import-Export Quote</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Shipment Consolidation Data</relationshipLabel>
        <relationshipName>Shipment_Orders_Consolidation_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Shipment_Orders_Consolidation_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Shopping_Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Field Order</label>
        <referenceTo>Shopping_Cart__c</referenceTo>
        <relationshipLabel>Shipment Consolidation Data</relationshipLabel>
        <relationshipName>Shipment_Consolidation_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Quote/Order</label>
        <referenceTo>Supplier_Quote__c</referenceTo>
        <relationshipLabel>Shipment Consolidation Data</relationshipLabel>
        <relationshipName>Shipment_Consolidation_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipment Consolidation Data (Supplier)</relationshipLabel>
        <relationshipName>Shipment_Consolidation_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment Consolidation Data</label>
    <nameField>
        <label>Shipment Consolidation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Consolidation Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Disbursement__c.object
<CustomObject>
    <description>Object specifying all payment history and details along with each Import-Export on each Account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Supplier Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Shipment_Disbursements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Disbursements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Disbursement</label>
    <nameField>
        <label>Disbursement Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Supplier_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Executive User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Suppliers_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Request_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Request</label>
        <referenceTo>Supplier_Request_RFP__c</referenceTo>
        <relationshipLabel>Suppliers Quotes/Orders</relationshipLabel>
        <relationshipName>Supplier_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Quote/Order</label>
    <nameField>
        <displayFormat>SQO# {YYYY}-{000000}</displayFormat>
        <label>Supplier Quote/Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Transport_Packaging_Data__c.object
<CustomObject>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Shipment_Packaging_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Transport Pickup/Delivery Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transport Pickup/Delivery Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Trigger_AssociatedDocument_Test.cls
@isTest
public class Trigger_AssociatedDocument_Test {
	@isTest(SeeAllData=true)
    //Trigger afectados
    //NEU_OM_UpdateFoAssociated_Document
    //PAK_Docs_tgr
    public static void AssociatedDocument_Test(){
        Associated_Document__c updateAssociatedDocument = [SELECT Name, Account__c,Import_Export_Quote__c,Shipment__c, Account__r.Account_Executive_User__c, 
                                                           Account__r.Account_External_Follower_User__c, Account__r.OwnerId, CreatedById, LastModifiedById, 
                                                           Claim__r.CreatedById, Import_Export_Quote__r.CreatedById, SCM_Contract__r.CreatedById,Shipment__r.CreatedById, 
                                                           Shipment_Consolidation_Data__r.CreatedById, Shipment_Disbursement__r.CreatedById, Shopping_Cart__r.CreatedById,
                                                           Supplier_Quote__r.CreatedById, Supplier_Request_RFP__r.CreatedById, Supply_Project__r.CreatedById, 
                                                           Shipment_Packaging_Consolidation_Data__r.CreatedById FROM Associated_Document__c 
                                                           WHERE Import_Export_Quote__c !=null AND Shipment__c !=null LIMIT 1];
        SCM_Contract__c scm_contract = new SCM_Contract__c( Name='SCM contract name', Account_for__c = updateAssociatedDocument.Account__c);
        insert scm_contract;
        Account carrier_test = [SELECT Id, Name FROM Account WHERE Record_Type_Name__c = 'Supply Chain Partner' LIMIT 1];
        Shipment_Consolidation_Data__c shipconsodata = new Shipment_Consolidation_Data__c(Name= ' test shipconsodata', Shipment__c = updateAssociatedDocument.Shipment__c);
        insert shipconsodata;
        Claim__c claim = new Claim__c(Customer__c = updateAssociatedDocument.Account__c);
        insert claim;
        Shopping_Cart__c shop = new Shopping_Cart__c(Customer__c=updateAssociatedDocument.Account__c);
        insert shop;
        Supply_Project__c supplyproject = new Supply_Project__c(Name='project test', Customer__c = updateAssociatedDocument.Account__c);
        insert supplyproject;
        Supplier_Quote__c supquote = new Supplier_Quote__c(Supply_Project__c= supplyproject.Id, Supplier__c=carrier_test.Id);
        insert supquote;
        Supplier_Request_RFP__c suprequest = new Supplier_Request_RFP__c(Supply_Project__c = supplyproject.Id, Supplier__c=carrier_test.Id);
        insert suprequest;
        Transport_Packaging_Data__c transporpack = new Transport_Packaging_Data__c(Name='transporpack', Shipment__c =updateAssociatedDocument.Shipment__c);
        insert transporpack;
        
        Associated_Document__c newAssociatedDocument = new Associated_Document__c(Name='test',Account__c= updateAssociatedDocument.Account__c,
                                                                                  Import_Export_Quote__c=updateAssociatedDocument.Import_Export_Quote__c, 
                                                                                  Shipment__c=updateAssociatedDocument.Shipment__c,Claim__c=claim.Id, 
                                                                                  SCM_Contract__c=scm_contract.Id, Shipment_Consolidation_Data__c=shipconsodata.Id,
                                                                                  Shopping_Cart__c=shop.Id, Supplier_Quote__c=supquote.Id,
                                                                                  Supplier_Request_RFP__c=suprequest.Id , Supply_Project__c=supplyproject.Id, 
                                                                                  Shipment_Packaging_Consolidation_Data__c=  transporpack.Id);
        insert newAssociatedDocument;
        updateAssociatedDocument.Name = 'test2';
        update updateAssociatedDocument;
     }
}