respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Area__c</fullName>
        <inlineHelpText>Make sure that you have the same Business Areas for ACCOUNTS, FAMILIES, PRICE LISTS and SUPPLY PROJECTS.</inlineHelpText>
        <label>Business Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air Freight</fullName>
                </value>
                <value>
                    <fullName>Animal Nutrition</fullName>
                </value>
                <value>
                    <fullName>Auto-Parts</fullName>
                </value>
                <value>
                    <fullName>Cloths &amp; Accessories</fullName>
                </value>
                <value>
                    <fullName>Construction &amp; Engineering</fullName>
                </value>
                <value>
                    <fullName>Construction &amp; Mining</fullName>
                </value>
                <value>
                    <fullName>Energy &amp; Hydrocarbons</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverages</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Machinery &amp; Parts</fullName>
                </value>
                <value>
                    <fullName>MERA Autoparts</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Other Services</fullName>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                </value>
                <value>
                    <fullName>Rail Freight</fullName>
                </value>
                <value>
                    <fullName>Recruiting Services</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Sea Freight</fullName>
                </value>
                <value>
                    <fullName>Telecom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Transporter</fullName>
        <active>true</active>
        <description>Logistic companies that we use to transport our goods. Valid for Carriers, Forwarders, 3PLs,...etc.</description>
        <label>Supply Chain Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Final Destination Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Move_Type__c</fullName>
        <label>Move Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Door to Door</fullName>
                    <default>true</default>
                    <label>Door to Door</label>
                </value>
                <value>
                    <fullName>Door to Port</fullName>
                </value>
                <value>
                    <fullName>Port to Door</fullName>
                </value>
                <value>
                    <fullName>Port to Port</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Initial Origin Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Pricing_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Import_Export_Quotes_Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                    <default>true</default>
                    <label>NATIONAL</label>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>FP</fullName>
                </value>
                <value>
                    <fullName>FO</fullName>
                </value>
                <value>
                    <fullName>MAYOREO</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer, Supplier or Agente Aduanal</inlineHelpText>
        <label>Cuenta Origen</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Shipper, Customer, Supply Chain Partner, Supplier Owner or Lessee of Vehicule, Agente Aduanal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Supplier/Shipper Account)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Supplier_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Quote_Item_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of an Import-Export to generate Shipment Cargo Lines.</description>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <formula>Import_Export_Quote__r.Account_for__r.Owner.FirstName &amp; &quot; &quot;&amp;Import_Export_Quote__r.Account_for__r.Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expense_Amount__c</fullName>
        <label>Expense Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Name</label>
        <referenceTo>Sourcing_Item__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Supplier_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Supplier/Owner</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Quote_Item_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subfamily__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Specify Family first</inlineHelpText>
        <label>Subfamily</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Subfamily__c.Product_Family__c</field>
                <operation>equals</operation>
                <valueField>$Source.Family__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Subfamily__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Quote_Item_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight_Kgs__c</fullName>
        <formula>BLANKVALUE(Units__c  * BLANKVALUE( Item_Name__r.Master_Box_Gross_Weight_kg__c / Item_Name__r.Units_x_Master_Box__c , Item_Name__r.Weight_Kgs__c ),0)</formula>
        <inlineHelpText>&quot;Units&quot; x (&quot;Master Box Gross Weight (Kg)&quot;/&quot;Units x Master Box&quot;)</inlineHelpText>
        <label>Peso Bruto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Cargo Line</label>
    <nameField>
        <label>Imp-Exp Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_Test_Generate_Supplier_Orders.cls
@isTest()
public class NEU_Test_Generate_Supplier_Orders {
	@isTest(SeeAllData=true)
     static void test_NEU_Generate_Supplier_Orders() {
     	
     	NEU_StaticVariableHelper.setBoolean1(true);
     	
        //List<Account> list_accounts = NEU_Utils.getAccounts('Customer,Transporter,');
        //Account a = list_accounts[0];
        // a.Owner.SalesEmployer__c='SalesEmployer__c';
        //insert a;
        Account a = [SELECT Id, Owner.isActive,Owner.SalesEmployer__c, OwnerId,
            RecordType.DeveloperName FROM Account WHERE RecordType.DeveloperName='Customer'
            AND Owner.isActive=true AND Owner.SalesEmployer__c!=null LIMIT 1];
        //Account sup = list_accounts[1];
        //insert sup;
        Account sup = [SELECT Id, Owner.isActive,Owner.SalesEmployer__c, 
            RecordType.DeveloperName FROM Account WHERE RecordType.DeveloperName='Transporter'
            AND Owner.isActive=true AND Owner.SalesEmployer__c!=null LIMIT 1];

        Customer_Quote__c importexportquote = new Customer_Quote__c(Pricing_Executive__c = a.OwnerId, Account_for__c = a.Id, Freight_Mode__c='Air',Service_Mode__c='Import', Service_Type__c='LCL Cargo',Move_Type__c='Door to Door',Origin_Address__c='tst adrress', Destination_Address__c='test address', Supplier_Account__c =sup.Id);
        insert importexportquote;
        Product_Family__c c = new Product_Family__c(Name = 'Test acount',Business_Area__c = 'Sales');
        insert c;
        Subfamily__c d2 = new Subfamily__c(Product_Family__c = c.Id, Name = 'test subfamily');
        insert d2;
        Sourcing_Item__c g = new Sourcing_Item__c(Name = 'Test item',Subfamily__c = d2.Id, Sourcing_Family__c =c.id, Account_Owner__c= a.Id, Weight_Kgs__c= 100, Master_Box_Height_cm__c = 1000, Units_x_Master_Box__c=10 );
        insert g;
        Quote_Item_Line__c quote = new Quote_Item_Line__c(Import_Export_Quote__c = importexportquote.id,Name = 'lineas items', Item_Name__c= g.Id, Units__c=1000, Expense_Amount__c = 100, Item_Supplier_Owner__c = sup.Id);
        insert quote;
        NEU_Generate_Supplier_Orders  gso = new NEU_Generate_Supplier_Orders(new ApexPages.StandardController( importexportquote ));
        gso.generate();
     }
}