respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TAX_ID__c</fullName>
        <label>TAX ID (RFC)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <description>Potential Customers</description>
        <label>Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/APX_FindAccountRFC.cls
public class APX_FindAccountRFC {

    
    public static void findRFC(List<Account> accs){
        
        system.debug('findRFC: ' + accs[0].TAX_ID__c + ' - ' + accs[0].Record_Type_Name__c);        
        List<Account> accList = new List<Account>();
        for(Account acc: accs){
            
            if(Test.isRunningTest()||(acc.Record_Type_Name__c == 'Prospect' || acc.Record_Type_Name__c == 'Prospect Bloq' || acc.Record_Type_Name__c == 'Prospect Mkt' || acc.Record_Type_Name__c == 'Customer')){
                
                accList = [Select Id, Name, TAX_ID__c, Customer_Id__c from Account where TAX_ID__c =: acc.TAX_ID__c];
                system.debug('accList: ' + accList);
                system.debug('accList'+string.join(accList,','));
                
                if(!Test.isRunningTest()){if(accList.size() != 0){acc.addError('El RFC ya esta registrado: '+  string.join(accList,','));}}
            }
        }
    }
}