respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomRate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tarifario</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fee_Category__c</fullName>
        <inlineHelpText>Be aware that if you change the values of this picklist the hard corde of the Import-Export PDF quote must also be changed by our end.</inlineHelpText>
        <label>Rate Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Road Freights</fullName>
                    <default>true</default>
                    <label>Road Freights</label>
                </value>
                <value>
                    <fullName>Other Service Charges</fullName>
                </value>
                <value>
                    <fullName>Sea Freights</fullName>
                </value>
                <value>
                    <fullName>Air Freights</fullName>
                </value>
                <value>
                    <fullName>POL Charges</fullName>
                </value>
                <value>
                    <fullName>POD Charges</fullName>
                </value>
                <value>
                    <fullName>Drayages</fullName>
                </value>
                <value>
                    <fullName>Mayoreo</fullName>
                </value>
                <value>
                    <fullName>Tarimas</fullName>
                </value>
                <value>
                    <fullName>Warehouse</fullName>
                </value>
                <value>
                    <fullName>IMPAK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sell Rate</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>% Service Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GroupGVS</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Moneda__c</fullName>
        <label>Moneda</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MXN</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Negociacion__c</fullName>
        <label>Negociacion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SI</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                    <default>true</default>
                    <label>Fixed</label>
                </value>
                <value>
                    <fullName>Per Kg</fullName>
                </value>
                <value>
                    <fullName>Per M3</fullName>
                </value>
                <value>
                    <fullName>Per Container</fullName>
                </value>
                <value>
                    <fullName>Per TON</fullName>
                </value>
                <value>
                    <fullName>Per Pallet</fullName>
                </value>
                <value>
                    <fullName>Per Day</fullName>
                </value>
                <value>
                    <fullName>% of Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Service_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SAP Service Type Sell</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Group__c</field>
                <operation>equals</operation>
                <valueField>SAP_Service_Type__c.Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>SAP_Service_Type__c.Activo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Service_Type__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Services_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TT_Days__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <label>TT Days</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Until__c</fullName>
        <defaultValue>now()</defaultValue>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CargaTarifarioVentaController.cls
public with sharing class CargaTarifarioVentaController {
    public class csv{
        public string Route {get;set;}
        public string RateName {get;set;}
        public string ValidFrom {get;set;}
        public string ValidUntil {get;set;}
        public string AccountFor {get;set;}
        public string CustomerID {get;set;}
        public string TTDays {get;set;}
        public string SellRate {get;set;}
        public string ContainerType {get;set;}
        public string Grupo {get;set;}
        public string SAPST {get;set;}
        public string Comments {get;set;}
        public string Moneda {get;set;}
    }   
    
    private class accountBase
    {
        public string customerId {get;set;}
        public string accountName {get;set;}
    }
    
    @AuraEnabled
    public static string cargarTarifario(string jsn){
        string ratetype = 'Fixed';
        string moneda = 'MXN';
        boolean tarif = true;
        string negociacion = 'Si';
        string rtId = Schema.SObjectType.Fee__c.getRecordTypeInfosByName().get('Sea/Ground Freight').getRecordTypeId();
        string ratecategory = 'Road Freights';
        boolean activo = true;
        // Requeridos: Ruta, rate name, rate category, account for, tt days, rate type, container type, sell rate
        try{
            System.debug('JSON from CSV: ' + jsn);
            List<csv> lines = (List<csv>)JSON.deserialize(jsn, List<csv>.class);
            Integer linesCount = lines.size();
            System.debug('No. Lines: ' + linesCount);
            if(linesCount > 0){
                Set<string> rutas = new Set<string>();
                Set<string> cuentas = new set<string>();//Set<accountBase>();
                Set<string> contenedores = new Set<string>();
                Set<string> sst = new Set<string>();                
                Map<string, Id> mapRutas = new Map<string, Id>();
                Map<string, Id> mapCuentas = new Map<string, Id>();
                Map<string, Id> mapContenedores = new Map<string, Id>();
                Map<string, Id> mapSst = new Map<string, Id>();
                
               
                for(csv l : lines)
                {
                    system.debug('linea l ' + l);
                    //CUENTAS
                    if(l.AccountFor == null || l.AccountFor == '')
                    {
                        return 'Todas las líneas deben tener un cliente';
                    }
                    if(l.CustomerID == null || l.CustomerID == '')
                    {
                        return 'Todas las líneas deben tener un customer ID';
                    }
                    if( l.AccountFor != null && l.AccountFor != '' && l.CustomerID != null && l.CustomerID != '')
                    {
                       // accountBase account = new accountBase();
                        //account.customerId = l.CustomerID;
                        //account.accountName = l.AccountFor;
                        cuentas.add( l.CustomerID );
                    }
                    
                    //RUTAS
                    if(l.Route == null || l.Route == ''){return 'Todas las líneas deben tener una ruta';}
                    else{if(!rutas.contains(l.Route)){rutas.add(l.Route.toLowercase());}}
                   
                    //CONTENEDORES
                    if(l.ContainerType == null || l.ContainerType == ''){return 'Todas las líneas deben tener un contenedor';}
                    else{if(!contenedores.contains(l.ContainerType)){contenedores.add(l.ContainerType);}}
                    
                    //SAP
                    if(l.SAPST == null || l.SAPST == ''){return 'Todas las líneas deben tener SAPST';}
                    else{if(!sst.contains(l.SAPST)){sst.add(l.SAPST);}}
                    
                    //
                    if(l.RateName == null || l.RateName == '')
                    {return 'Todas las líneas deben tener un nombre para la tarifa';}
                    else if(l.TTDays == null || l.TTDays == ''){return 'Todas las líneas deben tener TTDays';}
                    else if(l.SellRate == null || l.SellRate == ''){return 'Todas las líneas deben tener precio de venta';}
                    else if(l.Grupo == null || l.Grupo == ''){return 'Todas las líneas deben tener grupo';}
                }

                for(Carrier_Line_Load_Point__c ruta : [SELECT Id, Name FROM Carrier_Line_Load_Point__c WHERE Name IN:rutas]){
                    if(!mapRutas.containsKey(ruta.Name.toLowercase())){mapRutas.put(ruta.Name.toLowercase(), ruta.Id);}
                }
                
                system.debug('cuentas ' +  cuentas);
                
               // for (accountBase account : cuentas){
               	 for(Account a : [SELECT Id, Name,Customer_Id__c FROM Account WHERE  Customer_Id__c in: cuentas]){
                    if(!mapCuentas.containsKey(a.Customer_Id__c)){mapCuentas.put(a.Customer_Id__c, a.Id);}
               	 //}
                }
                for(Container_Type__c ct : [SELECT Id, Name FROM Container_Type__c WHERE Name IN:contenedores]){
                    if(!mapContenedores.containsKey(ct.Name)){mapContenedores.put(ct.Name, ct.Id);} 
                }
                for(SAP_Service_Type__c sapst : [SELECT Id, Name FROM SAP_Service_Type__c WHERE Name IN:sst]){
                    if(!mapSst.containsKey(sapst.Name)){mapSst.put(sapst.Name, sapst.Id);} 
                }
                
                system.debug('mapCuentas ' + mapCuentas);
                
                List<Fee__c> serviceRates = new List<Fee__c>();
                for(csv l : lines){
                    if(!mapRutas.containsKey(l.Route.toLowercase())){return 'La ruta ' + l.Route + ' no se encuentra en la base de datos';}
                    if(!mapCuentas.containsKey(l.customerID)){return 'El cliente ' + l.AccountFor + ' no se encuentra en la base de datos';}
                    if(!mapContenedores.containsKey(l.ContainerType)){return 'El contenedor ' + l.ContainerType + ' no se encuentra en la base de datos';}
                    if(!mapSst.containsKey(l.SAPST)){return 'El SAPST ' + l.SAPST + ' no se encuentra en la base de datos';}
                    Fee__c rate = new Fee__c();
                    rate.Route__c = mapRutas.get(l.Route.toLowercase());
                    rate.Name = l.RateName;
                    if(l.ValidFrom != null && l.ValidFrom != ''){rate.Valid_From__c = date.parse(l.ValidFrom);}
                    if(l.ValidUntil != null && l.ValidUntil != ''){rate.Valid_Until__c = date.parse(l.ValidUntil);}
                    rate.Account_for__c = mapCuentas.get(l.customerID);
                    rate.TT_Days__c = l.TTDays;
                    rate.Container_Type__c = mapContenedores.get(l.ContainerType);
                    rate.Fee_Rate__c = double.valueOf(l.SellRate);
                    rate.Group__c = l.Grupo;
                    rate.CurrencyIsoCode = l.Moneda;
                    rate.SAP_Service_Type__c = mapSst.get(l.SAPST);
                    if(l.Comments != null && l.Comments != ''){rate.Comments__c = l.Comments;}
                    // Valores del custom setting
                    rate.Rate_Type__c = ratetype;
                    // rate.CurrencyIsoCode = moneda;
                    rate.CustomRate__c = tarif;
                    rate.Negociacion__c = negociacion;
                    // rate.Moneda__c = moneda;
                    rate.RecordTypeId = rtId;
                    rate.Fee_Category__c = ratecategory;
                    rate.Active__c = activo;
                    
                    serviceRates.add(rate);
                }
                
                insert serviceRates;
                return 'ok';}else{return 'No se encontraron líneas en el documento';}}catch(Exception e){System.debug('EX: ' +  e.getMessage() + ' - ' + e.getCause() + ' - ' + e.getLineNumber() + ' - ' + e.getStackTraceString()); return e.getMessage() + ' - ' + e.getCause() + ' - ' + e.getLineNumber() + ' - ' + e.getStackTraceString();}
    }
}