respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Late_Outstanding_Payments__c</fullName>
        <label>Late Outstanding Payments</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Limit_Exceeded__c</fullName>
        <formula>Total_Collection_Outstanding_Balance__c - Credit_Limit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Limit Exceeded</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status_Account__c</fullName>
        <label>Status Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Discard</fullName>
                </value>
                <value>
                    <fullName>Discard with posibilities</fullName>
                </value>
                <value>
                    <fullName>Cold</fullName>
                    <default>true</default>
                    <label>Cold</label>
                </value>
                <value>
                    <fullName>Potential Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_Account_Warnings.cls
public with sharing class NEU_Account_Warnings 
{
    public Account record;
    public String disp_1 {get;set;}
    public String disp_2 {get;set;}
    public String disp_Inactive {get; set;}
    
    ApexPages.StandardController con;
    
    public NEU_Account_Warnings(ApexPages.StandardController stdController) 
    {
        con = stdController;

        try 
        { 
            record = [select Id, Name, Credit_Limit__c, Limit_Exceeded__c, Late_Outstanding_Payments__c, Status_Account__c  from Account where id = :con.getRecord().id];
        } 
        catch(Exception ee){record = new Account();}
        
        
        //PLEASE, CHECK LIMIT OF CREDIT ALREADY EXCEEDED ON ACCOUNT
        if(record.Credit_Limit__c  != null && record.Credit_Limit__c > 0 && record.Limit_Exceeded__c > 0)
            disp_1 = 'display:block;';
        else
            disp_1 = 'display:none;';
        
        //PLEASE, CHECK OUTSTANDING PAYMENTS ALREADY DUE ON ACCOUNT
        if(record.Late_Outstanding_Payments__c > 0)
            disp_2 = 'display:block;';
        else
            disp_2 = 'display:none;';

        //Customer is Inactive, please contact Administration Team if you think it's an error

        if(record.Status_Account__c == 'Inactive')
        {
            disp_Inactive = 'display:block;';
        }
        else
        {
            disp_Inactive = 'display:none;';
        }
        
    }
}