respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Consignee_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consignee Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Consignee__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consignee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Consignee)</relationshipLabel>
        <relationshipName>NEU_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Associated_Document__c.object
<CustomObject>
    <description>Import space for documents created and associated to an Account, Import-Export and/or shipment.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acuse</fullName>
                </value>
                <value>
                    <fullName>Bill of Lading</fullName>
                </value>
                <value>
                    <fullName>Guía Consolidado</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Import Permit</fullName>
                </value>
                <value>
                    <fullName>Customer Order</fullName>
                </value>
                <value>
                    <fullName>Order Confirmation</fullName>
                </value>
                <value>
                    <fullName>Technical Specifications</fullName>
                </value>
                <value>
                    <fullName>Proforma Invoice</fullName>
                </value>
                <value>
                    <fullName>Commercial Invoice</fullName>
                </value>
                <value>
                    <fullName>Packaging List</fullName>
                </value>
                <value>
                    <fullName>Shipping Line Instruction</fullName>
                </value>
                <value>
                    <fullName>Transport Delivery Instruction</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Telex</fullName>
                </value>
                <value>
                    <fullName>Op - Licencia</fullName>
                </value>
                <value>
                    <fullName>Op - Tarjeta Circulacion</fullName>
                </value>
                <value>
                    <fullName>Op - Placas Unidad</fullName>
                </value>
                <value>
                    <fullName>Formato de Alta de Proveedor Firmado</fullName>
                </value>
                <value>
                    <fullName>Comprobante de Domicilio</fullName>
                </value>
                <value>
                    <fullName>IFE del Represéntate Legal</fullName>
                </value>
                <value>
                    <fullName>Poliza Vigente y del Prestador</fullName>
                </value>
                <value>
                    <fullName>Opinion de Cumplimiento Ante el SAT</fullName>
                </value>
                <value>
                    <fullName>Convenio</fullName>
                </value>
                <value>
                    <fullName>Alta del SAT</fullName>
                </value>
                <value>
                    <fullName>Factura Timbrada</fullName>
                </value>
                <value>
                    <fullName>Perfil de Conductores</fullName>
                </value>
                <value>
                    <fullName>Negociación de tarifas</fullName>
                </value>
                <value>
                    <fullName>MC Number</fullName>
                </value>
                <value>
                    <fullName>Ejemplo de Acuse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_URL__c</fullName>
        <label>Document URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Import-Export Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer_Quote__c.Account_for__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Document</label>
    <nameField>
        <label>Associated Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>B_L_Status__c</fullName>
        <label>B/L Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Original</fullName>
                </value>
                <value>
                    <fullName>Telex</fullName>
                </value>
                <value>
                    <fullName>Sea Waybill</fullName>
                </value>
                <value>
                    <fullName>Original Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Consignee_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Dependent on &quot;Consignee Account&quot;</inlineHelpText>
        <label>Contacto Destino</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Consignee__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Consignee Contact)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer or Agente Aduanal</inlineHelpText>
        <label>Cuenta Destino</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Consignee, Supply Chain Partner, Agente Aduanal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Consignee Account (Destination))</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Dependent on Account for (Customer)</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Contact)</relationshipLabel>
        <relationshipName>Import_Export_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DO_Contact_1_Release_to_Company__c</fullName>
        <label>DO Contact 1 Release to Company</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DO_Contact_1_Shipment_Pickup__c</fullName>
        <label>DO Contact 1 Shipment Pickup</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DO_Release_Date__c</fullName>
        <label>DO Release Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DO_Release_Valid_To__c</fullName>
        <label>DO Release Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DO_Release_to_Company__c</fullName>
        <label>DO Release to Company</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DO_Remarks_Shipment_Pickup__c</fullName>
        <label>DO Remarks Shipment Pickup</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DO_Remarks__c</fullName>
        <label>DO Remarks</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DO_Shipment_Pickup__c</fullName>
        <label>DO Shipment Pickup</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Shipment_Delivery_Date__c</fullName>
        <label>Last Shipment (Delivery Date)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POD_incoterm__c</fullName>
        <label>POD incoterm</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CFR</fullName>
                </value>
                <value>
                    <fullName>CIF</fullName>
                </value>
                <value>
                    <fullName>CIP</fullName>
                </value>
                <value>
                    <fullName>CPT</fullName>
                </value>
                <value>
                    <fullName>DAP</fullName>
                </value>
                <value>
                    <fullName>DAT</fullName>
                </value>
                <value>
                    <fullName>DDP</fullName>
                </value>
                <value>
                    <fullName>EXW</fullName>
                </value>
                <value>
                    <fullName>FCA</fullName>
                </value>
                <value>
                    <fullName>FOB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_DO_save_pdf.cls
public with sharing class NEU_DO_save_pdf
{
	public Customer_Quote__c record;
	public string language {get;set;}
	public Customer_Quote__c new_ie{get;set;}
	public Boolean enabled{get;set;}
	public string url_pdf {get;set;}
	public Document documento_asociado
	{
		get
			{
				if (documento_asociado == null)
					documento_asociado = new Document();
				return documento_asociado;
			}
		set;
	}

	ApexPages.StandardController con;

	public NEU_DO_save_pdf(ApexPages.StandardController stdController)
		{

			con = stdController;

			try {
				record = [select Id, Name, Freight_Mode__c, B_L_Status__c, Account_for__c, Account_for__r.Id, Account_for__r.Name, Contact__c, Consignee__c,
						Consignee_Contact__c, POD_incoterm__c,DO_Contact_1_Shipment_Pickup__c,
						DO_Contact_1_Release_to_Company__c, DO_Release_to_Company__c, DO_Release_Date__c,
						DO_Release_Valid_To__c, DO_Remarks__c, DO_Remarks_Shipment_Pickup__c, DO_Shipment_Pickup__c
						from Customer_Quote__c where id =: con.getRecord().id limit 1 for update];
			} catch( Exception ee) {
				record = new Customer_Quote__c();
			}

			new_ie = new Customer_Quote__c();
			//Id Release To company == > The first time will always be empty, but if the document is edited a second time, the app get the specific fields
			if(!String.isEmpty(record.DO_Release_to_Company__c))
			{
				new_ie.Account_for__c = record.DO_Release_to_Company__c;

				//Id Contact 1 Release To company
				if(!String.isEmpty(record.DO_Contact_1_Release_to_Company__c))
					new_ie.Contact__c = record.DO_Contact_1_Release_to_Company__c;
			}
			else
			{
				//If the document does not yet exist, the data for the IE account is obtained
				new_ie.Account_for__c = record.Account_for__c;
				new_ie.Contact__c = record.Contact__c;
			}

			//Shipment Pickup Account
			if(!String.isEmpty(record.DO_Shipment_Pickup__c))
			{
				new_ie.Consignee__c = record.DO_Shipment_Pickup__c;

				//Id Contact 1 Shipment Pickup Account
				if(!String.isEmpty(record.DO_Contact_1_Shipment_Pickup__c))
					new_ie.Consignee_Contact__c = record.DO_Contact_1_Shipment_Pickup__c;

			}
			/*else
			{
				new_ie.Consignee__c = record.Consignee__c;
				new_ie.Consignee_Contact__c = record.Consignee_Contact__c;
			}*/

			//Release Date
			if(record.DO_Release_Date__c != null)
				new_ie.DO_Release_Date__c = record.DO_Release_Date__c;
			else
				new_ie.DO_Release_Date__c = system.today();
			//Valid To
			if(record.DO_Release_Valid_To__c != null)
				new_ie.DO_Release_Valid_To__c = record.DO_Release_Valid_To__c;
			else
				new_ie.DO_Release_Valid_To__c = system.today().adddays(3);
			/*Required Fields for Temporal Import/Export*/
			//Release Date
			new_ie.Last_Shipment_Delivery_Date__c = system.today();
			//Release Valid To
			new_ie.Valid_From__c = system.today().adddays(3);

			//Remarks For Goods
			if(!String.isEmpty(record.DO_Remarks__c))
				new_ie.DO_Remarks__c = record.DO_Remarks__c;
			//Remarks for Shipment Pick up
			if(!String.isEmpty(record.DO_Remarks_Shipment_Pickup__c))
				new_ie.DO_Remarks_Shipment_Pickup__c = record.DO_Remarks_Shipment_Pickup__c;

			//Comments future

			//Conditions for enabled Delivery Order
			enabled = true;
			if(record.Freight_Mode__c == 'Sea')
			{
				if(record.B_L_Status__c == null || record.B_L_Status__c == 'Original')
				{
					ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Needed Bill\'s of Lading (B/L Status) in Import/Export: '+record.Name));
					enabled = false;
				}
			}
			if(enabled)
			{
				generarURL_pdf();
			}
		}

	public void generarURL_pdf()
		{
			if(new_ie != null)
			{
				url_pdf = '';
				url_pdf += 'id=' + record.Id;
				url_pdf += '&id_rc=' +(new_ie.Account_for__c != null ? neu_utils.safestring(new_ie.Account_for__c) : '');
				url_pdf += '&id_rc_c1='+ (new_ie.Contact__c != null ? neu_utils.safestring(new_ie.Contact__c) : '');
				url_pdf += '&id_fd='+ (new_ie.Consignee__c != null ? neu_utils.safestring(new_ie.Consignee__c) : '');
				url_pdf += '&id_fd_c1='+ (new_ie.Consignee_Contact__c != null ? neu_utils.safestring(new_ie.Consignee_Contact__c) : '');
				url_pdf += '&remarks='+ (new_ie.DO_Remarks__c != null ? neu_utils.safestring(new_ie.DO_Remarks__c) : '');
				url_pdf += '&release_date='+new_ie.DO_Release_Date__c.format();
				url_pdf += '&release_valid='+new_ie.DO_Release_Valid_To__c.format();
				url_pdf += '&shipment_pick_up='+ (new_ie.DO_Remarks_Shipment_Pickup__c != null ? neu_utils.safestring(new_ie.DO_Remarks_Shipment_Pickup__c) : '');
			}
		}

	public string date_release {get;set;}
	public string date_valid_to {get;set;}

	public void generar_pdf()
		{
			//Release To Company previuosly Account For Import/Export
			List<Account> query_accountRelease = [select Id, Name from Account where Id=:new_ie.Account_for__c];
			if(query_accountRelease != null & query_accountRelease.size()>0)
			{
				//Check contacts
				List<Contact> query_contactRTC1 = [Select Id, Name from Contact where AccountId  =: new_ie.Account_for__c and Id =: new_ie.Contact__c];
				if(query_contactRTC1 == null || query_contactRTC1.size()==0)
					new_ie.Contact__c = null;
			}
			else
			{
				new_ie.Contact__c = null;

			}
			//Shipment Pickup Account previuosly FInal Delivery Account
			List<Account> query_accountFinal = [select Id, Name from Account where Id=:new_ie.Consignee__c];
			if(query_accountFinal != null & query_accountFinal.size()>0)
			{
				//Check contacts
				List<Contact> query_contactSP1 = [Select Id, Name from Contact where AccountId  =: new_ie.Consignee__c and Id =: new_ie.Consignee_Contact__c];
				if(query_contactSP1 == null || query_contactSP1.size()==0)
					new_ie.Consignee_Contact__c = null;

			}
			else
			{
				new_ie.Consignee_Contact__c = null;
			}

			//Reload pdf url
			generarURL_pdf();
		}

	public PageReference return_page()
		{
			return con.view();
		}

	public PageReference crear()
		{
			//Checks Required Fields
			Boolean error = false;
			if(new_ie.DO_Release_Date__c == null)
			{
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You must choose "Release Date"'));
				error = true;
			}
			if(new_ie.DO_Release_Valid_To__c == null)
			{
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You must choose "Release Valid To"'));
				error = true;
			}
			if(!error && Date.valueOf(new_ie.DO_Release_Date__c) >  new_ie.DO_Release_Valid_To__c)
			{
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Release Date must be greater than Release Valid To'));
				error = true;
			}
			if(error)
				return null;

			PageReference pdf = null;
			pdf = Page.NEU_DO_pdf;
			pdf.getParameters().put('id',record.Id);
			pdf.getParameters().put('id_rc',new_ie.Account_for__c);
			pdf.getParameters().put('id_rc_c1',new_ie.Contact__c);
			pdf.getParameters().put('id_fd',new_ie.Consignee__c);
			pdf.getParameters().put('id_fd_c1',new_ie.Consignee_Contact__c);
			pdf.getParameters().put('remarks',new_ie.DO_Remarks__c);
			pdf.getParameters().put('release_date',new_ie.DO_Release_Date__c.format());
			pdf.getParameters().put('release_valid',new_ie.DO_Release_Valid_To__c.format());
			pdf.getParameters().put('shipment_pick_up',new_ie.DO_Remarks_Shipment_Pickup__c);
			Blob body;

			try
			{
				body = pdf.getContent();
			}
			catch (VisualforceException e) { body = Blob.valueOf('Some Text');}
			String nameDocument = 'DO '+record.name +'.pdf';
			List<Folder> directorio = new List<Folder>();
			directorio = [Select Id, Name from Folder where Name =:'DO'];
			documento_asociado.Body = body;
			documento_asociado.Name = nameDocument;
			documento_asociado.AuthorId = UserInfo.getUserId();
			if(directorio.size()>0)
				documento_asociado.FolderId = directorio[0].Id;
			documento_asociado.IsPublic = true;

			//Update Fields in the Import/Export
			record.DO_Release_to_Company__c = new_ie.Account_for__c;
			record.DO_Contact_1_Release_to_Company__c = new_ie.Contact__c;
			record.DO_Shipment_Pickup__c = new_ie.Consignee__c;
			record.DO_Contact_1_Shipment_Pickup__c = new_ie.Consignee_Contact__c;
			record.DO_Release_Date__c = new_ie.DO_Release_Date__c;
			record.DO_Release_Valid_To__c = new_ie.DO_Release_Valid_To__c;
			record.DO_Remarks__c = new_ie.DO_Remarks__c;
			record.DO_Remarks_Shipment_Pickup__c = new_ie.DO_Remarks_Shipment_Pickup__c;
			try
			{
				update record;
			}catch (DMLException e)
			{
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error to Save Information in IE.'));
				return null;
			}

			//Delete Document if exists before
			List<Document> documents_old = [Select Id, Name from Document where Name = :nameDocument];
			try
			{
				delete documents_old;
			}catch (Exception e)
			{
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Failed to delete old document'));
			}

			//Delete Associated Documents
			List<Associated_Document__c> asociated_documents_old = [Select Id, Name from Associated_Document__c where Name = :nameDocument];
			try
			{
				delete asociated_documents_old;
			}catch (DMLException e)
			{
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Failed to delete associated document.'));
			}

			//Create New Document
			try
			{
				if(documento_asociado.Name != '' && documento_asociado.Name != null)
					insert documento_asociado;
			}
			catch (DMLException e)
			{
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error in File Upload.'));
			}

			Associated_Document__c new_document = new Associated_Document__c();
			new_document.Account__c = record.Account_for__c;
			new_document.Name = nameDocument;
			new_document.Document_Type__c = 'DO';
			new_document.Import_Export_Quote__c =record.Id;


			new_document.Document_URL__c = '/servlet/servlet.FileDownload?file='+documento_asociado.Id+'&oid=' + UserInfo.getOrganizationId();

			//Create Associated Document
			try
			{
				insert new_document;
				return new PageReference('/'+record.Id);
			}
			catch(Exception ex){return null;}


		}
}