respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Area__c</fullName>
        <inlineHelpText>Make sure that you have the same Business Areas for ACCOUNTS, FAMILIES, PRICE LISTS and SUPPLY PROJECTS.</inlineHelpText>
        <label>Business Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air Freight</fullName>
                </value>
                <value>
                    <fullName>Animal Nutrition</fullName>
                </value>
                <value>
                    <fullName>Auto-Parts</fullName>
                </value>
                <value>
                    <fullName>Cloths &amp; Accessories</fullName>
                </value>
                <value>
                    <fullName>Construction &amp; Engineering</fullName>
                </value>
                <value>
                    <fullName>Construction &amp; Mining</fullName>
                </value>
                <value>
                    <fullName>Energy &amp; Hydrocarbons</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverages</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Machinery &amp; Parts</fullName>
                </value>
                <value>
                    <fullName>MERA Autoparts</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Other Services</fullName>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                </value>
                <value>
                    <fullName>Rail Freight</fullName>
                </value>
                <value>
                    <fullName>Recruiting Services</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Sea Freight</fullName>
                </value>
                <value>
                    <fullName>Telecom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Supplier</fullName>
        <active>true</active>
        <description>Suppliers we purchase goods from.</description>
        <label>Supplier</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Supplier_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Supplier__c</fullName>
        <label>Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Supply Chain Partner, Purchase Agent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Suppliers Quotes/Orders (Supplier)</relationshipLabel>
        <relationshipName>Suppliers_Quotes_Supplier</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Supplier Quote/Order</label>
    <nameField>
        <displayFormat>SQO# {YYYY}-{000000}</displayFormat>
        <label>Supplier Quote/Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Supplier_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Sourcing_Item__c</referenceTo>
        <relationshipLabel>Supplier Quote/Order Lines</relationshipLabel>
        <relationshipName>Supplier_Quote_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Units</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subfamily__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subfamily</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Subfamily__c.Product_Family__c</field>
                <operation>equals</operation>
                <valueField>$Source.Family__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subfamily__c</referenceTo>
        <relationshipLabel>Supplier Quote/Order Lines</relationshipLabel>
        <relationshipName>Supplier_Quote_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Quote__c</fullName>
        <label>Supplier Quote/Order</label>
        <referenceTo>Supplier_Quote__c</referenceTo>
        <relationshipLabel>Supplier Quote/Order Lines</relationshipLabel>
        <relationshipName>Supplier_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <formula>Supplier_Quote__r.Supplier__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>As specified in &quot;Supplier&quot; inside &quot;Supplier Quote/Order&quot;</inlineHelpText>
        <label>Supplier</label>
        <type>Text</type>
    </fields>
    <label>Supplier Quote/Order Line</label>
    <nameField>
        <label>SQO Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Quote/Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_NEU_SQOLine_Update_Conversions.cls
@isTest
public class P2G_NEU_SQOLine_Update_Conversions {

    static void NEU(){
        Test.startTest();
        NEU_StaticVariableHelper.setBoolean1(true);
        Test.stopTest();
    }
    @isTest
    static void NEU_SQOLine_Update_Conversions(){
        Test.startTest();        
        List<Account> list_accounts = NEU_Utils.getAccounts('Supplier,Customer,');
        Account a = list_accounts[0];
        insert a;
        Account b = list_accounts[1];
        insert b;
        Product_Family__c c = new Product_Family__c(Name = 'Test acount', Business_Area__c = 'Auto-Parts');
        insert c;
        Subfamily__c d = new Subfamily__c(Product_Family__c = c.Id, Name = 'test subfamily');
        insert d;
        Sourcing_Item__c g = new Sourcing_Item__c(Name = 'Test item',Subfamily__c = d.Id, Sourcing_Family__c =c.id, Account_Owner__c= a.Id ,  HS_Code_Text__c='56489');
        insert g;
        Supplier_Quote__c supquote = new Supplier_Quote__c(Supplier__c=a.Id);
        insert supquote;
        Supplier_Quote_Line__c sup_quote_lines = new Supplier_Quote_Line__c(Supplier_Quote__c=supquote.Id, Name=' test quote line', Item__c= g.Id, Quantity__c=5);
        insert sup_quote_lines;
        
        sup_quote_lines.Name='Test002';
        update sup_quote_lines;
        Test.stopTest();
    }
}