respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zona__c</fullName>
        <formula>text(Route__r.Zona__c )</formula>
        <label>Zona</label>
        <type>Text</type>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supply Chain Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Carrier)</relationshipLabel>
        <relationshipName>Shipments_Carrier</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ETA_Point_of_Discharge__c</fullName>
        <label>ETA</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ETD_Time_from_Point_of_Load__c</fullName>
        <label>ETD Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>ETD_from_Point_of_Load__c</fullName>
        <label>ETD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Equip_Placed__c</fullName>
        <label>Placed Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Monitoreo_Recepci_n_Acuse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monitoreo Recepción Acuse</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Operation_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operation Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments_Route</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seguimiento_de_devolucion_comentarios__c</fullName>
        <label>Comentarios</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Shipment_Status_Mon__c</fullName>
        <label>Shipment Status Monitoreo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned_M</fullName>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>In Progress_M</fullName>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Awaiting load_M</fullName>
                    <label>Awaiting load</label>
                </value>
                <value>
                    <fullName>Loading_M</fullName>
                    <label>Loading</label>
                </value>
                <value>
                    <fullName>Delivery on Route_M</fullName>
                    <label>Delivery on Route</label>
                </value>
                <value>
                    <fullName>Awaiting Unload_M</fullName>
                    <label>Awaiting Unload</label>
                </value>
                <value>
                    <fullName>Unloading_M</fullName>
                    <label>Unloading</label>
                </value>
                <value>
                    <fullName>Finished_M</fullName>
                    <label>Finished</label>
                </value>
                <value>
                    <fullName>Failure_M</fullName>
                    <label>Failure</label>
                </value>
                <value>
                    <fullName>Incident_M</fullName>
                    <label>Incident</label>
                </value>
                <value>
                    <fullName>Cancel_M</fullName>
                    <label>Cancel</label>
                </value>
                <value>
                    <fullName>In Warehouse_M</fullName>
                    <label>In Warehouse</label>
                </value>
                <value>
                    <fullName>False_M</fullName>
                    <label>False</label>
                </value>
                <value>
                    <fullName>Operative Failure_M</fullName>
                    <label>Operative Failure</label>
                </value>
                <value>
                    <fullName>Robo_M</fullName>
                    <label>Robo</label>
                </value>
                <value>
                    <fullName>Error en Monitoreo_M</fullName>
                    <label>Error en Monitoreo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment_Status_Plann__c</fullName>
        <label>Shipment Status Planner</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Re assigned</fullName>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Rejected PakControl</fullName>
                </value>
                <value>
                    <fullName>Operative Failure</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Delivery on Route</fullName>
                    <isActive>false</isActive>
                    <label>Delivery On Route</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment_Type__c</fullName>
        <formula>LEFT(RIGHT(Name, LEN(Name) - FIND (&quot;-&quot;, Name)), FIND(&quot;-&quot; , RIGHT(Name, LEN(Name) - FIND (&quot;-&quot;, Name)))-1)</formula>
        <label>Shipment_Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Services_Sell_Amount__c</fullName>
        <description>Conversion to currency of the sum of &quot;Services Sell Amount&quot; from the Total Services Sell Amount Roll-Up</description>
        <formula>Total_Services_Sell_Amount_number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Sum of &quot;Services Sell Amount&quot;</inlineHelpText>
        <label>Total Services Sell Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Services_Std_Buy_Amount__c</fullName>
        <description>Conversion to currency of the total un-fixed &quot;Services Buy Amount&quot; from the Total Services Std. Buy Amount Roll-Up</description>
        <formula>Total_Services_Std_Buy_Amount_number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total un-fixed Service Lines&apos; &quot;Services Buy Amount&quot;</inlineHelpText>
        <label>Total Services Buy Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Carrier__c</fullName>
        <formula>Service_Rate_Name__r.Carrier_Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Carrier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <description>Campo para consultar el Customer Id del objeto Account (Customer)</description>
        <formula>Shipment__r.Account_for__r.Customer_Id__c</formula>
        <label>Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Rate_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Name</label>
        <referenceTo>Fee__c</referenceTo>
        <relationshipLabel>Shipment Service Lines</relationshipLabel>
        <relationshipName>Shipment_Service_Lines_Service_Rate_Name</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/User.object
<CustomObject>
    <fields>
        <fullName>Zona__c</fullName>
        <label>Zona</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Zona</fullName>
                </value>
                <value>
                    <fullName>PAC-SUR</fullName>
                </value>
                <value>
                    <fullName>Noroeste</fullName>
                </value>
                <value>
                    <fullName>GDL</fullName>
                </value>
                <value>
                    <fullName>Centro-Norte</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_AsignacionOppr.cls
public class P2G_AsignacionOppr {
    @AuraEnabled
    public static List<Shipment__c> seccion3(List<String> datos) {
        //status
        //fechaInicio
        //fechaFin
        //All/My
        //acc
        //carr
        //op
        List<Shipment__c> listaShipments = new List<Shipment__c>(); 
        String  idUser= UserInfo.getUserId();
        if(datos[1] == '' || datos[1]==null){
                    datos[1] = Datetime.now().format('yyyy-MM-dd');
        }
        if(datos[2] == ''|| datos[2]==null){
        			datos[2] = Datetime.now().format('yyyy-MM-dd');
        }
        try {
            String fechaInicioStr = datos[1];// + 'T00:00:00Z';
            String fechaFinStr = datos[2];// + 'T23:59:59Z';
            
            String soqlQuery = 'SELECT Id,Equip_Placed__c,Monitoreo_Recepci_n_Acuse__c,Name, Shipment_Status_Plann__c,ETD_Time_from_Point_of_Load__c, Operation_Executive__c, Operation_Executive__r.Name, ' +
                'Account_for__c, Account_for__r.Name, CreatedDate,Total_Services_Sell_Amount__c,Route__c,Total_Services_Std_Buy_Amount__c,Carrier__c,' +
                'Carrier__r.Name,ETD_from_Point_of_Load__c,ETA_Point_of_Discharge__c,Route__r.Name '+
                'FROM Shipment__c ' +
                'WHERE ETD_from_Point_of_Load__c = ' + fechaInicioStr; 
                //' AND ETD_from_Point_of_Load__c <= ' + fechaFinStr;
            if (datos[0] !='All') {
                soqlQuery += ' AND Shipment_Status_Plann__c = \'' + datos[0] + '\'';           
        	}
            if(datos[3] == 'mios'){
                soqlQuery += ' AND CreatedById = \''+ idUser +'\'';              
            }
            if(datos[4]!= null && datos[4]!=''){
                soqlQuery += ' AND Account_for__c = \''+ datos[4] +'\'';    
            }
            if(datos[5]!=null && datos[5]!=''){
                soqlQuery += ' AND Carrier__c = \''+ datos[5] +'\'';     
            }
            if(datos[6]!=null && datos[6]!=''){
                soqlQuery += ' AND Operation_Executive__c = \''+ datos[6] +'\'';      
            }
            if(datos[7]!=null && datos[7]!='All'){
                soqlQuery += ' AND Shipment_Type__c = \''+ datos[7] +'\'';
            }

            if(datos[8] != 'All'){
                soqlQuery += ' AND Id IN ( SELECT Shipment__c FROM Shipment_Fee_Line__c WHERE Service_Rate_Name__r.Zona__c = \''+ datos[8] + '\' )';
            }

            soqlQuery += ' ORDER BY ETD_Time_from_Point_of_Load__c ASC';
            System.debug('consulta seccion3: '+soqlQuery);
            listaShipments = Database.query(soqlQuery);
        } catch (Exception e) {
            System.debug('Error en seccion3: ' + e.getMessage());
        }
        
        return listaShipments;
    }
    
    @AuraEnabled
    public static List<Shipment__c> getStatus2(List<String> datos) {
        List<Shipment__c> listaShipments = new List<Shipment__c>(); 
        List<Shipment_Fee_Line__c> listaServiceLine = new List<Shipment_Fee_Line__c>(); 
        Map<String,String> zonas = new Map<String,String>();
        String  idUser= UserInfo.getUserId();
        String idGenerico =idUser;
        String idGenerico2 =idUser;
        if(!Test.isRunningTest()){
            idGenerico = System.Label.Operation_Executive;
            idGenerico2 = System.Label.Operation_Executive2;
        }
        
        try {
            String fechaInicioStr = datos[2];// + 'T00:00:00Z';
            String fechaFinStr = datos[3];// + 'T23:59:59Z';
            
            String soqlQuery = 'SELECT Id,Equip_Placed__c,Seguimiento_de_devolucion_comentarios__c,Monitoreo_Recepci_n_Acuse__c, Name,Shipment_Type__c,ETD_Time_from_Point_of_Load__c, Shipment_Status_Plann__c, Operation_Executive__c, Operation_Executive__r.Name, ' +
                'Account_for__c, Account_for__r.Name, CreatedDate,Total_Services_Sell_Amount__c,Route__c,ETD_from_Point_of_Load__c,'+
                'ETA_Point_of_Discharge__c, LastModifiedDate,Route__r.Name, Shipment_Status_Mon__c ' +
                'FROM Shipment__c ' +
                'WHERE Shipment_Status_Plann__c = \'' + datos[1] + '\'' +
                ' AND ETD_from_Point_of_Load__c = ' + fechaInicioStr;
                //' AND ETD_from_Point_of_Load__c <= ' + fechaFinStr;
            if(datos[4] == 'mios'){
                soqlQuery += ' AND Operation_Executive__c = \''+ idUser +'\'';              
            }
            if(datos[0] == '2'){
                soqlQuery += ' AND (Operation_Executive__c = null OR Operation_Executive__c = \'' +idGenerico +'\' OR Operation_Executive__c = \'' +idGenerico2 +'\' )';   
            }
            if(datos[0] == '3'){
                soqlQuery += ' AND Operation_Executive__c != null AND Operation_Executive__c != \'' +idGenerico +'\'' +' AND Operation_Executive__c != \'' +idGenerico2 +'\'';  
            }
            if(datos[0] == '5'){
                soqlQuery += ' AND Shipment_Status_Mon__c != \'Delivery on Route_M\'';   
            }
			if(!String.isBlank(datos[5])){
                soqlQuery += ' AND Account_for__c = \''+ datos[5] +'\'';    
            }
            if(!String.isBlank(datos[6])){
                soqlQuery += ' AND Carrier__c = \''+ datos[6] +'\'';     
            }
            if(!String.isBlank(datos[7])){
                soqlQuery += ' AND Operation_Executive__c = \''+ datos[7] +'\'';      
            }
            if(datos[0] == '7'){
                soqlQuery += ' AND Shipment_Status_Mon__c = \'Delivery on Route_M\'';// prod: Delivery on Route_M
            }
            if(datos[8] != 'All'){
                soqlQuery += ' AND Shipment_Type__c = \''+ datos[8] +'\'';
            }

            if(datos[9] != 'All'){
                soqlQuery += ' AND Id IN ( SELECT Shipment__c FROM Shipment_Fee_Line__c WHERE Service_Rate_Name__r.Zona__c = \''+ datos[9] + '\' )';
            }


            soqlQuery += ' ORDER BY ETD_Time_from_Point_of_Load__c ASC';
            System.debug('consulta columns' + soqlQuery);
            listaShipments = Database.query(soqlQuery);
            listaServiceLine = [SELECT Shipment__c, Service_Rate_Name__c,Service_Rate_Name__r.Zona__c FROM Shipment_Fee_Line__c WHERE Shipment__c IN:listaShipments];
            for(Shipment_Fee_Line__c item : listaServiceLine){
                if(item.Service_Rate_Name__c != null){
                    zonas.put(item.Shipment__c, item.Service_Rate_Name__r.Zona__c);
                }
            }

            for(Shipment__c item:listaShipments){
                item.Seguimiento_de_devolucion_comentarios__c = zonas.get(item.Id);
            }
        } catch (Exception e) {
            System.debug('Error consulta ' + e.getMessage());
        }
        
        return listaShipments;
    }
    
    @AuraEnabled
    public static void updateExecute(String shipmentId,list<String> datos) {
        NEU_StaticVariableHelper.setBoolean1(true);
        P2G_llamadoWebHelper.setWebServiceUpdate(true);
        Shipment__c shipmentToUpdate = new Shipment__c();
        shipmentToUpdate.Id = shipmentId;
        shipmentToUpdate.Shipment_Status_Plann__c = 'In Progress';
        shipmentToUpdate.Operation_Executive__c = UserInfo.getUserId();
        if(datos[1]!='No'){
            shipmentToUpdate.Shipment_Status_Plann__c = 'Pending';
            shipmentToUpdate.Operation_Executive__c = datos[1];
        }
        if (!Test.isRunningTest()){
            update shipmentToUpdate;
        }
        NEU_StaticVariableHelper.setBoolean1(false);
        P2G_llamadoWebHelper.setWebServiceUpdate(false);
    }
    
    @AuraEnabled
    public static  List<List<Shipment__c>> columns(String shipmentId,list<String> datos) {
        //[0] -> columna
        //[1] -> status
        //[2] -> startDate
        //[3] -> endDate
        //[4] -> all/mios
        //[5] -> account
        //[6] -> carrier
        //[7] -> Operation executive
        //[8] -> Zona
        list<Shipment__c> lista2 = new list<Shipment__c>();
        List<Shipment__c> lista3 = new List<Shipment__c>();
        List<Shipment__c> lista4 = new List<Shipment__c>();
        List<Shipment__c> lista5 = new List<Shipment__c>();
        List<Shipment__c> lista6 = new List<Shipment__c>();
        List<Shipment__c> lista7 = new List<Shipment__c>();
        if(datos[2] == ''){
                    datos[2] = Datetime.now().format('yyyy-MM-dd');
        }
        if(datos[3] == ''){
        			datos[3] = Datetime.now().format('yyyy-MM-dd');
        }
        lista2 = getStatus2(datos);
        datos[0] = '3';
        lista3 = getStatus2(datos);
        datos[0] = '4';
        datos[1] = 'In Progress';
        lista4 = getStatus2(datos);
        datos[0] = '5';
        datos[1] = 'Confirmed';
        lista5 = getStatus2(datos);
        datos[0] = '6';
        datos[1] = 'Closed';
        lista6 = getStatus2(datos);
       	datos[0] = '7';
        datos[1] = 'Confirmed';
        lista7 = getStatus2(datos);
        return new List<List<Shipment__c>>{lista2, lista3,lista4,lista5,lista6,lista7};
            }
    
    @AuraEnabled
    public static List<Account> searchAccounts(String search) {
        if (String.isNotBlank(search) && search.length() >= 3) {
            search = '%' + search + '%';
            return [SELECT Id, Name, Customer_Id__c FROM Account WHERE Name LIKE :search LIMIT 10];
        } else {
            return new List<Account>();
        }
    }
    @AuraEnabled
    public static List<User> searchOpExecutive(String search) {
        if (String.isNotBlank(search) && search.length() >= 3) {
            search = '%' + search + '%';
            return [SELECT Id, Name FROM User WHERE Name LIKE :search LIMIT 10];
        } else {
            return new List<User>();
        }
    }
}