respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Consignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consignee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Consignee)</relationshipLabel>
        <relationshipName>NEU_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Supplier</fullName>
        <active>true</active>
        <description>Suppliers we purchase goods from.</description>
        <label>Supplier</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts Addresses</relationshipLabel>
        <relationshipName>Accounts_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&quot;Shipping Address&quot;</defaultValue>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Address</fullName>
                </value>
                <value>
                    <fullName>Shipping Address</fullName>
                    <default>true</default>
                    <label>Shipping Address</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Location__c.object
<CustomObject>
    <description>Object used to define locations within given countries. Can be automatically generated from First Steps https://c.eu11.visual.force.com/apex/NEU_First_Steps</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>State__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Operadores__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Proveedor (SCP)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Operadores</relationshipLabel>
        <relationshipName>Operadores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Operadores</label>
    <nameField>
        <label>Nombre Operador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_Stop_B__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Stop B</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account Stop B)</relationshipLabel>
        <relationshipName>Shipments_Account_Stop_B</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Stop_C__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Stop C</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account Stop C)</relationshipLabel>
        <relationshipName>Shipments_Account_Stop_C</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Consignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Cuenta Destino</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Consignee</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Consignee)</relationshipLabel>
        <relationshipName>Shipments_Consignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Delivery Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>OI Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Pickup Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer or Supplier</inlineHelpText>
        <label>Cuenta Origen</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Supplier/Shipper Account)</relationshipLabel>
        <relationshipName>Shipments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Sea&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058LK&amp;oid=00Db0000000I1t3&amp;lastMod=1358783213000&apos;, &apos;Import - Sea&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Air&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058O4&amp;oid=00Db0000000I1t3&amp;lastMod=1358783262000&apos;, &apos;Import - Air&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Road&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OY&amp;oid=00Db0000000I1t3&amp;lastMod=1358783362000&apos;, &apos;Import - Road&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Rail&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OJ&amp;oid=00Db0000000I1t3&amp;lastMod=1358783317000&apos;, &apos;Import - Rail&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Sea&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058Nz&amp;oid=00Db0000000I1t3&amp;lastMod=1358783241000&apos;, &apos;Export - Sea&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Air&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058O9&amp;oid=00Db0000000I1t3&amp;lastMod=1358783289000&apos;, &apos;Export - Air&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Road&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OU&amp;oid=00Db0000000I1t3&amp;lastMod=1358783382000&apos;, &apos;Export - Road&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Rail&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OT&amp;oid=00Db0000000I1t3&amp;lastMod=1358783338000&apos;, &apos;Export - Rail&apos;), &apos;&apos;))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type (REVISAR)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Vehicle__c.Account_for_SCP__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Carrier__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tipo Unidad</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_JE_Update_Shipment_Addresses_test.cls
@isTest
public class NEU_JE_Update_Shipment_Addresses_test {    
    
    
    
    
    @testSetup
    static void setup(){
        Account acc= new Account();
        acc.Name='Test';
        acc.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        acc.OwnerId=UserInfo.getUserId();  
        acc.ShippingStreet='Test';
        acc.ShippingCity='Test01';
        acc.ShippingState='TEST0011';
        acc.ShippingPostalCode='TEST001';
        acc.ShippingCountry='test0000w';                
        insert acc;
        
        Account supplier = new Account(Name = 'Test Supplier', 
                                       RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Supplier').getRecordTypeId(),
                                       OwnerId=UserInfo.getUserId(),ShippingCity='Test01',
                                       ShippingState='TEST0011',
                                       ShippingPostalCode='TEST001',
                                       ShippingCountry='test0000w');
        insert supplier;
    }
    
    @isTest
    static void NEU_JE_Update_Shipment_Addresses() {                
        Test.startTest();
        Account customerAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Customer' LIMIT 1];
        Account supplierAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Supplier' LIMIT 1];                
        Shipment__c ship = new Shipment__c(
            Name = 'SP-TS-00057TEST',
            Freight_Mode__c='Sea',
            Service_Mode__c ='Import',
            Only_Warehouse_Service__c = true,
            Supplier_Account__c = supplierAccount.Id,
            Account_for__c = customerAccount.Id,
            Origin_Address__c = null,
            Destination_Address__c = null
        );
        insert ship;
        Test.stopTest();                
    }
    
    @isTest
    static void testPartialAddress() {
        Account acc = new Account(
            Name = 'Partial Address Test',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId(),
            ShippingCity = 'CityOnly',
            ShippingCountry = 'CountryOnly',
            ShippingState='StateOnly'
            
        );
        insert acc;
        
        Shipment__c ship = new Shipment__c(
            Name='SP-FN-TEST-007',            
            Account_for__c = acc.Id,
            Freight_Mode__c='Sea',
            Service_Mode__c ='Import',
            Only_Warehouse_Service__c = true
        );
        
        Test.startTest();
        insert ship;
        Test.stopTest();        
    }
    
    @isTest
    static void testNoAddress() {        
        Account acc = new Account(
            Name = 'No Address Test',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId()
        );
        insert acc;
        
        Shipment__c ship = new Shipment__c(
            Name = 'SP-TS-00057TEST',
            Freight_Mode__c='Sea',
            Service_Mode__c ='Import',
            Only_Warehouse_Service__c = true,            
            Account_for__c = acc.Id,
            Origin_Address__c = null,
            Destination_Address__c = null
        );
        
        Test.startTest();
        insert ship;
        Test.stopTest();                
    }
    /*
@isTest
static void NEU_JE_Update_Shipment_Addresses(){
Test.startTest();
Account customerAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Customer' LIMIT 1];
Account supplierAccount = [SELECT Id FROM Account WHERE RecordType.Name = 'Supplier' LIMIT 1];                
Shipment__c ship = new Shipment__c(
Name = 'SP-TS-00057TEST',
Freight_Mode__c='Sea',
Service_Mode__c ='Import',
Only_Warehouse_Service__c = true,
Supplier_Account__c = supplierAccount.Id,
Account_for__c = customerAccount.Id,
Origin_Address__c = null,
Destination_Address__c = null
);
insert ship;                        
Test.stopTest();
}
*/
    
    /*
@isTest(SeeAllData=true)
static void NEU_JE_Update_Shipment_Addresses ()
{
Account a= new Account();
a.Name='Test';
a.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
a.OwnerId=UserInfo.getUserId();        	
insert a;
Shipment__c ship = new Shipment__c(Name = 'SP-TS-00047', Account_for__c = a.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', Account_Stop_B__c  = a.Id,
Account_Stop_C__c = a.Id, Origin_Address__c ='test origin address', Destination_Address__c ='test destination address', Only_Warehouse_Service__c = true);
insert ship;
Shipment__c ship2 = new Shipment__c(Name = 'SP-TS-00048', Account_for__c = a.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import',
Account_Stop_C__c = a.Id, Origin_Address__c ='test origin address', Destination_Address__c ='test destination address', Only_Warehouse_Service__c = true);
insert ship2;
Shipment__c ship3 = new Shipment__c(Name = 'SP-TS-00049', Account_for__c = a.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', Account_Stop_B__c  = a.Id,
Origin_Address__c ='test origin address', Destination_Address__c ='test destination address', Only_Warehouse_Service__c = true);
insert ship3;

/*
//user        
User userT = new User();
userT.FirstName = 'leo';
userT.LastName = 'test';
userT.Email = 'leoTest@test.com';
userT.Username = 'leoTest@test.com.leoTest';
userT.Alias = 'TestL';
userT.TimeZoneSidKey = 'America/Mexico_City';
userT.LocaleSidKey = 'es_MX';
userT.EmailEncodingKey = 'UTF-8';
userT.ProfileId = [Select Id from Profile where Name = 'System Administrator'].Id;
userT.LanguageLocaleKey = 'es_MX';
insert userT;

//Account     
Account accCustomer = TestDataFactory.createAccounts('Cuenta customer', 'Customer');        
Account accCarrier = TestDataFactory.createAccounts('Cuenta carrier', 'Supply Chain Partner');                
//produccion Autotransporte  -- uat: Autotrasporte
Catalogo_SAT__c trans1 = TestDataFactory.createCatalogoSat('Camión-Remolque-Test', 'T3S17','Configuracion Autotransporte');                                         
//RecordType: AUT y  produccion : Tipo de Permiso     
Catalogo_SAT__c trans2 = TestDataFactory.createCatalogoSat('Autotransporte Federal Test' , 'T3S172','Tipo de Permiso'); 
Vehicle__c vehicle = TestDataFactory.createVehiculo(accCarrier.Id,trans1.Id,trans2.Id);
Catalogo_SAT__c cp = TestDataFactory.createCatalogoSat('980828','980828','Codigo Postal');
Operadores__c operador = TestDataFactory.createOperador(accCarrier.Id,cp.Id);
Container_Type__c ct = TestDataFactory.createContainerType('20" Container');
Country__c country1 = TestDataFactory.createCountry();
Country__c country2 = TestDataFactory.createCountry();
Country__c country3 = TestDataFactory.createCountry();
Country__c country4 = TestDataFactory.createCountry();
Location__c location1 = TestDataFactory.createLocation('test1',country1.Id);
Location__c location2 = TestDataFactory.createLocation('test2',country2.Id);
Location__c location3 = TestDataFactory.createLocation('test3',country3.Id);
Location__c location4= TestDataFactory.createLocation('test4',country4.Id);
State__c state1 = TestDataFactory.createState('nopalucan',country1.Id);
State__c state2 = TestDataFactory.createState('san martin',country1.Id);
State__c state3 = TestDataFactory.createState('san juan',country3.Id);
State__c state4= TestDataFactory.createState('panotla',country4.Id);
Account_Address__c ad = TestDataFactory.createAddressAccount('accAddress', accCustomer.Id, cp.Id);

Shipment__c ship = new Shipment__c(Name = 'SP-TS-00047', Account_for__c = a.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', Account_Stop_B__c  = a.Id,
Account_Stop_C__c = a.Id, Origin_Address__c ='test origin address', Destination_Address__c ='test destination address', Only_Warehouse_Service__c = true);
insert ship;

Shipment__c ship2 = new Shipment__c(Name = 'SP-TS-00048', Account_for__c = a.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import',
Account_Stop_C__c = a.Id, Origin_Address__c ='test origin address', Destination_Address__c ='test destination address', Only_Warehouse_Service__c = true);
/*
TestDataFactory.ShipmentCreate csp = new TestDataFactory.ShipmentCreate();
csp.name = 'SP-CE-22-000011';
csp.operador = operador.Id;
csp.vehiculo = vehicle.Id;
csp.accCarrier = accCarrier.Id;
csp.accCustomer = accCustomer.Id;
csp.user = userT.Id;
csp.freightMode = 'Road';
csp.serviceMode = 'IMPORT';
csp.serviceType = 'FTL';
csp.containerSize = ct.Name;   

TestDataFactory.ShipmentCreate csp1 = new TestDataFactory.ShipmentCreate();
csp1.name = 'SP-FN-22-000111';
csp1.operador = operador.Id;
csp1.vehiculo = vehicle.Id;
csp1.accCarrier = accCarrier.Id;
csp1.accCustomer = accCustomer.Id;
csp1.user = userT.Id;
csp1.freightMode = 'Road';
csp1.serviceMode = 'NATIONAL';
csp1.serviceType = 'FTL';
csp1.containerSize = ct.Name;                 

TestDataFactory.InfoCountry ic = new TestDataFactory.InfoCountry();
ic.countryOfdischarge = country1.Id;
ic.countryOfLoad = country1.Id;
ic.siteOfdischarge = location1.Id;
ic.siteOfLoad = location1.Id;
ic.stateofLoad = state2.Id;
ic.stateofDischarge = state2.Id;

Carrier_Line_Load_Point__c route1 = TestDataFactory.createRoute('Tlaxcala-Tlaxco', ic);                
Test.startTest(); 
Shipment__c shipment1 = TestDataFactory.createShipment(csp,ic);
//shipment1.Supplier_Account__c = accCarrier.Id;
//update shipment1;
Test.stopTest(); 

//Account_Address__c ad=new Account_Address__c(Account__c=a.id,Address__c='test',Type__c='Shipping Address');
//insert ad;
/*Shipment__c ship = new Shipment__c(Name = 'SP-CE-22-000194',Account_for__c = a.Id, Supplier_Account__c= a1.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', Origin_Address__c='test', Destination_Address__c ='test', Only_Warehouse_Service__c = true);
insert ship;
Shipment__c ship2 = new Shipment__c(Name = 'SP-CE-22-000195',Account_for__c = a.Id, Supplier_Account__c= a1.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', Consignee__c=a.id, Destination_Address__c ='test', Only_Warehouse_Service__c = true);
insert ship2;
Shipment__c ship3 = new Shipment__c(Name = 'SP-CE-22-000196',Account_for__c = a.Id, Supplier_Account__c= a1.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', Origin_Address__c='test',Consignee__c=a.id,Account_Destination_Address__c=ad.id, Only_Warehouse_Service__c = true);
insert ship3;

}
*/
}