respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Port_Airport_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site of Load/Discharge</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Location__c.Country__c</field>
                <operation>equals</operation>
                <valueField>$Source.Country_of_Load__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.State_of_Load_Discharge__c</field>
                <operation>equals</operation>
                <valueField>Location__c.State__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.State__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts who use this Site</relationshipLabel>
        <relationshipName>AccountsSite</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Carrier_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Carrier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Carrier Account)</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fee_Category__c</fullName>
        <inlineHelpText>Be aware that if you change the values of this picklist the hard corde of the Import-Export PDF quote must also be changed by our end.</inlineHelpText>
        <label>Rate Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Road Freights</fullName>
                    <default>true</default>
                    <label>Road Freights</label>
                </value>
                <value>
                    <fullName>Other Service Charges</fullName>
                </value>
                <value>
                    <fullName>Sea Freights</fullName>
                </value>
                <value>
                    <fullName>Air Freights</fullName>
                </value>
                <value>
                    <fullName>POL Charges</fullName>
                </value>
                <value>
                    <fullName>POD Charges</fullName>
                </value>
                <value>
                    <fullName>Drayages</fullName>
                </value>
                <value>
                    <fullName>Mayoreo</fullName>
                </value>
                <value>
                    <fullName>Tarimas</fullName>
                </value>
                <value>
                    <fullName>Warehouse</fullName>
                </value>
                <value>
                    <fullName>IMPAK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sell Rate</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>% Service Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GroupGVS</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Port_Airport_of_Discharge__c</fullName>
        <formula>Route__r.Port_Airport_of_Discharge__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site of Discharge</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Port_Airport_of_Load__c</fullName>
        <formula>Route__r.Port_Airport_of_Load__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site of Load</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_Service_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SAP Service Type Sell</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Group__c</field>
                <operation>equals</operation>
                <valueField>SAP_Service_Type__c.Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>SAP_Service_Type__c.Activo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Service_Type__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Services_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TT_Days__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <label>TT Days</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_Until__c</fullName>
        <defaultValue>now()</defaultValue>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Location__c.object
<CustomObject>
    <description>Object used to define locations within given countries. Can be automatically generated from First Steps https://c.eu11.visual.force.com/apex/NEU_First_Steps</description>
    <fields>
        <fullName>Zona_Metropolitana__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Zona metropolitana padre</description>
        <inlineHelpText>Zona metropolitana padre</inlineHelpText>
        <label>Zona Metropolitana</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supply Chain Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Carrier)</relationshipLabel>
        <relationshipName>Shipments_Carrier</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>OI Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments_Route</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Type__c</fullName>
        <formula>LEFT(RIGHT(Name, LEN(Name) - FIND (&quot;-&quot;, Name)), FIND(&quot;-&quot; , RIGHT(Name, LEN(Name) - FIND (&quot;-&quot;, Name)))-1)</formula>
        <label>Shipment_Type</label>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Carrier__c</fullName>
        <formula>Service_Rate_Name__r.Carrier_Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Carrier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <formula>Service_Rate_Name__r.Container_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Container Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <formula>TEXT(Service_Rate_Name__r.Group__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sap_Service_Type__c</fullName>
        <formula>Service_Rate_Name__r.SAP_Service_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sap Service Type Sell</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of a shipment. Child object of Import-Export Cargo Lines</description>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Shipment Cargo Lines</relationshipLabel>
        <relationshipName>Shipment_Cargo_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Cargo Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Cargo Line</label>
    <nameField>
        <label>Shipment Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateShipmentServiceLinesController.cls
public class CreateShipmentServiceLinesController {
    public class lineas{
        public string rate {get;set;}
        public integer units {get;set;}
        public string comments {get;set;}
        public string feecategory {get;set;}
        public string currencycode {get;set;}
        public double sell {get;set;}
        public double buy {get;set;}
    }
    
    @AuraEnabled
    public static Shipment__c getShipment(string shipId){
        system.debug('1 shipId : ' + shipId);
        Shipment__c s = [SELECT Id, Name, Account_for__c, Route__c,Shipment_Type__c
                         FROM Shipment__c 
                         WHERE Id =:shipId LIMIT 1];
        
        system.debug('2 s : ' + s);
        
        return s;
    }
    
    @AuraEnabled
    public static List<Fee__c> consultaRates(string shipId){
        
        system.debug('3 shipId : ' + shipId);
        
        Date fechaActual = system.today();
        Set<Id> containers = new Set<Id>();
        
        Shipment__c shipment = [SELECT Id, Account_for__c, Route__c, Carrier__c,Shipment_Type__c,
                                 Route__r.Port_Airport_of_Discharge__c,Route__r.Port_Airport_of_Load__c
                                FROM Shipment__c 
                                WHERE Id =:shipId LIMIT 1];
        
        System.debug('Shipment: ' + shipment);
        for(Shipment_Line__c cl : [SELECT Id, Container_Type__c 
                                   FROM Shipment_Line__c 
                                   WHERE Shipment__c =:shipId AND Container_Type__c != null]){
                                       if(!containers.contains(cl.Container_Type__c)){containers.add(cl.Container_Type__c);}
                                   }
        
        
        Location__c origin =[SELECT Id, Name, Zona_Metropolitana__c FROM Location__c where id =: shipment.Route__r.Port_Airport_of_Load__c limit 1 ];
        Location__c dest =[SELECT Id, Name, Zona_Metropolitana__c FROM Location__c where id =: shipment.Route__r.Port_Airport_of_Discharge__c limit 1 ];

        //BUSQUEDA ORIGINAL        
         List<Fee__c> rates =  [SELECT Id, Name, Group__c, SAP_Service_Type__c, SAP_Service_Type__r.Name, CurrencyIsoCode,
                               Route__c, Route__r.Name, Account_for__c, Account_for__r.Name, Carrier_Account__c, Carrier_Account__r.Name,
                               Container_Type__c, Container_Type__r.Name, Valid_Until__c, Fee_Rate__c, Fee_Category__c, TT_Days__c, Rate_Type__c,
                               Buy_Rate__c, CustomRate__c
                               FROM Fee__c 
                               WHERE Active__c = true 
                               AND (Valid_FROM__c <=: fechaActual OR Valid_FROM__c = NULL) 
                               AND (Valid_Until__c >=: fechaActual OR Valid_Until__c  = NULL)
                               AND (Account_for__c =:shipment.Account_for__c 
                                    OR (Account_for__r.name like'%TARIFARIO TERRESTRE NACIONAL%' AND carrier_account__C =: shipment.Carrier__C)
                                    OR (Account_for__r.name like'%Cotizador%' AND carrier_account__r.name  like'%Proveedor maestro%'))
                               AND Route__c =:shipment.Route__c
                               AND CustomRate__c = true
                               AND Container_Type__c IN: containers
                               Order by Account_for__R.NAME, Container_Type__r.Name,Carrier_Account__r.Name
                               LIMIT 50000];
        
        
        if(rates.size() == 0)
        {
            set<string> rutas = new set<string>();
            
            system.debug('ENTRAMOS');

            for(Carrier_Line_Load_Point__c rou : [SELECT Id  FROM Carrier_Line_Load_Point__c
                                                  where
                                                  Port_Airport_of_Load__c  =: origin.Zona_Metropolitana__c
                                                  and Port_Airport_of_Discharge__c =: dest.Zona_Metropolitana__c])
            {
                rutas.add(rou.id);
            }
            
            //Busqueda wtp-wtp
            rates = [SELECT Id, Name, Group__c, SAP_Service_Type__c, SAP_Service_Type__r.Name, CurrencyIsoCode,
                               Route__c, Route__r.Name, Account_for__c, Account_for__r.Name, Carrier_Account__c, Carrier_Account__r.Name,
                               Container_Type__c, Container_Type__r.Name, Valid_Until__c, Fee_Rate__c, Fee_Category__c, TT_Days__c, Rate_Type__c,
                               Buy_Rate__c, CustomRate__c
                     FROM Fee__c 
                     WHERE Active__c = true 
                      AND (Valid_Until__c >=: fechaActual OR Valid_Until__c  = NULL)
                     and (Valid_From__c = null or Valid_From__c  <=: fechaActual )
                     AND (Account_for__c =:shipment.Account_for__c 
                                    OR (Account_for__r.name like'%TARIFARIO TERRESTRE NACIONAL%' AND carrier_account__C =: shipment.Carrier__C)
                                    OR (Account_for__r.name like'%Cotizador%' AND carrier_account__r.name  like'%Proveedor maestro%'))
                     AND Route__c in: rutas
                      AND CustomRate__c = true
                               AND Container_Type__c IN: containers
                               Order by Account_for__R.NAME, Container_Type__r.Name,Carrier_Account__r.Name
                               LIMIT 50000];
            
            if(rates.size() == 0)
            {
                for(Carrier_Line_Load_Point__c rou : [SELECT Id  FROM Carrier_Line_Load_Point__c
                                                      where
                                                      Port_Airport_of_Load__c = : origin.id
                                                      and Port_Airport_of_Discharge__c =: dest.Zona_Metropolitana__c])
                {
                    rutas.add(rou.id);
                }
                
                // Busqueda origen-wtp
                rates = [SELECT Id, Name, Group__c, SAP_Service_Type__c, SAP_Service_Type__r.Name, CurrencyIsoCode,
                               Route__c, Route__r.Name, Account_for__c, Account_for__r.Name, Carrier_Account__c, Carrier_Account__r.Name,
                               Container_Type__c, Container_Type__r.Name, Valid_Until__c, Fee_Rate__c, Fee_Category__c, TT_Days__c, Rate_Type__c,
                               Buy_Rate__c, CustomRate__c
                         FROM Fee__c 
                         WHERE Active__c = true 
                         AND (Valid_Until__c >=: fechaActual OR Valid_Until__c  = NULL)
                         and (Valid_From__c = null or Valid_From__c  <=: fechaActual )
                         AND (Account_for__c =:shipment.Account_for__c 
                                    OR (Account_for__r.name like'%TARIFARIO TERRESTRE NACIONAL%' AND carrier_account__C =: shipment.Carrier__C)
                                    OR (Account_for__r.name like'%Cotizador%' AND carrier_account__r.name  like'%Proveedor maestro%'))
                         AND Route__c in: rutas
                         AND CustomRate__c = true
                               AND Container_Type__c IN: containers
                               Order by Account_for__R.NAME, Container_Type__r.Name,Carrier_Account__r.Name
                               LIMIT 50000];
                
                if(rates.size() == 0)
                {
                    for(Carrier_Line_Load_Point__c rou : [SELECT Id  FROM Carrier_Line_Load_Point__c
                                                          where
                                                          Port_Airport_of_Load__c =: origin.Zona_Metropolitana__c
                                                          and Port_Airport_of_Discharge__c =: dest.id])
                    {
                        rutas.add(rou.id);
                    }
                    
                    // Busqueda wtp- dest
                    rates = [SELECT Id, Name, Group__c, SAP_Service_Type__c, SAP_Service_Type__r.Name, CurrencyIsoCode,
                               Route__c, Route__r.Name, Account_for__c, Account_for__r.Name, Carrier_Account__c, Carrier_Account__r.Name,
                               Container_Type__c, Container_Type__r.Name, Valid_Until__c, Fee_Rate__c, Fee_Category__c, TT_Days__c, Rate_Type__c,
                               Buy_Rate__c, CustomRate__c
                             FROM Fee__c 
                             WHERE Active__c = true 
                            AND (Valid_Until__c >=: fechaActual OR Valid_Until__c  = NULL)
                             and (Valid_From__c = null or Valid_From__c  <=: fechaActual )
                              AND (Account_for__c =:shipment.Account_for__c 
                                    OR (Account_for__r.name like'%TARIFARIO TERRESTRE NACIONAL%' AND carrier_account__C =: shipment.Carrier__C)
                                    OR (Account_for__r.name like'%Cotizador%' AND carrier_account__r.name  like'%Proveedor maestro%')) 
                             AND Route__c in: rutas
                            AND CustomRate__c = true
                               AND Container_Type__c IN: containers
                               Order by Account_for__R.NAME, Container_Type__r.Name,Carrier_Account__r.Name
                               LIMIT 50000];
                }
            }
        }

        
        return rates;
    }
    
    @AuraEnabled
    public static List<Shipment_Fee_Line__c> consultaServiceLines(string shipId){
        
        system.debug('5 shipId : ' + shipId);
        
        List<Shipment_Fee_Line__c> serviceLines = [SELECT Id,Service_Rate_Category__c, Service_Rate_Name__c, Service_Rate_Name__r.Name,
                                                   Shipment__r.Route__r.Name, Service_Rate_Name__r.Delivery_Zone__c, Service_Rate_Name__r.Delivery_Zone__r.Name, Service_Rate_Name__r.Valid_Until__c,
                                                   Service_Rate_Name__r.Account_for__c, Service_Rate_Name__r.Account_for__r.Name, Rate_Type__c,
                                                   Shipment__r.Total_Volume_m3__c, Shipment__r.Total_Weight_Kg__c,
                                                   Service_Rate_Name__r.Container_Type__c, Service_Rate_Name__r.Container_Type__r.Name,
                                                   Units__c, Shipment_Sell_Price__c, Sell_Amount_Number__c, Shipment_Buy_Price__c, Std_Buy_Amount_Number__c,
                                                   Extension_Service_Name__c, CurrencyIsoCode
                                                   FROM 
                                                   Shipment_Fee_Line__c 
                                                   WHERE Shipment__c =:shipId];
        
        system.debug('6 serviceLines : ' + serviceLines);
        
        return serviceLines;
    }
    
    @AuraEnabled
    public static string createLineas(string shipId, string jsn){
        try{
            
            system.debug('7 shipId : ' + shipId);
            system.debug('8 jsn : ' + jsn);
            
            List<lineas> lines = (List<lineas>)JSON.deserialize(jsn, List<lineas>.class);
            List<Shipment_Fee_Line__c> currentLines = [SELECT Id 
                                                       FROM 
                                                       Shipment_Fee_Line__c 
                                                       WHERE Shipment__c =:shipId];
            
            system.debug('9 lines : ' + lines);
            system.debug('10 currentLines : ' + currentLines);
            
            
            Integer currentSize = currentLines.size();
            Integer contadorLineas = currentSize;
            List<Shipment_Fee_Line__c> shipmentLines = new List<Shipment_Fee_Line__c>();
            for(lineas l : lines){
                contadorLineas ++;
                Shipment_Fee_Line__c sl = new Shipment_Fee_Line__c();
                sl.Shipment__c = shipId;
                sl.Name = string.valueof(contadorLineas);
                string nombre_linea = '';
                while(sl.Name.length()<3){sl.Name = nombre_linea + string.valueof(contadorLineas);nombre_linea  +='0';}
                sl.Extension_Service_Name__c = l.comments;
                sl.Service_Rate_Name__c = l.rate;
                sl.Warehouse_Rate__c = (l.feecategory == 'Warehouse' ? true : false);
                sl.Units__c = l.units;
                sl.CurrencyIsoCode = l.currencycode;
                sl.Shipment_Sell_Price__c = l.sell;
                sl.Shipment_Buy_Price__c = l.buy;
                
                shipmentLines.add(sl);
            }
            insert shipmentLines;
            
            system.debug('11 shipmentLines : ' + shipmentLines);
            
            return 'ok';}catch(Exception e){
                system.debug('12 error : ' + e.getMessage());
                return 'Error: ' + e.getMessage();}
    }
    
    @AuraEnabled
    public static boolean isWTP(string shipmentId){
        
        Boolean showW =true;
        
        shipment__c quote = [SELECT Id, Account_for__c, Route__c,Shipment_Type__c,
                                   Route__r.Port_Airport_of_Discharge__c,Route__r.Port_Airport_of_Load__c
                                   FROM shipment__c 
                                   WHERE Id =:shipmentId LIMIT 1];
        
        
        Location__c origin =[SELECT Id, Name, Zona_Metropolitana__c FROM Location__c where id =: quote.Route__r.Port_Airport_of_Load__c limit 1 ];
        Location__c dest =[SELECT Id, Name, Zona_Metropolitana__c FROM Location__c where id =: quote.Route__r.Port_Airport_of_Discharge__c limit 1 ];
        
        if(origin.Zona_Metropolitana__c != null || dest.Zona_Metropolitana__c != null)
            showW=false;
        
        return showW;
    }
    
    public static void test()
    {
        string a = '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
        a+= '';
    }
}