respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Load/Discharge</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Receive_from_SAP__c</fullName>
        <label>Date Receive from SAP</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Enviado_SAP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enviado SAP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Location__c.object
<CustomObject>
    <description>Object used to define locations within given countries. Can be automatically generated from First Steps https://c.eu11.visual.force.com/apex/NEU_First_Steps</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>AUTORIZADO_FP_FO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AUTORIZADO FP/FO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AUTORIZAR_GASTO_EXTRA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AUTORIZAR GASTO EXTRA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Acuse_en_SAP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Acuse en SAP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cargo_insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cargo insurance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supply Chain Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Carrier)</relationshipLabel>
        <relationshipName>Shipments_Carrier</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cliente_con_cita2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cliente con cita</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Conversion_Rate_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Conversion Rate Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Load</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Shipments (Country of Load)</relationshipLabel>
        <relationshipName>Shipments_Country_of_Load</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customs_Broker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customs Broker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Planner_Confirmed__c</fullName>
        <label>Date Planner Confirmed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Receive_from_SAP__c</fullName>
        <label>Date Receive from SAP</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Devolucion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Devolución</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ETA_Point_of_Discharge__c</fullName>
        <label>ETA</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ETD_from_Point_of_Load__c</fullName>
        <label>ETD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Sales_ExecutiveSP__c</fullName>
        <label>Email Sales Executive</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enable_Route_Options__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Route Options</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enviado_Sap__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enviado Sap</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hazardous__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hazardous</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monitoreo_Recepci_n_Acuse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monitoreo Recepción Acuse</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_Containers__c</fullName>
        <label>Container Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NotificarGastoExtra__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notificar Gasto Extra</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OK_FACTURAR_FI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OK FACTURAR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Margen_Operativo__c</fullName>
        <label>Margen Operativo %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Placas_Validadas__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Placas Validadas</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reparto__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reparto</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SAP_Invoiced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SAP Invoiced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SP_Evaluated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SP Evaluated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sell_Amount_Bloq__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Autoriza Venta menor a Cotizacion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sell_Price_Modified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sell Price Modified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shipment_Status_Mon__c</fullName>
        <label>Shipment Status Monitoreo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned_M</fullName>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>In Progress_M</fullName>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Awaiting load_M</fullName>
                    <label>Awaiting load</label>
                </value>
                <value>
                    <fullName>Loading_M</fullName>
                    <label>Loading</label>
                </value>
                <value>
                    <fullName>Delivery on Route_M</fullName>
                    <label>Delivery on Route</label>
                </value>
                <value>
                    <fullName>Awaiting Unload_M</fullName>
                    <label>Awaiting Unload</label>
                </value>
                <value>
                    <fullName>Unloading_M</fullName>
                    <label>Unloading</label>
                </value>
                <value>
                    <fullName>Finished_M</fullName>
                    <label>Finished</label>
                </value>
                <value>
                    <fullName>Failure_M</fullName>
                    <label>Failure</label>
                </value>
                <value>
                    <fullName>Incident_M</fullName>
                    <label>Incident</label>
                </value>
                <value>
                    <fullName>Cancel_M</fullName>
                    <label>Cancel</label>
                </value>
                <value>
                    <fullName>In Warehouse_M</fullName>
                    <label>In Warehouse</label>
                </value>
                <value>
                    <fullName>False_M</fullName>
                    <label>False</label>
                </value>
                <value>
                    <fullName>Operative Failure_M</fullName>
                    <label>Operative Failure</label>
                </value>
                <value>
                    <fullName>Robo_M</fullName>
                    <label>Robo</label>
                </value>
                <value>
                    <fullName>Error en Monitoreo_M</fullName>
                    <label>Error en Monitoreo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solicitud_de_Maniobras__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Solicitud de Maniobras</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State of Load</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country_of_Load__c</field>
                <operation>equals</operation>
                <valueField>State__c.Country__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Shipments (State of Load)</relationshipLabel>
        <relationshipName>Shipments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Acuse_SAP__c</fullName>
        <label>Status Acuse SAP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VERIFY_ACUSE_SAP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ACUSE RECIBIDO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VERIFY_PAK_CONTROL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VERIFY PAK CONTROL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VoBo_Acuse_SAP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VoBo Acuse SAP</label>
        <type>Checkbox</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/User.object
<CustomObject>
    <fields>
        <fullName>State_of_Load__c</fullName>
        <label>State of Load</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_PAK_ShipmentHistoryTest.cls
@IsTest
public class P2G_PAK_ShipmentHistoryTest {
    @IsTest(SeeAllData=true)
    public static void testCargaCsv(){
        Shipment__c ship = [SELECT Id,Account_for__c FROM Shipment__c limit 1];
        ship.Acuse_en_SAP__c = True;
        ship.VERIFY_ACUSE_SAP__c = True;
        ship.Sell_Amount_Bloq__c = True;
        ship.AUTORIZADO_FP_FO__c = True;
        ship.AUTORIZAR_GASTO_EXTRA__c = True;
        ship.Cargo_insurance__c = True;
        ship.Cliente_con_cita2__c= True;
        ship.N_Containers__c = 2;
        ship.Conversion_Rate_Date__c = System.today()+1;
        ship.Customs_Broker__c = True;
        //ship.Date_Planner_Confirmed__c = System.now()+1;
        
        ship.Date_Receive_from_SAP__c = System.now()+1;
        ship.Devolucion__c = True;
        ship.Email_Sales_ExecutiveSP__c = 'testship@pak2go.com';
        //ship.Enable_Route_Options__c = True;
        ship.Enviado_Sap__c = True;
        ship.ETA_Point_of_Discharge__c = System.today();
        ship.ETD_from_Point_of_Load__c = System.today();
        ship.Hazardous__c = True;
        ship.Order_Margen_Operativo__c = 30;
        ship.Monitoreo_Recepci_n_Acuse__c = True;
        ship.NotificarGastoExtra__c = True;
        ship.OK_FACTURAR_FI__c = True;
        ship.Only_Warehouse_Service__c = True;
        ship.Placas_Validadas__c = True;
        ship.Reparto__c = True;
        ship.SAP_Invoiced__c = True;
        ship.Sell_Price_Modified__c = True;
        ship.Shipment_Customer_Evaluate__c = 'www.google.com';
        //ship.Name = '.';
        ship.Shipment_Status_Mon__c = 'In Progress';
        ship.Solicitud_de_Maniobras__c = True;
        ship.SP_Evaluated__c = True;
        ship.Status_Acuse_SAP__c = 'Enviado';
        ship.VERIFY_PAK_CONTROL__c = True;
        ship.VoBo_Acuse_SAP__c = True;
        //Account carrier = [SELECT Id FROM Account LIMIT 1];
        //ship.Carrier__c = [Select Id from Carrier__c limit 1].Id;        
        //ship.Country_of_Load__c = [Select Id from Country__c  where Name = 'Mexico T'].Id;
        //ship.State_of_Load__c = [Select Id from State__c   where Name = 'Sonora T'].Id;
        ship.Site_of_Load__c = 'a034T000004F9RiQAK';//[Select Id from Location__c    where Name LIKE 'Hermosillo T'].Id;
        ship.Country_of_Discharge__c = 'a004T0000028AZOQA2';//[Select Id from Country__c  where Name = 'Mexico T'].Id;
        ship.State_of_Discharge__c = 'a044T000003SdLoQAK';//[Select Id from State__c   where Name = 'Sonora T'].Id;
        ship.Site_of_Discharge__c = 'a034T000004FHWMQA4';//[Select Id from Location__c    where Name = 'Hermosillo T'].Id;        
        //ship.Operation_Executive__c = [SELECT Id FROM User WHERE Alias = 'TestL'].Id;
        ship.Freight_Mode__c = 'Sea';
        ship.Service_Mode__c = 'EXPORT';
        ship.Service_Type__c = 'FCL';
        ship.Status_Shipment__c = 'Active';
        ship.Destination_Address__c = 'En alguna parte de Xalapa, Veracruz';
        ship.Documentos_de_Cruce__c = True;
        ship.Email_Sales_ExecutiveSP__c = '';
        ship.Name_Cliente__c = 'Cliente de Prueba';
        ship.Marketplace_Auction__c = True;
        ship.National_Operator__c = [SELECT Id FROM Operadores__c limit 1].Id;
        ship.Traslado_Ingreso__c = 'Ingreso';
        //ship.Shipment_Status_Plann__c = 'In Progress';
        ship.Equip_Placed__c = System.Today();
        ship.CurrencyIsoCode = 'USD';
        ship.Email_Sales_ExecutiveSP__c ='pruebas@gmail.com';
        ship.Routing_Operation_Status__c = 'Finalizado';
        ship.Air_Shipment_Status__c = 'Closed';
        //ship.Date_time_FN_Finished__c = System.Today();
        ship.Vehicle__c = 'a2O4T0000000O94UAE';
        test.startTest();
	        update ship;
        test.stopTest();
        
    }  
    
    
}