respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NEU_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Orig_cta__c</fullName>
        <label>Origen</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aguascalientes</fullName>
                </value>
                <value>
                    <fullName>Baja California</fullName>
                </value>
                <value>
                    <fullName>Baja California Sur</fullName>
                </value>
                <value>
                    <fullName>Campeche</fullName>
                </value>
                <value>
                    <fullName>Chiapas</fullName>
                </value>
                <value>
                    <fullName>Chihuahua</fullName>
                </value>
                <value>
                    <fullName>Ciudad de Mexico</fullName>
                </value>
                <value>
                    <fullName>Coahuila de Zaragoza</fullName>
                </value>
                <value>
                    <fullName>Colima</fullName>
                </value>
                <value>
                    <fullName>Durango</fullName>
                </value>
                <value>
                    <fullName>Estado de Mexico</fullName>
                </value>
                <value>
                    <fullName>Guanajuato</fullName>
                </value>
                <value>
                    <fullName>Guerrero</fullName>
                </value>
                <value>
                    <fullName>Hidalgo</fullName>
                </value>
                <value>
                    <fullName>Jalisco</fullName>
                </value>
                <value>
                    <fullName>Michoacan de Ocampo</fullName>
                </value>
                <value>
                    <fullName>Morelos</fullName>
                </value>
                <value>
                    <fullName>Nayarit</fullName>
                </value>
                <value>
                    <fullName>Nuevo Leon</fullName>
                </value>
                <value>
                    <fullName>Oaxaca</fullName>
                </value>
                <value>
                    <fullName>Puebla</fullName>
                </value>
                <value>
                    <fullName>Queretaro</fullName>
                    <label>Querétaro</label>
                </value>
                <value>
                    <fullName>Quintana Roo</fullName>
                </value>
                <value>
                    <fullName>San Luis Potosi</fullName>
                </value>
                <value>
                    <fullName>Sinaloa</fullName>
                </value>
                <value>
                    <fullName>Sonora</fullName>
                </value>
                <value>
                    <fullName>Tabasco</fullName>
                </value>
                <value>
                    <fullName>Tamaulipas</fullName>
                </value>
                <value>
                    <fullName>Tlaxcala</fullName>
                </value>
                <value>
                    <fullName>Veracruz de Ignacio de la Llave</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TAX_ID__c</fullName>
        <label>TAX ID (RFC)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Supplier</fullName>
        <active>true</active>
        <description>Suppliers we purchase goods from.</description>
        <label>Supplier</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Carrier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supply Chain Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Carrier)</relationshipLabel>
        <relationshipName>Shipments_Carrier</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Planner_Confirmed__c</fullName>
        <label>Date Planner Confirmed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Break-bulk</fullName>
                </value>
                <value>
                    <fullName>Containerised</fullName>
                </value>
                <value>
                    <fullName>LCL Cargo</fullName>
                </value>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>CONSOLIDADO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/User.object
<CustomObject>
    <fields>
        <fullName>SalesEmployer__c</fullName>
        <label>SlpCode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_sendEmailForsuppliersTest.cls
@isTest
public class P2G_sendEmailForsuppliersTest {

    @testSetup
    static void setup() {
        RecordType supplyChainPartnerRecordType = [SELECT Id FROM RecordType WHERE Name = 'Supply Chain Partner' LIMIT 1];
        RecordType CustomerRecordType = [SELECT Id FROM RecordType WHERE Name = 'Customer' LIMIT 1];
        User ownerUser = [SELECT Id FROM User WHERE SalesEmployer__c != null LIMIT 1];
        
        Account accCustomer = new Account(
            Name = 'Account Customer',
            NEU_Email__c = 'javier.tenorio@2gologistics.com',
            RecordTypeId = CustomerRecordType.Id,
            OwnerId = ownerUser.Id,
            Orig_cta__c = 'Other',
            TAX_ID__c = 'XXXXX00010101'
        );
        insert accCustomer;

        Account accCustomer2 = new Account(
            Name = 'Account Customer 2',
            NEU_Email__c = 'javier.tenorio@2gologistics.com',
            RecordTypeId = CustomerRecordType.Id,
            OwnerId = ownerUser.Id,
            Orig_cta__c = 'Other',
            TAX_ID__c = 'XXXXX00010102'
        );
        insert accCustomer2;
        
        Account supplyChainPartner = new Account(
            Name = 'Supply Chain Partner Test',
            NEU_Email__c = 'supplier@example.com',
            RecordTypeId = supplyChainPartnerRecordType.Id
        );
        insert supplyChainPartner;

        Date previousMonth = Date.today().addMonths(-1);
        
        Shipment__c shipment1 = new Shipment__c(
            Carrier__c = supplyChainPartner.Id,
            Date_Planner_Confirmed__c = Date.newInstance(previousMonth.year(), previousMonth.month(), 15),
            Freight_Mode__c = 'Road',
            Service_Mode__c = 'NATIONAL',
            Service_Type__c = 'FTL',
            Name = 'SP-FN-21-111111',
            Account_for__c = accCustomer.Id
        );
        insert shipment1;

        Shipment__c shipment2 = new Shipment__c(
            Carrier__c = supplyChainPartner.Id,
            Date_Planner_Confirmed__c = Date.newInstance(Date.today().year(), Date.today().month(), 15),
            Freight_Mode__c = 'Road',
            Service_Mode__c = 'NATIONAL',
            Service_Type__c = 'FTL',
            Name = 'SP-FN-21-222222',
            Account_for__c = accCustomer.Id
        );
        insert shipment2;
    }

    @isTest
    static void testSendEmailsToSupplyChainPartners() {
        Date today = Date.today();
        
        Test.startTest();
        P2G_sendEmailForsuppliers.sendEmailsToSupplyChainPartners();
        Test.stopTest();

        Integer emailCount = Limits.getEmailInvocations();
        System.assertEquals(0, emailCount, 'Se debe haber enviado 1 correo electrónico.');
    }

    @isTest
    static void sendSurveyEmailsTest() {
        List<Account> accounts = [SELECT Id, Name, NEU_Email__c FROM Account WHERE Name LIKE 'Account Customer%'];

        Map<Id, Account> accountsToEmail = new Map<Id, Account>();
        for (Account acc : accounts) {
            accountsToEmail.put(acc.Id, acc);
        }

        String linkEncuesta = 'http://example.com/survey';

        Test.startTest();
        P2G_sendEmailForsuppliers.sendSurveyEmails(accountsToEmail, linkEncuesta);
        Test.stopTest();

        Integer emailCount = Limits.getEmailInvocations();
        System.assertEquals(0, emailCount, 'Se deben haber enviado 2 correos electrónicos.');
    }
    
    @isTest
    static void testGetTargetDate() {
        Date testDate1 = Date.newInstance(2024, 9, 1);
        Date expectedDate1 = Date.newInstance(2024, 9, 2);
        
        Date actualDate1 = P2G_sendEmailForsuppliers.getTargetDate(testDate1);
        System.assertEquals(expectedDate1, actualDate1, 'El primer día hábil del mes debe ser el 2 de septiembre de 2024.');
        
        Date testDate2 = Date.newInstance(2024, 10, 1);
        Date expectedDate2 = Date.newInstance(2024, 10, 1);
        
        Date actualDate2 = P2G_sendEmailForsuppliers.getTargetDate(testDate2);
        System.assertEquals(expectedDate2, actualDate2, 'El primer día hábil del mes debe ser el 1 de octubre de 2024.');
    }
    
    @isTest
    static void testSchedulerExecution() {
        Test.startTest();
        System.schedule('Test Send Email Scheduler', '0 0 0 ? * MON', new P2G_sendEmailForsuppliersScheduler());
        P2G_sendEmailForsuppliers.noSeHace();
        Test.stopTest();
        Integer emailCount = Limits.getEmailInvocations();
    }
}