respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_Stop_B__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Stop B</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account Stop B)</relationshipLabel>
        <relationshipName>Shipments_Account_Stop_B</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Stop_C__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Stop C</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account Stop C)</relationshipLabel>
        <relationshipName>Shipments_Account_Stop_C</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Delivery Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Pickup Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_NEU_Ground_Track_TraceTest.cls
@isTest
public class P2G_NEU_Ground_Track_TraceTest {
    
    @isTest
    public static void testNEU_Ground_Track_Trace()
    {
        NEU_StaticVariableHelper.setBoolean1(true);
        
        //List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        //Account a = list_accounts[0];
        //insert a;
        Account a= new Account();
        a.Name='Test';
        a.RecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();		
        a.OwnerId=UserInfo.getUserId();        	
        insert a;
        Shipment__c ship = new Shipment__c(Name = 'SP-TS-00047', Account_for__c = a.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', Account_Stop_B__c  = a.Id,
                                           Account_Stop_C__c = a.Id, Origin_Address__c ='test origin address', Destination_Address__c ='test destination address', Only_Warehouse_Service__c = true);
        insert ship;
        Shipment__c ship2 = new Shipment__c(Name = 'SP-TS-00048', Account_for__c = a.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import',
                                            Account_Stop_C__c = a.Id, Origin_Address__c ='test origin address', Destination_Address__c ='test destination address', Only_Warehouse_Service__c = true);
        insert ship2;
        Shipment__c ship3 = new Shipment__c(Name = 'SP-TS-00049', Account_for__c = a.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', Account_Stop_B__c  = a.Id,
                                            Origin_Address__c ='test origin address', Destination_Address__c ='test destination address', Only_Warehouse_Service__c = true);
        insert ship3;
        NEU_Ground_Track_Trace gtt = new NEU_Ground_Track_Trace(new ApexPages.StandardController( ship ));
        NEU_Ground_Track_Trace gtt2 = new NEU_Ground_Track_Trace(new ApexPages.StandardController( ship2 ));
        NEU_Ground_Track_Trace gtt3 = new NEU_Ground_Track_Trace(new ApexPages.StandardController( ship3 ));
    }
}