respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TAX_ID__c</fullName>
        <label>TAX ID (RFC)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_AccountUsageService.cls
public class P2G_AccountUsageService implements Database.Batchable<sObject>{

    @TestVisible
    private String consultaSOQL;
    
    public P2G_AccountUsageService(){
        this.consultaSOQL='SELECT Id, Name, TAX_ID__c, Record_Type_Name__c, Customer_Id__c, CreatedDate FROM Account '+
            'WHERE Record_Type_Name__c =\'Customer\' AND TAX_ID__c !=NULL AND Customer_Id__c!=NULL ' +
            'AND Owner.SalesEmployer__c!=NULL ORDER BY CreatedDate DESC';
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(consultaSOQL);
    }
    
    public void execute(Database.BatchableContext BC, List<Account> listAccounts) {                
    	P2G_AccountRelationShipmentService accService=new P2G_AccountRelationShipmentService();
        accService.main(listAccounts);
    }
    public void finish(Database.BatchableContext BC){
        System.debug('finalizo');
    }
    
}