respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_Destination_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup filter to select from Account Addresses associated to the selected Consignee Account</description>
        <inlineHelpText>Specify Consignee Account first</inlineHelpText>
        <label>Account Destination Address</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Account_Address__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account_Address__c.status__c</field>
                <operation>equals</operation>
                <value>Validado</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>equals</operation>
                <value>NATIONAL</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>notEqual</operation>
                <value>NATIONAL</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Address__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Account Destination Address)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Origin_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Dependent on &quot;Supplier/Shipper Account&quot;</inlineHelpText>
        <label>Account Origin Address</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (4)</booleanFilter>
            <filterItems>
                <field>Account_Address__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account_Address__c.status__c</field>
                <operation>equals</operation>
                <value>Validado</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>equals</operation>
                <value>NATIONAL</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>notEqual</operation>
                <value>NATIONAL</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Address__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Account Origin Address)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Final Destination Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FolioResume__c</fullName>
        <formula>LEFT( Name , 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Servicio</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Margen_Operativo__c</fullName>
        <formula>IF(Total_Services_Order_Amount_NoIMP__c = 0, 
0, 
( Total_Services_Order_Amount_NoIMP__c  - Total_Services_Std_Buy_Amount_NoIMP__c -  Calc_Gasto_Op_Dir__c  ) / Total_Services_Order_Amount_NoIMP__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Margen Operativo %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Initial Origin Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <inlineHelpText>Only Approved as Succesfull Quotes will be available for Pick &amp; Ship</inlineHelpText>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote being prepared</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Quote being prepared</label>
                </value>
                <value>
                    <fullName>Awaiting costs suppliers</fullName>
                    <color>#FF0000</color>
                    <label>Awaiting costs suppliers</label>
                </value>
                <value>
                    <fullName>Sent awaiting response</fullName>
                    <color>#FF6600</color>
                    <label>Sent awaiting response</label>
                </value>
                <value>
                    <fullName>Approved as Succesful</fullName>
                    <color>#006600</color>
                    <label>Approved as Succesful</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <color>#3366FF</color>
                    <label>Shipped</label>
                </value>
                <value>
                    <fullName>Quote Declined</fullName>
                    <color>#FF0000</color>
                    <label>Quote Declined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_Destination_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Dependent on &quot;Consignee Account&quot;</inlineHelpText>
        <label>Account Destination Address</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (1 AND 2 AND 5) OR (4 AND 6)</booleanFilter>
            <filterItems>
                <field>Account_Address__c.status__c</field>
                <operation>equals</operation>
                <value>Validado</value>
            </filterItems>
            <filterItems>
                <field>Account_Address__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>equals</operation>
                <value>NATIONAL</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>notEqual</operation>
                <value>NATIONAL</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>equals</operation>
                <value>PORT</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>notEqual</operation>
                <value>PORT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account_Address__c</referenceTo>
        <relationshipLabel>Shipments (Account Destination Address)</relationshipLabel>
        <relationshipName>Shipments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Origin_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Origin Address</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (1 AND 2 AND 5) OR (4 AND 6)</booleanFilter>
            <filterItems>
                <field>Account_Address__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account_Address__c.status__c</field>
                <operation>equals</operation>
                <value>Validado</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>equals</operation>
                <value>NATIONAL</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>notEqual</operation>
                <value>NATIONAL</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>equals</operation>
                <value>PORT</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>notEqual</operation>
                <value>PORT</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Address__c</referenceTo>
        <relationshipLabel>Shipments (Account Origin Address)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Delivery Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order_Margen_Operativo__c</fullName>
        <label>Margen Operativo %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Pickup Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SPMargen_Operativo__c</fullName>
        <formula>IF( Total_Services_Sell_Amount__c  = 0, 
0, 
(Total_Services_Sell_Amount__c -  Total_Services_Std_Buy_Amount__c  -  SPGasto_Operativo_Directo__c  ) / Total_Services_Sell_Amount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Margen Operativo %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TriggerCustomerQuote.cls
public class TriggerCustomerQuote {    
    
    public static void ActualizarShipment(list<Customer_Quote__c> listaRegistros)
    {                
        set<string> idShipments = new set<string>();
        map<string,Customer_Quote__c> mapQuote = new map<string,Customer_Quote__c>();
        list<Shipment__c> listaShipments = new list<Shipment__c>();
        
        for(Customer_Quote__c cq : listaRegistros)
            {
                if(cq.Quotation_status__c == 'Shipped'){
                    idShipments.add(cq.Last_Shipment__c);
                    mapQuote.put(cq.Last_Shipment__c,cq);
                }
            }
        
            if(!idShipments.isEmpty()){
                
                for(Shipment__c s : [select id,SPMargen_Operativo__c  from Shipment__c where id in :idShipments] )
                {
                    if(mapQuote.containsKey(s.id))
                    {
                        s.Order_Margen_Operativo__c = mapQuote.get(s.id).Margen_Operativo__c;
                        listaShipments.add(s);    
                    }                    
                }
                update listaShipments;               
            }               
        
    }
    public static void ActualizarLocations(list<Customer_Quote__c> listaRegistros)
    {
        set<string> idsAccountAdress = new set<string>();
        for(Customer_Quote__c cq : listaRegistros)
        {
            if(cq.Account_Origin_Address__c != null){
                 idsAccountAdress.add(cq.Account_Origin_Address__c);
            }
            if(cq.Account_Destination_Address__c != null){
                idsAccountAdress.add(cq.Account_Destination_Address__c);
            }
        }
        map<string,Account_Address__c> mapAccountAddress = new   map<string,Account_Address__c>();
        for(Account_Address__c aa: [select id,Address__c,Address_Coordinates__latitude__s,Address_Coordinates__longitude__s from Account_Address__c where id IN: idsAccountAdress]){mapAccountAddress.put(aa.id,aa);}
        system.debug('idsAccountAdress: '+idsAccountAdress);
        system.debug('Map: '+mapAccountAddress);
        
         if(mapAccountAddress != null){
       
           for(Customer_Quote__c cq : listaRegistros)
            {
                if(cq.Account_Origin_Address__c != null){
                   
                    system.debug(''+mapAccountAddress.get(cq.Account_Origin_Address__c));
                    
                    cq.Origin_Address__c = mapAccountAddress.get(cq.Account_Origin_Address__c).Address__c;
                    cq.Origin_Location__Latitude__s =mapAccountAddress.get(cq.Account_Origin_Address__c).Address_Coordinates__latitude__s;
                    cq.Origin_Location__Longitude__s =mapAccountAddress.get(cq.Account_Origin_Address__c).Address_Coordinates__longitude__s;
                }
                else
                {
                   // cq.Origin_Address__c = null;
                    cq.Origin_Location__Latitude__s = null;
                    cq.Origin_Location__Longitude__s = null;
                }
                
                
                if(cq.Account_Destination_Address__c != null){
                    cq.Destination_Address__c = mapAccountAddress.get(cq.Account_Destination_Address__c).Address__c;
                    cq.Destination_Location__latitude__s =mapAccountAddress.get(cq.Account_Destination_Address__c).Address_Coordinates__latitude__s;
                    cq.Destination_Location__longitude__s =mapAccountAddress.get(cq.Account_Destination_Address__c).Address_Coordinates__longitude__s;
                }
                else
                {
                   // cq.Destination_Address__c = null;
                    cq.Destination_Location__latitude__s = null;
                    cq.Destination_Location__longitude__s = null;
                }
            }         
        }
        
    }
    
     public static void ActualizaDistancia(list<Customer_Quote__c> listaRegistros)
    {
   /*     set<string> idsAccountAdress = new set<string>();
        for(Customer_Quote__c cq : listaRegistros)
        {
            if(cq.Account_Origin_Address__c != null){
                 idsAccountAdress.add(cq.Account_Origin_Address__c);
            }
            if(cq.Account_Destination_Address__c != null){
                idsAccountAdress.add(cq.Account_Destination_Address__c);
            }
        }
        map<string,Account_Address__c> mapAccountAddress = new   map<string,Account_Address__c>();
        for(Account_Address__c aa: [select id,Address__c,Address_Coordinates__latitude__s,Address_Coordinates__longitude__s from Account_Address__c where id IN: idsAccountAdress]){mapAccountAddress.put(aa.id,aa);}
        system.debug('idsAccountAdress: '+idsAccountAdress);
        system.debug('Map: '+mapAccountAddress);
        
         if(mapAccountAddress != null){
       
           for(Customer_Quote__c cq : listaRegistros)
            {
                if( ( cq.FolioResume__c == 'FN' || cq.FolioResume__c == 'FI' || cq.FolioResume__c == 'PT' )  && cq.Account_Origin_Address__c != null && cq.Account_Destination_Address__c != null)
                {         
       			  DistanceIEQ.googleMapsDistanceKM(CQ.Origin_Location__Latitude__s, CQ.Origin_Location__Longitude__s, CQ.Destination_Location__Latitude__s,CQ.Destination_Location__Longitude__s, CQ.id);
                }

            }         
        }*/
        
    }
}