respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <label>Segmentacion</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nuevo</fullName>
                </value>
                <value>
                    <fullName>Bronce</fullName>
                </value>
                <value>
                    <fullName>Plata</fullName>
                </value>
                <value>
                    <fullName>Cuenta Clave</fullName>
                </value>
                <value>
                    <fullName>None1</fullName>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Oro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TAX_ID__c</fullName>
        <label>TAX ID (RFC)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venta_Sap__c</fullName>
        <label>Venta</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sin Asignar</fullName>
                </value>
                <value>
                    <fullName>Credito</fullName>
                </value>
                <value>
                    <fullName>Contado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkPlace__c</fullName>
        <label>WorkPlace</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MTY</fullName>
                </value>
                <value>
                    <fullName>MXN</fullName>
                </value>
                <value>
                    <fullName>SAL</fullName>
                </value>
                <value>
                    <fullName>GDL</fullName>
                </value>
                <value>
                    <fullName>CUU</fullName>
                </value>
                <value>
                    <fullName>HER</fullName>
                </value>
                <value>
                    <fullName>JUA</fullName>
                </value>
                <value>
                    <fullName>LEO</fullName>
                </value>
                <value>
                    <fullName>MXI</fullName>
                </value>
                <value>
                    <fullName>MXS</fullName>
                </value>
                <value>
                    <fullName>SLP</fullName>
                </value>
                <value>
                    <fullName>PUE</fullName>
                </value>
                <value>
                    <fullName>TIJ</fullName>
                </value>
                <value>
                    <fullName>TOL</fullName>
                </value>
                <value>
                    <fullName>TOR</fullName>
                </value>
                <value>
                    <fullName>QUE</fullName>
                </value>
                <value>
                    <fullName>VER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts Addresses</relationshipLabel>
        <relationshipName>Accounts_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Calle_cat__c</fullName>
        <label>Calle</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <defaultValue>&quot;Shipping Address&quot;</defaultValue>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing Address</fullName>
                </value>
                <value>
                    <fullName>Shipping Address</fullName>
                    <default>true</default>
                    <label>Shipping Address</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Catalogo_SAT__c.object
<CustomObject>
    <description>Permite llevar el registro de los catalogos del SAT para la carta porte</description>
    <fields>
        <fullName>Clave_SAT__c</fullName>
        <description>Catalgo SAT Clave del catalogo al que corresponde</description>
        <label>Clave SAT</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Catalogo SAT</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos SAT</pluralLabel>
    <recordTypes>
        <fullName>Colonia</fullName>
        <active>true</active>
        <description>Catalogo el Sat c_Colonias</description>
        <label>Colonia</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Comercio_Exterior__c</fullName>
        <label>Comercio Exterior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Reference__c</fullName>
        <label>Customer Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <inlineHelpText>Only Approved as Succesfull Quotes will be available for Pick &amp; Ship</inlineHelpText>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote being prepared</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Quote being prepared</label>
                </value>
                <value>
                    <fullName>Awaiting costs suppliers</fullName>
                    <color>#FF0000</color>
                    <label>Awaiting costs suppliers</label>
                </value>
                <value>
                    <fullName>Sent awaiting response</fullName>
                    <color>#FF6600</color>
                    <label>Sent awaiting response</label>
                </value>
                <value>
                    <fullName>Approved as Succesful</fullName>
                    <color>#006600</color>
                    <label>Approved as Succesful</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <color>#3366FF</color>
                    <label>Shipped</label>
                </value>
                <value>
                    <fullName>Quote Declined</fullName>
                    <color>#FF0000</color>
                    <label>Quote Declined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <defaultValue>&quot;P2G&quot;</defaultValue>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                    <default>true</default>
                    <label>P2G</label>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Until__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Venta_Sap__c</fullName>
        <formula>text(Account_for__r.Venta_Sap__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Venta</label>
        <type>Text</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Location__c.object
<CustomObject>
    <description>Object used to define locations within given countries. Can be automatically generated from First Steps https://c.eu11.visual.force.com/apex/NEU_First_Steps</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>State__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Location Default</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ISO_Code_2c__c</fullName>
        <label>ISO_Code_2c</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Iso_Code__c</fullName>
        <label>Iso Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone_Planner_email__c</fullName>
        <label>Planner email</label>
        <type>Email</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/User.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Workplace__c</fullName>
        <label>Workplace</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/p2g_CotizadorTest.cls
@isTest
public class p2g_CotizadorTest {
    @TestSetup
    static void Setup(){
        List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        Account account_test = list_accounts[0];
        account_test.Name = 'Cotizador';
        account_test.Credit_Limit__c = 1000000;
        account_test.Venta_Sap__c='Credito';
        account_test.Segment__c='Nuevo';
        account_test.Workplace__c=null;
        insert account_test;
        Account carrier_test = new Account();
        String recordCarrier = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Supply Chain Partner').getRecordTypeId();
        carrier_test.RecordTypeId = recordCarrier;
        carrier_test.Name = 'Carrier de Test';
        carrier_test.TAX_ID__c = 'FLD120217NW5';
        carrier_test.Credit_Limit__c = 1000000;
        carrier_test.Venta_Sap__c='Credito';
        carrier_test.Segment__c='Nuevo';
        carrier_test.Workplace__c=null;
        carrier_test.Customer_Id__c ='P005153';
        insert carrier_test;
        User userT = [select id,managerId, userRole.Name  from user where id =: UserInfo.getUserId() limit 1];
        Rol_Margen__c rolMargen = TestDataFactory.createRolMargen(userT.userRole.Name);//Director Comercial ,Director Regional
        Catalogo_SAT__c catalogo = TestDataFactory.createCatalogoSat('Caja de acero test' , 'TCA125','Unidad Peso');
        Catalogo_SAT__c producto = TestDataFactory.createCatalogoSat('Papel' , 'TCA127','Productos y Servicios cP');
        Catalogo_SAT__c tipodeRemolque = TestDataFactory.createCatalogoSat('Caja Seca' , 'CTR007','Tipo de Remolque');
        Catalogo_SAT__c embalaje = TestDataFactory.createCatalogoSat('Caja' , 'TCA128','Tipo de Embalaje');
        Catalogo_SAT__c palet = TestDataFactory.createCatalogoSat('Pallet' , 'TCA228','Unidad Peso');
        update catalogo;
        Catalogo_SAT__c cp = new Catalogo_SAT__c();        
        cp.Name  = '9808282';
        cp.Clave_SAT__c = '9808282';
        cp.RecordTypeId = Schema.SobjectType.Catalogo_SAT__c.getRecordTypeInfosByName().get('Codigo Postal').getRecordTypeId();        
        insert cp;
        Catalogo_SAT__c colonia = new Catalogo_SAT__c();        
        colonia.Name  = 'Pruebacolonia';
        colonia.Clave_SAT__c = 'Pruebacolonia';
        colonia.RecordTypeId = Schema.SobjectType.Catalogo_SAT__c.getRecordTypeInfosByName().get('Colonia').getRecordTypeId();        
        insert colonia; 
        Country__c country = new Country__c(Name='Mxico');
        insert country;
        State__c state = new State__c(Name='Sonora',Country__c=country.Id,Iso_Code__c='SON',ISO_Code_2c__c='SO',Zone_Planner_email__c='kuresa@gmaidl.com',Active__c=true);
        insert state;
        Location__c location = new Location__c(Name='PruebaUnica', State__c=state.Id,Country__c=country.Id);
        insert location;
        Container_Type__c container = new Container_Type__c(Name='Super tracto Camion',Type__c='Road',Cargo_Weight_Kg__c=22222);
        insert container;
        Account_Address__c address1 = new  Account_Address__c();
        address1.Name ='Direccion test';
        address1.Account__c=account_test.Id;
        address1.Type__c='Shipping Address';
        address1.Calle_cat__c='AVENIDA ARBOLEDA';
        address1.Address__c='Arbolada 57B, Conj U los Sauces V, 50200 San José Guadalupe, Méx., México';
        address1.Address_Coordinates__Latitude__s =28.7276823;
        address1.Address_Coordinates__Longitude__s=-106.123545;
        insert address1;
        Customer_Quote__c quote = new Customer_Quote__c();
        String recordTypeId = Schema.SObjectType.Customer_Quote__c.getRecordTypeInfosByName().get('Import-Export Quote').getRecordTypeId();
        quote.RecordTypeId = recordTypeId;
        quote.Name='.';
        quote.Account_for__c = account_test.Id;
        quote.Team__c = 'P2G';
        quote.Quotation_Status__c = 'Quote being prepared';
        quote.Customer_Reference__c = 'hola soy una prueba';
        quote.Valid_From__c = system.today();
        quote.Valid_Until__c = system.today();
        quote.Comercio_Exterior__c = 'No';
        quote.Freight_Mode__c = 'Road';
        quote.Service_Mode__c = 'NATIONAL';
        quote.Service_Type__c = 'FTL';
        quote.CurrencyIsoCode = 'MXN';
        quote.Country_ofLoad__c = location.Country__c;
        quote.State_of_Load__c = location.State__c;
        quote.Site_of_Load__c = location.Id;
        quote.Country_ofDischarge__c = location.Country__c;
        quote.State_of_Discharge__c = location.State__c;
        quote.Site_of_Discharge__c = location.Id;
        quote.ETD__c = Date.today();
        quote.ETA__c = Date.today();
        quote.Community_Status__c = 'CUSTOMER CREATED';
        quote.Pricing_Executive__c= userT.Id;
        quote.Operations_Exec__c = userT.Id;
        insert quote;
    }
    
    @isTest
    static void testCrearLead() {
        
        p2g_Cotizador.wrapperCotizador cotizador = new p2g_Cotizador.wrapperCotizador();
        cotizador.nameCliente = 'Nombre Cliente de Prueba';
        cotizador.telefonoCliente = '1234567890';
        cotizador.emailCliente = 'cliente@ejemplo.com';
        cotizador.tipoServicio='SP-FN-FLETE NACIONAL';
        cotizador.sapServiceTypeName = 'Servicio de Prueba';
        cotizador.siteLoadName = 'Carga en Sitio de Prueba';
        cotizador.siteDischargeName = 'Descarga en Sitio de Prueba';
        cotizador.containerTypeName = 'Tipo de Contenedor de Prueba';
        cotizador.costo = '100.00';
        cotizador.cuentaId = '001XXXXXXXXXXXXXXX';
        cotizador.interiorOrigen = 'Int 123';
        cotizador.exteriorOrigen = 'Ext 456';
        cotizador.cPOrigenId = '987654';
        cotizador.coloniaOrigen = 'Colonia Origen de Prueba';
        cotizador.coloniaOrigenId = '654321';
        cotizador.calleDestino = 'Calle Destino de Prueba';
        cotizador.interiorDestino = 'Int 789';
        cotizador.exteriorDestino = 'Ext 012';
        cotizador.cPDestino = '543210';
        cotizador.cPDestinoId = '789012';
        cotizador.coloniaDestino = 'Colonia Destino de Prueba';
        cotizador.coloniaDestinoId = '210987';
        cotizador.etd = '2023-09-15';
        cotizador.eta = '2023-09-20';
        cotizador.buyRate = 536.6;
        cotizador.calleFiscal ='calle fiscal';
        cotizador.interiorFiscal ='34';
        cotizador.exteriorFiscal ='342';
        cotizador.cPFiscal ='cp fiscal';
        cotizador.cPFiscalId ='42334';
        cotizador.coloniaFiscal ='colonia fiscal';
        cotizador.coloniaFiscalId ='34234';

        Test.startTest(); 
        p2g_Cotizador.wrapperCotizador cotizador2 = p2g_Cotizador.Cotizador(cotizador,1);
        p2g_Cotizador.wrapperCotizador wrapper = new p2g_Cotizador.wrapperCotizador();
        p2g_Cotizador.wrapperCotizador wrf = p2g_Cotizador.getWrapper();
        
        p2g_Cotizador.wrapperCotizador coti = new p2g_Cotizador.wrapperCotizador();
        cotizador.cPOrigen = '12345';
        cotizador.razonSocial = 'Nombre de Prueba';
        cotizador.telefonoCliente = '1234567890';
        cotizador.emailCliente = 'test@test.com';
        cotizador.rfc = 'RFC12345';
        cotizador.banco = 'Banco de Prueba';
        cotizador.numeroCuenta = '1234567890';
        cotizador.calleOrigen = 'Calle de Prueba';
        Cotizador.tipoServicio ='SP-FN-FLETE NACIONAL';
        Account result = p2g_Cotizador.creaAccount(coti);
        
        List<Catalogo_SAT__c> codigoPostal = p2g_Cotizador.codigoPostal('adada',2,'Colonia');
		list<SAP_Service_Type__c> lista = p2g_Cotizador.getSapServiceType('asas','asasas');
        Map<String, Decimal> coordenadas = new Map<String, Decimal>();
        coordenadas.put('latitude', 37.7749);
        coordenadas.put('longitude', -122.4194);
        Catalogo_SAT__c colonia = [select Id FROM Catalogo_SAT__c where name = 'Pruebacolonia'];
        Account_Address__c direccion = p2g_Cotizador.creAccountAddres(
            'MiDireccionDePrueba',
            result.Id,
            'Name',
            '123 Calle Ejemplo',
            '456',
            'Apto 789',
            colonia.Id,
            'Colonia Ejemplo',
            coordenadas
        );
        p2g_Cotizador.updateQuote(cotizador2.quoteId,2,'','', '','','');
        p2g_Cotizador.updateQuote(cotizador2.quoteId,3,result.Id,'2023-09-15', '2023-09-15',direccion.Id, direccion.Id);
        Test.stopTest();
    }

}