respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Merchandise_Insurance__c</fullName>
        <inlineHelpText>Requerid for Impak</inlineHelpText>
        <label>Merchandise Insurance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Seguro AON</fullName>
                </value>
                <value>
                    <fullName>Seguro Paqueteria</fullName>
                </value>
                <value>
                    <fullName>Seguro Consolidado</fullName>
                </value>
                <value>
                    <fullName>NO REQUIERE</fullName>
                    <default>true</default>
                    <label>NO REQUIERE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Motivo__c</fullName>
        <label>Motivo</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                    <default>true</default>
                    <label>NATIONAL</label>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>FP</fullName>
                </value>
                <value>
                    <fullName>FO</fullName>
                </value>
                <value>
                    <fullName>MAYOREO</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>% Service Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GroupGVS</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Service_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SAP Service Type Sell</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Group__c</field>
                <operation>equals</operation>
                <valueField>SAP_Service_Type__c.Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>SAP_Service_Type__c.Activo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SAP_Service_Type__c</referenceTo>
        <relationshipLabel>Services Rates</relationshipLabel>
        <relationshipName>Services_Rates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Quote_Item_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of an Import-Export to generate Shipment Cargo Lines.</description>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Cargo_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Cargo Line</label>
    <nameField>
        <label>Imp-Exp Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateQuoteServiceLinesController_Test.cls
@isTest
public class CreateQuoteServiceLinesController_Test {
    @isTest
    public static void test(){
       /* SAP_Service_Type__c sst = new SAP_Service_Type__c();
        sst.Name = 'test';
        sst.Activo__c = true;
        sst.Group__c = 'Fletes';
        insert sst;
        
        Account a = new Account();
        a.Name = 'test';
        a.Customer_Id__c = 'DADA';
        insert a;
        
        Carrier_Line_Load_Point__c ruta = new Carrier_Line_Load_Point__c();
        ruta.Name = 'test';
        insert ruta;
        
        Container_Type__c ct = new Container_Type__c();
        ct.Name = 'test';
        insert ct;
        
        List<Carrier_Line_Load_Point__c> rutas = [SELECT Id, Name FROM Carrier_Line_Load_Point__c];
        System.debug('Rutas: ' + rutas);
        
        string json = '[{"Route":"-","RateName":"Flete 3","ValidFrom":"01/10/2040","ValidUntil":"30/10/2040","CustomerID":"DADA","AccountFor":"test","TTDays":"5","ContainerType":"test","SellRate":"50000", "Grupo":"Fletes", "SAPST":"test", "Comments":"N/A"}]';
        CargaTarifarioVentaController.cargarTarifario(json);
        
        Fee__c rate = [SELECT Id FROM Fee__c LIMIT 1];
        
        Customer_Quote__c quote = new Customer_Quote__c();
        quote.Name = 'test';
        quote.Account_for__c = a.Id;
        quote.CurrencyIsoCode = 'MXN';
        quote.Merchandise_Insurance__c = 'NO REQUIERE';
        quote.Motivo__c = 'NO';
        quote.Freight_Mode__c = 'Road';
        quote.Service_Mode__c = 'NATIONAL';
        quote.Service_Type__c = 'FTL';
        insert quote;
        
        Quote_Item_Line__c cl = new Quote_Item_Line__c();
        cl.Name = '001';
        cl.Import_Export_Quote__c = quote.Id;
        cl.Container_Type__c = ct.Id;
        cl.Units__c = 1;
        insert cl;
        
        CreateQuoteServiceLinesController.getQuote(quote.Id);
        CreateQuoteServiceLinesController.consultaRates(quote.Id);
        CreateQuoteServiceLinesController.consultaServiceLines(quote.Id);
        string jsonLineas = '[{"rate":"' + rate.Id +'","units":"1","comments":"Prueba json","feecategory":"Road Freights","currencycode":"MXN","sell":9000,"buy":0}]';
        CreateQuoteServiceLinesController.createLineas(quote.Id, jsonLineas);*/
        CreateQuoteServiceLinesController.test();
    }
}