respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account_Address__c.object
<CustomObject>
    <fields>
        <fullName>CalleEspejo__c</fullName>
        <label>Calle espejo</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodigoPostalEspejo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codigo Postal espejo</label>
        <referenceTo>Catalogo_SAT__c</referenceTo>
        <relationshipLabel>Accounts Addresses (Codigo Postal espejo)</relationshipLabel>
        <relationshipName>Accounts_AddressesmQ0H</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Codigo_Postal_CP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Codigo_Postal</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo_SAT__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Codigo Postal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo_SAT__c</referenceTo>
        <relationshipLabel>Accounts Addresses (Codigo_Postal)</relationshipLabel>
        <relationshipName>Accounts_Addresses5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Colonia_espejo__c</fullName>
        <label>Colonia espejo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EstadoEspejo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Estado espejo</label>
        <referenceTo>Catalogo_SAT__c</referenceTo>
        <relationshipLabel>Accounts Addresses (Estado espejo)</relationshipLabel>
        <relationshipName>Accounts_Addresses8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Folio_Origen_Destino2__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>Folio Origen Destino</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>LocalidadEspejo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Localidad espejo</label>
        <referenceTo>Catalogo_SAT__c</referenceTo>
        <relationshipLabel>Accounts Addresses (Localidad espejo)</relationshipLabel>
        <relationshipName>Accounts_Addresses6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Municipio_Cat2__c</fullName>
        <formula>Codigo_Postal_CP__r.Municipio_Ref_CP__r.Clave_SAT__c  &amp; &apos; &apos; &amp;   Codigo_Postal_CP__r.Municipio_Ref_CP__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Municipio CP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_Ext_cp__c</fullName>
        <label>Numero Ext</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_Int_cat__c</fullName>
        <label>Numero Int</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaisEspejo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pais espejo</label>
        <referenceTo>Catalogo_SAT__c</referenceTo>
        <relationshipLabel>Accounts Addresses (Pais espejo)</relationshipLabel>
        <relationshipName>Accounts_Addresses9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <description>Este campo registra los estatus en el proceso de validación de las coordenadas por el equipo de monitoreo en control room status_CR</description>
        <label>Status CR</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nuevo</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>Pendiente</fullName>
                </value>
                <value>
                    <fullName>Validado</fullName>
                </value>
                <value>
                    <fullName>Rechazado</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Catalogo_SAT__c.object
<CustomObject>
    <description>Permite llevar el registro de los catalogos del SAT para la carta porte</description>
    <fields>
        <fullName>Clave_SAT__c</fullName>
        <description>Catalgo SAT Clave del catalogo al que corresponde</description>
        <label>Clave SAT</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Catalogo SAT</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos SAT</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_Destination_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup filter to select from Account Addresses associated to the selected Consignee Account</description>
        <inlineHelpText>Specify Consignee Account first</inlineHelpText>
        <label>Account Destination Address</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>Account_Address__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account_Address__c.status__c</field>
                <operation>equals</operation>
                <value>Validado</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>equals</operation>
                <value>NATIONAL</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>notEqual</operation>
                <value>NATIONAL</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Address__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Account Destination Address)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Origin_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Dependent on &quot;Supplier/Shipper Account&quot;</inlineHelpText>
        <label>Account Origin Address</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR (4)</booleanFilter>
            <filterItems>
                <field>Account_Address__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account_Address__c.status__c</field>
                <operation>equals</operation>
                <value>Validado</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>equals</operation>
                <value>NATIONAL</value>
            </filterItems>
            <filterItems>
                <field>$Source.Service_Mode__c</field>
                <operation>notEqual</operation>
                <value>NATIONAL</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account_Address__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Account Origin Address)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Site_of_Discharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>PORT for Sea, AIRPORT for Air, TERMINAL SITE for Road and Rail.
Specify Country of Discharge first</inlineHelpText>
        <label>Site of Discharge</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>$Source.Country_ofDischarge__c</field>
                <operation>equals</operation>
                <valueField>Location__c.Country__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.State_of_Discharge__c</field>
                <operation>equals</operation>
                <valueField>Location__c.State__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.State__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Site of Discharge)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Site_of_Discharge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>PORT for Sea, AIRPORT for Air, TERMINAL SITE for Road and Rail.
Specify Country of Load first</inlineHelpText>
        <label>Site of Load</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>$Source.Country_ofLoad__c</field>
                <operation>equals</operation>
                <valueField>Location__c.Country__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.State_of_Load__c</field>
                <operation>equals</operation>
                <valueField>Location__c.State__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.State__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Site of Load)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Site_of_Load</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Location__c.object
<CustomObject>
    <description>Object used to define locations within given countries. Can be automatically generated from First Steps https://c.eu11.visual.force.com/apex/NEU_First_Steps</description>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_asignarAccountAddressMapTest.cls
@isTest
public class P2G_asignarAccountAddressMapTest {
	@isTest(SeeAllData=true)
    static void claseTest(){
        List<Account_Address__c> ubicacion = [SELECT Id, Name, CalleEspejo__c, Numero_Ext_cp__c, Numero_Int_cat__c, CodigoPostalEspejo__c,
                                 CodigoPostalEspejo__r.Name, Colonia_espejo__c, Municipio_Cat2__c, LocalidadEspejo__r.Name, EstadoEspejo__r.Name,
                                 PaisEspejo__r.Name, Folio_Origen_Destino2__c,Address_Coordinates__Latitude__s,Address_Coordinates__Longitude__s,
                                 EstadoEspejo__r.Clave_SAT__c, status__c, Codigo_Postal_CP__c
                                 FROM Account_Address__c WHERE status__c = 'Validado' OR status__c = 'Pendiente'];
        Customer_Quote__c direccion = [SELECT id, Account_Origin_Address__c, Account_Origin_Address__r.Name, Account_Origin_Address__r.CodigoPostalEspejo__c,
                                       Account_Origin_Address__r.CodigoPostalEspejo__r.Name, Account_Origin_Address__r.Address_Coordinates__Latitude__s,
                                       Account_Origin_Address__r.Address_Coordinates__Longitude__s, Account_Origin_Address__r.status__c,
                                       Account_Origin_Address__r.CalleEspejo__c, Account_Origin_Address__r.Numero_Ext_cp__c, 
                                       Account_Origin_Address__r.Numero_Int_cat__c, Account_Origin_Address__r.Colonia_espejo__c, 
                                       Account_Origin_Address__r.Municipio_Cat2__c, Account_Origin_Address__r.LocalidadEspejo__r.Name, 
                                       Account_Origin_Address__r.EstadoEspejo__r.Name, Account_Origin_Address__r.PaisEspejo__r.Name, Account_Origin_Address__r.Folio_Origen_Destino2__c,
                                       Account_Destination_Address__c, Account_Destination_Address__r.Name, Account_Destination_Address__r.CodigoPostalEspejo__c,
                                       Account_Destination_Address__r.CodigoPostalEspejo__r.Name, Account_Destination_Address__r.Address_Coordinates__Latitude__s,
                                       Account_Destination_Address__r.Address_Coordinates__Longitude__s, Account_Destination_Address__r.status__c,
                                       Account_Destination_Address__r.CalleEspejo__c, Account_Destination_Address__r.Numero_Ext_cp__c, 
                                       Account_Destination_Address__r.Numero_Int_cat__c, Account_Destination_Address__r.Colonia_espejo__c, 
                                       Account_Destination_Address__r.Municipio_Cat2__c, Account_Destination_Address__r.LocalidadEspejo__r.Name,
                                       Account_Destination_Address__r.EstadoEspejo__r.Name, Account_Destination_Address__r.PaisEspejo__r.Name, Account_Destination_Address__r.Folio_Origen_Destino2__c,
                                       Site_of_Load__c, Site_of_Load__r.Name, Site_of_Discharge__c, Site_of_Discharge__r.Name
                                 FROM Customer_Quote__c WHERE Account_for__r.Name LIKE: '%ejemplo%' LIMIT 1];
        P2G_asignarAccountAddressMap.address address = new P2G_asignarAccountAddressMap.address();
        list<Catalogo_SAT__c> getcp = P2G_asignarAccountAddressMap.getCP('93340');
        list<P2G_asignarAccountAddressMap.address> getBuscaAddress = P2G_asignarAccountAddressMap.getBuscaAddress(ubicacion[0].Name, '', '');
        list<P2G_asignarAccountAddressMap.address> getBuscaAddressSite = P2G_asignarAccountAddressMap.getBuscaAddress('','Monterrey', '');
        list<P2G_asignarAccountAddressMap.address> getBuscaAddressCP = P2G_asignarAccountAddressMap.getBuscaAddress('', '', ubicacion[0].Codigo_Postal_CP__c);
		list<P2G_asignarAccountAddressMap.address> llenarAddress = P2G_asignarAccountAddressMap.llenarAddress(ubicacion);
        Location__c seleccionLocacion = P2G_asignarAccountAddressMap.seleccionLocacion(ubicacion[0].Municipio_Cat2__c, 'Veracruz', 'Veracruz', ubicacion[0].EstadoEspejo__r.Clave_SAT__c);
        P2G_asignarAccountAddressMap.getAddressWrapper getAddress = P2G_asignarAccountAddressMap.getAddress(direccion.Id);
        P2G_asignarAccountAddressMap.getAddressWrapper llenarGetAddress = P2G_asignarAccountAddressMap.llenarGetAddress(direccion);
        String quitarAcentos = P2G_asignarAccountAddressMap.quitarAcentos('cadená');
    }
}