respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_InternalFollower</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Associated_Document__c.object
<CustomObject>
    <description>Import space for documents created and associated to an Account, Import-Export and/or shipment.</description>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Import-Export Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer_Quote__c.Account_for__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Document</label>
    <nameField>
        <label>Associated Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/CSH_Import_Export__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Use_Price_List_and_Dicounts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Price Lists and Dicounts</label>
        <type>Checkbox</type>
    </fields>
    <label>CSH Import/Export</label>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <formula>Account_for__r.Owner.FirstName  &amp; &quot; &quot; &amp;Account_for__r.Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner (Sales Executive)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Community_Status__c</fullName>
        <defaultValue>&apos;CUSTOMER CREATED&apos;</defaultValue>
        <label>Community Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CUSTOMER CREATED</fullName>
                    <default>true</default>
                    <label>CUSTOMER CREATED</label>
                </value>
                <value>
                    <fullName>SENT TO PAK2GO</fullName>
                </value>
                <value>
                    <fullName>COMPLETED BY PAK2GO</fullName>
                </value>
                <value>
                    <fullName>CONFIRMED</fullName>
                </value>
                <value>
                    <fullName>REJECTED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                    <default>true</default>
                    <label>NATIONAL</label>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>FP</fullName>
                </value>
                <value>
                    <fullName>FO</fullName>
                </value>
                <value>
                    <fullName>MAYOREO</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Import_Export_Fee_Line__c.object
<CustomObject>
    <description>Specifies transport fees associated to an Import-Export. Child object from &quot;Freight Rates Management&quot;</description>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote/Order</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Service Lines</relationshipLabel>
        <relationshipName>Import_Export_Fees_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Import-Export Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Break-bulk</fullName>
                </value>
                <value>
                    <fullName>Containerised</fullName>
                </value>
                <value>
                    <fullName>LCL Cargo</fullName>
                </value>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>CONSOLIDADO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Consolidation_Data__c.object
<CustomObject>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <formula>TEXT( Shipment__r.Freight_Mode__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Freight Mode</label>
        <type>Text</type>
    </fields>
    <label>Shipment Consolidation Data</label>
    <nameField>
        <label>Shipment Consolidation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Consolidation Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_OM_Import_ExportSteps.cls
public with sharing class NEU_OM_Import_ExportSteps {
    public Customer_Quote__c record;
    public string step {get;set;}
    public boolean todorelleno{get;set;}
    public string urlCQLPriceList{get;set;}
    public string urlCreateItemsLines{get;set;}
    ApexPages.StandardController con;
    public Integer stepNumber {get;set;}
    public string urlCQLPriceListM{get;set;}
    public string urlCreateItemsLinesM{get;set;}
    public Id shipmentID {get;set;}
    
    public String step_1 {get;set;}
    public String step_2 {get;set;}
    public String step_3 {get;set;}
    public String step_4 {get;set;}
    public String step_5 {get;set;}
    public String step_6 {get;set;}
    public String step_7 {get;set;}
    public String step_9 {get;set;}
    public String step_8 {get;set;}
    
    public String url_generate_shipment{get;set;}
    
    public boolean showNotifyCommunity 
	{
		get
		{
			if(record.Community_Status__c == 'SENT TO PAK2GO') //UserInfo.getUserId() == record.Account_for__r.Account_Executive_User__c
				showNotifyCommunity = true;	
			else
				showNotifyCommunity = false;
			return showNotifyCommunity;
		}
		set;
	}
            
    public String step_10
    {
        get
        {
            if(step_10==null)
            {
                List<Import_Export_Discount_Line__c> lines = [select Id from Import_Export_Discount_Line__c where Import_Export_Quote_Order__c=:record.Id limit 1];
                if(lines.size()>0)
                    step_10='step_inactive';
                else
                    step_10='step_active';
            }
            return step_10;
        }
        set;
    }

    public NEU_OM_Import_ExportSteps(ApexPages.StandardController stdController) {



        con = stdController;
        
        try {
            record = [select Id, Name, Account_for__r.Account_Executive_User__c, Community_Status__c, Freight_Mode__c, Service_Mode__c, Service_Type__c from Customer_Quote__c where Id =: con.getRecord().id];
        } catch( Exception ee) { 
            record = new Customer_Quote__c();
        }
        
        url_generate_shipment = 'apex/NEU_Generate_Shipments?id='+record.Id;

        //No damos la url de generar shipment a el usuario de Alejandro Garza unicamente para los services types FO
        //if( record.Service_Type__c != 'FO' && UserInfo.getUserId() == '0050Y000003ntxTQAQ')
        //Cambio jose@neurored: Alejandro Garza es el unico que puede generar de tipo FO
        if( record.Service_Type__c == 'FO' && UserInfo.getUserId() != '0050Y000003ntxTQAQ')
            url_generate_shipment = '';

        if( record.Service_Type__c == 'FO' && UserInfo.getProfileId() == '00e0Y000000XFLFQA4')
            url_generate_shipment = 'apex/NEU_Generate_Shipments?id='+record.Id;

        step_1 = 'step_active';
        step_2 = 'step_active';
        step_3 = 'step_active';
        step_4 = 'step_active';
        step_5 = 'step_active';
        step_6 = 'step_active';
        step_7 = 'step_active';
        step_9 = 'step_active';
        step_8 = 'step_active';
        
        boolean condescuentocreate = true;
        
        CSH_Import_Export__c sr = CSH_Import_Export__c.getInstance(userinfo.getuserid());
        if(sr == null)
        {
          sr = CSH_Import_Export__c.getInstance(userinfo.getProfileId());
          if(sr == null)
              sr = CSH_Import_Export__c.getOrgDefaults();
        }
        if(sr!=null)
            condescuentocreate=!sr.Use_Price_List_and_Dicounts__c;
        
        urlCQLPriceList =Site.getBaseUrl()+'/apex/NEU_OM_CQLPriceListYDiscount?id='+record.Id+'';
        urlCQLPriceListM=Site.getBaseUrl()+'/apex/NEU_OM_CQLPriceListYDiscount?id='+record.Id+'&sf1=1';
        
        
        if(condescuentocreate == false) 
        {
            urlCreateItemsLines = Site.getBaseUrl() + '/apex/NEU_OM_CreateItemsLinesAndDiscount?id='+record.Id+'';
            urlCreateItemsLinesM= Site.getBaseUrl() + '/apex/NEU_OM_CreateItemsLinesAndDiscount?id='+record.Id+'&sf1=1';
        }
        else
        {

            System.debug('URL val: ' + Site.getBaseUrl());
            urlCreateItemsLines = '/apex/NEU_OM_CreateItemsLines?id='+record.Id+'';
            urlCreateItemsLinesM= '/apex/NEU_OM_CreateItemsLines?id='+record.Id+'&sf1=1';
        }
        
        boolean hayduty=false;
        
        
         //-----------------------
        List<Quote_Item_Line__c> qiline = new List<Quote_Item_Line__c>();
        qiline = [select Id, Name, Import_Export_Quote__c from Quote_Item_Line__c where Import_Export_Quote__c =: record.Id];
        if(qiline.size() > 0)
        {
            step_1 = 'step_inactive';
        }
        
        List<Quote_Item_Line__c> qiline2 = new List<Quote_Item_Line__c>();
        qiline2 = [select Id, Name, Import_Export_Quote__c, Delivery_Date__c, Delivery_Number__c from Quote_Item_Line__c where Import_Export_Quote__c =: record.Id];
        boolean tienen_fecha=false;
        for(Quote_Item_Line__c quiline: qiline2)
        {
                if(quiline.Delivery_Date__c != null || quiline.Delivery_Number__c != null)
                {
                    tienen_fecha = true;
                    break;
                }
        }
        
        if(tienen_fecha == true)
        {
           step_2 ='step_inactive';
        }
        
        List<Import_Export_Fee_Line__c> impexpfeeli = new List<Import_Export_Fee_Line__c>();
        impexpfeeli = [select Id, Name, Import_Export_Quote__c from Import_Export_Fee_Line__c where Import_Export_Quote__c =: record.Id];
        if(impexpfeeli.size() > 0)
        {
            step_3='step_inactive';
        }
        
        List<Quote_Item_Line__c> qilines = new List<Quote_Item_Line__c>();
        qilines = [select Id, Name, Import_Export_Quote__c, Customs_Value__c from Quote_Item_Line__c where Import_Export_Quote__c =: record.Id];
        for(Quote_Item_Line__c qil : qilines)
        {
            if(qil.Customs_Value__c > 0 && qil.Customs_Value__c != null)
                hayduty = true;
        }
        
        if(hayduty == true)
        {
            step_4='step_inactive';
        }
        
        List<Associated_Document__c> documentos_asociados2 = new List<Associated_Document__c>();
        documentos_asociados2 = [select Id, Name, Import_Export_Quote__c from Associated_Document__c where Import_Export_Quote__c =: record.Id and Name like :record.Name+'%IEQ%'];
        if(documentos_asociados2.size()>0)
        {
            step_5 = 'step_inactive';
        }
        
        List<Associated_Document__c> documentos_asociados = new List<Associated_Document__c>();
        documentos_asociados = [select Id, Name, Import_Export_Quote__c from Associated_Document__c where Import_Export_Quote__c =: record.Id];
        stepNumber=0;
        if(documentos_asociados.size()>0)
        {
            step_6 = 'step_inactive';
        }
        
        List<Task> tareas = new List<Task>();
        tareas = [select Id, WhatId from Task where WhatId =: record.Id];
        if(tareas.size()>0)
        {
            step_7 ='step_inactive';
        }
        
        List<Fee__c> listado_fees = new List<Fee__c>();
        listado_fees = [select Id, Name from Fee__c where Import_Export_Quoted_Marketplace__c =: record.Id];
        if(listado_fees.size()>0)
        {
            step_9 = 'step_inactive';
        }
        
        List<Shipment_Consolidation_Data__c> shipment_consolidation_data = [select Id, Name, Shipment__c 
        from Shipment_Consolidation_Data__c where Shipment__c != null and Import_Export_Quote__c =: record.Id];
        if(record.Freight_Mode__c == 'Road' && record.Service_Mode__c == 'NATIONAL')
        {
        	step_8 = 'step_active';
        }
        else
        {
        	if(shipment_consolidation_data.size() > 0)
        	{
	            shipmentID = shipment_consolidation_data[0].Shipment__c;
	            step_8 ='step_inactive';
        	}
        }
        
        //----------------------------
    }   
}