respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ActiveSap__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Consignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consignee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Consignee)</relationshipLabel>
        <relationshipName>NEU_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Clave_de_Unidad_de_Peso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clave de Unidad de Peso</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Catalogo_SAT__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Unidad Peso</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Catalogo_SAT__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer or Agente Aduanal</inlineHelpText>
        <label>Cuenta Destino</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Consignee, Supply Chain Partner, Agente Aduanal</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Consignee Account (Destination))</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Container_Size__c</fullName>
        <label>Container Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>20&quot; Container</fullName>
                </value>
                <value>
                    <fullName>40&quot; Container</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Destination_Address__c</fullName>
        <label>Final Destination Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin_Address__c</fullName>
        <label>Initial Origin Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Pricing_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Import_Export_Quotes_Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <inlineHelpText>Only Approved as Succesfull Quotes will be available for Pick &amp; Ship</inlineHelpText>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote being prepared</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Quote being prepared</label>
                </value>
                <value>
                    <fullName>Awaiting costs suppliers</fullName>
                    <color>#FF0000</color>
                    <label>Awaiting costs suppliers</label>
                </value>
                <value>
                    <fullName>Sent awaiting response</fullName>
                    <color>#FF6600</color>
                    <label>Sent awaiting response</label>
                </value>
                <value>
                    <fullName>Approved as Succesful</fullName>
                    <color>#006600</color>
                    <label>Approved as Succesful</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <color>#3366FF</color>
                    <label>Shipped</label>
                </value>
                <value>
                    <fullName>Quote Declined</fullName>
                    <color>#FF0000</color>
                    <label>Quote Declined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Per Kg</fullName>
                </value>
                <value>
                    <fullName>Per TON</fullName>
                </value>
                <value>
                    <fullName>Per M3</fullName>
                </value>
                <value>
                    <fullName>Per Container</fullName>
                </value>
                <value>
                    <fullName>Per Pallet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer, Supplier or Agente Aduanal</inlineHelpText>
        <label>Cuenta Origen</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Shipper, Customer, Supply Chain Partner, Supplier Owner or Lessee of Vehicule, Agente Aduanal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Supplier/Shipper Account)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Supplier_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Fee_Category__c</fullName>
        <inlineHelpText>Be aware that if you change the values of this picklist the hard corde of the Import-Export PDF quote must also be changed by our end.</inlineHelpText>
        <label>Rate Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Road Freights</fullName>
                    <default>true</default>
                    <label>Road Freights</label>
                </value>
                <value>
                    <fullName>Other Service Charges</fullName>
                </value>
                <value>
                    <fullName>Sea Freights</fullName>
                </value>
                <value>
                    <fullName>Air Freights</fullName>
                </value>
                <value>
                    <fullName>POL Charges</fullName>
                </value>
                <value>
                    <fullName>POD Charges</fullName>
                </value>
                <value>
                    <fullName>Drayages</fullName>
                </value>
                <value>
                    <fullName>Mayoreo</fullName>
                </value>
                <value>
                    <fullName>Tarimas</fullName>
                </value>
                <value>
                    <fullName>Warehouse</fullName>
                </value>
                <value>
                    <fullName>IMPAK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>% Service Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                    <default>true</default>
                    <label>Fixed</label>
                </value>
                <value>
                    <fullName>Per Kg</fullName>
                </value>
                <value>
                    <fullName>Per M3</fullName>
                </value>
                <value>
                    <fullName>Per Container</fullName>
                </value>
                <value>
                    <fullName>Per TON</fullName>
                </value>
                <value>
                    <fullName>Per Pallet</fullName>
                </value>
                <value>
                    <fullName>Per Day</fullName>
                </value>
                <value>
                    <fullName>% of Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Import_Export_Fee_Line__c.object
<CustomObject>
    <description>Specifies transport fees associated to an Import-Export. Child object from &quot;Freight Rates Management&quot;</description>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote/Order</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Service Lines</relationshipLabel>
        <relationshipName>Import_Export_Fees_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <formula>TEXT(Import_Export_Quote__r.Quotation_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quotation Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <formula>TEXT ( Service_Rate_Name__r.Rate_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rate Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Units</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Quote_Item_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of an Import-Export to generate Shipment Cargo Lines.</description>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Cargo Line</label>
    <nameField>
        <label>Imp-Exp Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_Import_Export_ContainerType_to_SizeT.cls
@isTest
public class NEU_Import_Export_ContainerType_to_SizeT {

    
    @isTest
    public static void runTest(){
        
        Test.startTest();
        List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        Account a = list_accounts[0];
        a.ActiveSap__c = true;
        insert a;
        Account sup = TestDataFactory.createAccounts('Cuenta carrier', 'Supply Chain Partner');
		//Account sup1 = TestDataFactory.createAccounts('Cuenta carrier', 'Supply Chain Partner');        
        User usr = TestDataFactory.createUserAdmin();
		Rol_Margen__c rm = TestDataFactory.createRolMargen('Director Comercial');
        Catalogo_SAT__c catalogo = TestDataFactory.createCatalogoSat('Caja de acero test' , 'TCA125','Unidad Peso'); 
        //Customer_Quote__c importexportquote = new Customer_Quote__c(Account_for__c = a.Id, Consignee__c = a.Id, Supplier_Account__c = sup.Id, Quotation_Status__c=' Approved as Succesful', Container_Size__c = '20" Container');
        Customer_Quote__c importexportquote = new Customer_Quote__c(Account_for__c = a.Id, Consignee__c = a.Id, Supplier_Account__c = sup.Id, Quotation_Status__c=' Quote being prepared', Container_Size__c = '20" Container', Origin_Address__c = '', Destination_Address__c = '', Only_Warehouse_Service__c = true,Pricing_Executive__c=userinfo.getUserId(),Clave_de_Unidad_de_Peso__c = catalogo.Id);
        insert importexportquote;       
        Quote_Item_Line__c quote = new Quote_Item_Line__c(Import_Export_Quote__c = importexportquote.id,Name = 'lineas items',Units__c=10);
        insert quote;
        
        Fee__c service_rate = new Fee__c();
        service_rate.Name = 'Sercie Rate Test';
        service_rate.Fee_Category__c = 'Disbursement';
        service_rate.Rate_Type__c = 'Per Kg';
        service_rate.Account_for__c = a.Id;
        insert service_rate;
        
        Import_Export_Fee_Line__c ie_service_line = new Import_Export_Fee_Line__c();
        ie_service_line.Import_Export_Quote__c = importexportquote.Id;
        ie_service_line.Name = '001';
        ie_service_line.Service_Rate_Name__c = service_rate.Id;
        ie_service_line.Extension_Service_Name__c = 'Test Name';
        ie_service_line.Discount__c = 10;
        ie_service_line.Quote_Buy_Price__c = 10;
        ie_service_line.Quote_Sell_Price__c = 10;
        ie_service_line.Units__c = 10;
        insert ie_service_line;
        
        importexportquote.Quotation_Status__c ='Approved as Succesful';
        update importexportquote;
        Test.stopTest();
    }
}