respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Load/Discharge</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_Airport_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site of Load/Discharge</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Location__c.Country__c</field>
                <operation>equals</operation>
                <valueField>$Source.Country_of_Load__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.State_of_Load_Discharge__c</field>
                <operation>equals</operation>
                <valueField>Location__c.State__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.State__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Accounts who use this Site</relationshipLabel>
        <relationshipName>AccountsSite</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Supplier</fullName>
        <active>true</active>
        <description>Suppliers we purchase goods from.</description>
        <label>Supplier</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Location__c.object
<CustomObject>
    <description>Object used to define locations within given countries. Can be automatically generated from First Steps https://c.eu11.visual.force.com/apex/NEU_First_Steps</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subdivision__c</fullName>
        <label>Subdivision</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNLOCODE__c</fullName>
        <label>UNLOCODE</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Location Default</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>ATAPOD__c</fullName>
        <label>OI ATAPOD</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Country_of_Discharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Discharge</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Shipments (Country of Discharge)</relationshipLabel>
        <relationshipName>Shipments_Country_of_Discharge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Load</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Shipments (Country of Load)</relationshipLabel>
        <relationshipName>Shipments_Country_of_Load</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>OI Date</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ETA_ATA__c</fullName>
        <label>OI ETA / ATA</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ETD__c</fullName>
        <label>OI ETD</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Imo_Number__c</fullName>
        <label>OI Imo Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Activity__c</fullName>
        <label>OI Last Activity</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>OI Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMSI__c</fullName>
        <label>OI MMSI</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Port_Of_Discharging__c</fullName>
        <label>OI Port Of Discharging</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Port_Of_Loading__c</fullName>
        <label>OI Port Of Loading</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments_Route</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Truck_Vessel_Flight_ETA__c</fullName>
        <formula>Truck_Vessel_Flight__r.Vessel_Flight_ETA_Point_of_Discharge__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vessel ETA Port of Discharge</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Truck_Vessel_Flight_ETD__c</fullName>
        <formula>Truck_Vessel_Flight__r.Vessel_Flight_ETD_Point_of_Load__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vessel ETD Port of Loading</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Truck_Vessel_Latitude__c</fullName>
        <label>OI Vessel Latitude</label>
        <precision>12</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Truck_Vessel_Longitude__c</fullName>
        <label>OI Vessel Longitude</label>
        <precision>12</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vessel_Activities__c</fullName>
        <label>OI Vessel Activities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Vessel_Course__c</fullName>
        <label>OI Vessel Course</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vessel_Information__c</fullName>
        <label>OI Vessel Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Vessel_Name__c</fullName>
        <label>OI Vessel Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vessel_Speed__c</fullName>
        <label>OI Vessel Speed</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_test_See_Vessel_Shipments.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class NEU_test_See_Vessel_Shipments {

     static testMethod void test_See_Vessel_Shipment() {
          NEU_StaticVariableHelper.setBoolean1(true);
      ApexPages.currentPage().getParameters().put('test', 'test');
      List<Account> list_accounts = NEU_Utils.getAccounts('Customer,Supplier,');    
      Account a = list_accounts[0];
      insert a;
      Account sup = list_accounts[1];
      insert sup;
      Country__c country = new Country__c(ISO_Code__c='test');
      insert country;
      Location__c location = new Location__c(City__c='test city',Country__c=country.id,Subdivision__c='test subdivision', UNLOCODE__c='test');
      insert location;
      Carrier_Line_Load_Point__c ruta = new Carrier_Line_Load_Point__c(Name='test routa', Country_of_Discharge__c=country.Id,Country_of_Load__c=country.Id,Port_Airport_of_Discharge__c=location.Id,Port_Airport_of_Load__c=location.Id);
      insert ruta;
      Shipment__c ship = new Shipment__c(Account_for__c = a.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', IMO_Number__c = '9392561', Vessel_Information__c='information vessel' , Vessel_Activities__c= 'vessel activities', Country_of_Discharge__c= country.Id , Country_of_Load__c = country.Id, Port_Of_Loading__c ='test port of loading', Port_Of_Discharging__c='test port of discharging' , Route__c =ruta.Id, Only_Warehouse_Service__c = true);
      insert ship;
      List<Shipment__c> shipments = new List<Shipment__c>();
      shipments = [select Id, Name, Route__c, Country_of_Load__c, Truck_Vessel_Flight_ETD__c, Truck_Vessel_Flight_ETA__c,  ATAPOD__c , Last_Activity__c, 
      Country_of_Discharge__c, Route__r.Name, Date__c, Location__c, ETD__c,
      Truck_Vessel_Latitude__c, Truck_Vessel_Longitude__c, Vessel_Speed__c, Vessel_Course__c, Imo_Number__c, Vessel_Information__c, Vessel_Activities__c, Vessel_Name__c, MMSI__c, ETA_ATA__c, Port_Of_Loading__c, Port_Of_Discharging__c  from Shipment__c where id =: ship.Id ];
     
      ApexPages.StandardSetController stdController = new ApexPages.StandardSetController(shipments);
      NEU_See_Vessel_Shipments uda = new NEU_See_Vessel_Shipments(stdController);
      uda.ship = shipments;
      uda.getTrackAndTrace();
      uda.getbyvessel();
      uda.Id_shipment_consulta = ship.Id;
      uda.getByIMO('9392561',0);
      uda.Id_shipment_consulta_activities = ship.Id;
      uda.getactivities();
      uda.guardar_cambios();
      uda.getinformation();
     }
  
}