respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_InternalFollower</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_Executive_User__c</fullName>
        <formula>Account_for__r.Owner.FirstName  &amp; &quot; &quot; &amp;Account_for__r.Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner (Sales Executive)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_for_Billing_Address__c</fullName>
        <description>Specify Billing Address with parameters: Street, City, Postal Code, State and Country</description>
        <formula>Account_for__r.BillingStreet  &amp; &quot;, &quot; &amp;  Account_for__r.BillingCity &amp; &quot;, &quot; &amp;  Account_for__r.BillingPostalCode &amp; &quot;, &quot; &amp;  Account_for__r.BillingState &amp; &quot;, &quot; &amp;  Account_for__r.BillingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account for (Billing Address)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_for_Shipping_Address__c</fullName>
        <description>Specify Shipping Street, City, Postal Code, State and Country</description>
        <formula>Account_for__r.ShippingStreet  &amp; &quot;, &quot; &amp;  Account_for__r.ShippingCity  &amp; &quot;, &quot; &amp; Account_for__r.ShippingPostalCode  &amp; &quot;, &quot; &amp;  Account_for__r.ShippingState &amp; &quot;, &quot; &amp;  Account_for__r.ShippingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account for (Shipping Address)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Approved_Date__c</fullName>
        <label>Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Dependent on Account for (Customer)</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Contact)</relationshipLabel>
        <relationshipName>Import_Export_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <inlineHelpText>Only Approved as Succesfull Quotes will be available for Pick &amp; Ship</inlineHelpText>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote being prepared</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Quote being prepared</label>
                </value>
                <value>
                    <fullName>Awaiting costs suppliers</fullName>
                    <color>#FF0000</color>
                    <label>Awaiting costs suppliers</label>
                </value>
                <value>
                    <fullName>Sent awaiting response</fullName>
                    <color>#FF6600</color>
                    <label>Sent awaiting response</label>
                </value>
                <value>
                    <fullName>Approved as Succesful</fullName>
                    <color>#006600</color>
                    <label>Approved as Succesful</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <color>#3366FF</color>
                    <label>Shipped</label>
                </value>
                <value>
                    <fullName>Quote Declined</fullName>
                    <color>#FF0000</color>
                    <label>Quote Declined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Per Kg</fullName>
                </value>
                <value>
                    <fullName>Per TON</fullName>
                </value>
                <value>
                    <fullName>Per M3</fullName>
                </value>
                <value>
                    <fullName>Per Container</fullName>
                </value>
                <value>
                    <fullName>Per Pallet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SUM_Buy_Origin_Amount_number__c</fullName>
        <label>SUM Buy Origin Amount (number)</label>
        <summarizedField>Quote_Item_Line__c.Origin_Buy_Amount_header__c</summarizedField>
        <summaryForeignKey>Quote_Item_Line__c.Import_Export_Quote__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <label>Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed</fullName>
                    <default>true</default>
                    <label>Fixed</label>
                </value>
                <value>
                    <fullName>Per Kg</fullName>
                </value>
                <value>
                    <fullName>Per M3</fullName>
                </value>
                <value>
                    <fullName>Per Container</fullName>
                </value>
                <value>
                    <fullName>Per TON</fullName>
                </value>
                <value>
                    <fullName>Per Pallet</fullName>
                </value>
                <value>
                    <fullName>Per Day</fullName>
                </value>
                <value>
                    <fullName>% of Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Import_Export_Fee_Line__c.object
<CustomObject>
    <description>Specifies transport fees associated to an Import-Export. Child object from &quot;Freight Rates Management&quot;</description>
    <fields>
        <fullName>Buy_Amount__c</fullName>
        <description>If &quot;Quote Buy Price&quot; positive then maximum value between &quot;Quote Buy Price&quot; x &quot;Units&quot; or &quot;Min Amount&quot;
If &quot;Quote Buy Price&quot; negative then minimum value between &quot;Quote Buy Price&quot; x &quot;Units&quot; or &quot;Min Amount&quot;</description>
        <formula>IF(Quote_Buy_Price__c &gt;= 0 ,MAX (Quote_Buy_Price__c * Units__c, IF((ISNULL(Quote_Buy_Price__c)== true) || (Quote_Buy_Price__c = 0), 0, Min_Amount__c ) ), MIN (Quote_Buy_Price__c* Units__c, IF((ISNULL(Quote_Buy_Price__c )== true) || (Quote_Buy_Price__c = 0), 0, - Min_Amount__c ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Highest value between &quot;Quote Buy Price&quot; x &quot;Units&quot; and &quot;Min Amount&quot;</inlineHelpText>
        <label>Std. Buy Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Extension_Service_Name__c</fullName>
        <label>Comments Service Line</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote/Order</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Service Lines</relationshipLabel>
        <relationshipName>Import_Export_Fees_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <formula>TEXT(Import_Export_Quote__r.Quotation_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quotation Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Buy_Price__c</fullName>
        <label>Quote Std. Buy Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote_Sell_Price__c</fullName>
        <label>Quote Sell Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_Type__c</fullName>
        <formula>TEXT ( Service_Rate_Name__r.Rate_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rate Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sell_Amount__c</fullName>
        <description>Conversion to currency of &quot;Sell Gross Amount&quot; x (1 - &quot;Discount&quot;)</description>
        <formula>Sell_Gross_Amount__c * (1 - Discount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>&quot;Sell Gross Amount&quot; x (1 - &quot;Discount&quot;)</inlineHelpText>
        <label>Sell Net Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Rate_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Name</label>
        <referenceTo>Fee__c</referenceTo>
        <relationshipLabel>Import-Export Service Lines</relationshipLabel>
        <relationshipName>Import_Export_Fees_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Units</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Quote_Item_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of an Import-Export to generate Shipment Cargo Lines.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Conversion to currency of &quot;Units&quot; x &quot;Price&quot;</description>
        <formula>Units__c  *  Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>&quot;Units&quot; x &quot;Price&quot;</inlineHelpText>
        <label>Origin Sell Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Unit Origin Sell Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Cargo Line</label>
    <nameField>
        <label>Imp-Exp Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_OM_GenerateQuote.cls
public with sharing class NEU_OM_GenerateQuote {

    public Customer_Quote__c record;
    public List<Import_Export_Fee_Line__c> revefeelines {get;set;}
    public List<Import_Export_Fee_Line__c> disburfeelines {get;set;}
    public List<Import_Export_Fee_Line__c> Transportfeelines {get;set;}
    public List<Quote_Item_Line__c> itemslines {get;set;}
    public String cotizacion_completa {get;set;}
    public decimal total_lineas {get;set;}
    public Decimal total_lineas_items {get;set;}
    public Decimal total_disburfee {get;set;}
    public Decimal total_refee {get;set;}
    public Decimal total_transfee {get;set;}
    public Decimal total_fees {get;set;}
    public Decimal total_document {get;set;}
    public String resultado {get;set;}
    public boolean hay_fees_disbur {get;set;}
    public boolean hay_fees_reve {get;set;}
    public boolean hay_fees_trans {get;set;}
    public boolean hay_items {get;set;}
    public decimal totaltaxes {get;set;}
    public string totalestrans {get;set;}
    public string totalrefee {get;set;}
    public string totallineasitems {get;set;}
    public string totaldisburfee {get;set;}
    public string totaldocumentos {get;set;}
    public string totalfees {get;set;}
    public string totaltaxesstring {get;set;}
    
    public string currency_customer_quote {get;set;}
    
    ApexPages.StandardController con;
            
    public NEU_OM_GenerateQuote(ApexPages.StandardController stdController) {

        con = stdController;
        
        try { 
        record = [select Id, Name, Account_for__c,  Quotation_Status__c, Approved_Date__c, Account_Executive_User__c,Account_for__r.Name,Account_for_Billing_Address__c,Account_for_Shipping_Address__c,Contact__r.Name,SUM_Buy_Origin_Amount_number__c from Customer_Quote__c where id =: con.getRecord().id limit 1 for update];
        } catch( Exception ee) { 
            record = new Customer_Quote__c();
        }
        total_lineas_items =0;
        total_disburfee =0;
        total_refee =0;
        total_fees = 0;
        total_document = 0;
        totaltaxes = 0;
        total_transfee = 0;
        hay_fees_disbur =false;
        currency_customer_quote = NEU_CurrencyUtils.getCurrencyIsoCode(record);
            disburfeelines = [select Id, Name, Import_Export_Quote__c, Units__c, Extension_Service_Name__c, Service_Rate_Name__r.Name, Rate_Type__c, Quote_Sell_Price__c,Sell_Amount__c, Quote_Buy_Price__c, Buy_Amount__c, Service_Rate_Name__c, Service_Rate_Name__r.Fee_Category__c from Import_Export_Fee_Line__c where Import_Export_Quote__c =: record.Id and Service_Rate_Name__r.Fee_Category__c =: 'Disbursement']; 
            for(Import_Export_Fee_Line__c lines:disburfeelines)
            {
                total_disburfee +=lines.Sell_Amount__c;
                hay_fees_disbur = true;
            }
        hay_fees_reve = false;
        revefeelines = [select Id, Name, Import_Export_Quote__c, Units__c, Extension_Service_Name__c,Service_Rate_Name__r.Name, Rate_Type__c, Quote_Sell_Price__c,Sell_Amount__c, Quote_Buy_Price__c, Buy_Amount__c, Service_Rate_Name__c, Service_Rate_Name__r.Fee_Category__c from Import_Export_Fee_Line__c where Import_Export_Quote__c =: record.Id and Service_Rate_Name__r.Fee_Category__c =: 'Clearing Costs']; 
         for(Import_Export_Fee_Line__c lines:revefeelines)
          {
                total_refee +=lines.Sell_Amount__c;
                hay_fees_reve = true;
          }
        hay_fees_trans =false; 
        Transportfeelines = [select Id, Name,Extension_Service_Name__c, Units__c, Import_Export_Quote__c,Service_Rate_Name__r.Name, Rate_Type__c, Quote_Sell_Price__c,Sell_Amount__c, Quote_Buy_Price__c, Buy_Amount__c, Service_Rate_Name__c, Service_Rate_Name__r.Fee_Category__c from Import_Export_Fee_Line__c where Import_Export_Quote__c =: record.Id and Service_Rate_Name__r.Fee_Category__c =: 'Transport & Freights']; 
         for(Import_Export_Fee_Line__c lines:Transportfeelines)
          {
                total_transfee +=lines.Sell_Amount__c;
                hay_fees_trans = true;
                
          }
          hay_items = false;
         itemslines = [select Id, Name,Item_Name__r.Name, Extension_Item_Name__c, Duty__c,Price__c, Item_Supplier_Owner__c, Item_Supplier_Owner__r.Name, Units__c, Amount__c,Product_Item_DC__c,Total_Taxes_Form__c, Family__c  from Quote_Item_Line__c where Import_Export_Quote__c =: record.Id order by Family__c]; 
         for(Quote_Item_Line__c lines:itemslines)
         {
                total_lineas_items +=lines.Amount__c;
                if(lines.Total_Taxes_Form__c!= null)
                    totaltaxes += lines.Total_Taxes_Form__c;
                hay_items = true;
         }
            
        total_document = total_lineas_items+total_refee+total_disburfee+total_transfee+totaltaxes;
        total_fees = total_refee +total_disburfee+total_transfee;
        
        Decimal rA2 = total_transfee;
        List<String> args2 = new String[]{'0','number','###,###,##0.00'};
        String s2 = String.format(rA2.format(), args2);
        totalestrans = s2;
        
        rA2 = total_refee;
        s2 = String.format(rA2.format(), args2);
        totalrefee  = s2;
        
        rA2 = total_lineas_items;
        s2 = String.format(rA2.format(), args2);
        totallineasitems  = s2;
        
        rA2 = total_disburfee;
        s2 = String.format(rA2.format(), args2);
        totaldisburfee = s2;
        
        rA2 = total_document;
        s2 = String.format(rA2.format(), args2);
        totaldocumentos = s2;
        
        rA2 = total_fees;
        s2 = String.format(rA2.format(), args2);
        totalfees = s2;
        
        rA2 = totaltaxes;
        s2 = String.format(rA2.format(), args2);
        totaltaxesstring = s2;  
     
    }
    
}