respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Area__c</fullName>
        <inlineHelpText>Make sure that you have the same Business Areas for ACCOUNTS, FAMILIES, PRICE LISTS and SUPPLY PROJECTS.</inlineHelpText>
        <label>Business Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air Freight</fullName>
                </value>
                <value>
                    <fullName>Animal Nutrition</fullName>
                </value>
                <value>
                    <fullName>Auto-Parts</fullName>
                </value>
                <value>
                    <fullName>Cloths &amp; Accessories</fullName>
                </value>
                <value>
                    <fullName>Construction &amp; Engineering</fullName>
                </value>
                <value>
                    <fullName>Construction &amp; Mining</fullName>
                </value>
                <value>
                    <fullName>Energy &amp; Hydrocarbons</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverages</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Machinery &amp; Parts</fullName>
                </value>
                <value>
                    <fullName>MERA Autoparts</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Other Services</fullName>
                </value>
                <value>
                    <fullName>Purchasing</fullName>
                </value>
                <value>
                    <fullName>Rail Freight</fullName>
                </value>
                <value>
                    <fullName>Recruiting Services</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Sea Freight</fullName>
                </value>
                <value>
                    <fullName>Telecom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customers who purchase goods or services from us. Also for Shippers and Consignees.</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Comercio_Exterior__c</fullName>
        <label>Comercio Exterior</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Reference__c</fullName>
        <label>Customer Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ETD__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>ETD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <inlineHelpText>Only Approved as Succesfull Quotes will be available for Pick &amp; Ship</inlineHelpText>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote being prepared</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Quote being prepared</label>
                </value>
                <value>
                    <fullName>Awaiting costs suppliers</fullName>
                    <color>#FF0000</color>
                    <label>Awaiting costs suppliers</label>
                </value>
                <value>
                    <fullName>Sent awaiting response</fullName>
                    <color>#FF6600</color>
                    <label>Sent awaiting response</label>
                </value>
                <value>
                    <fullName>Approved as Succesful</fullName>
                    <color>#006600</color>
                    <label>Approved as Succesful</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <color>#3366FF</color>
                    <label>Shipped</label>
                </value>
                <value>
                    <fullName>Quote Declined</fullName>
                    <color>#FF0000</color>
                    <label>Quote Declined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                    <default>true</default>
                    <label>NATIONAL</label>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>FP</fullName>
                </value>
                <value>
                    <fullName>FO</fullName>
                </value>
                <value>
                    <fullName>MAYOREO</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <defaultValue>&quot;P2G&quot;</defaultValue>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                    <default>true</default>
                    <label>P2G</label>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_Until__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Valid Until</label>
        <type>Date</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <label>Flight Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MAWB_Number__c</fullName>
        <label>MAWB Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Only_Warehouse_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Warehouse Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Mode__c</fullName>
        <label>Service Mode</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>IMPORT</fullName>
                </value>
                <value>
                    <fullName>EXPORT</fullName>
                </value>
                <value>
                    <fullName>NATIONAL</fullName>
                </value>
                <value>
                    <fullName>INTERNATIONAL</fullName>
                </value>
                <value>
                    <fullName>PORT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Break-bulk</fullName>
                </value>
                <value>
                    <fullName>Containerised</fullName>
                </value>
                <value>
                    <fullName>LCL Cargo</fullName>
                </value>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>CONSOLIDADO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/User.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P2G</fullName>
                </value>
                <value>
                    <fullName>WCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_test_Traxon.cls
@isTest
private class NEU_test_Traxon {
    static testMethod void test_NEU_ChampEmail()
    {
    	NEU_StaticVariableHelper.setBoolean1(true);
        NEU_ChampEmail.eventData e1=new NEU_ChampEmail.eventData();
        NEU_ChampEmail.eventData e2=new NEU_ChampEmail.eventData();
        e1.compareTo(e2);
        e1.myDateTime=system.now();
        e1.compareTo(e2);
        e1.myDateTime=null;
        e2.myDateTime=system.now();
        e1.compareTo(e2);
        e1.myDateTime=e2.myDateTime.addDays(1);
        e1.compareTo(e2);
        e2.myDateTime=e1.myDateTime.addDays(1);
        e1.compareTo(e2);

        NEU_ChampEmail ce = new NEU_ChampEmail();
        Messaging.InboundEmail  mail = new Messaging.InboundEmail();
        mail.subject ='test'; 
        List<String> new_address = new List<String>();
        new_address.add('test');
        new_address.add('test2');
        mail.toAddresses = new_address;
        mail.fromAddress = 'test@neurored.com';
        mail.plainTextBody='DDD';
        ce.handleInboundEmail(mail, null);

        mail.fromAddress = 'test@test.neurored.com';
        mail.plainTextBody='DDD\r\nDDD\r\nDDD';
        ce.handleInboundEmail(mail, null);

        mail.plainTextBody='+CIMFSA:A+\r\nDDD\r\nDDD';
        ce.handleInboundEmail(mail, null);

        mail.plainTextBody='+CIMFSA:7+\r\nDDD\r\nDDD';
        ce.handleInboundEmail(mail, null);

        mail.plainTextBody='+CIMFSA:15+\r\nDDD\r\nDDD';
        ce.handleInboundEmail(mail, null);

        mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/\r\nDDD';
        ce.handleInboundEmail(mail, null);

        mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/\r\nRCS/01XXX000/DDD';
        ce.handleInboundEmail(mail, null);

        mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/\r\nRCS/DDJAN0000/DDD';
        ce.handleInboundEmail(mail, null);

        mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/\r\nDEP/FLNUM/01JA/DDDDDD/S0101-X/0101';
        ce.handleInboundEmail(mail, null);

        mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/T1L23\r\nDEP/FLNUM/01JAN/DDDDDD/S010/0101';
        ce.handleInboundEmail(mail, null);

        mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/T1K23';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-P/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-N/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-S/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-T/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-A/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-B/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-C/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-D/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-E/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-F/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-G/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-H/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-I/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-J/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-K/0101';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-L/0101';
        ce.handleInboundEmail(mail, null);

        mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/\r\nRCS/01XXX0000/DDD';
        ce.handleInboundEmail(mail, null);

        mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/\r\nRCS/01DEC0000/DDD';
        ce.handleInboundEmail(mail, null);
        List<Account> list_accounts = NEU_Utils.getAccounts('Customer,');
        Account a = list_accounts[0];
        insert a;
        Shipment__c ship = new Shipment__c(Name = 'SP-TS-0001', Account_for__c = a.Id, Freight_Mode__c='Air', Service_Mode__c ='Import',MAWB_Number__c='012345678901', Only_Warehouse_Service__c = true);
        insert ship;
        Shipment_Program__c ship_prog = new Shipment_Program__c(Number_of_Containers__c =2, Flight_Number__c='10',MAWB_Number__c='012345678901');
        insert ship_prog;

        mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/';
        mail.plainTextBody+='\r\nRCS/01JAN0000/DDD/T1K23';
        mail.plainTextBody+='\r\nRCS/01JAN0000/DDD/T1L23/DDD';
        mail.plainTextBody+='\r\nRCT/DD/01JAN0000/DDD/T1/DDD/DDD';
        mail.plainTextBody+='\r\nRCF/FLNUM/01JAN0000/DDD/T1';
        mail.plainTextBody+='\r\nBKD/FLNUM/01JAN/DDDDDD/T1';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/T1';
        mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/T1/S0101-X';
        mail.plainTextBody+='\r\nDEP/FLNUM/01JAN/DDDDDD/T1';
        mail.plainTextBody+='\r\nDEP/FLNUM/01JAN/DDDDDD/T1/S0101-X';
        mail.plainTextBody+='\r\nPRE/FLNUM/01JAN/DDDDDD/T1';
        mail.plainTextBody+='\r\nPRE/FLNUM/01JAN/DDDDDD/T1/S0101-X';
        mail.plainTextBody+='\r\nTFD/DD/01JAN0000/DDD/T1/DDD/DDD/DDD';
        mail.plainTextBody+='\r\nNFD/01JAN0000/DDD/T1/DDD';
        mail.plainTextBody+='\r\nAWD/01JAN0000/DDD/T1/DDD';
        mail.plainTextBody+='\r\nCCD/01JAN0000/DDD/T1';
        mail.plainTextBody+='\r\nDLV/01JAN0000/DDD/T1/DDD';
        mail.plainTextBody+='\r\nDIS/FLNUM/01JAN0000/DDD/DDD/T1';
        mail.plainTextBody+='\r\nCRC/01JAN0000/DDD/T1/FLNUM';
        mail.plainTextBody+='\r\nDDL/01JAN0000/DDD/T1/DDD';
        mail.plainTextBody+='\r\nTGC/01JAN0000/DDD/T1';
        mail.plainTextBody+='\r\nARR/FLNUM/01JAN0000/DDD/T1';
        mail.plainTextBody+='\r\nAWR/FLNUM/01JAN0000/DDD/T1';
        mail.plainTextBody+='\r\nFOH/01JAN0000/DDD/T1/DDD';
        ce.handleInboundEmail(mail, null);

    }
	static testMethod void test_NEU_TRAXON_ChampEmail()
    {
    	NEU_Traxon_ChampEmail.eventData e1=new NEU_Traxon_ChampEmail.eventData();
    	NEU_Traxon_ChampEmail.eventData e2=new NEU_Traxon_ChampEmail.eventData();
    	e1.compareTo(e2);
    	e1.myDateTime=system.now();
    	e1.compareTo(e2);
    	e1.myDateTime=null;
    	e2.myDateTime=system.now();
    	e1.compareTo(e2);
    	e1.myDateTime=e2.myDateTime.addDays(1);
    	e1.compareTo(e2);
    	e2.myDateTime=e1.myDateTime.addDays(1);
    	e1.compareTo(e2);
    	
    	NEU_Traxon_ChampEmail ce = new NEU_Traxon_ChampEmail();
    	Messaging.InboundEmail  mail = new Messaging.InboundEmail();
    	mail.subject ='test'; 
    	List<String> new_address = new List<String>();
    	new_address.add('test');
    	new_address.add('test2');
    	mail.toAddresses = new_address;
    	mail.fromAddress = 'test@neurored.com';
    	mail.plainTextBody='DDD';
    	ce.handleInboundEmail(mail, null);

    	mail.fromAddress = 'test@test.neurored.com';
    	mail.plainTextBody='DDD\r\nDDD\r\nDDD';
    	ce.handleInboundEmail(mail, null);

    	mail.plainTextBody='+CIMFSA:A+\r\nDDD\r\nDDD';
    	ce.handleInboundEmail(mail, null);

    	mail.plainTextBody='+CIMFSA:7+\r\nDDD\r\nDDD';
    	ce.handleInboundEmail(mail, null);

    	mail.plainTextBody='+CIMFSA:15+\r\nDDD\r\nDDD';
    	ce.handleInboundEmail(mail, null);

    	mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/\r\nDDD';
    	ce.handleInboundEmail(mail, null);

    	mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/\r\nRCS/01XXX000/DDD';
    	ce.handleInboundEmail(mail, null);

    	mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/\r\nRCS/DDJAN0000/DDD';
    	ce.handleInboundEmail(mail, null);

    	mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/\r\nDEP/FLNUM/01JA/DDDDDD/S0101-X/0101';
    	ce.handleInboundEmail(mail, null);

    	mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/T1L23\r\nDEP/FLNUM/01JAN/DDDDDD/S010/0101';
    	ce.handleInboundEmail(mail, null);

    	mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/T1K23';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-P/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-N/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-S/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-T/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-A/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-B/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-C/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-D/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-E/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-F/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-G/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-H/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-I/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-J/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-K/0101';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/DDD/S0101-L/0101';
    	ce.handleInboundEmail(mail, null);

    	mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/\r\nRCS/01XXX0000/DDD';
    	ce.handleInboundEmail(mail, null);

    	mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/\r\nRCS/01DEC0000/DDD';
    	ce.handleInboundEmail(mail, null);

        Account a = new Account(Name = 'Test acount ', RecordTypeId = Schema.SobjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId(),Business_Area__c = 'Sales');
        insert a;  
		NEU_StaticVariableHelper.setBoolean1(true);
		User userT = [SELECT Id, ManagerId, UserRole.Name FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
		Rol_Margen__c rolMargen = TestDataFactory.createRolMargen(userT.UserRole.Name); // Director Comercial, Director Regional

		Customer_Quote__c importexportquoteR = new Customer_Quote__c();
		String recordTypeId = Schema.SObjectType.Customer_Quote__c.getRecordTypeInfosByName().get('Import-Export Quote').getRecordTypeId();
		importexportquoteR.RecordTypeId = recordTypeId;
		importexportquoteR.Name = '.';
		importexportquoteR.Account_for__c = a.Id;
		importexportquoteR.Team__c = 'P2G';
		importexportquoteR.Quotation_Status__c = 'Quote being prepared';
		importexportquoteR.Customer_Reference__c = 'hola soy una prueba';
		importexportquoteR.Valid_From__c = System.today();
		importexportquoteR.Valid_Until__c = System.today();
		importexportquoteR.Comercio_Exterior__c = 'No';
		importexportquoteR.Freight_Mode__c = 'Road';
		importexportquoteR.Service_Mode__c = 'NATIONAL';
		importexportquoteR.Service_Type__c = 'FTL';
		importexportquoteR.CurrencyIsoCode = 'MXN';
		importexportquoteR.ETD__c = Date.today();
		importexportquoteR.ETA__c = Date.today();
		importexportquoteR.Community_Status__c = 'CUSTOMER CREATED';
		importexportquoteR.Pricing_Executive__c = userT.Id;
		importexportquoteR.Operations_Exec__c = userT.Id;
		insert importexportquoteR;


        Shipment__c ship = new Shipment__c(Name = 'SP-TS-0009', Account_for__c = a.Id, Freight_Mode__c='Sea', Service_Mode__c ='Import', Service_Type__c='LCL Cargo', MAWB_Number__c='');
        insert ship;
	    //Shipment_Program__c ship_prog = new Shipment_Program__c(Number_of_Containers__c =2, Flight_Number__c='10',MAWB_Number__c='012345678901');
	    //insert ship_prog; 

    	mail.plainTextBody='+CIMFSA:15+\r\n012345678901DDDDDD/';
    	mail.plainTextBody+='\r\nRCS/01JAN0000/DDD/T1K23';
    	mail.plainTextBody+='\r\nRCS/01JAN0000/DDD/T1L23/DDD';
    	mail.plainTextBody+='\r\nRCT/DD/01JAN0000/DDD/T1/DDD/DDD';
    	mail.plainTextBody+='\r\nRCF/FLNUM/01JAN0000/DDD/T1';
    	mail.plainTextBody+='\r\nBKD/FLNUM/01JAN/DDDDDD/T1';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/T1';
    	mail.plainTextBody+='\r\nMAN/FLNUM/01JAN/DDDDDD/T1/S0101-X';
    	mail.plainTextBody+='\r\nDEP/FLNUM/01JAN/DDDDDD/T1';
    	mail.plainTextBody+='\r\nDEP/FLNUM/01JAN/DDDDDD/T1/S0101-X';
    	mail.plainTextBody+='\r\nPRE/FLNUM/01JAN/DDDDDD/T1';
    	mail.plainTextBody+='\r\nPRE/FLNUM/01JAN/DDDDDD/T1/S0101-X';
    	mail.plainTextBody+='\r\nTFD/DD/01JAN0000/DDD/T1/DDD/DDD/DDD';
    	mail.plainTextBody+='\r\nNFD/01JAN0000/DDD/T1/DDD';
    	mail.plainTextBody+='\r\nAWD/01JAN0000/DDD/T1/DDD';
    	mail.plainTextBody+='\r\nCCD/01JAN0000/DDD/T1';
    	mail.plainTextBody+='\r\nDLV/01JAN0000/DDD/T1/DDD';
    	mail.plainTextBody+='\r\nDIS/FLNUM/01JAN0000/DDD/DDD/T1';
    	mail.plainTextBody+='\r\nCRC/01JAN0000/DDD/T1/FLNUM';
    	mail.plainTextBody+='\r\nDDL/01JAN0000/DDD/T1/DDD';
    	mail.plainTextBody+='\r\nTGC/01JAN0000/DDD/T1';
    	mail.plainTextBody+='\r\nARR/FLNUM/01JAN0000/DDD/T1';
    	mail.plainTextBody+='\r\nAWR/FLNUM/01JAN0000/DDD/T1';
    	mail.plainTextBody+='\r\nFOH/01JAN0000/DDD/T1/DDD';
    	ce.handleInboundEmail(mail, null);
    }
    
}