respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Air_Waybill__c.object
<CustomObject>
    <fields>
        <fullName>Airline_Code_Number__c</fullName>
        <formula>Carrier_Account__r.Airline_Code_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>1A</inlineHelpText>
        <label>Carrier Code Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alternative_Fligtht_1__c</fullName>
        <label>Alternative Fligtht 1</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alternative_Fligtht_2__c</fullName>
        <label>Alternative Fligtht 2</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carrier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>1C</inlineHelpText>
        <label>Carrier Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Supply Chain Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Air_Waybills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hide_House_Totals__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide House Totals</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>House_Reference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>House Reference</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Waybill_Consolidation__c.Waybill__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Waybill_Consolidation__c</referenceTo>
        <relationshipLabel>Waybills</relationshipLabel>
        <relationshipName>Waybills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Charges_House__c</fullName>
        <label>Other Charges House</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Other_Charges_Master__c</fullName>
        <label>Other Charges Master</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Shipments_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipments Program</label>
        <referenceTo>Shipment_Program__c</referenceTo>
        <relationshipName>Air_Waybills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_House__c</fullName>
        <label>Tax House</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Master__c</fullName>
        <label>Tax Master</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Other_Charges_Due_Agent_House__c</fullName>
        <label>Total Other Charges Due Agent House</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Other_Charges_Due_Agent_Master__c</fullName>
        <label>Total Other Charges Due Agent Master</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Other_Charges_Due_House__c</fullName>
        <label>Total Other Charges Due House</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Other_Charges_Due_Master__c</fullName>
        <label>Total Other Charges Due Master</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Valuation_Charge_House__c</fullName>
        <label>Valuation Charge House</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Valuation_Charge_Master__c</fullName>
        <label>Valuation Charge Master</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Weight_Charge_House__c</fullName>
        <label>Weight Charge House</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Weight_Charge_Master__c</fullName>
        <label>Weight Charge Master</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Waybill</label>
    <nameField>
        <label>Waybill Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waybills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Associated_Document__c.object
<CustomObject>
    <description>Import space for documents created and associated to an Account, Import-Export and/or shipment.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Air_Waybill__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Air_Waybill</label>
        <referenceTo>Air_Waybill__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consolidation_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipments Program</label>
        <referenceTo>Shipment_Program__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acuse</fullName>
                </value>
                <value>
                    <fullName>Bill of Lading</fullName>
                </value>
                <value>
                    <fullName>Guía Consolidado</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Import Permit</fullName>
                </value>
                <value>
                    <fullName>Customer Order</fullName>
                </value>
                <value>
                    <fullName>Order Confirmation</fullName>
                </value>
                <value>
                    <fullName>Technical Specifications</fullName>
                </value>
                <value>
                    <fullName>Proforma Invoice</fullName>
                </value>
                <value>
                    <fullName>Commercial Invoice</fullName>
                </value>
                <value>
                    <fullName>Packaging List</fullName>
                </value>
                <value>
                    <fullName>Shipping Line Instruction</fullName>
                </value>
                <value>
                    <fullName>Transport Delivery Instruction</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Telex</fullName>
                </value>
                <value>
                    <fullName>Op - Licencia</fullName>
                </value>
                <value>
                    <fullName>Op - Tarjeta Circulacion</fullName>
                </value>
                <value>
                    <fullName>Op - Placas Unidad</fullName>
                </value>
                <value>
                    <fullName>Formato de Alta de Proveedor Firmado</fullName>
                </value>
                <value>
                    <fullName>Comprobante de Domicilio</fullName>
                </value>
                <value>
                    <fullName>IFE del Represéntate Legal</fullName>
                </value>
                <value>
                    <fullName>Poliza Vigente y del Prestador</fullName>
                </value>
                <value>
                    <fullName>Opinion de Cumplimiento Ante el SAT</fullName>
                </value>
                <value>
                    <fullName>Convenio</fullName>
                </value>
                <value>
                    <fullName>Alta del SAT</fullName>
                </value>
                <value>
                    <fullName>Factura Timbrada</fullName>
                </value>
                <value>
                    <fullName>Perfil de Conductores</fullName>
                </value>
                <value>
                    <fullName>Negociación de tarifas</fullName>
                </value>
                <value>
                    <fullName>MC Number</fullName>
                </value>
                <value>
                    <fullName>Ejemplo de Acuse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_URL__c</fullName>
        <label>Document URL</label>
        <type>Url</type>
    </fields>
    <label>Associated Document</label>
    <nameField>
        <label>Associated Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_Air_Waybills_save_PDF.cls
public with sharing class NEU_Air_Waybills_save_PDF 
{
    public Air_Waybill__c record {get;set;}
    public string language {get;set;}
    public String errores {get;set;}
    public String id_waybill {get;set;}
    public List<Air_Waybill_Line__c> lines {get;set;}
    public List<Air_Waybill_Line__c> lines_house {get;set;} 
    
    public string awb_type 
    {
        get 
        {
          if (awb_type == null)
          	awb_type=ApexPages.currentPage().getParameters().get('type');
          return awb_type;
        }
        set;
    }    
    
    public Document documento_asociado 
    {
        get 
        {
          if (documento_asociado == null)
            documento_asociado = new Document();
          return documento_asociado;
        }
        set;
    }
    
    public boolean displayBackground
	{
		get 
		{
			if (displayBackground == null)
				displayBackground = true;
			return displayBackground;
		}
		set;
	}
	
    public void updateFilters()
    {
    }
    
    ApexPages.StandardController con;
            
    public NEU_Air_Waybills_save_PDF(ApexPages.StandardController stdController) 
    {

        con = stdController;
        
        try { 
        	record = [select Id, Name, Carrier_Account__c, Shipments_Program__c, Weight_Charge_House__c, 
        				Valuation_Charge_House__c, Total_Other_Charges_Due_House__c, Hide_House_Totals__c, 
        				Total_Other_Charges_Due_Agent_House__c, Tax_House__c, Other_Charges_House__c, 
        				Weight_Charge_Master__c, Valuation_Charge_Master__c, Total_Other_Charges_Due_Master__c, 
        				Total_Other_Charges_Due_Agent_Master__c, Tax_Master__c, Other_Charges_Master__c, 
        				House_Reference__c, Alternative_Fligtht_1__c, Alternative_Fligtht_2__c, Airline_Code_Number__c 
        				from Air_Waybill__c where Id =: con.getRecord().Id];
        } catch( Exception ee) { 
            record = new Air_Waybill__c();
        }
        
       lines = [SELECT Id, Name, Description__c, Rate_Charge_Master__c, Rate_Charge__c, Chargeable_Weight_Master__c, 
       			Min_Amount_Master__c, House_Reference__c FROM Air_Waybill_Line__c WHERE Air_Waybill__c =: record.Id
       			order by Name];
       
       lines_house = [SELECT Id, Name, Description__c ,Rate_Charge_House__c, Rate_Charge__c, Chargeable_Weight_House__c, 
       				Min_Amount_House__c, House_Reference__c FROM Air_Waybill_Line__c WHERE Air_Waybill__c =: record.Id 
       				and House_Reference__c=:record.House_Reference__c order by Name];
       			
		id_waybill = record.Id;               
    }
    
    public PageReference clear_values()
    {
    	try 
    	{
    		//HOUSE
    		if(awb_type == 'house') 
    		{
    			record.Weight_Charge_House__c = null;
    			record.Valuation_Charge_House__c = null;
    			record.Tax_House__c = null;
    			record.Total_Other_Charges_Due_Agent_House__c = null;
    			record.Total_Other_Charges_Due_House__c = null;
    		}
    		//MASTER
    		if(awb_type == 'master') 
    		{
    			record.Weight_Charge_Master__c = null;
    			record.Valuation_Charge_Master__c = null;
    			record.Tax_Master__c = null;
    			record.Total_Other_Charges_Due_Agent_Master__c = null;
    			record.Total_Other_Charges_Due_Master__c = null;
    		}
    		update record; 
    		
    	} catch( Exception ee) {}
    	
    	PageReference pdf = null;
	    pdf = Page.NEU_Air_Waybills_save_PDF;
	    pdf.getParameters().put('type',awb_type);
	    pdf.getParameters().put('id',record.Id);
	    if(displayBackground)
        {
        	pdf.getParameters().put('background','true'); 
        }
        else
        {
        	pdf.getParameters().put('background','false');
        }	       	    
	    return pdf;
    }
    
    public PageReference refrescar_pdf()
    {
    	try 
    	{
    		//HOUSE
    		if(record.Weight_Charge_House__c != null || record.Valuation_Charge_House__c != null || record.Tax_House__c != null 
    		|| record.Total_Other_Charges_Due_Agent_House__c != null || record.Total_Other_Charges_Due_House__c != null) 
    		{
    			record.Weight_Charge_House__c=(record.Weight_Charge_House__c != null ? NEU_Utils.safeDecimal(record.Weight_Charge_House__c) : 0);
    			record.Valuation_Charge_House__c=(record.Valuation_Charge_House__c != null ? NEU_Utils.safeDecimal(record.Valuation_Charge_House__c) : 0);
    			record.Tax_House__c=(record.Tax_House__c != null ? NEU_Utils.safeDecimal(record.Tax_House__c) : 0);
    			record.Total_Other_Charges_Due_Agent_House__c=(record.Total_Other_Charges_Due_Agent_House__c != null ? NEU_Utils.safeDecimal(record.Total_Other_Charges_Due_Agent_House__c) : 0);
    			record.Total_Other_Charges_Due_House__c=(record.Total_Other_Charges_Due_House__c != null ? NEU_Utils.safeDecimal(record.Total_Other_Charges_Due_House__c) : 0);
    		}
    		//MASTER
    		if(record.Weight_Charge_Master__c != null || record.Valuation_Charge_Master__c != null || record.Tax_Master__c != null 
    		|| record.Total_Other_Charges_Due_Agent_Master__c != null || record.Total_Other_Charges_Due_Master__c != null) 
    		{
    			record.Weight_Charge_Master__c=(record.Weight_Charge_Master__c != null ? NEU_Utils.safeDecimal(record.Weight_Charge_Master__c) : 0);
    			record.Valuation_Charge_Master__c=(record.Valuation_Charge_Master__c != null ? NEU_Utils.safeDecimal(record.Valuation_Charge_Master__c) : 0);
    			record.Tax_Master__c=(record.Tax_Master__c != null ? NEU_Utils.safeDecimal(record.Tax_Master__c) : 0);
    			record.Total_Other_Charges_Due_Agent_Master__c=(record.Total_Other_Charges_Due_Agent_Master__c != null ? NEU_Utils.safeDecimal(record.Total_Other_Charges_Due_Agent_Master__c) : 0);
    			record.Total_Other_Charges_Due_Master__c=(record.Total_Other_Charges_Due_Master__c != null ? NEU_Utils.safeDecimal(record.Total_Other_Charges_Due_Master__c) : 0);
    		}
    		//Alternative_Fligtht
    		if(record.Alternative_Fligtht_1__c != null || record.Alternative_Fligtht_2__c != null)
    		{
    			record.Alternative_Fligtht_1__c = (record.Alternative_Fligtht_1__c != null ? NEU_Utils.safeString(record.Alternative_Fligtht_1__c) : '');
    			record.Alternative_Fligtht_2__c = (record.Alternative_Fligtht_2__c != null ? NEU_Utils.safeString(record.Alternative_Fligtht_2__c) : '');
    		} 
    		update record; 
    		if(awb_type == 'house') 
    			update lines_house;
    		if(awb_type == 'master') 
    			update lines;
    		
    	} catch( Exception ee) {}
    	
    	PageReference pdf = null;
	    pdf = Page.NEU_Air_Waybills_save_PDF;
	    pdf.getParameters().put('type',awb_type);
	    pdf.getParameters().put('id',record.Id);
	    if(displayBackground)
        {
        	pdf.getParameters().put('background','true'); 
        }
        else
        {
        	pdf.getParameters().put('background','false');
        }	       	    
	    return pdf;
    }
    
    public PageReference return_page()
    {
        return con.view();
    }
    
    public PageReference crear()
    {
        PageReference pdf = null;
        pdf = Page.NEU_Air_Waybills_PDF;
        pdf.getParameters().put('id',record.Id);        
        pdf.getParameters().put('type',awb_type);
        
        if(displayBackground)
        {
        	pdf.getParameters().put('background','true'); 
        }
        else
        {
        	pdf.getParameters().put('background','false');
        }
        
        Blob body;
        
        try 
        {
            body = pdf.getContent();
        } 
        catch (VisualforceException e) { body = Blob.valueOf('Some Text');}
        
        List<Folder> directorio = new List<Folder>();
        directorio = [Select Id, Name from Folder where Name =:'Air Waybill'];
        documento_asociado.Body = body;
        documento_asociado.Name = 'Waybill_'+record.name +'.pdf';
        documento_asociado.AuthorId = UserInfo.getUserId();
        if(directorio.size()>0)
           documento_asociado.FolderId = directorio[0].Id;
        documento_asociado.IsPublic = true; 
        
        try 
        {
            if(documento_asociado.Name != '' && documento_asociado.Name != null)
                insert documento_asociado;
        }  
        catch (DMLException e)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error in File Upload.'));
        }
        
        Associated_Document__c new_document = new Associated_Document__c();
        new_document.Account__c = record.Carrier_Account__c;
        new_document.Name = (awb_type == 'house' ? 'House ' : 'Master ') + 'Waybill '+record.Name +'.pdf';
        new_document.Air_Waybill__c =record.Id;
        new_document.Document_Type__c = 'Waybill';
        if(record.Shipments_Program__c != null || Test.isRunningTest())
            new_document.Consolidation_Program__c =record.Shipments_Program__c;
            
        new_document.Document_URL__c = '/servlet/servlet.ImageServer?id='+documento_asociado.Id+'&oid=' + UserInfo.getOrganizationId(); 
        
        try
        {
            insert new_document;
            return new PageReference('/'+record.Id);
        }
        catch(Exception ex){return null;}
             
    }
    
    public void fail()
    { 
    	if(record.House_Reference__c==null)
		{
			errores='House Reference is null in the Waybill.';
			id_waybill = '';
			return;	
		}
    	for(Air_Waybill_Line__c awl: lines)
		{
			if(awl.Rate_Charge__c==null)
			{
				errores='Rate/Charge is null in Line '+awl.Name+'.';
				id_waybill = '';
				return;	
			}
			if(awl.House_Reference__c==null)
			{
				errores='House Reference is null in Line '+awl.Name+'.';
				id_waybill = '';
				return;	
			}
		}		
    }
}