respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Associated_Document__c.object
<CustomObject>
    <description>Import space for documents created and associated to an Account, Import-Export and/or shipment.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Document_Description__c</fullName>
        <label>Document Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Reference__c</fullName>
        <label>Document Reference</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acuse</fullName>
                </value>
                <value>
                    <fullName>Bill of Lading</fullName>
                </value>
                <value>
                    <fullName>Guía Consolidado</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Import Permit</fullName>
                </value>
                <value>
                    <fullName>Customer Order</fullName>
                </value>
                <value>
                    <fullName>Order Confirmation</fullName>
                </value>
                <value>
                    <fullName>Technical Specifications</fullName>
                </value>
                <value>
                    <fullName>Proforma Invoice</fullName>
                </value>
                <value>
                    <fullName>Commercial Invoice</fullName>
                </value>
                <value>
                    <fullName>Packaging List</fullName>
                </value>
                <value>
                    <fullName>Shipping Line Instruction</fullName>
                </value>
                <value>
                    <fullName>Transport Delivery Instruction</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Telex</fullName>
                </value>
                <value>
                    <fullName>Op - Licencia</fullName>
                </value>
                <value>
                    <fullName>Op - Tarjeta Circulacion</fullName>
                </value>
                <value>
                    <fullName>Op - Placas Unidad</fullName>
                </value>
                <value>
                    <fullName>Formato de Alta de Proveedor Firmado</fullName>
                </value>
                <value>
                    <fullName>Comprobante de Domicilio</fullName>
                </value>
                <value>
                    <fullName>IFE del Represéntate Legal</fullName>
                </value>
                <value>
                    <fullName>Poliza Vigente y del Prestador</fullName>
                </value>
                <value>
                    <fullName>Opinion de Cumplimiento Ante el SAT</fullName>
                </value>
                <value>
                    <fullName>Convenio</fullName>
                </value>
                <value>
                    <fullName>Alta del SAT</fullName>
                </value>
                <value>
                    <fullName>Factura Timbrada</fullName>
                </value>
                <value>
                    <fullName>Perfil de Conductores</fullName>
                </value>
                <value>
                    <fullName>Negociación de tarifas</fullName>
                </value>
                <value>
                    <fullName>MC Number</fullName>
                </value>
                <value>
                    <fullName>Ejemplo de Acuse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_URL__c</fullName>
        <label>Document URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Supplier_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Quote/Order</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier_Quote__c.Supply_Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Supply_Project__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier_Quote__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Request_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Request (RFP)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier_Request_RFP__c.Supply_Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Supply_Project__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier_Request_RFP__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supply_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supply Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supply_Project__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supply_Project__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Document</label>
    <nameField>
        <label>Associated Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Supplier_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Suppliers_Quotes_Buyer_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Request_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Request</label>
        <referenceTo>Supplier_Request_RFP__c</referenceTo>
        <relationshipLabel>Suppliers Quotes/Orders</relationshipLabel>
        <relationshipName>Supplier_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <label>Supplier</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Supply Chain Partner, Purchase Agent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Suppliers Quotes/Orders (Supplier)</relationshipLabel>
        <relationshipName>Suppliers_Quotes_Supplier</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Supply_Project_Number__c</fullName>
        <formula>Supply_Project__r.Supply_Project_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>As specified in &quot;Supply Project Number&quot; inside &quot;Supply Project&quot;</inlineHelpText>
        <label>Supply Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supply_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Supply Project</label>
        <referenceTo>Supply_Project__c</referenceTo>
        <relationshipName>Suppliers_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Quote/Order</label>
    <nameField>
        <displayFormat>SQO# {YYYY}-{000000}</displayFormat>
        <label>Supplier Quote/Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Quotes/Orders</pluralLabel>
    <recordTypes>
        <fullName>Supplier_Quote</fullName>
        <active>true</active>
        <label>Supplier Quote</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_Associated_10Documents_Request.cls
public with sharing class NEU_Associated_10Documents_Request {

     public List<Associated_Document__c> document {get;set;}
     public String Document_type {get;set;}
     public string Document_Description {get;set;}
      
     public string type_document = null;
     
     public string gettype_document()
     {
        List<Supplier_Quote__c> Supplier_Quote = [select Id, Name,Customer__c, Supplier__c,Supply_Project__c,
        Supplier_Request_RFP__c, Supply_Project__r.Supply_Project_Number__c,
        Supplier_Request_RFP__r.Document_1_Type__c, Supplier_Request_RFP__r.Document_2_Type__c, 
        Supplier_Request_RFP__r.Document_3_Type__c, Supplier_Request_RFP__r.Document_4_Type__c, 
        Supplier_Request_RFP__r.Document_5_Type__c, Supplier_Request_RFP__r.Document_6_Type__c, 
        Supplier_Request_RFP__r.Document_7_Type__c, Supplier_Request_RFP__r.Document_8_Type__c, 
        Supplier_Request_RFP__r.Document_9_Type__c, Supplier_Request_RFP__r.Document_10_Type__c, 
        Supply_Project_Number__c  from Supplier_Quote__c where id =: ApexPages.currentPage().getParameters().get('id')];
        if(Supplier_Quote.size() > 0)
        {
            if(ApexPages.currentPage().getParameters().get('docu') != null)
            {
                if(ApexPages.currentPage().getParameters().get('docu') == '1')
                    Document_type = Supplier_Quote[0].Supplier_Request_RFP__r.Document_1_Type__c;
                if(ApexPages.currentPage().getParameters().get('docu') == '2')
                    Document_type = Supplier_Quote[0].Supplier_Request_RFP__r.Document_2_Type__c;
                if(ApexPages.currentPage().getParameters().get('docu') == '3')
                    Document_type = Supplier_Quote[0].Supplier_Request_RFP__r.Document_3_Type__c;
                if(ApexPages.currentPage().getParameters().get('docu') == '4')
                    Document_type = Supplier_Quote[0].Supplier_Request_RFP__r.Document_4_Type__c;
                if(ApexPages.currentPage().getParameters().get('docu') == '5')
                    Document_type = Supplier_Quote[0].Supplier_Request_RFP__r.Document_5_Type__c;
                if(ApexPages.currentPage().getParameters().get('docu') == '6')
                    Document_type = Supplier_Quote[0].Supplier_Request_RFP__r.Document_6_Type__c;
                if(ApexPages.currentPage().getParameters().get('docu') == '7')
                    Document_type = Supplier_Quote[0].Supplier_Request_RFP__r.Document_7_Type__c;
                if(ApexPages.currentPage().getParameters().get('docu') == '8')
                    Document_type = Supplier_Quote[0].Supplier_Request_RFP__r.Document_8_Type__c;
                if(ApexPages.currentPage().getParameters().get('docu') == '9')
                    Document_type = Supplier_Quote[0].Supplier_Request_RFP__r.Document_9_Type__c;
                if(ApexPages.currentPage().getParameters().get('docu') == '10')
                    Document_type = Supplier_Quote[0].Supplier_Request_RFP__r.Document_10_Type__c;
            }
        }
        this.type_document = Document_type;
        return type_document;
     }
     
     /*public Document documento_asociado 
    {
        get 
        {
          if (documento_asociado == null)
            documento_asociado = new Document();
          return documento_asociado;
        }
        set;
    }*/
    public transient Blob documento_asociado{get;set;}
    public transient String documento_asociadoName{get;set;}
    
     public PageReference Upload_Documents()
    {
        List<Supplier_Quote__c> Supplier_Quote = [select Id, Name,Customer__c, Supplier__c,Supply_Project__c,
        Supplier_Request_RFP__c, Supply_Project__r.Supply_Project_Number__c,
        Supplier_Request_RFP__r.Document_1_Type__c, Supplier_Request_RFP__r.Document_2_Type__c, 
        Supplier_Request_RFP__r.Document_3_Type__c, Supplier_Request_RFP__r.Document_4_Type__c, 
        Supplier_Request_RFP__r.Document_5_Type__c, Supplier_Request_RFP__r.Document_6_Type__c, 
        Supplier_Request_RFP__r.Document_7_Type__c, Supplier_Request_RFP__r.Document_8_Type__c, 
        Supplier_Request_RFP__r.Document_9_Type__c, Supplier_Request_RFP__r.Document_10_Type__c, 
        Supply_Project_Number__c  from Supplier_Quote__c where id =: ApexPages.currentPage().getParameters().get('id')];

        List<Folder> directorio = new List<Folder>();
        
        directorio = [Select Id, Name from Folder where Name =: Document_type];//Document_type
        if(directorio.size()<1)
        {
            directorio = [Select Id, Name from Folder where Name =:'Associated Documents'];
            
        }
        
        //DOCUMENTO1
         Document document=new Document();
        if(documento_asociadoName != '' && documento_asociadoName != null)
        {
        	document.Body=documento_asociado;
            document.Name=documento_asociadoName;
            document.AuthorId = UserInfo.getUserId();
            if(directorio.size() > 0){
                document.FolderId = directorio[0].Id;
            }
            document.IsPublic = true; 
        }
        
        try 
        {
            if(documento_asociadoName != '' && documento_asociadoName != null)
                insert document;
        }  
        catch (DMLException e)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error in File Upload.'));
        }
        
    
        Associated_Document__c new_document= new Associated_Document__c();
        if(documento_asociadoName != '' && documento_asociadoName != null)
        {
            new_document.Document_URL__c = Site.getBaseURL()+'/servlet/servlet.ImageServer?id='+document.Id+'&oid=' + UserInfo.getOrganizationId();
            string nombredeldocumento = documento_asociadoName;
            Integer indiceDePunto = nombredeldocumento.indexOf('.');
            new_document.Name=nombredeldocumento.substring(0, indiceDePunto);
        }
        
        new_document.Document_Reference__c=(Supplier_Quote.size() > 0 ? Supplier_Quote[0].Supply_Project_Number__c + ' - ':'')+'Document '+ApexPages.currentPage().getParameters().get('docu');//poner documento 10 
        new_document.Document_Description__c = Document_Description;
        new_document.Document_Type__c=Document_type;// poner mismo que supply porject 
        
        if(Supplier_Quote.size() > 0)
        {
            new_document.Account__c = Supplier_Quote[0].Supplier__c; 
            new_document.Supplier_Quote__c =Supplier_Quote[0].Id;
            new_document.Supplier_Request_RFP__c =Supplier_Quote[0].Supplier_Request_RFP__c;
          //  new_document.Supply_Project__c =Supplier_Quote[0].Supply_Project__c;
        }
        
        try
        {
            insert new_document;
            PageReference pgReturnPage;
            String returnUrl = Site.getBaseURL() +'/apex/NEU_Associated_10Documents_Request?redirec=true';
            pgReturnPage = new PageReference(returnUrl);
            pgReturnPage.setRedirect(true);
            return pgReturnPage;

        }
        catch(Exception e){ return null;}
    }
    
}