respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Associated_Document__c.object
<CustomObject>
    <description>Import space for documents created and associated to an Account, Import-Export and/or shipment.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Available_for_Community__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available for Community</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_URL__c</fullName>
        <label>Document URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Warehouse_Exit_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Warehouse Exit Order</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Warehouse_Exit_Order__c.Account_for_Customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Warehouse_Exit_Order__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Document</label>
    <nameField>
        <label>Associated Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Warehouse__c.object
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_GenerateWEDocExitOrderSave.cls
public with sharing class NEU_GenerateWEDocExitOrderSave
{
    public Warehouse_Exit_Order__c record {get;set;}
    public Document documento_asociado 
    {
        get 
        {
          if (documento_asociado == null)
            documento_asociado = new Document();
          return documento_asociado;
        }
        set;
    }
    
    ApexPages.StandardController con;
            
    public NEU_GenerateWEDocExitOrderSave(ApexPages.StandardController stdController) 
    {
        con = stdController;
        
        try 
        { 
        	record = [select Id, Name, Warehouse__c, Account_for_Customer__c
        	from Warehouse_Exit_Order__c where id =: con.getRecord().id];
        } 
        catch(Exception ee){record = new Warehouse_Exit_Order__c();}
    }
    
    public PageReference crear()
    {
        PageReference pdf = Page.NEU_GenerateWEDocExitOrder;
        pdf.getParameters().put('id',record.Id);
            
        Blob body;
        
        try 
        {
            body = pdf.getContent();
        } 
        catch(VisualforceException e){body = Blob.valueOf('Some Text');}
        
        List<Folder> directorio = [select Id, Name from Folder where Name =:'Associated Documents'];
        documento_asociado.Body = body;
        documento_asociado.Name = record.Name +'_Warehouse_Embarque.pdf';
        documento_asociado.AuthorId = UserInfo.getUserId();
        if(directorio.size() > 0)
            documento_asociado.FolderId = directorio[0].Id;
        documento_asociado.IsPublic = true; 

        try 
        {
            if(documento_asociado.Name != '' && documento_asociado.Name != null)
                insert documento_asociado;
        }  
        catch (DMLException e){ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error in File Upload.'));}
    
        Associated_Document__c new_document = new Associated_Document__c();
        new_document.Account__c = record.Account_for_Customer__c;
        new_document.Warehouse_Exit_Order__c = record.Id;
        new_document.Available_for_Community__c = true;
        new_document.Name = record.Name +'_Warehouse_Embarque.pdf';
            
        new_document.Document_URL__c = '/servlet/servlet.FileDownload?file='+documento_asociado.Id+'&oid=' + UserInfo.getOrganizationId(); 
        
        try
        {
            insert new_document;
            return new PageReference('/'+record.Id);
        }
        catch(Exception ex){return null;}      
    }
}