respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Associated_Document__c.object
<CustomObject>
    <description>Import space for documents created and associated to an Account, Import-Export and/or shipment.</description>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acuse</fullName>
                </value>
                <value>
                    <fullName>Bill of Lading</fullName>
                </value>
                <value>
                    <fullName>Guía Consolidado</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Import Permit</fullName>
                </value>
                <value>
                    <fullName>Customer Order</fullName>
                </value>
                <value>
                    <fullName>Order Confirmation</fullName>
                </value>
                <value>
                    <fullName>Technical Specifications</fullName>
                </value>
                <value>
                    <fullName>Proforma Invoice</fullName>
                </value>
                <value>
                    <fullName>Commercial Invoice</fullName>
                </value>
                <value>
                    <fullName>Packaging List</fullName>
                </value>
                <value>
                    <fullName>Shipping Line Instruction</fullName>
                </value>
                <value>
                    <fullName>Transport Delivery Instruction</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Telex</fullName>
                </value>
                <value>
                    <fullName>Op - Licencia</fullName>
                </value>
                <value>
                    <fullName>Op - Tarjeta Circulacion</fullName>
                </value>
                <value>
                    <fullName>Op - Placas Unidad</fullName>
                </value>
                <value>
                    <fullName>Formato de Alta de Proveedor Firmado</fullName>
                </value>
                <value>
                    <fullName>Comprobante de Domicilio</fullName>
                </value>
                <value>
                    <fullName>IFE del Represéntate Legal</fullName>
                </value>
                <value>
                    <fullName>Poliza Vigente y del Prestador</fullName>
                </value>
                <value>
                    <fullName>Opinion de Cumplimiento Ante el SAT</fullName>
                </value>
                <value>
                    <fullName>Convenio</fullName>
                </value>
                <value>
                    <fullName>Alta del SAT</fullName>
                </value>
                <value>
                    <fullName>Factura Timbrada</fullName>
                </value>
                <value>
                    <fullName>Perfil de Conductores</fullName>
                </value>
                <value>
                    <fullName>Negociación de tarifas</fullName>
                </value>
                <value>
                    <fullName>MC Number</fullName>
                </value>
                <value>
                    <fullName>Ejemplo de Acuse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_URL__c</fullName>
        <label>Document URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shipment__c.Account_for__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Document</label>
    <nameField>
        <label>Associated Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PAK_AttachmentSHIP.cls
public class PAK_AttachmentSHIP {
    public ApexPages.StandardController C {get;set;}
    public Shipment__c SHIP {get;set;}
    
    public PAK_AttachmentSHIP(ApexPages.StandardController controller){
            C = controller;
            SHIP =(Shipment__c) controller.getRecord(); 
    }
    
    public PageReference SendWS(){
        try{
            Boolean hasFiles = false;
            for(Associated_Document__c ad : [Select Id, Name, Document_URL__c, Document_Type__c, Shipment__r.Name FROM Associated_Document__c WHERE Shipment__c =:SHIP.Id AND Document_Type__c = 'Acuse' AND Document_URL__c LIKE '%https://associateddocs.s3.amazonaws.com%']){
                hasFiles = true;
                String attachName = ad.Name;
                System.debug('ShipId: ' + SHIP.Id);
                System.debug('AttachName: ' + attachName);
                System.debug('URL: ' + ad.Document_URL__c);
                System.debug('TypeDocument: ' + ad.Document_Type__c);
                String Body = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">'+
                                       '<soapenv:Header/>'+
                                       '<soapenv:Body>'+
                                          '<tem:GuardarDocAWS>'+
                                             '<tem:doc_aws>'+
                                                //'<tem:customerId>'+ACC.Id+'</tem:customerId>'+
                                                '<tem:attachmentName>'+attachName+'</tem:attachmentName>'+
                    							'<tem:url>'+ad.Document_URL__c+'</tem:url>'+
                    							'<tem:TypeDocument>'+ad.Document_Type__c+'</tem:TypeDocument>'+
                                                //'<tem:attachment>'+documentoImagenBase64+'</tem:attachment>'+
                        						'<tem:shipmentId>'+SHIP.Id+'</tem:shipmentId>'+
                        						'<tem:shipmentNumber>'+ ad.Shipment__r.Name +'</tem:shipmentNumber>'+
                                             '</tem:doc_aws>'+
                        					 '<tem:nombreUsuario>'+UserInfo.getName()+'</tem:nombreUsuario>'+
                                          '</tem:GuardarDocAWS>'+
                                       '</soapenv:Body>'+
                                    '</soapenv:Envelope>';
                    
                    Http httpProtocol = new Http();
                    HttpRequest request = new HttpRequest();
                    request.setEndpoint('http://35.169.18.187/pakws92/WSDocsAWS.asmx');
                    request.setMethod('POST');
                    request.setTimeout(60000); 
                    request.setHeader('Content-Type', 'text/xml;charset=utf-8');
                    request.setHeader('SOAPAction', 'http://tempuri.org/GuardarDocAWS');
                    request.setBody(Body);
                    HttpResponse response = httpProtocol.send(request);

                    System.debug('-----------'+response.getBody());
                    System.debug('-------------------'+Body);
                    if(response.getStatusCode() == 200){
                        System.debug('Exito----- se envio correctamente'); 
                    }else{
                        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,response.getBody());
                        ApexPages.addMessage(myMsg);
                        return null;
                    }
            }
            if(hasFiles){
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.CONFIRM,'Se envió correctamente. Verificar respuesta de SAP en el área de Responses.');
            	ApexPages.addMessage(myMsg);
            }else{
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'No se encontraron documentos para enviar');
                ApexPages.addMessage(myMsg);
            }
            //ServiceLogger.log('PAK_AttachmentSHIP');           
            return null;
        }catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());
            ApexPages.addMessage(myMsg);            
            return null;
        }
    }

}