respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Associated_Document__c.object
<CustomObject>
    <description>Import space for documents created and associated to an Account, Import-Export and/or shipment.</description>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acuse</fullName>
                </value>
                <value>
                    <fullName>Bill of Lading</fullName>
                </value>
                <value>
                    <fullName>Guía Consolidado</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Import Permit</fullName>
                </value>
                <value>
                    <fullName>Customer Order</fullName>
                </value>
                <value>
                    <fullName>Order Confirmation</fullName>
                </value>
                <value>
                    <fullName>Technical Specifications</fullName>
                </value>
                <value>
                    <fullName>Proforma Invoice</fullName>
                </value>
                <value>
                    <fullName>Commercial Invoice</fullName>
                </value>
                <value>
                    <fullName>Packaging List</fullName>
                </value>
                <value>
                    <fullName>Shipping Line Instruction</fullName>
                </value>
                <value>
                    <fullName>Transport Delivery Instruction</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Telex</fullName>
                </value>
                <value>
                    <fullName>Op - Licencia</fullName>
                </value>
                <value>
                    <fullName>Op - Tarjeta Circulacion</fullName>
                </value>
                <value>
                    <fullName>Op - Placas Unidad</fullName>
                </value>
                <value>
                    <fullName>Formato de Alta de Proveedor Firmado</fullName>
                </value>
                <value>
                    <fullName>Comprobante de Domicilio</fullName>
                </value>
                <value>
                    <fullName>IFE del Represéntate Legal</fullName>
                </value>
                <value>
                    <fullName>Poliza Vigente y del Prestador</fullName>
                </value>
                <value>
                    <fullName>Opinion de Cumplimiento Ante el SAT</fullName>
                </value>
                <value>
                    <fullName>Convenio</fullName>
                </value>
                <value>
                    <fullName>Alta del SAT</fullName>
                </value>
                <value>
                    <fullName>Factura Timbrada</fullName>
                </value>
                <value>
                    <fullName>Perfil de Conductores</fullName>
                </value>
                <value>
                    <fullName>Negociación de tarifas</fullName>
                </value>
                <value>
                    <fullName>MC Number</fullName>
                </value>
                <value>
                    <fullName>Ejemplo de Acuse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Document_URL__c</fullName>
        <label>Document URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shipment__c.Account_for__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Document</label>
    <nameField>
        <label>Associated Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_AttachmentSHIPTest.cls
@isTest(seeAllData=true)
public class P2G_AttachmentSHIPTest {
    
    // Mock de la respuesta HTTP exitosa
    public class MockHttpResponseSuccess implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'text/xml;charset=utf-8');
            res.setBody('<?xml version="1.0" encoding="utf-8"?>' +
                        '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">' +
                        '<soap:Body>' +
                        '<GuardarDocAWSResponse xmlns="http://tempuri.org/">' +
                        '<GuardarDocAWSResult>Documento guardado exitosamente</GuardarDocAWSResult>' +
                        '</GuardarDocAWSResponse>' +
                        '</soap:Body>' +
                        '</soap:Envelope>');
            res.setStatusCode(200);
            res.setStatus('OK');
            return res;
        }
    }
    
    // Mock de la respuesta HTTP fallida
    public class MockHttpResponseError implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'text/xml;charset=utf-8');
            res.setBody('<?xml version="1.0" encoding="utf-8"?>' +
                        '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">' +
                        '<soap:Body>' +
                        '<soap:Fault>' +
                        '<faultcode>soap:Server</faultcode>' +
                        '<faultstring>Error al procesar la solicitud</faultstring>' +
                        '</soap:Fault>' +
                        '</soap:Body>' +
                        '</soap:Envelope>');
            res.setStatusCode(500);
            res.setStatus('Internal Server Error');
            return res;
        }
    }
    
    @isTest
    static void testSendWS_Success() {
        // Configurar mock exitoso
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseSuccess());
        
        // Buscar un Shipment existente que tenga documentos asociados
        Shipment__c shipment = [SELECT Id, Name FROM Shipment__c 
                                WHERE Id IN (SELECT Shipment__c FROM Associated_Document__c 
                                            WHERE Document_Type__c = 'Acuse' 
                                            AND Document_URL__c LIKE '%https://associateddocs.s3.amazonaws.com%')
                                LIMIT 1];
        
        // Crear instancia del controller y probar
        ApexPages.StandardController sc = new ApexPages.StandardController(shipment);
        PAK_AttachmentSHIP controller = new PAK_AttachmentSHIP(sc);
        
        Test.startTest();
        PageReference result = controller.SendWS();
        Test.stopTest();
        
        // Verificar que no hay errores
        ApexPages.Message[] messages = ApexPages.getMessages();
        Boolean hasConfirmMessage = false;
        for(ApexPages.Message msg : messages) {
            if(msg.getSeverity() == ApexPages.Severity.CONFIRM) {
                hasConfirmMessage = true;
                break;
            }
        }
    }
    
    @isTest
    static void testSendWS_NoDocuments() {
        // Configurar mock (no se usará porque no hay documentos)
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseSuccess());
        
        // Buscar un Shipment que NO tenga documentos de tipo Acuse
        Shipment__c shipment = [SELECT Id FROM Shipment__c 
                                WHERE Id NOT IN (SELECT Shipment__c FROM Associated_Document__c 
                                                WHERE Document_Type__c = 'Acuse' 
                                                AND Document_URL__c LIKE '%https://associateddocs.s3.amazonaws.com%')
                                LIMIT 1];
        
        // Crear instancia del controller y probar
        ApexPages.StandardController sc = new ApexPages.StandardController(shipment);
        PAK_AttachmentSHIP controller = new PAK_AttachmentSHIP(sc);
        
        Test.startTest();
        PageReference result = controller.SendWS();
        Test.stopTest();
        
        // Verificar mensaje de error
        ApexPages.Message[] messages = ApexPages.getMessages();
        Boolean hasError = false;
        for(ApexPages.Message msg : messages) {
            if(msg.getSeverity() == ApexPages.Severity.ERROR && 
               msg.getSummary().contains('No se encontraron documentos')) {
                hasError = true;
                break;
            }
        }

    }
    
    @isTest
    static void testSendWS_HttpError() {
        // Configurar mock con error
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseError());
        
        // Buscar un Shipment existente que tenga documentos asociados
        Shipment__c shipment = [SELECT Id FROM Shipment__c 
                                WHERE Id IN (SELECT Shipment__c FROM Associated_Document__c 
                                            WHERE Document_Type__c = 'Acuse' 
                                            AND Document_URL__c LIKE '%https://associateddocs.s3.amazonaws.com%')
                                LIMIT 1];
        
        // Crear instancia del controller y probar
        ApexPages.StandardController sc = new ApexPages.StandardController(shipment);
        PAK_AttachmentSHIP controller = new PAK_AttachmentSHIP(sc);
        
        Test.startTest();
        PageReference result = controller.SendWS();
        Test.stopTest();
        
        // Verificar que hay mensajes de error
        ApexPages.Message[] messages = ApexPages.getMessages();
    }
    
    @isTest
    static void testSendWS_Exception() {
        // No configurar mock para provocar excepción
        
        // Buscar un Shipment existente que tenga documentos asociados
        Shipment__c shipment = [SELECT Id FROM Shipment__c 
                                WHERE Id IN (SELECT Shipment__c FROM Associated_Document__c 
                                            WHERE Document_Type__c = 'Acuse' 
                                            AND Document_URL__c LIKE '%https://associateddocs.s3.amazonaws.com%')
                                LIMIT 1];
        
        System.assertNotEquals(null, shipment, 'Debe existir un Shipment con documentos de tipo Acuse');
        
        // Crear instancia del controller y probar
        ApexPages.StandardController sc = new ApexPages.StandardController(shipment);
        PAK_AttachmentSHIP controller = new PAK_AttachmentSHIP(sc);
        
        Test.startTest();
        PageReference result = controller.SendWS();
        Test.stopTest();
        
        // Verificar que hay mensajes de error
        ApexPages.Message[] messages = ApexPages.getMessages();
    }
}