respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Associated_Document__c.object
<CustomObject>
    <description>Import space for documents created and associated to an Account, Import-Export and/or shipment.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Consolidation_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipments Program</label>
        <referenceTo>Shipment_Program__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_URL__c</fullName>
        <label>Document URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Shipment__c.Account_for__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Document</label>
    <nameField>
        <label>Associated Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Quote_Item_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of an Import-Export to generate Shipment Cargo Lines.</description>
    <fields>
        <fullName>Delivered__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Controlled by Shipments deliveries.</inlineHelpText>
        <label>Delivered</label>
        <type>Checkbox</type>
    </fields>
    <label>Import-Export Cargo Line</label>
    <nameField>
        <label>Imp-Exp Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Outbound_Consolidation_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outbound Program</label>
        <referenceTo>Shipment_Program__c</referenceTo>
        <relationshipLabel>Shipments (Included in this Outbound Program)</relationshipLabel>
        <relationshipName>Shipments_OutboundConsolidationProgram</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of a shipment. Child object of Import-Export Cargo Lines</description>
    <fields>
        <fullName>Delivered__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Controlled by Deliveries</inlineHelpText>
        <label>Delivered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote_Item_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Cargo Line</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Quote_Item_Line__c.Import_Export_Quote__c</field>
                <operation>equals</operation>
                <valueField>$Source.Import_Export_Quote__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Quote_Item_Line__c</referenceTo>
        <relationshipLabel>Shipment Cargo Lines</relationshipLabel>
        <relationshipName>Shipment_Items_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Cargo Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Cargo Line</label>
    <nameField>
        <label>Shipment Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_Save_All_Delivery_Note.cls
public with sharing class NEU_Save_All_Delivery_Note {


    public Shipment_Program__c record;

    ApexPages.StandardController con;
            
    public NEU_Save_All_Delivery_Note(ApexPages.StandardController stdController) {

        con = stdController;
        
       try { 
        record = [select Id, Name  from Shipment_Program__c where id =: con.getRecord().id limit 1 for update];
        } catch( Exception ee) { 
            record = new Shipment_Program__c();
        }
    }
    
    public PageReference  generar_todos()
    {
        
            List<Folder> directorio = [Select Id, Name from Folder where Name =:'Associated Documents'];
            List<Associated_Document__c> todos_los_documentos_asociados = new List<Associated_Document__c>();
            List<Shipment__c> todos_los_shipment =[select id, Name, Account_for__c, Outbound_Consolidation_Program__c from Shipment__c where Outbound_Consolidation_Program__c =: record.Id];
            
            for(Shipment__c ship : todos_los_shipment)
            {
                //crear documento
                PageReference pdf = Page.NEU_DeliveryNote_pdf;
                pdf.getParameters().put('id',ship.Id);
                Blob body;
                try {
             
                    body = pdf.getContent();
             
                } catch (VisualforceException e) {
                    body = Blob.valueOf('Some Text');
                }
                //guardar documento
                    Document documento_asociado = new Document();
                    documento_asociado.Body = body;
                    documento_asociado.Name = record.name +' DeliveryNote.pdf';
                    documento_asociado.AuthorId = UserInfo.getUserId();
                    if(directorio.size()>0)
                        documento_asociado.FolderId = directorio[0].Id;
                    documento_asociado.IsPublic = true; 
        
                
                try 
                {
                    if(documento_asociado.Name != '' && documento_asociado.Name != null)
                        insert documento_asociado;
                }  
                catch (DMLException e)
                {
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error in File Upload.'));
                    return null;
                }
            
                //relacionar documento con objeto
                Associated_Document__c new_document = new Associated_Document__c();
                new_document.Account__c = ship.Account_for__c;
                new_document.Name =ship.Name +' DeliveryNote.pdf';
                new_document.Shipment__c = ship.Id;
                new_document.Consolidation_Program__c = record.Id;
                new_document.Document_URL__c = '/servlet/servlet.FileDownload?file='+documento_asociado.Id+'&oid=' + UserInfo.getOrganizationId(); 
                todos_los_documentos_asociados.add(new_document);
                
            
            }
            
            List<Shipment_Line__c> lista_shipments_lines = [select Id, Name, Delivered__c, Quote_Item_Line__c, Quote_Item_Line__r.Delivered__c, Shipment__c, Shipment__r.Outbound_Consolidation_Program__c from Shipment_Line__c where Shipment__r.Outbound_Consolidation_Program__c =: record.Id];
            List<Quote_Item_Line__c> lista_quote_lines = new List<Quote_Item_Line__c>();
            for(Shipment_Line__c ship_li : lista_shipments_lines )
            {
                ship_li.Delivered__c = true;
                if(ship_li.Quote_Item_Line__c != null)
                {
                    ship_li.Quote_Item_Line__r.Delivered__c = true;
                    lista_quote_lines.add(ship_li.Quote_Item_Line__r);
                }
            }
            
            //insersiones y actualizaciones
            try
            {
                if(todos_los_documentos_asociados != null && todos_los_documentos_asociados.size()>0)
                    insert todos_los_documentos_asociados;
                if(lista_shipments_lines != null && lista_shipments_lines.size()>0) 
                    update lista_shipments_lines;
                if(lista_shipments_lines != null && lista_shipments_lines.size()>0) 
                    update lista_shipments_lines;
            }
            catch(Exception ex)
            {
                return null;
            }   
        return new PageReference('/'+record.Id);
    }
}