respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Associated_Document__c.object
<CustomObject>
    <description>Import space for documents created and associated to an Account, Import-Export and/or shipment.</description>
    <fields>
        <fullName>Supplier_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Quote/Order</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier_Quote__c.Supply_Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Supply_Project__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier_Quote__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Request_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Request (RFP)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supplier_Request_RFP__c.Supply_Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Supply_Project__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supplier_Request_RFP__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associated_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supply_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supply Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Supply_Project__c.Customer__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Supply_Project__c</referenceTo>
        <relationshipLabel>Associated Documents</relationshipLabel>
        <relationshipName>Associate_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associated Document</label>
    <nameField>
        <label>Associated Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Supplier_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Supplier_Quote_Status__c</fullName>
        <label>Supplier Quote/Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Valid</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Sent Bid</fullName>
                </value>
                <value>
                    <fullName>Sent Final Bid</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Import-Export Consolidated</fullName>
                </value>
                <value>
                    <fullName>Consolidated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Request_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Request</label>
        <referenceTo>Supplier_Request_RFP__c</referenceTo>
        <relationshipLabel>Suppliers Quotes/Orders</relationshipLabel>
        <relationshipName>Supplier_Quote</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supply_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Supply Project</label>
        <referenceTo>Supply_Project__c</referenceTo>
        <relationshipName>Suppliers_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier Quote/Order</label>
    <nameField>
        <displayFormat>SQO# {YYYY}-{000000}</displayFormat>
        <label>Supplier Quote/Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Quotes/Orders</pluralLabel>
    <recordTypes>
        <fullName>Supplier_Quote</fullName>
        <active>true</active>
        <label>Supplier Quote</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_OM_ProjectSteps.cls
public with sharing class NEU_OM_ProjectSteps {

    public Supply_Project__c record;
    public string step {get;set;}
    public String step_1 {get;set;}
    public String step_2 {get;set;}
    public String step_3 {get;set;}
    public String step_4 {get;set;}
    public String step_5 {get;set;}
    public String step_6 {get;set;}
    public String step_7 {get;set;}
    public String step_8 {get;set;}
    public boolean todorelleno{get;set;}
    
    ApexPages.StandardController con;
            
    public NEU_OM_ProjectSteps(ApexPages.StandardController stdController) {

        con = stdController;
        
        system.debug( con.getRecord() );
        try { 
        record = [select Id, Name from Supply_Project__c where Id =: con.getRecord().id];
        } catch( Exception ee) { 
            record = new Supply_Project__c();
        }
        
        boolean target_price = true;
        todorelleno = true;
        
        step_1 = 'step_active';
        step_2 = 'step_active';
        step_3 = 'step_active';
        step_4 = 'step_active';
        step_5 = 'step_active';
        step_6 = 'step_active';
        step_7 = 'step_active';
        step_8 = 'step_active';
         
        //COMPROBACIÓN AUCTION SETUP
            todorelleno = false;
        
        List<Items_to_Supply__c> project_item = new List<Items_to_Supply__c>();
        project_item = [select Id, Name, Target_Price__c, Supply_Project__c, Quantity__c from Items_to_Supply__c where Supply_Project__c =: record.Id];
        if(project_item.size() > 0)
        {
            step_1 = 'step_inactive';
        }
            
        //COMPROBACIÓN ORDER
        List<Associated_Document__c> documentos_asociados = new List<Associated_Document__c>();
        documentos_asociados = [select Id, Name, Supply_Project__c from Associated_Document__c where Supply_Project__c =: record.Id ];//and Name like:'%Supplier Quote.pdf'
        if(documentos_asociados.size() > 0)
        {
            step_2= 'step_inactive';
        }
        
         //COMPROBACIÓN PARTICIPANTS
        List<Supplier_to_Invite__c> Supplier_to_Invite = new List<Supplier_to_Invite__c>();
        Supplier_to_Invite = [select Id, Name, Supply_Project__c from Supplier_to_Invite__c where Supply_Project__c =: record.Id];
        if(Supplier_to_Invite.size() > 0)
        {
            step_3= 'step_inactive';
        }
        
        //COMPROBACIÓN RFP REQUEST
        List<Supplier_Request_RFP__c> supplier_requests = new List<Supplier_Request_RFP__c>();
        supplier_requests = [select Id, Name, Supply_Project__c from Supplier_Request_RFP__c where Supply_Project__c =: record.Id];
        if(supplier_requests.size() > 0)
        {
            step_4 = 'step_inactive';
        }
        
        //COMPROBACIÓN SUPPLIER OFFERS
        List<Supplier_Quote__c> Supplier_Quote = new List<Supplier_Quote__c>();
        Supplier_Quote = [select Id, Name, Supply_Project__c from Supplier_Quote__c where Supply_Project__c =: record.Id];
        if(Supplier_Quote.size() > 0)
        {
            step_5 = 'step_inactive';
        }
        
        
        //COMPROBACIÓN SUPPLIER OFFERS aprobadas
        List<Supplier_Quote__c> Supplier_Quote2 = new List<Supplier_Quote__c>();
        Supplier_Quote2 = [select Id, Name, Supply_Project__c from Supplier_Quote__c where Supply_Project__c =: record.Id and Supplier_Quote_Status__c='Approved'];
        if(Supplier_Quote2.size() > 0)
        {
            step_6 = 'step_inactive';
            step_7 = 'step_inactive';
        }
        
         //COMPROBACIÓN QUOTATION
        List<Supplier_Quote__c> quotations = new List<Supplier_Quote__c>();
        quotations = [select Id, Name, Supply_Project__c from Supplier_Quote__c where Supply_Project__c =: record.Id and RecordTypeId =: Schema.SobjectType.Supplier_Quote__c.getRecordTypeInfosByName().get('Supplier Order').getRecordTypeId()];
        if(quotations.size() > 0)
        {
            step_8= 'step_inactive';
        }
        
                
              
                /*List<Associated_Document__c> new_associated_document = new List<Associated_Document__c>();
                new_associated_document = [select Id, Name, Supply_Project__c from Associated_Document__c where Supply_Project__c =: record.Id];
                if(new_associated_document.size()>0)
                {
                    step = 'paso2';
                }*/
            
    }   

}