respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Cred_Cifid__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Usuario__c</fullName>
        <label>Usuario</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Cifid</label>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Import_Export_Fee_Line__c.object
<CustomObject>
    <description>Specifies transport fees associated to an Import-Export. Child object from &quot;Freight Rates Management&quot;</description>
    <fields>
        <fullName>Buy_Amount__c</fullName>
        <description>If &quot;Quote Buy Price&quot; positive then maximum value between &quot;Quote Buy Price&quot; x &quot;Units&quot; or &quot;Min Amount&quot;
If &quot;Quote Buy Price&quot; negative then minimum value between &quot;Quote Buy Price&quot; x &quot;Units&quot; or &quot;Min Amount&quot;</description>
        <formula>IF(Quote_Buy_Price__c &gt;= 0 ,MAX (Quote_Buy_Price__c * Units__c, IF((ISNULL(Quote_Buy_Price__c)== true) || (Quote_Buy_Price__c = 0), 0, Min_Amount__c ) ), MIN (Quote_Buy_Price__c* Units__c, IF((ISNULL(Quote_Buy_Price__c )== true) || (Quote_Buy_Price__c = 0), 0, - Min_Amount__c ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Highest value between &quot;Quote Buy Price&quot; x &quot;Units&quot; and &quot;Min Amount&quot;</inlineHelpText>
        <label>Std. Buy Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Carrier__c</fullName>
        <formula>Service_Rate_Name__r.Carrier_Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Carrier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote/Order</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Service Lines</relationshipLabel>
        <relationshipName>Import_Export_Fees_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Quote_Buy_Price__c</fullName>
        <label>Quote Std. Buy Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote_Sell_Price__c</fullName>
        <label>Quote Sell Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sell_Amount__c</fullName>
        <description>Conversion to currency of &quot;Sell Gross Amount&quot; x (1 - &quot;Discount&quot;)</description>
        <formula>Sell_Gross_Amount__c * (1 - Discount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>&quot;Sell Gross Amount&quot; x (1 - &quot;Discount&quot;)</inlineHelpText>
        <label>Sell Net Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Rate_Category__c</fullName>
        <formula>TEXT(Service_Rate_Name__r.Fee_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rate Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Rate_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Name</label>
        <referenceTo>Fee__c</referenceTo>
        <relationshipLabel>Import-Export Service Lines</relationshipLabel>
        <relationshipName>Import_Export_Fees_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Units</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Cifid_SendQuoteLines.cls
public class Cifid_SendQuoteLines {
    public static boolean firstRun = true;
    
    @future(callout=true)
    public static void send(Set<Id> lstIds, Integer operation){
        System.debug('Cifid_SendQuoteLines FutureHandler - operation: ' + operation + ' lstIds: ' + lstIds);
        List<CifidQuoteLines.Quote> lstSend = new List<CifidQuoteLines.Quote>();
        if(operation == 3){
            System.debug('Cifid_SendQuoteLines Op - 3');
            CifidQuoteLines.Quote quote = new CifidQuoteLines.Quote();
            List<CifidQuoteLines.QuoteLine> lstQuoteLines = new List<CifidQuoteLines.QuoteLine>();
            quote.operation = operation;
            for(Id lineId : lstIds){
                CifidQuoteLines.QuoteLine ql = new CifidQuoteLines.QuoteLine();
                ql.idLine = lineId;
                lstQuoteLines.add(ql);
            }
            quote.lines = lstQuoteLines;
            lstSend.add(quote);
            System.debug('Cifid_SendQuoteLines lstSend == **** ' + lstSend);
        }else{
            List<Import_Export_Fee_Line__c> lstLines = [SELECT Id, Service_Rate_Category__c, Service_Rate_Name__r.Name, Units__c, Quote_Sell_Price__c, Sell_Amount__c, Quote_Buy_Price__c, Buy_Amount__c, Carrier__c, Import_Export_Quote__r.Name
                                                        FROM Import_Export_Fee_Line__c WHERE Id IN:lstIds ORDER BY Import_Export_Quote__r.Name];
            System.debug('Cifid_SendQuoteLines lines **** ' + lstLines);
            
            CifidQuoteLines.Quote quote = new CifidQuoteLines.Quote();
            System.debug('Cifid_SendQuoteLines FirstLine **** ' + lstLines[0].Import_Export_Quote__r.Name);
            quote.quoteName = lstLines[0].Import_Export_Quote__r.Name;
            quote.operation = operation;
            
            List<CifidQuoteLines.QuoteLine> lstQuoteLines = new List<CifidQuoteLines.QuoteLine>();
            
            for(Import_Export_Fee_Line__c line : lstLines){    
                if(line.Import_Export_Quote__r.Name == quote.quoteName){
                    System.debug('Cifid_SendQuoteLines line name == **** ' + line.Import_Export_Quote__r.Name);
                    CifidQuoteLines.QuoteLine ql = new CifidQuoteLines.QuoteLine();
                    ql.idLine = line.Id;
                    ql.rateCategory = line.Service_Rate_Category__c;
                    ql.rateName = line.Service_Rate_Name__r.Name;
                    ql.units = line.Units__c;
                    ql.quoteSellPrice = line.Quote_Sell_Price__c;
                    ql.sellNetAmmount = line.Sell_Amount__c;
                    ql.quoteStdBuyPrice = line.Quote_Buy_Price__c;
                    ql.StdBuyAmmount = line.Buy_Amount__c;
                    ql.carrier = line.Carrier__c;
                    lstQuoteLines.add(ql);
                }else{
                    System.debug('Cifid_SendQuoteLines line name != **** ' + line.Import_Export_Quote__r.Name);
                    quote.lines = lstQuoteLines;
                    lstSend.add(quote);
                    
                    lstQuoteLines = new List<CifidQuoteLines.QuoteLine>();
                    quote = new CifidQuoteLines.Quote();
                    quote.quoteName = line.Import_Export_Quote__r.Name;
                    quote.operation = operation;
                    
                    CifidQuoteLines.QuoteLine ql = new CifidQuoteLines.QuoteLine();
                    ql.idLine = line.Id;
                    ql.rateCategory = line.Service_Rate_Category__c;
                    ql.rateName = line.Service_Rate_Name__r.Name;
                    ql.units = line.Units__c;
                    ql.quoteSellPrice = line.Quote_Sell_Price__c;
                    ql.sellNetAmmount = line.Sell_Amount__c;
                    ql.quoteStdBuyPrice = line.Quote_Buy_Price__c;
                    ql.StdBuyAmmount = line.Buy_Amount__c;
                    ql.carrier = line.Carrier__c;
                    lstQuoteLines.add(ql);
                }
            }
            quote.lines = lstQuoteLines;
            lstSend.add(quote);
            System.debug('Cifid_SendQuoteLines lstSend == **** ' + lstSend);
        }
        HttpResponse res;
        if(!Test.isRunningTest()){res = login();}
        
        String SESSION_ID;
        Dom.XmlNode resultElmt;
        if(!Test.isRunningTest()){                
            resultElmt = res.getBodyDocument().getRootElement().getChildElement('Body','http://schemas.xmlsoap.org/soap/envelope/').getChildElement('loginResponse','urn:partner.soap.sforce.com').getChildElement('result','urn:partner.soap.sforce.com');                          
            SESSION_ID = resultElmt.getChildElement('sessionId','urn:partner.soap.sforce.com').getText();
        }else{
            SESSION_ID = 'TestId';
        } 
        
        CifidQuoteLines.Cifid_QuoteLines cifid = new CifidQuoteLines.Cifid_QuoteLines();
        cifid.SessionHeader = new CifidQuoteLines.SessionHeader_element();
        cifid.SessionHeader.sessionId = SESSION_ID;
        
        for(CifidQuoteLines.Quote s : lstSend){
            if(!Test.isRunningTest()){System.debug('CIFID_TRIGGER response ' + s.quoteName + ' **** ' + cifid.quoteLines(s));}
        }
    }
    
    public static HttpResponse login(){
        String dominio = 'login';
        sObject credencial;   
        if(!Test.isRunningTest()){
            credencial = Database.query('SELECT Usuario__c, Password__c, Token__c FROM Cred_Cifid__c');
        }
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://' + dominio + '.salesforce.com/services/Soap/u/44.0');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'text/xml;charset=UTF-8');
        req.setHeader('SOAPAction', '""');
        if(!Test.isRunningTest()){
            req.setBody('<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Header/><Body><login xmlns="urn:partner.soap.sforce.com"><username>' + 
                        credencial.get('Usuario__c') + '</username><password>' + credencial.get('Password__c') + credencial.get('Token__c') + '</password></login></Body></Envelope>');
        }
        
        Http h = new Http();
        HttpResponse res = h.send(req); 
        return res;
    }
    
    public static void Test(){
        String Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
        Test0 = '';
    }
}