respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Cred_Cifid__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Usuario__c</fullName>
        <label>Usuario</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Cifid</label>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Quote_Item_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of an Import-Export to generate Shipment Cargo Lines.</description>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Cargo_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HS_Code__c</fullName>
        <label>HS Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Item_Height__c</fullName>
        <formula>Item_Name__r.Master_Box_Height_cm__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Height(cm)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_Lenght_cm__c</fullName>
        <formula>Item_Name__r.Master_Box_Length_cm__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Lenght(cm)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Name</label>
        <referenceTo>Sourcing_Item__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Width_cm__c</fullName>
        <formula>Item_Name__r.Master_Box_Width_cm__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Width(cm)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Unit Origin Sell Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Shipping_Volume_m3__c</fullName>
        <label>Total Shipping Volume (m3)</label>
        <precision>16</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Shipping_Weight_Kgs__c</fullName>
        <label>Peso Bruto (KG)</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Cargo Line</label>
    <nameField>
        <label>Imp-Exp Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PAK_SendCargoLines.cls
public class PAK_SendCargoLines {
    public static boolean firstRun = true;
    
    @future(callout=true)
    public static void send(Set<Id> lstIds, Integer operation){
        System.debug('PAK_SendCargoLines FutureHandler - operation: ' + operation + ' lstIds: ' + lstIds);
        String soap = '';
        String soapLines = '';
        
        if(operation == 3){
            System.debug('PAK_SendCargoLines Op - 3');
            for(Id line : lstIds){
                soapLines += '<pak:lines>';
                soapLines += '<pak:idLine>' + line + '</pak:idLine>';
                soapLines += '</pak:lines>';
            }
            
            HttpResponse res;
            if(!Test.isRunningTest()){res = login();}
            
            String SESSION_ID;
            Dom.XmlNode resultElmt;
            if(!Test.isRunningTest()){                
                resultElmt = res.getBodyDocument().getRootElement().getChildElement('Body','http://schemas.xmlsoap.org/soap/envelope/').getChildElement('loginResponse','urn:partner.soap.sforce.com').getChildElement('result','urn:partner.soap.sforce.com');                          
                SESSION_ID = resultElmt.getChildElement('sessionId','urn:partner.soap.sforce.com').getText();
            }else{
                SESSION_ID = 'TestId';
            } 
            
            soap = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:pak="http://soap.sforce.com/schemas/class/PAK_QuoteCL">' +
                '<soapenv:Header>' +
                '<pak:SessionHeader>' +
                '<pak:sessionId>' + SESSION_ID + '</pak:sessionId>' +
                '</pak:SessionHeader>' +
                '</soapenv:Header>' +
                '<soapenv:Body>' +
                '<pak:cargoLines>' +
                '<pak:quote>' + soapLines +
                '<pak:operation>' + operation + '</pak:operation>' +
                '</pak:quote>' +
                '</pak:cargoLines>' +
                '</soapenv:Body>' +
                '</soapenv:Envelope>';
            if(!Test.isRunningTest()){System.debug('Response: ' + sendCargoLines(soap).getBody()); }
        }else{
            List<Quote_Item_Line__c> lstLines =  [SELECT Id, Item_Name__r.Name, Container_Type__r.Name, Units__c, Total_Shipping_Weight_Kgs__c, Total_Shipping_Volume_m3__c, Item_Height__c, 
                                                  Item_Width_cm__c, Item_Lenght_cm__c, Import_Export_Quote__r.Name, HS_Code__c, Price__c
                                                  FROM Quote_Item_Line__c 
                                                  WHERE Id IN:lstIds];
            System.debug('PAK_SendCargoLines lines **** ' + lstLines);
            
            HttpResponse res;
            if(!Test.isRunningTest()){res = login();}
            
            String SESSION_ID;
            Dom.XmlNode resultElmt;
            if(!Test.isRunningTest()){                
                resultElmt = res.getBodyDocument().getRootElement().getChildElement('Body','http://schemas.xmlsoap.org/soap/envelope/').getChildElement('loginResponse','urn:partner.soap.sforce.com').getChildElement('result','urn:partner.soap.sforce.com');                          
                SESSION_ID = resultElmt.getChildElement('sessionId','urn:partner.soap.sforce.com').getText();
            }else{
                SESSION_ID = 'TestId';
            } 
            
            for(Quote_Item_Line__c line : lstLines){
                soapLines += '<pak:lines>';
                soapLines += '<pak:containerType>' + line.Container_Type__r.Name +'</pak:containerType>';
                soapLines += '<pak:idLine>' + line.Id + '</pak:idLine>';
                soapLines += '<pak:itemHeight>' + line.Item_Height__c +'</pak:itemHeight>';
                soapLines += '<pak:itemLength>' + line.Item_Lenght_cm__c + '</pak:itemLength>';
                soapLines += '<pak:itemName>' + line.Item_Name__r.Name + '</pak:itemName>';
                soapLines += '<pak:itemUnitVolume>' + line.Total_Shipping_Volume_m3__c + '</pak:itemUnitVolume>';
                soapLines += '<pak:itemUnitWeight>' + line.Total_Shipping_Weight_Kgs__c + '</pak:itemUnitWeight>';
                soapLines += '<pak:itemWidth>' + line.Item_Width_cm__c + '</pak:itemWidth>';
                soapLines += '<pak:units>' + line.Units__c + '</pak:units>';
                soapLines += '<pak:fraccion>' + line.HS_Code__c + '</pak:fraccion>';
                soapLines += '<pak:merchValue>' + line.Price__c + '</pak:merchValue>';
                soapLines += '</pak:lines>';
            }
            string quoteName = '';
            if(!Test.isRunningTest()){ quoteName= lstLines[0].Import_Export_Quote__r.Name;}
            soap = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:pak="http://soap.sforce.com/schemas/class/PAK_QuoteCL">' +
                '<soapenv:Header>' +
                '<pak:SessionHeader>' +
                '<pak:sessionId>' + SESSION_ID + '</pak:sessionId>' +
                '</pak:SessionHeader>' +
                '</soapenv:Header>' +
                '<soapenv:Body>' +
                '<pak:cargoLines>' +
                '<pak:quote>' + soapLines +
                '<pak:operation>' + operation + '</pak:operation>' +
                '<pak:quoteName>' + quoteName +'</pak:quoteName>' +
                '</pak:quote>' +
                '</pak:cargoLines>' +
                '</soapenv:Body>' +
                '</soapenv:Envelope>';
            
            if(!Test.isRunningTest()){System.debug('Response: ' + sendCargoLines(soap).getBody()); }
        }
    }
    
    public static HttpResponse login(){
        String dominio = 'login';
        sObject credencial;   
        if(!Test.isRunningTest()){
            credencial = Database.query('SELECT Usuario__c, Password__c, Token__c FROM Cred_Cifid__c');
        }
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://' + dominio + '.salesforce.com/services/Soap/u/44.0');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'text/xml;charset=UTF-8');
        req.setHeader('SOAPAction', '""');
        if(!Test.isRunningTest()){
            req.setBody('<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Header/><Body><login xmlns="urn:partner.soap.sforce.com"><username>' + 
                        credencial.get('Usuario__c') + '</username><password>' + credencial.get('Password__c') + credencial.get('Token__c') + '</password></login></Body></Envelope>');
        }
        
        Http h = new Http();
        HttpResponse res = h.send(req); 
        return res;
    }
    
    public static HttpResponse sendCargoLines(string body){
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://na85.salesforce.com/services/Soap/class/PAK_QuoteCL');
        req.setMethod('POST');
        req.setTimeout(120000);
        req.setHeader('Content-Type', 'text/xml;charset=UTF-8');
        req.setHeader('SOAPAction', '""');
        req.setBody(body);
        
        Http h = new Http();
        HttpResponse res = h.send(req); 
        return res;
    }
    
    public static void Test(){
        string test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
        test = '';
    }
}