respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Import_Export_Quotes_Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Quote_Item_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of an Import-Export to generate Shipment Cargo Lines.</description>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <formula>Import_Export_Quote__r.Account_for__r.Owner.FirstName &amp; &quot; &quot;&amp;Import_Export_Quote__r.Account_for__r.Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Cargo_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Name</label>
        <referenceTo>Sourcing_Item__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Items_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Margin_at_Destination__c</fullName>
        <label>Margin at Destination</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TEUS__c</fullName>
        <label>TEUS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Shipping_Volume_m3__c</fullName>
        <label>Total Shipping Volume (m3)</label>
        <precision>16</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Shipping_Weight_Kgs__c</fullName>
        <label>Peso Bruto (KG)</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Import-Export Cargo Line</label>
    <nameField>
        <label>Imp-Exp Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Trigger_QuoteItemLine_Test.cls
@isTest
public class Trigger_QuoteItemLine_Test {
	@isTest(SeeAllData=true)
    //Triggers afectados
    //NEU_Import_Export_Line_Update_Margin
    //NEU_Quote_Item_Line_copy
    //PAK_CargoLines
    public static void QuoteItemLine_Test(){
        Customer_Quote__c ieqo = [SELECT Id,Account_for__c FROM Customer_Quote__c WHERE Last_Shipment__c = null AND Pricing_Executive__c != null LIMIT 1];
        Container_Type__c container = [SELECT Id, TEUS__c FROM Container_Type__c LIMIT 1];
        Sourcing_Item__c item =  new Sourcing_Item__c();
        item.Name = 'item tst';
        item.Account_Owner__c = ieqo.Account_for__c;
        insert item;
        
        Quote_Item_Line__c ql = new Quote_Item_Line__c();
        ql.Name = 'tst1';
        ql.Item_Name__c = item.Id;
        ql.Units__c = 1;
        ql.Margin_at_Destination__c = 2;
        ql.Import_Export_Quote__c = ieqo.Id;
        insert ql;
        
        ql.Container_Type__c = container.id;
        ql.Total_Shipping_Weight_Kgs__c = 20;
        ql.Total_Shipping_Volume_m3__c = 10;
        update ql;
        
     }
}