respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Freight_Mode__c</fullName>
        <label>Freight Mode</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Air</fullName>
                </value>
                <value>
                    <fullName>Sea</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                    <default>true</default>
                    <label>Road</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ignore__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ignore</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Type__c</fullName>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Freight_Mode__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>FTL</fullName>
                </value>
                <value>
                    <fullName>LTL</fullName>
                </value>
                <value>
                    <fullName>FCL</fullName>
                </value>
                <value>
                    <fullName>LCL</fullName>
                </value>
                <value>
                    <fullName>PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>CARGA</fullName>
                </value>
                <value>
                    <fullName>TARIMAS</fullName>
                </value>
                <value>
                    <fullName>FP</fullName>
                </value>
                <value>
                    <fullName>FO</fullName>
                </value>
                <value>
                    <fullName>MAYOREO</fullName>
                </value>
                <value>
                    <fullName>ENVIO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>EXTRAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Traffic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Specify Account for (Customer) and Service Product first</inlineHelpText>
        <label>Traffic</label>
        <referenceTo>Traffic__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_CreateTraffics.cls
public with sharing class NEU_CreateTraffics 
{
	public string resultado {get;set;}
	
    public PageReference create_traffic()
    {
		List<Customer_Quote__c> importexport = [select Id, Name from Customer_Quote__c 
		where Freight_Mode__c != 'Multimodal' and Traffic__c = null and Ignore__c = false and Service_Type__c != 'PAQUETERIA' limit 1];
		
		try
		{
			if(importexport.size() > 0)
			{
				update importexport;
				
				PageReference pgReturnPage;
		        String returnUrl = '/apex/NEU_CreateTraffics';
		        pgReturnPage = new PageReference(returnUrl);
		        pgReturnPage.setRedirect(true);
		        return pgReturnPage;
			}
			else
			{
				resultado = 'FIN';
				return null;
			}
		}
		catch(Exception ex)
		{
			resultado = ''+ex;
			return null;
		}
    }
}