respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Total_IEQO_Creados__c</fullName>
        <label>Total IEQO Creados</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>PROJ_Modalidad__c</fullName>
        <label>Modalidad</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

force-app/main/default/classes/p2G_FoliosEnOportunidadesTest.cls
@isTest(SeeAllData=true)
public class p2G_FoliosEnOportunidadesTest {
	@isTest
    public static void prueba(){
        NEU_StaticVariableHelper.setBoolean1(true);
        OpportunityLineItem oli = [SELECT OpportunityId , PROJ_Modalidad__c FROM OpportunityLineItem 
                                   WHERE OpportunityId != null AND Opportunity.Total_IEQO_Creados__c > 0
                                   LIMIT 1];
        System.debug('OpportunityLineItem: ' + oli);
        List<Customer_Quote__c> getIEQO = p2G_FoliosEnOportunidades.getIEQO(oli.OpportunityId,'FN-');
        String asignar = p2G_FoliosEnOportunidades.asignarFolio(oli.OpportunityId,getIEQO[0].Id);
        List<p2G_FoliosEnOportunidades.wrapperProduct> lista = p2G_FoliosEnOportunidades.getRoute(oli.OpportunityId);
        List<p2G_FoliosEnOportunidades.wrapperProduct> listaCrear = new List<p2G_FoliosEnOportunidades.wrapperProduct>();
        listaCrear.add(lista[0]);
        String ss = p2G_FoliosEnOportunidades.foliosACrear(listaCrear);
        List<Customer_Quote__c> listaIEQ = [SELECT Id,Name,Opportunity__c FROM Customer_Quote__c limit 1];
        p2G_FoliosEnOportunidades.enviarCorreo(listaIEQ,'pruebita');
        p2G_FoliosEnOportunidades.asignarFolio(oli.Id,listaIEQ[0].Id);
        List<p2G_FoliosEnOportunidades.wrapperProduct> wrapper = p2G_FoliosEnOportunidades.getWrapper();
        p2G_FoliosEnOportunidades.crearFoliosFuturo(lista);
        lista[0].grupo ='SP-FI-FLETE INTER';
        p2G_FoliosEnOportunidades.grupo(lista[0]);
        lista[0].grupo ='SP-A-AEREO';
        p2G_FoliosEnOportunidades.grupo(lista[0]);
        lista[0].grupo ='SP-CE-COMERCIO EXT';
        p2G_FoliosEnOportunidades.grupo(lista[0]);
        lista[0].grupo ='SP-M-MARITIMO';
        p2G_FoliosEnOportunidades.grupo(lista[0]);
        lista[0].grupo ='SP-PTO-PUERTOS';
        p2G_FoliosEnOportunidades.grupo(lista[0]);
        lista[0].grupo ='SP-R-GLOBAL ROUTING';
        p2G_FoliosEnOportunidades.grupo(lista[0]);
        lista[0].grupo ='SP-EX-SEGUROS';
        p2G_FoliosEnOportunidades.grupo(lista[0]);
        lista[0].grupo ='SP-PQ-PAQUETERIA';
        p2G_FoliosEnOportunidades.grupo(lista[0]);
        lista[0].grupo ='SP-WH-ALMACENAJE';
        p2G_FoliosEnOportunidades.grupo(lista[0]);
        lista[0].grupo ='SP-T-CONSOLIDADO';
        p2G_FoliosEnOportunidades.grupo(lista[0]);
        
    }
}