respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Date_Pricing_responded__c</fullName>
        <label>Date Pricing responded</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Ext_Pricing_Impk__c</fullName>
        <label>External Pricer Executive</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Final_Client_WS__c</fullName>
        <label>External Final Client</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Stage_Impak__c</fullName>
        <label>External Stage (Impak)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PAK_ImpkQuote.cls
global class PAK_ImpkQuote {
    global class estatus{
        webservice String code {get; set;}
        webservice String message {get; set;}
    }
    
    global class Quote{
        webservice String quoteName {get;set;}
        webservice String pricing {get;set;}
        webservice Datetime datePricingResponse {get;set;}
        webservice String FinalClient {get;set;}
        webservice String stage {get;set;}
    }
    
    webservice static estatus updateQuote(Quote quote){
        System.debug('Quote: ' + quote);
        estatus result = new estatus();
        try{
            List<Customer_Quote__c> qc = [SELECT Id, Ext_Pricing_Impk__c, Date_Pricing_responded__c, External_Final_Client_WS__c, External_Stage_Impak__c FROM Customer_Quote__c WHERE Name =:quote.quoteName];
            if(qc.size()>0){
                qc[0].Ext_Pricing_Impk__c = quote.pricing;
                qc[0].Date_Pricing_responded__c = quote.datePricingResponse;
                qc[0].External_Final_Client_WS__c = quote.FinalClient;
                qc[0].External_Stage_Impak__c = quote.stage;
                update qc[0];
                result.code = '1';
                result.message = 'Quote updated';
            }else{
                result.code = '0';
                result.message = 'Quote updated';
            }            
        }catch(Exception e)
        {
            result.code = '0';
            result.message = 'Error:'+ e.getMessage()+' en la siguiente Linea: '+ e.getLineNumber() + ' - Trace: ' + e.getStackTraceString() + ' - Cause: ' + e.getCause();
        }
        return result;
    }
}