respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Pricing_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Import_Export_Quotes_Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quotation_Status__c</fullName>
        <inlineHelpText>Only Approved as Succesfull Quotes will be available for Pick &amp; Ship</inlineHelpText>
        <label>Quotation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote being prepared</fullName>
                    <color>#FF9900</color>
                    <default>true</default>
                    <label>Quote being prepared</label>
                </value>
                <value>
                    <fullName>Awaiting costs suppliers</fullName>
                    <color>#FF0000</color>
                    <label>Awaiting costs suppliers</label>
                </value>
                <value>
                    <fullName>Sent awaiting response</fullName>
                    <color>#FF6600</color>
                    <label>Sent awaiting response</label>
                </value>
                <value>
                    <fullName>Approved as Succesful</fullName>
                    <color>#006600</color>
                    <label>Approved as Succesful</label>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                    <color>#3366FF</color>
                    <label>Shipped</label>
                </value>
                <value>
                    <fullName>Quote Declined</fullName>
                    <color>#FF0000</color>
                    <label>Quote Declined</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <recordTypes>
        <fullName>Import_Export_Order</fullName>
        <active>true</active>
        <description>For Import-Export Quotes approved.</description>
        <label>Import-Export Order</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_Import_Export_Quotes_SearchTest.cls
@isTest
public class NEU_Import_Export_Quotes_SearchTest {
    @isTest
    static void testConstructorAndCargaFiltros() {
        Test.startTest();
        NEU_Import_Export_Quotes_Search controller = new NEU_Import_Export_Quotes_Search();
        controller.carga_filtros();
        controller.search_import_export_quote_order();
        controller.step_Instalacion = '2';
        controller.anterior_siguiente_Instalacion();
        controller.step_order = '2';
        controller.anterior_siguiente_order();
        List<SelectOption> etdOptions = controller.getETD_operator_list();
        List<SelectOption> etaOptions = controller.getETA_operator_list();
        List<SelectOption> serviceTypeOptions = controller.getservices_type();
        Test.stopTest();
    }
    @isTest(SeeAllData=true)
    static void testUpdateStatusQuote() {
        Customer_Quote__c testQuote = [SELECT Id FROM Customer_Quote__c WHERE RecordType.DeveloperName = 'Import_Export_Order' AND Pricing_Executive__c != null AND Quotation_Status__c = 'Approved as Succesful' LIMIT 1];
        
        NEU_Import_Export_Quotes_Search controller = new NEU_Import_Export_Quotes_Search();
        controller.carga_filtros();
        controller.ids_ie_quotes = testQuote.Id;
        controller.filter_status_quote = new Customer_Quote__c(Quotation_Status__c = 'Approved as Succesful');
        
        Test.startTest();
        controller.update_status_quote();
        Test.stopTest();
        
    }
    @isTest(SeeAllData=true)
    static void testGoCompareMethods() {
        NEU_Import_Export_Quotes_Search controller = new NEU_Import_Export_Quotes_Search();
        controller.carga_filtros();
        
        Test.startTest();
        controller.go_compare_quote();
        controller.go_compare_orders();
        Test.stopTest();
        
        System.assertNotEquals(0, controller.ie_quotes.size(), 'Should have quotes after compare');
        System.assertNotEquals(0, controller.ie_orders.size(), 'Should have orders after compare');
    }
}