respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Pricing_Executive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Executive</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Import_Export_Quotes_Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Import_Export_Fee_Line__c.object
<CustomObject>
    <description>Specifies transport fees associated to an Import-Export. Child object from &quot;Freight Rates Management&quot;</description>
    <fields>
        <fullName>Import_Export_Quote__c</fullName>
        <label>Import-Export Quote/Order</label>
        <referenceTo>Customer_Quote__c</referenceTo>
        <relationshipLabel>Import-Export Service Lines</relationshipLabel>
        <relationshipName>Import_Export_Fees_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Import-Export Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Usuario_IC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usuario IC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SubProducto__c/SubProducto__c.object-meta.xml
<CustomObject>
    <label>SubProducto</label>
    <nameField>
        <label>Cargo Adicional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubProductos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_reporteProductosOportunidadTest.cls
@isTest(SeeAllData=true)
public class P2G_reporteProductosOportunidadTest {
    @isTest
    public static void test(){
        List<OpportunityLineItem> getProducts = P2G_reporteProductosOportunidad.getProducts();
        List<Subproducto__c> getSubProductos = P2G_reporteProductosOportunidad.getSubProductos();
        List<P2G_reporteProductosOportunidad.ComboboxOption> getAccountOptions = P2G_reporteProductosOportunidad.getAccountOptions();
        List<P2G_reporteProductosOportunidad.ComboboxOption> getOwnerOppoOptions = P2G_reporteProductosOportunidad.getOwnerOppoOptions();
        List<P2G_reporteProductosOportunidad.ComboboxOption> getIcOptions = P2G_reporteProductosOportunidad.getIcOptions();
        List<OpportunityLineItem> buscaProductosPendientes = P2G_reporteProductosOportunidad.buscaProductosPendientes('Pendiente por cotizar', 'SP-FN-FLETE NACIONAL', getProducts[0].Opportunity.AccountId, getProducts[0].Opportunity.OwnerId, getProducts[0].Opportunity.Usuario_IC__c);
        List<Subproducto__c> buscaSubProductosPendientes = P2G_reporteProductosOportunidad.buscaSubProductosPendientes('Pendiente por cotizar','SP-FN-FLETE NACIONAL', getProducts[0].Opportunity.AccountId, getProducts[0].Opportunity.OwnerId, getProducts[0].Opportunity.Usuario_IC__c);
        List<OpportunityLineItem> buscaProductosCotizados = P2G_reporteProductosOportunidad.buscaProductosCotizados('Cotizada', 'SP-FN-FLETE NACIONAL', getProducts[0].Opportunity.AccountId, getProducts[0].Opportunity.OwnerId, getProducts[0].Opportunity.Usuario_IC__c);
        List<Subproducto__c> buscaSubProductosCotizados = P2G_reporteProductosOportunidad.buscaSubProductosCotizados('Cotizada', 'SP-FN-FLETE NACIONAL', getProducts[0].Opportunity.AccountId, getProducts[0].Opportunity.OwnerId, getProducts[0].Opportunity.Usuario_IC__c);
        List<OpportunityLineItem> buscaProductosAceptados = P2G_reporteProductosOportunidad.buscaProductosAceptados('Aceptada', 'SP-FN-FLETE NACIONAL', getProducts[0].Opportunity.AccountId, getProducts[0].Opportunity.OwnerId, getProducts[0].Opportunity.Usuario_IC__c);
        List<Subproducto__c> buscaSubProductosAceptados = P2G_reporteProductosOportunidad.buscaSubProductosAceptados('Aceptada', 'SP-FN-FLETE NACIONAL', getProducts[0].Opportunity.AccountId, getProducts[0].Opportunity.OwnerId, getProducts[0].Opportunity.Usuario_IC__c);
        List<p2G_FoliosEnOportunidades.wrapperProduct> getProductsAceptados = P2G_reporteProductosOportunidad.getProductsAceptados();
        List<Account> getAccountAceptados = P2G_reporteProductosOportunidad.getAccountAceptados('Cliente');
        List<p2G_FoliosEnOportunidades.wrapperProduct> getProductsEnCuentas = P2G_reporteProductosOportunidad.getProductsEnCuentas(getAccountAceptados[0].Id,'SP-FN-FLETE NACIONAL');
        List<Import_Export_Fee_Line__c> getServiceLineIEQO = P2G_reporteProductosOportunidad.getServiceLineIEQO();
        List<Import_Export_Fee_Line__c> buscaIEQOPendientes = P2G_reporteProductosOportunidad.buscaIEQOPendientes('Awaiting costs suppliers','FN', getServiceLineIEQO[0].Import_Export_Quote__r.Account_for__c, getServiceLineIEQO[0].Import_Export_Quote__r.CreatedById, getServiceLineIEQO[0].Import_Export_Quote__r.Pricing_Executive__c);
        list<User> getUser = P2G_reporteProductosOportunidad.getUser('Mar');
    }

}