respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Last_Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer, Supplier or Agente Aduanal</inlineHelpText>
        <label>Cuenta Origen</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Shipper, Customer, Supply Chain Partner, Supplier Owner or Lessee of Vehicule, Agente Aduanal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders (Supplier/Shipper Account)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Supplier_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Supplier_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Record Type must be Customer or Supplier</inlineHelpText>
        <label>Cuenta Origen</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Supplier/Shipper Account)</relationshipLabel>
        <relationshipName>Shipments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_test_Disbursements.cls
@isTest(seeAllData=true)
private class NEU_test_Disbursements {

    static testMethod void testRedirectWithImportExportId() {
        // Obtener un Customer Quote con cuenta de proveedor relacionada
        List<Customer_Quote__c> quotes = [
            SELECT Id, Name, Supplier_Account__c 
            FROM Customer_Quote__c 
            WHERE Supplier_Account__c != null 
            LIMIT 1
        ];

        Customer_Quote__c quote = quotes[0];

        Test.setCurrentPageReference(new PageReference('Page.myPage'));
        System.currentPageReference().getParameters().put('import_export_id', quote.Id);

        NEU_NewDisbursementButton ndb = new NEU_NewDisbursementButton();
        ndb.redirect();
    }

    static testMethod void testRedirectWithShipmentId() {
        // Obtener un Shipment y su Customer Quote relacionado
        List<Shipment__c> shipments = [
            SELECT Id, Name, Supplier_Account__c 
            FROM Shipment__c 
            WHERE Supplier_Account__c != null 
            LIMIT 1
        ];

        Shipment__c shipment = shipments[0];

        List<Customer_Quote__c> relatedQuotes = [
            SELECT Id, Name 
            FROM Customer_Quote__c 
            WHERE Last_Shipment__c = :shipment.Id 
            LIMIT 1
        ];
        if (relatedQuotes.isEmpty()) return;

        Test.setCurrentPageReference(new PageReference('Page.myPage'));
        System.currentPageReference().getParameters().put('shipment_id', shipment.Id);

        NEU_NewDisbursementButton ndb = new NEU_NewDisbursementButton();
        ndb.redirect();
    }
}