respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Customer_Quote__c.object
<CustomObject>
    <description>Object defining all details of a quote or an order associated to a customer Account. Master object for all preceding Import-Export objects</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect, Prospect Bloq, Prospect Mkt</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Import-Export Quotes Orders (Account for)</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <description>Animation showing mode of Transport dependent on option entered in &quot;Freight Mode&quot;</description>
        <formula>IF(TEXT(Freight_Mode__c) = &apos;Sea&apos;, IMAGE(&apos;/img/icon/custom51_100/ship32.png&apos;, &apos;Sea&apos;), IF(TEXT(Freight_Mode__c) = &apos;Air&apos;, IMAGE(&apos;/img/icon/plane32.png&apos;, &apos;Air&apos;), IF(TEXT(Freight_Mode__c) = &apos;Road&apos;, IMAGE(&apos;/img/icon/custom51_100/truck32.png&apos;, &apos;Road&apos;), IF( TEXT(Freight_Mode__c) = &apos;Rail&apos;, IMAGE(&apos;/img/icon/train32.png&apos;, &apos;Rail&apos;), IF( TEXT(Freight_Mode__c) = &apos;Multimodal&apos;, IMAGE(&apos;/img/icon/custom51_100/ship32.png&apos;, &apos;Multimodal&apos;)&amp; &quot; &quot; &amp; IMAGE(&apos;/img/icon/train32.png&apos;, &apos;Multimodal&apos;) ,&apos;&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Import-Export Quotes/Orders</relationshipLabel>
        <relationshipName>Import_Export_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Quote/Order</label>
    <nameField>
        <label>Import-Export Quote/Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Quote_Item_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of an Import-Export to generate Shipment Cargo Lines.</description>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Import-Export Cargo Lines</relationshipLabel>
        <relationshipName>Import_Export_Cargo_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Cargo Line</label>
    <nameField>
        <label>Imp-Exp Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>ATA__c</fullName>
        <inlineHelpText>Actual Time of Arrival
Fecha y hora Compromiso para Descargar</inlineHelpText>
        <label>ATA</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ATD__c</fullName>
        <inlineHelpText>Actual Time of Departure
Fecha y hora en que la Unidad llegará a Cargar</inlineHelpText>
        <label>ATD</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Container_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Container Type</label>
        <referenceTo>Container_Type__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Departure_Time__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Equip_Loaded__c</fullName>
        <label>Loading Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Equip_Placed__c</fullName>
        <label>Placed Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Equip_Reserved__c</fullName>
        <description>Fecha de cuando llego al destino, se activa por medio de una geocerca</description>
        <label>Unloading Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Equip_Solicited__c</fullName>
        <description>Se llena cuando inicia el proceso de descarga</description>
        <label>Unloading Placed Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Equip_Unloaded__c</fullName>
        <description>Fecha cuando ya se termino la descarga</description>
        <label>Unloaded Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <description>Animation based on &quot;Freight Mode&quot; selection; if &quot;Freight Mode&quot; = Sea then Ship Image, else if &quot;Freight Mode&quot; = Air then Plane Image, else if &quot;Freight Mode&quot; = Road then Truck Image, else if &quot;Freight Mode&quot; = Rail then Train Image, else if &quot;Freight Mode&quot; = Multimodal then Ship and Train Images</description>
        <formula>IF(TEXT(Freight_Mode__c) = &apos;Sea&apos;, IMAGE(&apos;/img/icon/custom51_100/ship32.png&apos;, &apos;Sea&apos;), IF(TEXT(Freight_Mode__c) = &apos;Air&apos;, IMAGE(&apos;/img/icon/plane32.png&apos;, &apos;Air&apos;), IF(TEXT(Freight_Mode__c) = &apos;Road&apos;, IMAGE(&apos;/img/icon/custom51_100/truck32.png&apos;, &apos;Road&apos;), IF( TEXT(Freight_Mode__c) = &apos;Rail&apos;, IMAGE(&apos;/img/icon/train32.png&apos;, &apos;Rail&apos;), IF( TEXT(Freight_Mode__c) = &apos;Multimodal&apos;, IMAGE(&apos;/img/icon/custom51_100/ship32.png&apos;, &apos;Multimodal&apos;)&amp; &quot; &quot; &amp; IMAGE(&apos;/img/icon/train32.png&apos;, &apos;Multimodal&apos;) ,&apos;&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>National_Operator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operator 1</label>
        <referenceTo>Operadores__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments_Route</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Status_Mon__c</fullName>
        <label>Shipment Status Monitoreo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned_M</fullName>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>In Progress_M</fullName>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Awaiting load_M</fullName>
                    <label>Awaiting load</label>
                </value>
                <value>
                    <fullName>Loading_M</fullName>
                    <label>Loading</label>
                </value>
                <value>
                    <fullName>Delivery on Route_M</fullName>
                    <label>Delivery on Route</label>
                </value>
                <value>
                    <fullName>Awaiting Unload_M</fullName>
                    <label>Awaiting Unload</label>
                </value>
                <value>
                    <fullName>Unloading_M</fullName>
                    <label>Unloading</label>
                </value>
                <value>
                    <fullName>Finished_M</fullName>
                    <label>Finished</label>
                </value>
                <value>
                    <fullName>Failure_M</fullName>
                    <label>Failure</label>
                </value>
                <value>
                    <fullName>Incident_M</fullName>
                    <label>Incident</label>
                </value>
                <value>
                    <fullName>Cancel_M</fullName>
                    <label>Cancel</label>
                </value>
                <value>
                    <fullName>In Warehouse_M</fullName>
                    <label>In Warehouse</label>
                </value>
                <value>
                    <fullName>False_M</fullName>
                    <label>False</label>
                </value>
                <value>
                    <fullName>Operative Failure_M</fullName>
                    <label>Operative Failure</label>
                </value>
                <value>
                    <fullName>Robo_M</fullName>
                    <label>Robo</label>
                </value>
                <value>
                    <fullName>Error en Monitoreo_M</fullName>
                    <label>Error en Monitoreo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment_Status_Plann__c</fullName>
        <label>Shipment Status Planner</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Re assigned</fullName>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Rejected PakControl</fullName>
                </value>
                <value>
                    <fullName>Operative Failure</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Delivery on Route</fullName>
                    <isActive>false</isActive>
                    <label>Delivery On Route</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Notes__c</fullName>
        <label>Special Notes 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>VERIFY_PAK_CONTROL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VERIFY PAK CONTROL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Vehicle__c.Account_for_SCP__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Carrier__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PK2_TABLE_MONITOREO.cls
public class PK2_TABLE_MONITOREO {
    public list<Customer_Quote__c> lsMonitoreo {get;set;}
    
    public PK2_TABLE_MONITOREO(){
        Date Lunes = Date.today().toStartOfWeek();
        Date Domingo = Date.today().toStartOfWeek()+6;
        
        lsMonitoreo = [Select Id,
                       Name,
                       Mode__c,
                       Route__r.Name,
                       Container_Type__r.Name,
                       Account_for__r.Name,
                       Last_Shipment__r.VERIFY_PAK_CONTROL__c,
                       Last_Shipment__r.Name,
                       Last_Shipment__c,
                       Last_Shipment__r.Shipment_Status_Plann__c,
                       Last_Shipment__r.Shipment_Status_Mon__c,
                       Last_Shipment__r.Equip_Placed__c,
                       Last_Shipment__r.Equip_Loaded__c,
                       Last_Shipment__r.Departure_Time__c,
                       Last_Shipment__r.ATD__c,
                       Last_Shipment__r.Equip_Reserved__c,
                       Last_Shipment__r.Equip_Solicited__c,
                       Last_Shipment__r.Equip_Unloaded__c,
                       Last_Shipment__r.National_Operator__r.Name,
                       Last_Shipment__r.ATA__c,
                       Last_Shipment__r.Vehicle__r.Name,
                       Last_Shipment__r.Special_Notes__c,
                       (Select Container_Type__r.Name From Import_Export_Items_Lines__r)
                       From Customer_Quote__c Where Name LIKE 'FN-%' and Quotation_Status__c IN ('Shipped') and Last_Shipment__r.Shipment_Status_Plann__c ='Confirmed' and CreatedDate >=:Lunes and CreatedDate <=:Domingo  Order by Quotation_Status__c,ETD__c asc];
    }
}