respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <label>Account for</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Supplier, Customer, Supply Chain Partner</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services Rates (Account for)</relationshipLabel>
        <relationshipName>Fees_Account_for</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Response__c.object
<CustomObject>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Shipment</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Disbursement</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>ShipmentLine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SolOrdenCompraSAP__c</fullName>
        <label>SolOrdenCompraSAP</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>CONFIRM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SAP Response</label>
    <nameField>
        <displayFormat>RE-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Account_for__c</fullName>
        <inlineHelpText>Record Type must be Customer</inlineHelpText>
        <label>Account for (Customer)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer, Prospect</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments (Account for)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ShipmentService__c</fullName>
        <formula>left(Name, 5)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Servicio</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Traslado_Ingreso__c</fullName>
        <label>Tipo de Carta Porte</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ingreso</fullName>
                    <default>true</default>
                    <label>Ingreso</label>
                </value>
                <value>
                    <fullName>Traslado</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <isActive>false</isActive>
                    <label>Normal</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Sea&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058LK&amp;oid=00Db0000000I1t3&amp;lastMod=1358783213000&apos;, &apos;Import - Sea&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Air&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058O4&amp;oid=00Db0000000I1t3&amp;lastMod=1358783262000&apos;, &apos;Import - Air&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Road&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OY&amp;oid=00Db0000000I1t3&amp;lastMod=1358783362000&apos;, &apos;Import - Road&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Rail&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OJ&amp;oid=00Db0000000I1t3&amp;lastMod=1358783317000&apos;, &apos;Import - Rail&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Sea&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058Nz&amp;oid=00Db0000000I1t3&amp;lastMod=1358783241000&apos;, &apos;Export - Sea&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Air&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058O9&amp;oid=00Db0000000I1t3&amp;lastMod=1358783289000&apos;, &apos;Export - Air&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Road&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OU&amp;oid=00Db0000000I1t3&amp;lastMod=1358783382000&apos;, &apos;Export - Road&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Rail&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OT&amp;oid=00Db0000000I1t3&amp;lastMod=1358783338000&apos;, &apos;Export - Rail&apos;), &apos;&apos;))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type (REVISAR)</label>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Orden_Compra__c</fullName>
        <description>orden de compra dada por sap</description>
        <label>Orden de Compra</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Rate_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Name</label>
        <referenceTo>Fee__c</referenceTo>
        <relationshipLabel>Shipment Service Lines</relationshipLabel>
        <relationshipName>Shipment_Service_Lines_Service_Rate_Name</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_CapturaOrdenCompraTest.cls
@isTest(SeeAllData=true)
public class P2G_CapturaOrdenCompraTest {

    @isTest
    static void testMainUpdatesOrdenCompra() {
        List<Shipment_Fee_Line__c> targetLines = [
            SELECT Id, Shipment__c, Orden_Compra__c
            FROM Shipment_Fee_Line__c
            WHERE Orden_Compra__c = NULL
              AND Shipment__c != NULL
              AND Shipment__r.Traslado_Ingreso__c != NULL
              AND (Shipment__r.ShipmentService__c = 'SP-M' OR Shipment__r.ShipmentService__c = 'SP-A')
              AND Shipment__r.account_for__c != NULL
              AND Service_Rate_Name__r.Account_for__c != NULL      
            ORDER BY CreatedDate DESC        
            LIMIT 5
        ];

        Set<Id> shipmentIds = new Set<Id>();
        for (Shipment_Fee_Line__c line : targetLines) {
            shipmentIds.add(line.Shipment__c);
        }

        List<Response__c> newResponses = new List<Response__c>();
        Integer i = 0;
        for (Id shipId : shipmentIds) {
            Response__c res = new Response__c();
            res.Type__c = 'CONFIRM';
            res.SolOrdenCompraSAP__c = 'OC-TEST-' + i;
            res.Object__c = 'Shipment';
            res.Shipment__c = shipId;            
            newResponses.add(res);
            i++;
        }

        insert newResponses;

        Test.startTest();
        P2G_CapturaOrdenCompra.main(newResponses);
        Test.stopTest();

        // Verificar que los Shipment_Fee_Line__c se actualizaron con la Orden de Compra
        List<Shipment_Fee_Line__c> updatedLines = [
            SELECT Id, Orden_Compra__c
            FROM Shipment_Fee_Line__c
            WHERE Id IN :targetLines
        ];
        for (Shipment_Fee_Line__c line : updatedLines) {
            System.assertNotEquals(null, line.Orden_Compra__c, 'La orden de compra debe haberse actualizado');
        }
    }

    @isTest
    static void testMainWithNoMatchingResponses() {
        Shipment__c anyShipment = [
            SELECT Id FROM Shipment__c 
            WHERE Traslado_Ingreso__c != NULL
              AND account_for__c != NULL 
            ORDER BY CreatedDate DESC               
            LIMIT 1
        ];

        Response__c invalidResponse = new Response__c();
        invalidResponse.Type__c = 'ERROR';
        invalidResponse.SolOrdenCompraSAP__c = 'OC-INVALID';
        invalidResponse.Object__c = 'Shipment';
        invalidResponse.Shipment__c = anyShipment.Id;
        insert invalidResponse;

        Test.startTest();
        P2G_CapturaOrdenCompra.main(new List<Response__c>{invalidResponse});
        Test.stopTest();
    }

    @isTest
    static void testMainWithNullShipmentInResponse() {
        Response__c nullShipmentRes = new Response__c();
        nullShipmentRes.Type__c = 'CONFIRM';
        nullShipmentRes.SolOrdenCompraSAP__c = 'OC-IGNORE';
        nullShipmentRes.Object__c = 'Shipment';
        nullShipmentRes.Shipment__c = null;
        insert nullShipmentRes;

        Test.startTest();
        P2G_CapturaOrdenCompra.main(new List<Response__c>{nullShipmentRes});
        Test.stopTest();
    }

    @isTest
    static void testEditOrdenCompraDirectly() {
        Shipment__c anyShipment = [
            SELECT Id 
            FROM Shipment__c 
            WHERE Traslado_Ingreso__c != NULL
              AND account_for__c != NULL 
            ORDER BY CreatedDate DESC                
            LIMIT 1
        ];
        
        List<Shipment_Fee_Line__c> feeLines = [
            SELECT Id, Shipment__c, Orden_Compra__c
            FROM Shipment_Fee_Line__c
            WHERE Shipment__c = :anyShipment.Id
              AND Orden_Compra__c = NULL
            LIMIT 1
        ];
        
        if (!feeLines.isEmpty()) {
            Map<Id, String> testMap = new Map<Id, String>();
            testMap.put(anyShipment.Id, 'OC-DIRECT-TEST');
            
            Test.startTest();
            P2G_CapturaOrdenCompra.editOrdenCompra(feeLines, testMap);
            Test.stopTest();

            // Verificar actualización
            Shipment_Fee_Line__c updatedLine = [SELECT Orden_Compra__c FROM Shipment_Fee_Line__c WHERE Id = :feeLines[0].Id];
            System.assertEquals('OC-DIRECT-TEST', updatedLine.Orden_Compra__c);
        }
    }
}