respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Fee__c</fullName>
        <label>% Service Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Es_de_IEQ__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Es de IEQ</label>
        <type>Checkbox</type>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/p2g_CreateServiceLineShipmentSec2.cls
public class p2g_CreateServiceLineShipmentSec2 {
	@AuraEnabled
    public static List<p2g_CreateServiceLineQuote.quoteFeeLineWrapper> CrearLineQuote(String line, Integer numLinea){
        System.debug('Json que llego: '+ numLinea);
        List<P2G_UpdateShipmentServiceLine.shipmentFeeLineWrapper> listWrapper = P2G_UpdateShipmentServiceLine.CrearListaWrapper(line,numLinea);
        System.debug('La line wrapper: '+ listWrapper);
        //calcular nombre de linea
        Integer NameLine = p2g_CreateServiceLineShipment.CalculoNombreLine(listWrapper[0].ShipmentId);
        List<Fee__c> listaFee = new List<Fee__c>();
        List<Shipment_Fee_Line__c> listaFeeLine = new List<Shipment_Fee_Line__c>();
        List<p2g_CreateServiceLineQuote.quoteFeeLineWrapper> listaRespuesta =new List<p2g_CreateServiceLineQuote.quoteFeeLineWrapper>();
        String message;
        p2g_CreateServiceLineQuote.quoteFeeLineWrapper nuevalinea = new p2g_CreateServiceLineQuote.quoteFeeLineWrapper();
        try{
            System.debug('Entra al try');
            for(P2G_UpdateShipmentServiceLine.shipmentFeeLineWrapper wrapper: listWrapper){
                //Modificar campo devolucion
                Fee__c updateRate = p2g_CreateServiceLineShipment.updateRate(wrapper);
                listaFee.add(updateRate);
                //Crear Lista Service linea
                Shipment_Fee_Line__c feeLine = p2g_CreateServiceLineShipment.CreateServiceLine(NameLine,wrapper);
                feeLine.Es_de_IEQ__c = true; // viene de cotizacion
                listaFeeLine.add(feeLine); //Guardar en lista
                NameLine++;
                system.debug('set: '+listaFee);
                system.debug('line: '+listaFeeLine+' name: '+NameLine);
            }
            //modifucar Rate
            system.debug('fee: '+listaFee);
            Update listaFee;
            //Crear service Line
            System.debug('la lista a modificar de Service Line es: '+listaFeeLine);
            insert listaFeeLine;
            Integer posicion=0;
            for(P2G_UpdateShipmentServiceLine.shipmentFeeLineWrapper wrapper: listWrapper){
                wrapper.Id = listaFeeLine[posicion].Id;
                wrapper.Name = listaFeeLine[posicion].Name;
                nuevalinea = p2g_CreateServiceLineQuote.rellenaSeccion(wrapper);
                listaRespuesta.add(nuevalinea);
                posicion++;
            }
            message='Se realizo la inserción exitosamente';
        }catch(Exception e){
            System.debug('Entra al catch');
            listaRespuesta = null;
            message='Error al realizar la inserción: '+e.getMessage()+e.getLineNumber();
            System.debug('Error al realizar la modificacion: '+e.getMessage()+e.getLineNumber());
        }
        System.debug('lo que devuelve es: '+nuevalinea);
        return listaRespuesta;
    }
}