respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>Fee__c</fullName>
        <label>% Service Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LOT_Url__c</fullName>
        <label>LOT Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LOT__c</fullName>
        <formula>IF( LOT_Url__c!=null,HYPERLINK( MID($Api.Enterprise_Server_URL_300, FIND(&apos;/&apos;,$Api.Enterprise_Server_URL_300,9),FIND( &apos;/services&apos;, $Api.Enterprise_Server_URL_300)- FIND(&apos;/&apos;,$Api.Enterprise_Server_URL_300,9))+LOT_Url__c , IMAGE(&apos;/img/icon/contracts32.png&apos;,&apos;Document&apos;,32,32),&apos;_blank&apos;),null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LOT</label>
        <type>Text</type>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_Upload_LOT_Service_Rate.cls
public with sharing class NEU_Upload_LOT_Service_Rate {

    public Fee__c record;

    public transient Blob documento1{get;set;}
    public transient String documento1name{get;set;}
    
    public NEU_Upload_LOT_Service_Rate(ApexPages.StandardController stdController) {

     if (!Test.isRunningTest()) {
        stdController.AddFields(new String[]
        {
            'Id',
            'Name',
            'LOT__c',
            'LOT_Url__c'
        });
     }
     record=(Fee__c)stdController.getRecord();
    }
    
    public Pagereference upload()
    {
        if(ApexPages.currentPage().getParameters().get('test') != null)
        {
            documento1Name = 'doc1';
        }
        
        List<Folder> directorio_photos = new List<Folder>();
        directorio_photos = [Select Id, Name from Folder where Name='Services Rates'];
        
        //DOCUMENTO1
        Document document=new Document();
        if(documento1Name != '' && documento1Name != null)
        {
            
            document.AuthorId = UserInfo.getUserId();
            if(directorio_photos.size()>0)
                document.FolderId = directorio_photos[0].Id;
            document.IsPublic = true; 
            document.Body=documento1;
            document.Name=documento1Name;
        }

        try 
        {
            if(documento1Name != '' && documento1Name != null)
            {
                insert document;
                record.LOT_Url__c = '/servlet/servlet.FileDownload?file='+document.Id+'&oid=' + UserInfo.getOrganizationId(); 
                update record;
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,'FILE HAVE BEEN UPLOADED CORRECTLY.'));
                documento1=null;
            }
        }  
        catch (DMLException e)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error in File Upload.'));
        }
        return null;
    }
}