respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Fee__c.object
<CustomObject>
    <description>Object used to store all transport fees recorded in the system.</description>
    <fields>
        <fullName>CustomRate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tarifario</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>% Service Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Service Rate</label>
    <nameField>
        <label>Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Import_Export_Fee_Line__c.object
<CustomObject>
    <description>Specifies transport fees associated to an Import-Export. Child object from &quot;Freight Rates Management&quot;</description>
    <fields>
        <fullName>Service_Rate_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Name</label>
        <referenceTo>Fee__c</referenceTo>
        <relationshipLabel>Import-Export Service Lines</relationshipLabel>
        <relationshipName>Import_Export_Fees_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Import-Export Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Import-Export Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Service_Rate_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Name</label>
        <referenceTo>Fee__c</referenceTo>
        <relationshipLabel>Shipment Service Lines</relationshipLabel>
        <relationshipName>Shipment_Service_Lines_Service_Rate_Name</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_ImpExpSerLinCurrency_Handler.cls
public class P2G_ImpExpSerLinCurrency_Handler {    
    //Actualizamos el campo CurrencyIsoCode del objetoa Service Rate
    public static void updateCurrencyIsoCodeImpExpSerLin(List<Import_Export_Fee_Line__c> newRecords, Map<Id, Import_Export_Fee_Line__c> oldMap){
        List<Fee__c> serviceRateList = new List<Fee__c>();
        for (Import_Export_Fee_Line__c impExpServiceLine : newRecords) {
        	Import_Export_Fee_Line__c oldRecord = oldMap.get(impExpServiceLine.Id);            
            if(oldRecord!=null && impExpServiceLine.CurrencyIsoCode!=oldRecord.CurrencyIsoCode){
            	if (impExpServiceLine.Service_Rate_Name__c != null && impExpServiceLine.Service_Rate_Name__r.CustomRate__c==false) {
                    serviceRateList.add(new Fee__c(
                            Id = impExpServiceLine.Service_Rate_Name__c,
                            CurrencyIsoCode = impExpServiceLine.CurrencyIsoCode
                    ));
                }
            }
        }
		
        if(!serviceRateList.isEmpty()){
            updateCurrencyIsoCodeByServiceRate(serviceRateList);
            update serviceRateList;
        }
        
    }
    
    //Actualizamos el campo CurrencyIsoCode del objeto Shipment Service Line
    public static void updateCurrencyIsoCodeByServiceRate(List<Fee__c> serviceRateList){
        Map<Id,String> mapServiceRate= new Map<Id,String>();
        SET<String> servRateIds = new SET<String>();
        for(Fee__c servRate: serviceRateList){
            mapServiceRate.put(servRate.Id,servRate.CurrencyIsoCode);
            servRateIds.add(servRate.Id);
        }
        
        List<Shipment_Fee_Line__c> spSLList=
            [SELECT Id, CurrencyIsoCode, Service_Rate_Name__c FROM Shipment_Fee_Line__c
            WHERE Service_Rate_Name__c in : servRateIds];
        
        for(Shipment_Fee_Line__c sp: spSLList){
            if(sp.CurrencyIsoCode!=mapServiceRate.get(sp.Service_Rate_Name__c)){
				sp.CurrencyIsoCode=mapServiceRate.get(sp.Service_Rate_Name__c);
            }
        }
        
        if(!spSLList.isEmpty()){
            update spSLList;
        }
    }
}