respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Invoice__c.object
<CustomObject>
    <description>Object defining all details of an invoice, as specified on Account detail and through the Import-Export Quote/Order</description>
    <fields>
        <fullName>Campo_Control__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campo para el monitoreo y control de registros bloqueados por parte de SAP</description>
        <label>Campo Control</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Send to Sap</fullName>
                </value>
                <value>
                    <fullName>Received from Sap</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Facturado</fullName>
                </value>
                <value>
                    <fullName>Cobrado</fullName>
                </value>
                <value>
                    <fullName>Cobrado parcial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Timbrado_Factura_SAP__c</fullName>
        <label>Timbrado Factura SAP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <recordTypes>
        <fullName>Invoice</fullName>
        <active>true</active>
        <label>Invoice</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Campo_Control__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campo para el monitoreo y control de registros bloqueados por parte de SAP</description>
        <label>Campo Control</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shipment_Service_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Base Shipment Service Line</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Shipment__c</field>
                <operation>equals</operation>
                <valueField>Shipment_Fee_Line__c.Shipment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Shipment_Fee_Line__c</referenceTo>
        <relationshipLabel>Shipment Service Lines</relationshipLabel>
        <relationshipName>Shipment_Service_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_InvoiceHandlerService.cls
public class P2G_InvoiceHandlerService {

    public Invoice__c getInvoice(String invoiceId) {
        if (String.isBlank(invoiceId)) return null;

        return [
            SELECT Id, Invoice_Status__c, Shipment__c, Timbrado_Factura_SAP__c 
            FROM Invoice__c 
            WHERE Id = :invoiceId
            LIMIT 1
        ];
    }

    public Set<String> getShipmentServiceLineByInvoiceId(String invoiceId) {
        Set<String> ids = new Set<String>();
        if (String.isBlank(invoiceId)) return ids;

        for (Invoice_Line__c line : [
            SELECT Shipment_Service_Line__c 
            FROM Invoice_Line__c 
            WHERE Invoice__c = :invoiceId
        ]) {
            if (line.Shipment_Service_Line__c != null) ids.add(line.Shipment_Service_Line__c);
        }
        return ids;
    }

    public Boolean updateInvoice(Invoice__c invoice, P2G_CancelacionInvoiceController.DataFactura datosFactura) {
        if(invoice != null){
            invoice.Invoice_Status__c = 'Cancel';
        	update invoice;
            return true;
        }
        /*if (invoice != null || (datosFactura.UUID == invoice.Timbrado_Factura_SAP__c)){
        	invoice.Invoice_Status__c = datosFactura.statusFactura;
        	update invoice;    
        } */        
        return false;
    }

    public void updateShipmentServiceLine(Set<String> ids) {
        if (ids == null || ids.isEmpty()) return;

        List<Shipment_Fee_Line__c> lines = [
            SELECT Id, Campo_Control__c 
            FROM Shipment_Fee_Line__c 
            WHERE Id IN :ids
        ];

        for (Shipment_Fee_Line__c line : lines) {
            line.Campo_Control__c = false;
        }
        update lines;
    }
}