respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Invoice__c.object
<CustomObject>
    <description>Object defining all details of an invoice, as specified on Account detail and through the Import-Export Quote/Order</description>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type</valueSetName>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <recordTypes>
        <fullName>Invoice</fullName>
        <active>true</active>
        <label>Invoice</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Response__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipName>Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Shipment</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Disbursement</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>ShipmentLine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>CONFIRM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SAP Response</label>
    <nameField>
        <displayFormat>RE-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Sea&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058LK&amp;oid=00Db0000000I1t3&amp;lastMod=1358783213000&apos;, &apos;Import - Sea&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Air&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058O4&amp;oid=00Db0000000I1t3&amp;lastMod=1358783262000&apos;, &apos;Import - Air&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Road&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OY&amp;oid=00Db0000000I1t3&amp;lastMod=1358783362000&apos;, &apos;Import - Road&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Rail&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OJ&amp;oid=00Db0000000I1t3&amp;lastMod=1358783317000&apos;, &apos;Import - Rail&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Sea&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058Nz&amp;oid=00Db0000000I1t3&amp;lastMod=1358783241000&apos;, &apos;Export - Sea&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Air&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058O9&amp;oid=00Db0000000I1t3&amp;lastMod=1358783289000&apos;, &apos;Export - Air&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Road&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OU&amp;oid=00Db0000000I1t3&amp;lastMod=1358783382000&apos;, &apos;Export - Road&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Rail&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OT&amp;oid=00Db0000000I1t3&amp;lastMod=1358783338000&apos;, &apos;Export - Rail&apos;), &apos;&apos;))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type (REVISAR)</label>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Debit Note</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Note</fullName>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/P2G_LastSAPResponseErrorTest.cls
@isTest
public class P2G_LastSAPResponseErrorTest {
	
    @isTest(SeeAllData=true)
    static void mainTestErrorTrigger(){
        Invoice__c invoice= [SELECT Id FROM Invoice__c LIMIT 1];
        
        Response__c res= new Response__c();
        res.Invoice__c=invoice.Id;
        res.Object__c='Invoice';
        res.Type__c='ERROR';
        res.Message__c='Error';
        insert res;                
        Test.startTest();
        P2G_LastSAPResponseError.mainTrigger(res);
        Test.stopTest();
    }
    
    @isTest(SeeAllData=true)
    static void mainTestConfirmTrigger(){
        Invoice__c invoice= [SELECT Id FROM Invoice__c LIMIT 1];        
        Response__c res= new Response__c();
        res.Invoice__c=invoice.Id;
        res.Object__c='Invoice';
        res.Type__c='CONFIRM';
        res.Message__c='Confirm';
        insert res;                        
        Test.startTest();
        P2G_LastSAPResponseError.mainTrigger(res);
        Test.stopTest();
    }
    
    @isTest(SeeAllData=true)
    static void mainTestErrorInvoice(){
        Response__c res= [SELECT Id, Invoice__c FROM Response__c WHERE Invoice__c!=null and Type__c='ERROR' LIMIT 1];
        PAK_WSMESSAGES.MESSAGE msg = new PAK_WSMESSAGES.MESSAGE();
        msg.Message='Class.: line , column 1: Update failed. First exception on row 0 with id; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION';
        msg.Invoice=res.Invoice__c;
        Test.startTest();
       	P2G_LastSAPResponseError.main(msg);
        Test.stopTest();
        
    }
    
    @isTest(SeeAllData=true)
    static void mainTestConfirmInvoice(){
        Response__c res= [SELECT Id, Invoice__c FROM Response__c WHERE Invoice__c!=null and Type__c='CONFIRM' LIMIT 1];
        PAK_WSMESSAGES.MESSAGE msg = new PAK_WSMESSAGES.MESSAGE();
        msg.Message='Orden de Venta Actualizada: 00002';
        msg.Invoice=res.Invoice__c;
        Test.startTest();
       	P2G_LastSAPResponseError.main(msg);
        Test.stopTest();
    }
    @isTest(SeeAllData=true)
    static void mainTestErrorShipment(){
        Response__c res= [SELECT Id, Shipment__c FROM Response__c WHERE Shipment__c!=null and Type__c='ERROR' LIMIT 1];
        PAK_WSMESSAGES.MESSAGE msg = new PAK_WSMESSAGES.MESSAGE();
        msg.Message='Class.: line 66, column 1: Update failed. First exception on row 0 with id; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION';
        msg.Shipment=res.Shipment__c;
        Test.startTest();
       	P2G_LastSAPResponseError.main(msg);
        Test.stopTest();
    }
    
    @isTest(SeeAllData=true)
    static void mainTestConfirmShipment(){
        Response__c res= [SELECT Id, Shipment__c FROM Response__c WHERE Shipment__c!=null and Type__c='CONFIRM' LIMIT 1];
        PAK_WSMESSAGES.MESSAGE msg = new PAK_WSMESSAGES.MESSAGE();
        msg.Message='Orden de Venta Actualizada: 00002';
        msg.Shipment=res.Shipment__c;
        Test.startTest();
       	P2G_LastSAPResponseError.main(msg);
        Test.stopTest();
    }
}