respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Location__c.object
<CustomObject>
    <description>Object used to define locations within given countries. Can be automatically generated from First Steps https://c.eu11.visual.force.com/apex/NEU_First_Steps</description>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Country_of_Discharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Discharge</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Shipments (Country of Discharge)</relationshipLabel>
        <relationshipName>Shipments_Country_of_Discharge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Load</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Shipments (Country of Load)</relationshipLabel>
        <relationshipName>Shipments_Country_of_Load</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_of_Discharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>PORT for Sea, AIRPORT for Air, TERMINAL SITE for Road and Rail.
Dependent on &quot;Country of Discharge&quot;</inlineHelpText>
        <label>Site of Discharge</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>$Source.Country_of_Discharge__c</field>
                <operation>equals</operation>
                <valueField>Location__c.Country__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.State_of_Discharge__c</field>
                <operation>equals</operation>
                <valueField>Location__c.State__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.State__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Shipments (Site of Discharge)</relationshipLabel>
        <relationshipName>Shipments_Site_of_Discharge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>PORT for Sea, AIRPORT for Air, TERMINAL SITE for Road and Rail.
Dependent on &quot;Country of Load&quot;</inlineHelpText>
        <label>Site of Load</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>$Source.Country_of_Load__c</field>
                <operation>equals</operation>
                <valueField>Location__c.Country__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.State_of_Load__c</field>
                <operation>equals</operation>
                <valueField>Location__c.State__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.State__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Shipments (Site of Load)</relationshipLabel>
        <relationshipName>Shipments_Site_of_Load</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_of_Discharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State of Discharge</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country_of_Discharge__c</field>
                <operation>equals</operation>
                <valueField>State__c.Country__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Shipments (State of Discharge)</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State of Load</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country_of_Load__c</field>
                <operation>equals</operation>
                <valueField>State__c.Country__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Shipments (State of Load)</relationshipLabel>
        <relationshipName>Shipments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_TrackTraceShipmentTest.cls
@isTest(SeeAllData=true)
public class NEU_TrackTraceShipmentTest {
    
    @isTest
    static void test_getShipment() {
        // Obtiene un Shipment__c real de la org
        Shipment__c shipment = [SELECT Id FROM Shipment__c LIMIT 1];
        Test.startTest();
        Shipment__c result = NEU_TrackTraceShipment.getShipment(shipment.Id);
        System.assertNotEquals(null, result, 'El Shipment no debe ser null');
        Test.stopTest();
    }

    @isTest
    static void test_getShipmentTrack() {
        // Obtiene un Shipment__c real de la org con un Shipment_Track__c asociado (si existe)
        Shipment__c shipment = [SELECT Id FROM Shipment__c LIMIT 1];
        Test.startTest();
        Shipment_Track__c result = NEU_TrackTraceShipment.getShipmentTrack(shipment.Id);
        Test.stopTest();
    }

    @isTest
    static void test_getRoadData() {
        // Obtiene un Shipment__c real de la org con paradas
        Shipment__c shipment = [SELECT Id FROM Shipment__c LIMIT 1];
        List<Shipment_Stop__c> stops = [SELECT Id FROM Shipment_Stop__c WHERE Shipment__c = :shipment.Id LIMIT 1];
        
        Test.startTest();
        List<Shipment_Stop__c> result = NEU_TrackTraceShipment.getRoadData(shipment.Id);
        Test.stopTest();
    }

    @isTest
    static void test_getRoutePoints() {
        // Obtiene un Shipment__c real de la org con relaciones necesarias
        Shipment__c shipment = [SELECT Id, 
            Country_of_Load__r.Name, 
            State_of_Load__r.Name, 
            Site_of_Load__r.Name, 
            Country_of_Discharge__r.Name, 
            State_of_Discharge__r.Name, 
            Site_of_Discharge__r.Name 
            FROM Shipment__c 
            WHERE Country_of_Load__r.Name != null AND 
                  State_of_Load__r.Name != null AND 
                  Site_of_Load__r.Name != null AND 
                  Country_of_Discharge__r.Name != null AND 
                  State_of_Discharge__r.Name != null AND 
                  Site_of_Discharge__r.Name != null
            LIMIT 1];
        
        Test.startTest();
        List<NEU_TrackTraceShipment.Route_Point_s> points = NEU_TrackTraceShipment.getRoutePoints(shipment);
    }
}