respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Location__c.object
<CustomObject>
    <description>Object used to define locations within given countries. Can be automatically generated from First Steps https://c.eu11.visual.force.com/apex/NEU_First_Steps</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>State__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Location Default</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Country_of_Discharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Discharge</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Shipments (Country of Discharge)</relationshipLabel>
        <relationshipName>Shipments_Country_of_Discharge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country of Load</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Shipments (Country of Load)</relationshipLabel>
        <relationshipName>Shipments_Country_of_Load</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direccion_Monitoreo__c</fullName>
        <label>Direccion Monitoreo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>OI Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_of_Discharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>PORT for Sea, AIRPORT for Air, TERMINAL SITE for Road and Rail.
Dependent on &quot;Country of Discharge&quot;</inlineHelpText>
        <label>Site of Discharge</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>$Source.Country_of_Discharge__c</field>
                <operation>equals</operation>
                <valueField>Location__c.Country__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.State_of_Discharge__c</field>
                <operation>equals</operation>
                <valueField>Location__c.State__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.State__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Shipments (Site of Discharge)</relationshipLabel>
        <relationshipName>Shipments_Site_of_Discharge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_of_Load__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>PORT for Sea, AIRPORT for Air, TERMINAL SITE for Road and Rail.
Dependent on &quot;Country of Load&quot;</inlineHelpText>
        <label>Site of Load</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>$Source.Country_of_Load__c</field>
                <operation>equals</operation>
                <valueField>Location__c.Country__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.State_of_Load__c</field>
                <operation>equals</operation>
                <valueField>Location__c.State__c</valueField>
            </filterItems>
            <filterItems>
                <field>Location__c.State__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Shipments (Site of Load)</relationshipLabel>
        <relationshipName>Shipments_Site_of_Load</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>States</relationshipLabel>
        <relationshipName>States</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_AirTrackTrace.cls
public with sharing class NEU_AirTrackTrace 
{
    public Shipment__c record;
    public string direccion_origen {get;set;}
    public string direccion_destino {get;set;}
    public string direcciones_recogidas {get;set;}
    public string truck_last_position {get;set;}
    
    ApexPages.StandardController con;
     
    public NEU_AirTrackTrace(ApexPages.StandardController stdController) 
    {
        con = stdController;
              
        try 
        { 
            record = [select Id, Name, Site_of_Load__c, Site_of_Load__r.Name, Country_of_Load__c, Country_of_Load__r.Name, Site_of_Discharge__c, Site_of_Discharge__r.Name,
            Country_of_Discharge__c, Country_of_Discharge__r.Name, Direccion_Monitoreo__c
            from Shipment__c where Id =: con.getRecord().id];
        } 
        catch(Exception ee){record = new Shipment__c();}
        
        List<Shipment_Stop__c> shipment_stops = [SELECT Id, Name, Country__c, State__c, Location__c, Address__c, Country__r.Name, State__r.Name, Location__r.Name
       	FROM Shipment_Stop__c WHERE Shipment__c =: record.Id limit 7];
       	
       	List<Truck_Position__c> truck_positions = [SELECT Id, Name, Country__c, State__c, Location__c, Address__c, Country__r.Name, State__r.Name, Location__r.Name
       	FROM Truck_Position__c WHERE Shipment__c =: record.Id ORDER BY Date_Time_Reported__c DESC limit 1];
       	
       	Integer TIMEOUT = 50000;

       	//DIRECCIONES
        direccion_origen = '';
        direccion_destino = '';
        direcciones_recogidas = '';
        truck_last_position = '';
        
        direccion_origen = (record.Site_of_Load__c != null ? record.Site_of_Load__r.Name : '')+', '+(record.Country_of_Load__c != null ? record.Country_of_Load__r.Name : '');
        direccion_destino = (record.Site_of_Discharge__c != null ? record.Site_of_Discharge__r.Name : '')+', '+(record.Country_of_Discharge__c != null ? record.Country_of_Discharge__r.Name : '');
            
        //ORIGIN
        if(direccion_origen != '')
        {
	        direcciones_recogidas += (record.Site_of_Load__c != null ? record.Site_of_Load__r.Name : '')+', '+(record.Country_of_Load__c != null ? record.Country_of_Load__r.Name : '')+'|';
	        direcciones_recogidas += '/sfsites/c/resource/origin_icon|';
	        
	        //COORDINATES
			Http h = new Http(); 
			HttpRequest req = new HttpRequest();
			req.setEndpoint('https://maps.googleapis.com/maps/api/geocode/json?address='+direccion_origen.replace(' ','+')+'&key=AIzaSyAK8UqXuiT9IFTwkvhF-Nh1wS2JAdk6Fig'); 
			req.setMethod('GET');
			req.setTimeout(TIMEOUT);
			HttpResponse res;
			if (!Test.isRunningTest())
				res = h.send(req); 
			
			if(res != null && res.getBody() != null)
        	{
        		JSONParser parser = JSON.createParser(res.getBody());
        		
        		while(parser.nextToken() != null)
        		{
        			if((parser.getCurrentToken() == JSONToken.FIELD_NAME) && (parser.getText() == 'location')) 
		        	{
		                parser.nextToken();
			            parser.nextToken();
			            parser.nextToken();
			            
			            //LATITUDE
			            direcciones_recogidas += (parser.getText() != null ? double.valueof(parser.getText()) : 0)+'|';
			            
			            parser.nextToken();
			            parser.nextToken();
			            
			            //LONGITUDE
			            direcciones_recogidas += (parser.getText() != null ? double.valueof(parser.getText()) : 0)+';';
			            
			            break;
		            }
        		}
        	}
        }
		
        //DESTINATION
        if(direccion_destino != '')
        {
	       	direcciones_recogidas += (record.Site_of_Discharge__c != null ? record.Site_of_Discharge__r.Name : '')+', '+(record.Country_of_Discharge__c != null ? record.Country_of_Discharge__r.Name : '')+'|';
	        direcciones_recogidas += '/sfsites/c/resource/destination_icon|';
	        
	        //COORDINATES
    		Http h = new Http(); 
			HttpRequest req = new HttpRequest();
			req.setEndpoint('https://maps.googleapis.com/maps/api/geocode/json?address='+direccion_destino.replace(' ','+')+'&key=AIzaSyAK8UqXuiT9IFTwkvhF-Nh1wS2JAdk6Fig'); 
			req.setMethod('GET');
			req.setTimeout(TIMEOUT);
			HttpResponse res;
			if (!Test.isRunningTest())
				res = h.send(req); 
			
			if(res != null && res.getBody() != null)
        	{
        		JSONParser parser = JSON.createParser(res.getBody());
        		
        		while(parser.nextToken() != null)
        		{
        			if((parser.getCurrentToken() == JSONToken.FIELD_NAME) && (parser.getText() == 'location')) 
		        	{
		                parser.nextToken();
			            parser.nextToken();
			            parser.nextToken();
			            
			            //LATITUDE
			            direcciones_recogidas += (parser.getText() != null ? double.valueof(parser.getText()) : 0)+'|';
			            
			            parser.nextToken();
			            parser.nextToken();
			            
			            //LONGITUDE
			            direcciones_recogidas += (parser.getText() != null ? double.valueof(parser.getText()) : 0);
			            
			            break;
		            }
        		}
        	}
        }
    }
}