respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SP-FN-FLETE NACIONAL</fullName>
                </value>
                <value>
                    <fullName>SP-FI-FLETE INTER</fullName>
                </value>
                <value>
                    <fullName>SP-A-AEREO</fullName>
                </value>
                <value>
                    <fullName>SP-AW-GLOBAL AEREO</fullName>
                </value>
                <value>
                    <fullName>SP-CE-COMERCIO EXT</fullName>
                </value>
                <value>
                    <fullName>SP-EX-SEGUROS</fullName>
                </value>
                <value>
                    <fullName>SP-M-MARITIMO</fullName>
                </value>
                <value>
                    <fullName>SP-PQ-PAQUETERIA</fullName>
                </value>
                <value>
                    <fullName>SP-PTO-PUERTOS</fullName>
                </value>
                <value>
                    <fullName>SP-R-GLOBAL ROUTING</fullName>
                </value>
                <value>
                    <fullName>SP-SL-SERV LOGISTICO</fullName>
                </value>
                <value>
                    <fullName>SP-T-CONSOLIDADO</fullName>
                </value>
                <value>
                    <fullName>SP-W-GLOBAL MARITIMO</fullName>
                </value>
                <value>
                    <fullName>SP-WH-ALMACENAJE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cotizada</fullName>
                </value>
                <value>
                    <fullName>No Cotizada</fullName>
                </value>
                <value>
                    <fullName>Pendiente por Cotizar</fullName>
                    <default>true</default>
                    <label>Pendiente por Cotizar</label>
                </value>
                <value>
                    <fullName>Rechazada</fullName>
                </value>
                <value>
                    <fullName>Aceptada</fullName>
                </value>
                <value>
                    <fullName>Negociación con cliente</fullName>
                </value>
                <value>
                    <fullName>Cerrada</fullName>
                    <isActive>false</isActive>
                    <label>Cerrada</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tipo_de_moneda__c</fullName>
        <description>Colocar el tipo de moneda con el cual se tiene que hacer la cotizacion</description>
        <label>Tipo de moneda</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MXN</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/SubProducto__c/SubProducto__c.object-meta.xml
<CustomObject>
    <label>SubProducto</label>
    <nameField>
        <label>Cargo Adicional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubProductos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubProducto__c/fields/SAP_Service_Type_Buy__c.field-meta.xml
<CustomField>
    <fullName>SAP_Service_Type_Buy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SAP Service Type Buy</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.SubProduct_Grupo_Oportunidad__c</field>
            <operation>equals</operation>
            <valueField>SAP_Service_Type__c.Group__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SAP_Service_Type__c</referenceTo>
    <relationshipLabel>SubProductos (SAP Service Type Buy)</relationshipLabel>
    <relationshipName>SubProductos1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cotizada</fullName>
            </value>
            <value>
                <fullName>No Cotizada</fullName>
            </value>
            <value>
                <fullName>Pendiente por Cotizar</fullName>
                <default>true</default>
                <label>Pendiente por Cotizar</label>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
            <value>
                <fullName>Aceptada</fullName>
            </value>
            <value>
                <fullName>Negociación con cliente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/SubProduct_Buy_Price__c.field-meta.xml
<CustomField>
    <fullName>SubProduct_Buy_Price__c</fullName>
    <label>Buy Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/SubProduct_Grupo_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>SubProduct_Grupo_Oportunidad__c</fullName>
    <label>Grupo Oportunidad</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SP-FN-FLETE NACIONAL</fullName>
            </value>
            <value>
                <fullName>SP-FI-FLETE INTER</fullName>
            </value>
            <value>
                <fullName>SP-A-AEREO</fullName>
            </value>
            <value>
                <fullName>SP-CE-COMERCIO EXT</fullName>
            </value>
            <value>
                <fullName>SP-M-MARITIMO</fullName>
            </value>
            <value>
                <fullName>SP-PTO-PUERTOS</fullName>
            </value>
            <value>
                <fullName>SP-R-GLOBAL ROUTING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/SubProduct_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>SubProduct_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>SubProductos</relationshipLabel>
    <relationshipName>SubProductos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/SubProduct_Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>SubProduct_Opportunity_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>SubProductos</relationshipLabel>
    <relationshipName>SubProductos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/SubProduct_Sell_Price__c.field-meta.xml
<CustomField>
    <fullName>SubProduct_Sell_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Campo que permite a los equipos comerciales colocar el precio de venta</description>
    <label>Sell Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/Tipo_de_moneda__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_moneda__c</fullName>
    <label>Tipo de moneda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/triggerOppoProducYSubproducTest.cls
@isTest(SeeAllData=true)
public class triggerOppoProducYSubproducTest {
	@isTest
    static void prueba() {
        List<SubProducto__c> subProd = [SELECT Id, Name, SubProduct_Opportunity_Product__c, SubProduct_Opportunity__c,SubProducto__c.SubProduct_Grupo_Oportunidad__c,
                                  SubProduct_Opportunity_Product__r.Status__c, Status__c,SubProduct_Opportunity__r.Group__c FROM SubProducto__c
                                       WHERE SubProduct_Sell_Price__c != null AND SAP_Service_Type_Buy__c != null AND SubProduct_Grupo_Oportunidad__c != null 
                                        AND id =: 'a3CRQ000009iKib2AE'];
        Sap_Service_Type__c service = [SELECT Id, Name, Group__c FROM Sap_Service_Type__c 
                                                       WHERE Name LIKE : '%cargo%' AND Group__c =: subProd[0].SubProduct_Grupo_Oportunidad__c limit 1];
        List<String> idOppo = new List<String>();
        for(SubProducto__c sub: subProd){
            idOppo.add(sub.SubProduct_Opportunity__c);
        }
        OpportunityLineItem oliUpdate = new OpportunityLineItem();
        oliUpdate.Id = subProd[0].SubProduct_Opportunity_Product__c;
        oliUpdate.Status__c = 'Cotizada';
        oliUpdate.Tipo_de_moneda__c = 'EUR';
        update oliUpdate;
        SubProducto__c sub = new SubProducto__c();
        sub.Id = subProd[0].Id;
        sub.Status__c = 'Cotizada';
        sub.Tipo_de_moneda__c = 'USD';
        sub.CurrencyIsoCode = 'MXN';
        sub.SubProduct_Sell_Price__c = 2340;
        sub.SubProduct_Buy_Price__c = 3490;
        update sub;
        oliUpdate.Id = subProd[0].SubProduct_Opportunity_Product__c;
        oliUpdate.Status__c = 'Negociación con cliente';
        update oliUpdate;
    }
}