respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Buy_Price__c</fullName>
        <label>Buy Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tipo_de_moneda__c</fullName>
        <description>Colocar el tipo de moneda con el cual se tiene que hacer la cotizacion</description>
        <label>Tipo de moneda</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MXN</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/SubProducto__c/SubProducto__c.object-meta.xml
<CustomObject>
    <label>SubProducto</label>
    <nameField>
        <label>Cargo Adicional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubProductos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubProducto__c/fields/SubProduct_Buy_Price__c.field-meta.xml
<CustomField>
    <fullName>SubProduct_Buy_Price__c</fullName>
    <label>Buy Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/SubProduct_Grupo_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>SubProduct_Grupo_Oportunidad__c</fullName>
    <label>Grupo Oportunidad</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SP-FN-FLETE NACIONAL</fullName>
            </value>
            <value>
                <fullName>SP-FI-FLETE INTER</fullName>
            </value>
            <value>
                <fullName>SP-A-AEREO</fullName>
            </value>
            <value>
                <fullName>SP-CE-COMERCIO EXT</fullName>
            </value>
            <value>
                <fullName>SP-M-MARITIMO</fullName>
            </value>
            <value>
                <fullName>SP-PTO-PUERTOS</fullName>
            </value>
            <value>
                <fullName>SP-R-GLOBAL ROUTING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/SubProduct_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>SubProduct_Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>SubProductos</relationshipLabel>
    <relationshipName>SubProductos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/SubProduct_Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>SubProduct_Opportunity_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>SubProductos</relationshipLabel>
    <relationshipName>SubProductos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/SubProduct_SAP_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>SubProduct_SAP_Service_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SAP Service Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.SubProduct_Grupo_Oportunidad__c</field>
            <operation>equals</operation>
            <valueField>SAP_Service_Type__c.Group__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SAP_Service_Type__c</referenceTo>
    <relationshipLabel>SubProductos</relationshipLabel>
    <relationshipName>SubProductos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/SubProduct_Sell_Price__c.field-meta.xml
<CustomField>
    <fullName>SubProduct_Sell_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Campo que permite a los equipos comerciales colocar el precio de venta</description>
    <label>Sell Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SubProducto__c/fields/Tipo_de_moneda__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_moneda__c</fullName>
    <label>Tipo de moneda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/P2G_convertCurrencyOppoProductTest.cls
@isTest
public class P2G_convertCurrencyOppoProductTest {
@isTest(SeeAllData=true)
    public static void load(){
        OpportunityLineItem convertEUR = P2G_convertCurrencyOppoProduct.actualizarBuyPriceCurrency('Sales Price', 23, 'MXN', 'EUR');
        OpportunityLineItem convertUSD = P2G_convertCurrencyOppoProduct.actualizarBuyPriceCurrency('Buy Price', 23, 'EUR', 'USD');
        
        OpportunityLineItem oli = [SELECT Id, OpportunityId FROM OpportunityLineItem WHERE Opportunity.Account.Name LIKE : '%Ejemplo%' LIMIT 1];
        oli.Buy_Price__c = 39;
        oli.UnitPrice = 20;
        oli.Tipo_de_moneda__c = 'USD';
        update oli;
        
        SubProducto__c subProEURBuy = P2G_convertCurrencyOppoProduct.convertirBuySubProducto(23.12, 'MXN', 'EUR');
        SubProducto__c subProUSDBuy = P2G_convertCurrencyOppoProduct.convertirBuySubProducto(23.12, 'EUR', 'USD');
        SubProducto__c subProEURSell = P2G_convertCurrencyOppoProduct.convertirSellSubProducto(23.12, 'MXN', 'EUR');
        SubProducto__c subProUSDSell = P2G_convertCurrencyOppoProduct.convertirSellSubProducto(23.12, 'EUR', 'USD');
        
        SubProducto__c subProducto = new SubProducto__c();
        subProducto.Name = 'Carga Adicional';
        subProducto.SubProduct_Opportunity__c = oli.OpportunityId;
        subProducto.SubProduct_Opportunity_Product__c = oli.Id;
        subProducto.SubProduct_Grupo_Oportunidad__c = 'SP-FN-FLETE NACIONAL';
        subProducto.SubProduct_SAP_Service_Type__c = 'a1n4T000001XXY6QAO';//UAT a1n0R000001lZcYQAU  Prod a1n4T000001XXY6QAO
        subProducto.CurrencyIsoCode = 'EUR';
        subProducto.SubProduct_Buy_Price__c = 23;
        subProducto.SubProduct_Sell_Price__c = 23;
        insert subProducto;
        subProducto.CurrencyIsoCode = 'EUR';
        subProducto.SubProduct_Buy_Price__c = 32;
        subProducto.SubProduct_Sell_Price__c = 32;
        update subProducto;
    }
}