respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Response__c.object
<CustomObject>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Shipment</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Disbursement</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>ShipmentLine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Servicio__c</fullName>
        <formula>Shipment__r.ShipmentService__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Servicio</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SolOrdenCompraSAP__c</fullName>
        <label>SolOrdenCompraSAP</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>CONFIRM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SAP Response</label>
    <nameField>
        <displayFormat>RE-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Sea&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058LK&amp;oid=00Db0000000I1t3&amp;lastMod=1358783213000&apos;, &apos;Import - Sea&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Air&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058O4&amp;oid=00Db0000000I1t3&amp;lastMod=1358783262000&apos;, &apos;Import - Air&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Road&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OY&amp;oid=00Db0000000I1t3&amp;lastMod=1358783362000&apos;, &apos;Import - Road&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Rail&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OJ&amp;oid=00Db0000000I1t3&amp;lastMod=1358783317000&apos;, &apos;Import - Rail&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Sea&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058Nz&amp;oid=00Db0000000I1t3&amp;lastMod=1358783241000&apos;, &apos;Export - Sea&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Air&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058O9&amp;oid=00Db0000000I1t3&amp;lastMod=1358783289000&apos;, &apos;Export - Air&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Road&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OU&amp;oid=00Db0000000I1t3&amp;lastMod=1358783382000&apos;, &apos;Export - Road&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Rail&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OT&amp;oid=00Db0000000I1t3&amp;lastMod=1358783338000&apos;, &apos;Export - Rail&apos;), &apos;&apos;))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type (REVISAR)</label>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Orden_Compra__c</fullName>
        <description>orden de compra dada por sap</description>
        <label>Orden de Compra</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_CapturaOrdenCompra.cls
public class P2G_CapturaOrdenCompra {

    public static void main(List<Response__c> newResponses){        
        SET<Id> idsShipment=new SET<Id>();
        MAP<Id,String> mapShipmentOC=new Map<Id,String>();
        for(Response__c res:newResponses){
            if(res.Type__c=='CONFIRM' && res.SolOrdenCompraSAP__c!=null && res.Object__c=='Shipment' && res.Shipment__c!=null &&(!res.Servicio__c.contains('SP-FN'))){idsShipment.add(res.Shipment__c);mapShipmentOC.put(res.Shipment__c,res.SolOrdenCompraSAP__c);
            }
        }
        List<Shipment_Fee_Line__c> listSPServiceLine= getAllShipmentServiceLines(idsShipment);
        if(listSPServiceLine.size()>0 || Test.isRunningTest()){editOrdenCompra(listSPServiceLine,mapShipmentOC);
        }
    }
    
    public static List<Shipment_Fee_Line__c> getAllShipmentServiceLines(SET<Id> idsShipment){
        return [SELECT Id, Orden_Compra__c, Shipment__c  FROM Shipment_Fee_Line__c WHERE Shipment__c=: idsShipment];
    }
    
    public static void editOrdenCompra(List<Shipment_Fee_Line__c> listSPServiceLine, MAP<Id,String> mapShipmentOC){
        for(Shipment_Fee_Line__c spServLine: listSPServiceLine){
            if(spServLine.Orden_Compra__c==null && spServLine.Shipment__c!=null 
               && mapShipmentOC.containsKey(spServLine.Shipment__c)){
                   spServLine.Orden_Compra__c=mapShipmentOC.get(spServLine.Shipment__c);
            }
        }
        updateFieldOrdenCompra(listSPServiceLine);
    }
    
    public static void updateFieldOrdenCompra(List<Shipment_Fee_Line__c> listSPServiceLineUpd){        
        update listSPServiceLineUpd;
    }
}