respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Response__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>CONFIRM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SAP Response</label>
    <nameField>
        <displayFormat>RE-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Sea&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058LK&amp;oid=00Db0000000I1t3&amp;lastMod=1358783213000&apos;, &apos;Import - Sea&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Air&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058O4&amp;oid=00Db0000000I1t3&amp;lastMod=1358783262000&apos;, &apos;Import - Air&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Road&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OY&amp;oid=00Db0000000I1t3&amp;lastMod=1358783362000&apos;, &apos;Import - Road&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Import&apos;, TEXT(Freight_Mode__c) = &apos;Rail&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OJ&amp;oid=00Db0000000I1t3&amp;lastMod=1358783317000&apos;, &apos;Import - Rail&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Sea&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058Nz&amp;oid=00Db0000000I1t3&amp;lastMod=1358783241000&apos;, &apos;Export - Sea&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Air&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058O9&amp;oid=00Db0000000I1t3&amp;lastMod=1358783289000&apos;, &apos;Export - Air&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Road&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OU&amp;oid=00Db0000000I1t3&amp;lastMod=1358783382000&apos;, &apos;Export - Road&apos;), IF(AND(TEXT(Service_Mode__c) = &apos;Export&apos;, TEXT(Freight_Mode__c) = &apos;Rail&apos;) = TRUE, IMAGE(&apos;https://c.eu2.content.force.com/servlet/servlet.ImageServer?id=015b000000058OT&amp;oid=00Db0000000I1t3&amp;lastMod=1358783338000&apos;, &apos;Export - Rail&apos;), &apos;&apos;))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type (REVISAR)</label>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_NoEliminarLineaEnSAP.cls
public class P2G_NoEliminarLineaEnSAP {
    public static void noElimiarLinea(Shipment_Fee_Line__c serviceLine){
        Datetime dateResponse = consultaSapResponse(serviceLine.Shipment__c);
        if(dateResponse != NULL && dateResponse > serviceLine.CreatedDate){
            if(!Test.isRunningTest()){
                serviceLine.addError('No se puede eliminar la línea si ya ha sido enviada a SAP');
            }
        }
    }
    public static Datetime consultaSapResponse(String spId){
        Datetime creacionResponse;
        List<Response__c> response = [SELECT Id, Name, CreatedDate FROM Response__c WHERE Shipment__c =: spId 
                                      AND Type__c = 'CONFIRM' 
                                      AND Message__c != 'Carga correcta en recurso confiable'
                                      Order By CreatedDate desc LIMIT 1];
        if(response.size() > 0){
            creacionResponse = response[0].CreatedDate;
        }else{
            creacionResponse = NULL;
        }
        return creacionResponse;
    }
}