respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Scheduler_Shipment_Services_Lines__c.object
<CustomObject>
    <fields>
        <fullName>Cron_Expression__c</fullName>
        <label>Cron Expression</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cron_Job_Id__c</fullName>
        <label>Cron Job Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Scheduler Shipment Service Line</label>
    <nameField>
        <label>Scheduler Shipment Services Lines Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduler Shipment Services Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RefreshSchedulerReport.cls
public with sharing class RefreshSchedulerReport {
	public Scheduler_Shipment_Services_Lines__c record;
	ApexPages.StandardController con;
	
	public RefreshSchedulerReport(ApexPages.StandardController stdController) {
   		con = stdController;
   	   	system.debug( con.getRecord() );
		try { 
			record = [select Id, Name, Cron_Job_Id__c, Cron_Expression__c from Scheduler_Shipment_Services_Lines__c where id = :con.getRecord().id];
		} 
		catch( Exception ee) { 
			record = new Scheduler_Shipment_Services_Lines__c();
		}
	}
		
	public Pagereference refresh()
	{
		for (CronTrigger t : [select Id from CronTrigger where Id = :record.Cron_Job_Id__c])
		{
			System.abortJob(t.Id);
		}	
		
		record.Cron_Job_Id__c = System.schedule(record.Name, record.Cron_Expression__c, new ProcessSchedulerReport());
  		update record;
		
		PageReference pgReturnPage;
		String returnUrl = '/' + record.Id;
    	pgReturnPage = new PageReference(returnUrl);
        pgReturnPage.setRedirect(true);
		return pgReturnPage;
	}
}