respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Poor</fullName>
                </value>
                <value>
                    <fullName>Average</fullName>
                </value>
                <value>
                    <fullName>Good</fullName>
                </value>
                <value>
                    <fullName>Very Good</fullName>
                </value>
                <value>
                    <fullName>Excellent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PAK_ServiceSurvey.cls
public class PAK_ServiceSurvey {
    public Shipment__c shipment {get;set;}
    public Boolean valid {get;set;}
    
    public PAK_ServiceSurvey(){}
    
    public PageReference validate(){
        valid = true;
        Id shipId = ApexPages.currentPage().getParameters().get('shipId');        
        if(shipId == null){
            PageReference pageRef = new PageReference('/apex/FileNotFound');return pageRef;
        }else{
            shipment = [SELECT Id, Name, Rating__c FROM Shipment__c WHERE Id =:shipId LIMIT 1];
            if(shipment.Rating__c != null){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 'Encuesta ya recibida'));valid = false;
            }
        }
        return null;
    }
    
    public PageReference save() {
        try{
            if(shipment.Rating__c != null){
                update shipment;
                valid = false;
            	ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM, 'Encuesta recibida exitosamente!'));
            }            
        }catch(Exception ex){ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM, ex.getMessage()));
        }
        return null;
    }
}