respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>Equipment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Carrier_Line_Load_Point__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments_Route</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_test_Vessel.cls
@isTest(SeeAllData=true)
private class NEU_test_Vessel {

    @isTest
    static void testConstructorAndFeedMethod() {
        // Buscar un Shipment__c real para pruebas (porque SeeAllData=true)
        Shipment__c shipment = [
            SELECT Id, Name, Route__c, Equipment__c, CurrencyIsoCode 
            FROM Shipment__c 
            WHERE Route__c != null 
            LIMIT 1
        ];

        // Crear el StandardController con el registro real
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(shipment);

        // Ejecutar el constructor
        Test.startTest();
        NEU_Updated_Position_of_Ship controller = new NEU_Updated_Position_of_Ship(stdCtrl);
        Test.stopTest();

        // Llamar a create_feed() (aunque el cuerpo se omite durante test por isRunningTest)
        controller.create_feed();
    }
}