respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Disbursement__c.object
<CustomObject>
    <description>Object specifying all payment history and details along with each Import-Export on each Account</description>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Disbursements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Disbursement</label>
    <nameField>
        <label>Disbursement Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <recordTypes>
        <fullName>Disbursement</fullName>
        <active>true</active>
        <label>Disbursement</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PAK_CANCEL_INV_SERVICETest.cls
@isTest(seeAllData=true)
private class PAK_CANCEL_INV_SERVICETest {
    
    @isTest
    static void testCANCEL_Pedido() {
        Shipment__c shipment = [SELECT Id FROM Shipment__c LIMIT 1];
        
        PAK_Update_ACC.CANCEL_INV cancelInv = new PAK_Update_ACC.CANCEL_INV();
        cancelInv.Tipo = 'PEDIDO';
        cancelInv.IdInovice = shipment.Id;
        
        List<PAK_Update_ACC.CANCEL_INV> cancels = new List<PAK_Update_ACC.CANCEL_INV>{cancelInv};
        
        Test.startTest();
        List<PAK_CANCEL_INV_SERVICE.status> results = PAK_CANCEL_INV_SERVICE.CANCEL(cancels);
        Test.stopTest();
    }
    
    @isTest
    static void testCANCEL_Proveedor() {
        Shipment_Disbursement__c disbursement = [SELECT Id FROM Shipment_Disbursement__c LIMIT 1];
        
        PAK_Update_ACC.CANCEL_INV cancelInv = new PAK_Update_ACC.CANCEL_INV();
        cancelInv.Tipo = 'PROVEEDOR';
        cancelInv.IdInovice = disbursement.Id;
        
        List<PAK_Update_ACC.CANCEL_INV> cancels = new List<PAK_Update_ACC.CANCEL_INV>{cancelInv};
        
        Test.startTest();
        List<PAK_CANCEL_INV_SERVICE.status> results = PAK_CANCEL_INV_SERVICE.CANCEL(cancels);
        Test.stopTest();
    }
    
    @isTest
    static void testCANCEL_OrdenVenta() {
        Shipment__c shipment = [SELECT Id FROM Shipment__c LIMIT 1];
        
        PAK_Update_ACC.CANCEL_INV cancelInv = new PAK_Update_ACC.CANCEL_INV();
        cancelInv.Tipo = 'ORDENVENTA';
        cancelInv.IdInovice = shipment.Id;
        
        List<PAK_Update_ACC.CANCEL_INV> cancels = new List<PAK_Update_ACC.CANCEL_INV>{cancelInv};
        
        Test.startTest();
        List<PAK_CANCEL_INV_SERVICE.status> results = PAK_CANCEL_INV_SERVICE.CANCEL(cancels);
        Test.stopTest();
    }
    
    @isTest
    static void testCANCEL_Error() {
        PAK_Update_ACC.CANCEL_INV cancelInv = new PAK_Update_ACC.CANCEL_INV();
        cancelInv.Tipo = 'PEDIDO';
        cancelInv.IdInovice = '001000000000000';
        
        List<PAK_Update_ACC.CANCEL_INV> cancels = new List<PAK_Update_ACC.CANCEL_INV>{cancelInv};
        
        Test.startTest();
        List<PAK_CANCEL_INV_SERVICE.status> results = PAK_CANCEL_INV_SERVICE.CANCEL(cancels);
        Test.stopTest();
    }
}