respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Operador_Validado__c</fullName>
        <formula>National_Operator__r.Validado__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Operador Validado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Vehicle__c.Account_for_SCP__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Carrier__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Line__c.object
<CustomObject>
    <description>Specifies items to be transported as part of a shipment. Child object of Import-Export Cargo Lines</description>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Cargo Lines</relationshipLabel>
        <relationshipName>Shipment_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Cargo Line</label>
    <nameField>
        <label>Shipment Cargo Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Cargo Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Vehiculo_Validado__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check para saber si el vehículo está disponible para uso</description>
        <label>Vehículo Validado</label>
        <type>Checkbox</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_NEU_Ship_Line_Update_MarginTest.cls
@isTest
public class P2G_NEU_Ship_Line_Update_MarginTest {
	@isTest(SeeAllData=true)
    static void NEU_Shipment_Line_Update_Margin(){
        Shipment__c sp= [SELECT Id FROM Shipment__c WHERE Operador_Validado__c!=null AND ( Vehicle__c!=null OR Vehicle__r.Vehiculo_Validado__c !=TRUE) ORDER BY CreatedDate DESC LIMIT 1];
        Shipment_Line__c spLine= new Shipment_Line__c();
        spLine.Name='';
        spLine.Shipment__c=sp.Id;
        insert spLine;        
    }
}