respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Consolidation_Data__c.object
<CustomObject>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Shipment_Orders_Consolidation_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Consolidation Data</label>
    <nameField>
        <label>Shipment Consolidation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Consolidation Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_test_Return_Import_Export_Quote.cls
@isTest(seeAllData=true)
private class NEU_test_Return_Import_Export_Quote {

    @isTest
    static void testReturnIE() {

        Shipment__c existingShipment = [
            SELECT Id FROM Shipment__c 
            WHERE Id IN (SELECT Shipment__c FROM Shipment_Consolidation_Data__c)
            LIMIT 1
        ];

        // Crear el StandardController con el Shipment existente
        ApexPages.StandardController sc = new ApexPages.StandardController(existingShipment);

        // Instanciar la clase a probar
        NEU_Return_Import_Export_Quote controller = new NEU_Return_Import_Export_Quote(sc);

        // Llamar el método a probar
        PageReference result = controller.return_ie();
    }

    @isTest
    static void testReturnIENoResults() {
        // Obtener un Shipment__c que no tenga relación con Shipment_Consolidation_Data__c
        Shipment__c noConsoShipment = [
            SELECT Id FROM Shipment__c 
            WHERE Id NOT IN (SELECT Shipment__c FROM Shipment_Consolidation_Data__c)
            LIMIT 1
        ];

        ApexPages.StandardController sc = new ApexPages.StandardController(noConsoShipment);

        NEU_Return_Import_Export_Quote controller = new NEU_Return_Import_Export_Quote(sc);

        PageReference result = controller.return_ie();
    }
}