respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <fields>
        <fullName>Shipment_Status_Mon__c</fullName>
        <label>Shipment Status Monitoreo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned_M</fullName>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>In Progress_M</fullName>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Awaiting load_M</fullName>
                    <label>Awaiting load</label>
                </value>
                <value>
                    <fullName>Loading_M</fullName>
                    <label>Loading</label>
                </value>
                <value>
                    <fullName>Delivery on Route_M</fullName>
                    <label>Delivery on Route</label>
                </value>
                <value>
                    <fullName>Awaiting Unload_M</fullName>
                    <label>Awaiting Unload</label>
                </value>
                <value>
                    <fullName>Unloading_M</fullName>
                    <label>Unloading</label>
                </value>
                <value>
                    <fullName>Finished_M</fullName>
                    <label>Finished</label>
                </value>
                <value>
                    <fullName>Failure_M</fullName>
                    <label>Failure</label>
                </value>
                <value>
                    <fullName>Incident_M</fullName>
                    <label>Incident</label>
                </value>
                <value>
                    <fullName>Cancel_M</fullName>
                    <label>Cancel</label>
                </value>
                <value>
                    <fullName>In Warehouse_M</fullName>
                    <label>In Warehouse</label>
                </value>
                <value>
                    <fullName>False_M</fullName>
                    <label>False</label>
                </value>
                <value>
                    <fullName>Operative Failure_M</fullName>
                    <label>Operative Failure</label>
                </value>
                <value>
                    <fullName>Robo_M</fullName>
                    <label>Robo</label>
                </value>
                <value>
                    <fullName>Error en Monitoreo_M</fullName>
                    <label>Error en Monitoreo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_wsUpdateShipment.cls
@RestResource(urlMapping='/updateShipmnet/*')
global class P2G_wsUpdateShipment {
    public static final String NOMBRE_SERVICIO = 'url';
    @HttpPost
    global static String updateShipmnet(){
        String message;
        String trackinId='';
        if(RestContext.request != null){
            String requestBody = RestContext.request.requestBody.toString();
            Map<String, Object> jsonMap = (Map<String, Object>)JSON.deserializeUntyped(requestBody);
            String idShip = (String)jsonMap.get('idShip');
            String status = (String)jsonMap.get('status');
            message = updateStatus(idShip, status);
        }
        return 'Conexion Exitosa'+message;
    }
    public static String updateStatus(String idShip, String status){
        String message;
        try{
            Shipment__c ship = [SELECT Shipment_Status_Mon__c FROM Shipment__c WHERE id=:idShip];
            if(status=='success'){        
            	ship.Shipment_Status_Mon__c= 'Delivery on Route_M';     
            }
            else{
                ship.Shipment_Status_Mon__c= 'Error en Monitoreo_M';
            }
            update ship;            
        }
        catch(Exception e){
            message = e.getMessage()+ ' '+e.getLineNumber();
        }
        return message;
    }
}