respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-02-lote2-clases-muertas/unpackaged/unpackaged/classes/P2G_blockTest.cls
@isTest(SeeAllData=true)
private class P2G_blockTest {
    
    @isTest
    static void testValidateUpdateWithCartaPorte() {
        
        Carta_Porte__c cartaPorte = [SELECT Id, Shipment__c FROM Carta_Porte__c Limit 1];
        Shipment_Fee_Line__c linea = [SELECT Id,Shipment__c FROM Shipment_Fee_Line__c  WHERE Shipment__c =: cartaPorte.Shipment__c limit 1];
        // Test
        Test.startTest();
        try {
            List<Shipment_Fee_Line__c> lineas = new List<Shipment_Fee_Line__c>();
            lineas.add(linea);
            P2G_block.validateUpdate(lineas); // Esto debería fallar
            update linea;
        } catch (Exception e) {
            System.debug('error');
        }
        Test.stopTest();
    }
}