respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment__c.object
<CustomObject>
    <description>Object used to define a shipment associated to an Account and Import-Export order.</description>
    <label>Shipment</label>
    <nameField>
        <label>Shipment Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Shipment_Fee_Line__c.object
<CustomObject>
    <fields>
        <fullName>Conversion_Rate_to_Buy_Currency_Header__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Conversion Rate to Buy Currency Header</label>
        <precision>12</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Shipment Service Line</label>
    <nameField>
        <label>Service Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/P2G_UpdateTc.cls
public class P2G_UpdateTc {
    //@future
    public static void procesarTC(Id shipmentId, Decimal tipoCambio) {
        NEU_StaticVariableHelper.setBoolean1(true);
        List<Shipment_Fee_Line__c> feeLinesToUpdate = new List<Shipment_Fee_Line__c>();

        for (Shipment_Fee_Line__c feeLine : [
            SELECT Id, Conversion_Rate_to_Buy_Currency_Header__c,CurrencyIsoCode
            FROM Shipment_Fee_Line__c
            WHERE Shipment__c = :shipmentId
            AND CurrencyIsoCode = 'USD'
        ]) {
            feeLine.Conversion_Rate_to_Buy_Currency_Header__c = 1/tipoCambio;
            feeLinesToUpdate.add(feeLine);
        }

        if (!feeLinesToUpdate.isEmpty()) {
            try{
                update feeLinesToUpdate;
            }catch(Exception e){
                System.debug('Error al actualzar lneas');
                
            }
            
        } else {
            System.debug('Error No se encontraron registros a actualizar.');
        }
    }
}