respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Supplier_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>Total_Amount_Number__c</formula>
        <inlineHelpText>SUM of Original Amounts from Supplier Quote/Order</inlineHelpText>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Supplier Quote/Order</label>
    <nameField>
        <displayFormat>SQO# {YYYY}-{000000}</displayFormat>
        <label>Supplier Quote/Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Quotes/Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

respaldo-depuracion/2026-09-04-lote3-campos-objetos/objects/Supplier_Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Family</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Supplier Quote/Order Lines</relationshipLabel>
        <relationshipName>Supplier_Quote_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Sourcing_Item__c</referenceTo>
        <relationshipLabel>Supplier Quote/Order Lines</relationshipLabel>
        <relationshipName>Supplier_Quote_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Units</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supplier_Quote__c</fullName>
        <label>Supplier Quote/Order</label>
        <referenceTo>Supplier_Quote__c</referenceTo>
        <relationshipLabel>Supplier Quote/Order Lines</relationshipLabel>
        <relationshipName>Supplier_Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>Net_Amount__c   +  Expense_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>&quot;Net Amount&quot; + &quot;Expense Amount&quot;</inlineHelpText>
        <label>Total Origin Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Origin_Price__c</fullName>
        <formula>Total_Amount__c / Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>&quot;Total Amount&quot; / &quot;Units&quot;</inlineHelpText>
        <label>Unit Origin Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Supplier Quote/Order Line</label>
    <nameField>
        <label>SQO Line</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier Quote/Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NEU_OM_Save_Generate_Quote_Order_pdf.cls
public with sharing class NEU_OM_Save_Generate_Quote_Order_pdf {
    
    public Supplier_Quote__c record;
    public List<Supplier_Quote_Line__c> itemslines {get;set;}
    public String cotizacion_completa {get;set;}
    public decimal total_lineas {get;set;}
    public Decimal total_lineas_items {get;set;}
    public Decimal total_document {get;set;}
    public String resultado {get;set;}
    public boolean hay_items {get;set;}
    public string totallineasitems {get;set;}
    public string totaldocumentos {get;set;}
    
    public string currency_supplier_quote {get;set;}
    ApexPages.StandardController con;
            
    public NEU_OM_Save_Generate_Quote_Order_pdf(ApexPages.StandardController stdController) {

        con = stdController;
        
        try { 
        record = Database.query('select Id, '+(UserInfo.isMultiCurrencyOrganization()== true ? 'CurrencyIsoCode ,' : '')+'  Name from Supplier_Quote__c where id = \''+ con.getRecord().id+'\'');
        } catch( Exception ee) { 
            record = new Supplier_Quote__c();
        }
        
        total_lineas_items =0;
        total_document = 0;
        currency_supplier_quote = NEU_CurrencyUtils.getCurrencyIsoCode(record); 
         hay_items = false;
         itemslines = [select Id, Name, Supplier_Quote__c, Total_Amount__c, Unit_Origin_Price__c, Quantity__c, Item__c, Item__r.Name  from Supplier_Quote_Line__c where Supplier_Quote__c =: record.Id order by Family__c]; 
         for(Supplier_Quote_Line__c lines:itemslines)
         {
                total_lineas_items +=lines.Total_Amount__c;
                hay_items = true;
         }
            
        total_document = total_lineas_items;

        List<String> args2 = new String[]{'0','number','###,###,##0.00'};

        Decimal rA2 = total_lineas_items;
        String s2 = String.format(rA2.format(), args2);
        totallineasitems  = s2;
        
        
        rA2 = total_document;
        s2 = String.format(rA2.format(), args2);
        totaldocumentos = s2;
        
    
     
    }
    
}